### ISSUE TITLE
Personnalisation application

### ISSUE THREAD

**Issue by lecault** [geobretagne/mviewer#10]
Dans le but de personnaliser les applications métiers issues du mviewer, il serait bien de : 

- Pouvoir paramétrer le titre de l'application qui apparaît dans l'onglet d'un navigateur ou dans la barre listant les couches à gauche.

- Pouvoir insérer une aide personnalisée à l'application.

Ces informations, actuellement dans le index.html, pourrait être migrées dans le config.xml.

**Comment by spelhate** [comment]
Done
