### ISSUE TITLE
Filtre/recherche sur la liste des données

### ISSUE THREAD

**Issue by spelhate** [geobretagne/mviewer#102]
La proposition suivante s'avérerait utile pour les applications mobilisant de nombreuses données. Dans ce cas, des difficultés peuvent être rencontrées pour trouver certains jeux de données.
La fonctionnalité opérerait sur les données présentes dans les thématiques en filtrant les données dont le titre ou la description contiendrait le terme recherché.
Au niveau de l'IHM, il faudrait ajouter une box de recherche en chapeau des thématiques.

Qu'en pensez-vous ?

**Comment by bchartier** [comment]
Oui cela me paraît utile même si cela ne devrait pas concerner beaucoup de cartes/applications.
Cela pourrait concerner par exemple une carte/application qui recenserait toutes les couches de données produites par un organisme par exemple.
