### ISSUE TITLE
Renommer config.xml en config-sample.xml

### ISSUE THREAD

**Issue by bchartier** [geobretagne/mviewer#103]
Comme pour mviewerstudio, je propose qu'on renomme config.xml en config-sample.xml afin de faciliter la gestion de configurations spécifiques à certains déploiements.

**Comment by bchartier** [comment]
Pour illustrer : commit sur le dépôt de Neogeo :
https://github.com/neogeo-technologies/mviewer/commit/aae6e5a160c797c22e993d1940a2fc1c50df53a7

**Comment by spelhate** [comment]
Ok pour moi.

**Comment by bchartier** [comment]
Proposé dans le pull request #105

**Comment by spelhate** [comment]
merged.
