### ISSUE TITLE
Version de Font Awesome

### ISSUE THREAD

**Issue by bchartier** [geobretagne/mviewer#104]
Dans la version actuelle de mviewer on 2 versions de font awesome : 4.6.3 et 5.6.3.
Seule la dernière est utilisée.
Dans la version actuelle de mviewerstudio c'est la version 4.6.3 qui est utilisée.
Quand on charge une carte produite par studio dans mviewer on a un message d'erreur dans la console du genre :

> Problème Icone thématique Nouvelle thématique : caret-right
> notation dépréciée avec font-awesome 5.6.3. Utiliser une notation du type 'fas fa-caret-right

Je propose de passer partout en 5.6.3, d'adapter le code de studio et de supprimer de dépôt l'ancienne version de la lib.

**Comment by spelhate** [comment]
Parfait.

**Comment by bchartier** [comment]
Proposé dans le pull request #105

**Comment by spelhate** [comment]
Merged

**Comment by bchartier** [comment]
@spelhate : je me demande si cette modif n'a pas eu un effet de bord sur Kartenn : pictos du fichier d'aide ?

**Comment by spelhate** [comment]
Tu peux être plus précis ?

**Comment by bchartier** [comment]
![image](https://user-images.githubusercontent.com/2361255/52728585-d9234a00-2fb7-11e9-8d70-aec1a438e5fe.png)

Le pictogramme utilisé a changé de style.
cf. https://fontawesome.com/icons/creative-commons?style=brands

**Comment by spelhate** [comment]
Vu.
A la place de l'ancien picto `fa-creative-commons`, il faut utiliser `far fa-copyright`
