### ISSUE TITLE
Pointeur de carte figé

### ISSUE THREAD

**Issue by fefe78800** [geobretagne/mviewer#108]
Bonjour,
Je travaille actuellement à la réalisation d'une carte grâce au package Mviewer pour mon stage. Je rencontre actuellement un problème que je ne parviens pas à régler: en fait, le pointeur de carte (ou map-marker), lorsque je clique sur une entité dans la carte, reste figé dans le plan de l'écran et ne reste pas associé aux coordonnées de l'objet pointé... 
Je souhaitais savoir comment régler ce problème de façon à ce que le pointeur reste calé sur la position de l'objet géographique dans la carte.
Merci par avance de vos contributions !

**Comment by bchartier** [comment]
Bonjour,
Idéalement, ce serait bien de partager ce qui a été fait pour que la communauté des utilisateurs de mviewer puisse constater le problème et le diagnostiquer. Sans cela les échanges risquent d'être abstraits, longs et infructueux.
Une démo en ligne ou, à défaut, un fichier de config serait une première étape.
Ensuite, il peut être utile d'avoir une description du contexte et de l'enchaînement des actions qui mènent au souci.
Ne pas oublier qu'il s'agit d'applications web et que le code impliqué peut ne pas s'exécuter de la même manière dans tous les navigateurs et sur tous les terminaux. Pensez donc à tester votre travail sur plusieurs clients web pour identifier si le problème est spécifique à l'un d'eux.

**Comment by fefe78800** [comment]
Oui bien sûr, vous trouverez le HTML et le fichier config en XML dans le dossier zippé ici présent. Pour ce qui est des actions, je ne peux pas vraiment expliquer quoi que ce soit, puisque toutes mes tentatives n'ont rien donné (style mouseposition, ou d'autres attributs qui n'ont sûrement rien à voir avec le problème)... Et pour ce qui est des clients Web, le problème reste inchangé sur n'importe lequel...

[Nouveau dossier.zip](https://github.com/geobretagne/mviewer/files/2885058/Nouveau.dossier.zip)

**Comment by bchartier** [comment]
J'ai déployé les deux fichiers dans l'arborescence de mviewer sur mon poste.
Par sûr de comprendre ce que vous appelez "pointeur de carte". Le map-marker est censé s'afficher quand on fait quoi ? Quand on demande de localiser la position de son terminal ou lorsque l'on clique sur la carte pour interroger un objet ?

**Comment by fefe78800** [comment]
Le pointeur de carte ici (
![pointeur](https://user-images.githubusercontent.com/47820885/53160104-86551e00-35c7-11e9-83e9-a25a3e9e4be3.jpg)
) s'affiche normalement sur une entité d'une couche pour l'interroger. Et par conséquent, ce pointeur ne reste pas associé à la position de l'objet, mais figé dans l'écran de la carte (je ne sais pas si je me fais bien comprendre...)

**Comment by spelhate** [comment]
Bonjour,
Le pointeur (pin)  matérialise le **lieu cliqué** sur la carte. Il s'agit d'un indicateur de position qui permet de localiser les informations associées au clic.

**Comment by spelhate** [comment]
> Le pointeur de carte ici (
> ![pointeur](https://user-images.githubusercontent.com/47820885/53160104-86551e00-35c7-11e9-83e9-a25a3e9e4be3.jpg)
> ) s'affiche normalement sur une entité d'une couche pour l'interroger. Et par conséquent, ce pointeur ne reste pas associé à la position de l'objet, mais figé dans l'écran de la carte (je ne sais pas si je me fais bien comprendre...)

Quel serait pour vous le comportement normal de ce pointeur ?

**Comment by fefe78800** [comment]
En fait, pour être plus précis, le pointeur est sensé, lorsque l'on clique sur une entité dans une couche, marquer et fixer sa position dans la carte, même si on bouge la carte ou que l'on dézoome par exemple. Or dans mon cas, le pointeur s'affiche bien quand on clique sur un objet, mais si je fais déplacer la carte ou que je dézoome, il ne garde pas la position de l'objet fixe et se déplace lui-aussi (en gros, il ne garde pas la position fixe qu'il est sensé avoir)...

**Comment by fefe78800** [comment]
Alors, je vois où se situe mon problème; dans mon HTML, les lignes de code qui gèrent mon pointeur sont les suivantes : 
`<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" id="els_marker" x="0px" y="0px" viewBox="0 0 297 297" style="enable-background:new 0 0 297 297;" xml:space="preserve" width="30px" height="30px">
                                                                                                                                                                              <path d="M148.5,0C85.646,0,34.511,51.136,34.511,113.989c0,25.11,8.008,48.926,23.157,68.873  c13.604,17.914,32.512,31.588,53.658,38.904l27.464,68.659c1.589,3.971,5.434,6.574,9.71,6.574c4.276,0,8.121-2.603,9.71-6.574  l27.464-68.659c21.146-7.316,40.054-20.99,53.658-38.904c15.149-19.947,23.157-43.763,23.157-68.873  C262.489,51.136,211.354,0,148.5,0z M148.5,72.682c22.777,0,41.308,18.53,41.308,41.308c0,22.777-18.53,41.309-41.308,41.309  c-22.777,0-41.308-18.531-41.308-41.309C107.192,91.212,125.723,72.682,148.5,72.682z"/><g></g><g></g><g></g><g></g><g></g><g></g><g></g><g></g><g></g><g></g><g></g><g></g><g></g><g></g><g></g>
            </svg>
`
Pourtant, j'ai copié les mêmes lignes que la démo de l'index, et rien n'a vraiment changé (je pense que ce doit être la balise <path> le problème, mais je ne sais pas exactement quoi)...

**Comment by bchartier** [comment]
Pas sûr de comprendre.
Est-ce que vous soupçonnez que ce sont des modifs locales de votre fichier index.html qui introduisent un comportement non souhaité ?
Si c'est le cas, essayez avec le fichier index.html d'origine.

**Comment by spelhate** [comment]
Disposez-vous d'un lien permettant de visualiser le problème ?
Sinon j'ai déjà eu ce type de problème après avoir modifié le style (css) du container qui héberge la carte.
C'est peut-être une piste. Exemple si la div #map a une position `relative` au lieu de `fixed`, on constate le désordre que vous décrivez.

**Comment by fefe78800** [comment]
Oui je pense que ça doit venir de chez moi, ça ne fait aucun doute. Simplement, même en copiant les lignes de code (sans changement de version des scripts), il n'y a pas de changement sur le problème. 
A noter toutefois, je ne sais pas si cela a un rapport, mais j'ai seulement un script qui change dans mon html: le script Openlayers que j'avais avait la version 4.5 et celle dans l'index.html est la 5.3.0, et je ne parviens pas à charger ma carte lorsque j'intègre la dernière version (je suis bloqué à la page de chargement); je précise que j'ai téléchargé les fichiers de la version 5.3.0 sur Internet, les mêmes que sur le Github

**Comment by fefe78800** [comment]
Voici un lien vers la carte s'il fonctionne: https://extranet.ville-houilles.fr/mviewer/Carte_de_la_ville_de_Houilles_leitao.html
Je vais voir pour le CSS.

**Comment by spelhate** [comment]
Je vois. Ca va être compliqué de reconstituer le puzzle.
Soit vous restez dans la version d'origine de votre projet. Soit vous repartez d'une copie propre du projet.
Pour éviter les soucis de ce genre, Git est votre ami. Il dispose en effet de mécanismes avancés de synchronisation entre une copie locale du projet mviewer et le dépôt source.

**Comment by fefe78800** [comment]
Oui. Je vais voir, cela me semble complexe dans la mesure où ce n'est pas moi qui ai lancé le projet, ce qui nécessite aussi une réorganisation de notre bibliothèque pour éviter doublons et interférences.
Et pour le CSS, la position: fixed dans #map n'a pas arrangé le problème.

**Comment by fefe78800** [comment]
Pour vous redonner des nouvelles, concernant la version Openlayers 5.3.0, impossible de charger le moindre projet, même en reprenant les fichiers existants sur Git. J'en reste toujours à la fenêtre de chargement qui bloque et qui charge à l'infini. J'ai toujours cette impression que ce peut être lié au défaut du pointeur, car toutes les démos de Mviewer utilisent cette version et ont le pointeur qui fonctionne normalement.
Sinon, j'ai aussi tenté de modifier simplement les lignes de script et de link correspondants à Openlayers dans le début du HTML, sans résultats non plus

**Comment by bchartier** [comment]
Si votre projet ne se charge pas, il faut que vous regardiez ce qui se passe dans la console javascript des outils de développements de votre navigateur web préféré. Le débugueur vous permettra d'identifier la séquence qui bloque le chargement du projet.

Le déploiement de mviewer n'est pas presse-bouton (sauf si vous utilisez le studio) et il faut donc pouvoir mettre régulièrement les mains dans le cambouis pour comprendre ce qu'il se passe et corriger ses défauts de jeunesse.

**Comment by spelhate** [comment]
Vous avez un lien vers l'application qui ne se charge pas ? Ça permettra de mieux comprendre ce qui se passe. Sinon, je vous conseille de repartir de la dernière version de mviewer (master) et de tester vos applications (config.xml). En principe, il ne faut modifier que les fichiers xml. ON ne touche pas aux fichiers js... ou index.html.

**Comment by fefe78800** [comment]
Voici un lien vers la carte s'il fonctionne: https://extranet.ville-houilles.fr/mviewer/Carte_de_la_ville_de_Houilles_leitao.html j'ai téléchargé la version master, mais je pense qu'il peut y avoir des interférences entre la version Openlayers et ce qui héberge mon application, je vais essayer de voir avec mon supérieur pour voir si cela peut venir de là

**Comment by spelhate** [comment]
Dans le téléchargement, il y a la bonne version d'Openlayers.
Sinon je ne peux pas me connecter au lien fourni. Il m'est demandé un login / mot de passe.

**Comment by fefe78800** [comment]
Vous pouvez accéder à la plateforme ici sinon, qui est une version officielle (et non ma version d'essai comme précédemment). https://www.ville-houilles.fr/Bienvenue-a-Houilles/Plan-de-la-ville le même problème se retrouve ici aussi

**Comment by JJardin77580** [comment]
Bonjour, 
Lorsque l'on ouvre la console du navigateur, on remarque que vous avez dans votre fichier mviewer.js la variable 'getCoord' à la ligne 197 qui est non définie. 
Et en regardant le code du master du mviewer vous devriez avoir : 
`  coordinateFormat: function(coordinate) {
                        let getCoord = ol.coordinate.toStringHDMS(ol.proj.transform(coordinate,
                            _projection.getCode(), 'EPSG:4326'));
                        let coordStr = getCoord.replace(/ /g,"").replace("N","N - ");
                        return coordStr;
}`

Or vous avez : 
`new ol.control.MousePosition({
                    projection: _projection.getCode(),
                    undefinedHTML: 'y , x',
                    className: 'custom-mouse-position',
                    target: document.getElementById('mouse-position'),
                    coordinateFormat: function(coordinate) {
                        ol.coordinate.toStringHDMS(ol.proj.transform(coordinate, _projection.getCode(), 'EPSG:4326'));
                        getCoord.replace(/ /g,"").replace("N","N - ");
                        return coordStr;
                    }
                }),`

Ceci devrait déjà corriger certaines anomalies dans votre application.

**Comment by fefe78800** [comment]
Bonjour, 
Merci beaucoup, cela fonctionne! En fait, le projet est en EPSG: 3857 et dans le js, il est en 4326. Et il manquait les lignes d'appel (letgetcoord= et let coordStr =) 
Du coup, mon pointeur semble être bien stable sur ma carte!
