### ISSUE TITLE
Toplayer pour plusieurs couches ? (casser l'ordre d'apparition des couches)

### ISSUE THREAD

**Issue by fefe78800** [geobretagne/mviewer#109]
Bonjour,
Sur un projet de cartographie interactive, je cherche activement une solution pour ordonner l'apparition de mes couches. En fait, je constate que la superposition des couches dans la carte se base sur l'ordre de sélection depuis l'utilisateur (en gros dernière couche saisie= couche en 1er-plan). Je souhaite casser cet ordre d'apparition en souhaitant que les couches ponctuelles restent en premier plan, au-dessus des couches linéaires et surfaciques afin qu'elles ne soient pas masquées. 

J'ai déjà trouvé une solution partielle qui s'applique pour une couche:  l'attribut toplayer="true" permet de fixer une couche "en haut" de la légende, mais lorsque je le fais pour toutes mes autres couches ponctuelles, cela ne fonctionne pas, et cela rajoute même des doublons de couche en légende comme voici : 
![probleme](https://user-images.githubusercontent.com/47820885/53154336-d4175980-35ba-11e9-9fd2-4207a0525855.jpg)

Et je vous joins ici le code du fichier configuration XML:
`<?xml version="1.0" encoding="UTF-8"?>
<config>
    <application title="Carte de la ville de Houilles" mouseposition="true" logo="" help="https://extranet.ville-houilles.fr/mviewer/mviewer_help_houilles.html" showhelp="false" measuretools="true" exportpng="true" coordinates="false" style="css/themes/vert_de_gris.css" geoloc="true" togglealllayersfromtheme="true"/>    
    <mapoptions maxzoom="19" projection="EPSG:3857" center="243674.82,6262495.96" zoom="15" rotation="true"/>
  

    <baselayers style="default"> 
	<baselayer visible="true" id="OpenStreetMap" thumbgallery="img/basemap/imgHouilles/OpenstreetMapH.png" title="OSM" label="OpenStreetMap" type="OSM" url="https://{a-c}.tile.openstreetmap.org/{z}/{x}/{y}.png" attribution="Données : les contributeurs d'&lt;a href=&quot;https://www.openstreetmap.org/&quot; target=&quot;_blank&quot;&gt;OpenStreetMap &lt;/a&gt;&lt;a href=&quot;https://www.openstreetmap.org/copyright&quot; target=&quot;_blank&quot;&gt;ODbL &lt;/a&gt;"  ></baselayer> 
    <baselayer visible="false" id="Positron" thumbgallery="img/basemap/imgHouilles/PositronH.png" title="CartoDb" label="Positron" type="OSM" url="https://{a-c}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}.png" attribution="Map tiles by  &lt;a href=&quot;https://cartodb.com/attributions&quot;&gt;CartoDb&lt;/a&gt;, under  &lt;a href=&quot;https://creativecommons.org/licenses/by/3.0/&quot;&gt;CC BY 3.0 &lt;/a&gt;"  ></baselayer> 
    <baselayer visible="false" id="Orthophotographie" thumbgallery="img/basemap/imgHouilles/OrthoH.png" title="Esri world imagery" label="Esri world imagery" type="OSM" url="http://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}" attribution="Esri world imagery"  ></baselayer> 
   
	</baselayers>    
    <proxy url=""/>
    <olscompletion url="https://api-adresse.data.gouv.fr/search/?q" type="ban"/>
    <searchparameters bbox="false" localities="false" features="true" />   

    <themes id="houilles"> 
        <theme name="Espaces Publics"  collapsed="true" id="Espaces_publics" icon="building"> 
			<layer id="WGS84_Houilles_EspacesVerts2" 
			
					name="Espaces verts"
					type="wms"
					visible="false"
					opacity="0.3"
					queryable="true" 
					fields="nom"
					aliases="nom"
                    infoformat="application/vnd.ogc.gml"
					featurecount="1"
					stylealias="WGS84_Houilles_EspacesVerts2"
					attributefilter="false" 
					attributefield="Nom" 
					attributevalues="espaces_co" 
                    url="https://extranet.ville-houilles.fr/geoserver/houillesSIG/ows"
                    attribution="Source: Ville de Houilles, DIST et service SIG ©, 2018" 
					metadata="https://extranet.ville-houilles.fr/geonetwork/srv/fre/catalog.search#/metadata/341a0c43-2932-45bd-9cb8-746630bab34a"
					metadata-csw="https://extranet.ville-houilles.fr//geonetwork/srv/fre/csw?SERVICE=CSW&amp;VERSION=2.0.2&amp;REQUEST=GetRecordById&amp;elementSetName=full&amp;ID=341a0c43-2932-45bd-9cb8-746630bab34a">
					<template url="https://extranet.ville-houilles.fr/mviewer/templates/espacesverts.mst"></template> 
			</layer>
              <layer id="wgs84_houilles_cimetieres" 
			  
					name="Cimetière"
					type="wms"
					visible="false"
					queryable="true" 
					fields="nom"
					aliases="nom"
                    infoformat="application/vnd.ogc.gml"
					featurecount="1"
					stylealias="wgs84_houilles_cimetieres"
					opacity="0.6"
					attributefilter="false" 
					attributefield="nom" 
					attributevalues="adresse" 
					toplayer="true"
                    url="https://extranet.ville-houilles.fr/geoserver/houillesSIG/ows"
                    attribution="Source: Ville de Houilles, service Environnement et service SIG ©, 2018" 
					metadata="https://extranet.ville-houilles.fr/geonetwork/srv/fre/catalog.search#/metadata/a0197537-17c8-4b98-b0e6-697ec37f4c66"
					metadata-csw="https://extranet.ville-houilles.fr//geonetwork/srv/fre/csw?SERVICE=CSW&amp;VERSION=2.0.2&amp;REQUEST=GetRecordById&amp;elementSetName=full&amp;ID=a0197537-17c8-4b98-b0e6-697ec37f4c66">
					<template url="https://extranet.ville-houilles.fr/mviewer/templates/Cimetieres.mst"></template> 
			</layer>
			<layer id="bati_test" 
			 
					name="Batiments et services communaux"
					type="wms"
					visible="false"
					queryable="true"
					
					fields="nom"
					aliases="nom"
                    infoformat=" application/vnd.ogc.gml"
					featurecount="1"
		            legendurl="https://extranet.ville-houilles.fr/mviewer/png_test/legendebatib.png"
					attributefilter="false" 
					attributefield="nom" 
					attributevalues="adresse" 
					toplayer="true"
                    url="https://extranet.ville-houilles.fr/geoserver/houillesSIG/ows"
                    attribution="Source: Ville de Houilles, DIST et service SIG ©, 2018" 
					metadata="https://extranet.ville-houilles.fr/geonetwork/srv/fre/catalog.search#/metadata/7dc9aaf2-3a94-4e4d-b054-0ea95fc599ff"
					metadata-csw="https://extranet.ville-houilles.fr//geonetwork/srv/fre/csw?SERVICE=CSW&amp;VERSION=2.0.2&amp;REQUEST=GetRecordById&amp;elementSetName=full&amp;ID=7dc9aaf2-3a94-4e4d-b054-0ea95fc599ff">
					<template url="https://extranet.ville-houilles.fr/mviewer/templates/equipements.mst"></template> 
			</layer>
			</theme>                    
		<theme name="Hygiène et propreté"  collapsed="true" id="hygiène" icon="paw"> 
		<layer id="canisites_test_wgs84 " 
		
					name="Canisites"
					type="wms"
					visible="false"
					queryable="true" 
					fields="adresse"
					aliases="adresse"
                    infoformat="text/html"
					featurecount="1"
					stylealias="canisites_test_wgs84"
					legendurl="https://extranet.ville-houilles.fr/mviewer/png_test/dogd.png"
					attributefilter="true" 
					attributefield="adresse" 
					attributevalues="adresse" 
                    url="https://extranet.ville-houilles.fr/geoserver/houillesSIG/ows"
                    attribution="Source: Ville de Houilles, DIST et service SIG ©, 2018" 
					metadata="https://extranet.ville-houilles.fr/geonetwork/srv/fre/catalog.search#/metadata/b59e22ca-f280-4648-ac0a-5cfc8247db33"
					metadata-csw="https://extranet.ville-houilles.fr//geonetwork/srv/fre/csw?SERVICE=CSW&amp;VERSION=2.0.2&amp;REQUEST=GetRecordById&amp;elementSetName=full&amp;ID=b59e22ca-f280-4648-ac0a-5cfc8247db33">
					<template url="https://extranet.ville-houilles.fr/mviewer/templates/canisites.mst"></template> 
			</layer>
			<layer id="wgs84_houilles_distributeurssacscanins" 
			
					name="Distributeurs de sacs canins"
					type="wms"
					visible="false"
					queryable="true" 
					fields="adresse"
					aliases="adresse"
                    infoformat="application/vnd.ogc.gml"
					featurecount="1"
					stylealias="wgs84_houilles_distributeurssacscanins"
					legendurl="https://extranet.ville-houilles.fr/mviewer/png_test/poop1.png"
					attributefilter="false" 
					attributefield="adresse" 
					attributevalues="adresse" 
                    url="https://extranet.ville-houilles.fr/geoserver/houillesSIG/ows"
                    attribution="Source: Ville de Houilles, Service environnement et service SIG ©, 2018" 
					metadata="https://extranet.ville-houilles.fr/geonetwork/srv/fre/catalog.search#/metadata/b9fe47df-8f6e-47d8-9d3b-b47e42c2f3e2"
					metadata-csw="https://extranet.ville-houilles.fr//geonetwork/srv/fre/csw?SERVICE=CSW&amp;VERSION=2.0.2&amp;REQUEST=GetRecordById&amp;elementSetName=full&amp;ID=b9fe47df-8f6e-47d8-9d3b-b47e42c2f3e2">
					<template url="https://extranet.ville-houilles.fr/mviewer/templates/Distributeurssacscanins.mst"></template> 
			</layer>
		</theme>  
		<theme name="Stationnement"  collapsed="true" id="stationnement" icon="car"> 
			<layer id="WGS84_Houilles_PlacesHandicapees" 
			
				name="Places de stationnement handicapées" 
				visible="false"
				queryable="true"
                infoformat="text/html"
                type="wms"
                url="https://extranet.ville-houilles.fr/geoserver/houillesSIG/ows" 
				legendurl="https://extranet.ville-houilles.fr/mviewer/Templatic-map-icons_test/handicap.png"
                attribution="Source: Ville de Houilles, Service voirie et service SIG ©, 2018" 
                metadata="https://extranet.ville-houilles.fr/geonetwork/srv/fre/catalog.search#/metadata/87180283-634d-4ea4-a006-34f8469b9219" 
                metadata-csw="https://extranet.ville-houilles.fr//geonetwork/srv/fre/csw?SERVICE=CSW&amp;VERSION=2.0.2&amp;REQUEST=GetRecordById&amp;elementSetName=full&amp;ID=87180283-634d-4ea4-a006-34f8469b9219">    
            </layer>
			<layer id="WGS84_Voirie_ParkingsVelos" 
			
				name="Stationnements vélos" 
				visible="false" 
				queryable="true"
                infoformat="text/html"
                type="wms"
                url="https://extranet.ville-houilles.fr/geoserver/houillesSIG/ows" 
				legendurl="https://extranet.ville-houilles.fr/mviewer/png_test/bicycle.png"
                attribution="Source: Ville de Houilles, Service voirie et service SIG ©, 2018" 
                metadata="https://extranet.ville-houilles.fr/geonetwork/srv/fre/catalog.search#/metadata/066513de-5384-45b8-b801-72ef2a6e8372" 
                metadata-csw="https://extranet.ville-houilles.fr//geonetwork/srv/fre/csw?SERVICE=CSW&amp;VERSION=2.0.2&amp;REQUEST=GetRecordById&amp;elementSetName=full&amp;ID=066513de-5384-45b8-b801-72ef2a6e8372"> 
            </layer>
			<layer id="WGS84_Voirie_ParkingsAutoPublics" 
			
				name="Stationnements automobiles (public)" 
				visible="false" 
				queryable="true" 
				fields=""
				aliases=""
                infoformat="application/vnd.ogc.gml"
				featurecount="1"
                type="wms"
				exclusive="true"
				
                url="https://extranet.ville-houilles.fr/geoserver/houillesSIG/ows" 
				legendurl="https://extranet.ville-houilles.fr/mviewer/png_test/parking1.png"
                attribution="Source: Ville de Houilles, Service voirie et service SIG ©, 2018" 
                metadata="https://extranet.ville-houilles.fr/geonetwork/srv/fre/catalog.search#/metadata/cd24edba-6640-43a6-8733-95597bb4793f" 
                metadata-csw="https://extranet.ville-houilles.fr//geonetwork/srv/fre/csw?SERVICE=CSW&amp;VERSION=2.0.2&amp;REQUEST=GetRecordById&amp;elementSetName=full&amp;ID=cd24edba-6640-43a6-8733-95597bb4793f">  
				<template url="https://extranet.ville-houilles.fr/mviewer/templates/auto_test.mst"></template> 
			</layer>
			<layer id="WGS84_Houilles_Stationnement_RuesReglementees" 
			
				name="Stationnement réglementé sur voirie"
				type="wms"
				visible="false"
				queryable="true" 
				url="https://extranet.ville-houilles.fr/geoserver/houillesSIG/ows"
                attribution="Source: Ville de Houilles, Service Voirie et service SIG ©, 2018">
			</layer>
		</theme>
        <theme name="Territoire"  collapsed="false" id="territoire" icon="map"> 
			<layer 
				id="wgs84_houilles_limitescommunales" 
				
				name="Limites communales"
				type="wms"
				url="https://extranet.ville-houilles.fr/geoserver/houillesSIG/ows"
				visible="true" 
				queryable="true" 
				infoformat="text/html"
                attribution="Source: IGN©, 2017, BDTOPO" 
                metadata="https://extranet.ville-houilles.fr/geonetwork/srv/fre/catalog.search#/metadata/a1acbbb1-8274-49a9-adb6-fcd45125aa8a" 
                metadata-csw="https://extranet.ville-houilles.fr//geonetwork/srv/fre/csw?SERVICE=CSW&amp;VERSION=2.0.2&amp;REQUEST=GetRecordById&amp;elementSetName=full&amp;ID=a1acbbb1-8274-49a9-adb6-fcd45125aa8a">
			</layer>
            <layer id="wgs84_houilles_quartiers" 
		
				name="Quartiers" 
				visible="true" 
				opacity="0.9"
				queryable="true"
                infoformat="text/html"
                type="wms"
                url="https://extranet.ville-houilles.fr/geoserver/houillesSIG/ows" 
                attribution="Source: Ville de Houilles, service SIG©" 
                metadata="https://extranet.ville-houilles.fr/geonetwork/srv/fre/catalog.search#/metadata/afbe29f6-eb91-4db0-b271-c2f6b93e130e" 
                metadata-csw="https://extranet.ville-houilles.fr//geonetwork/srv/fre/csw?SERVICE=CSW&amp;VERSION=2.0.2&amp;REQUEST=GetRecordById&amp;elementSetName=full&amp;ID=afbe29f6-eb91-4db0-b271-c2f6b93e130e">
			</layer>
			
        </theme>

    </themes>
</config>
`
J'ai tenté aussi d'allier des possibilités de z-index étant donné que mes couches sont hébergées sous GeoServer, mais sans grand résultat non plus...
Je vous remercie d'avance de vos contributions !

**Comment by bchartier** [comment]
L'objet de ce ticket c'est de ne plus avoir ces doublons c'est ça ?
Pour ma part, je n'ai pas réussi à reproduire l'apparition de ces doublons.
Il faudrait nous indiquer quelle séquence de manipulation engendre cela, dans quel navigateur par exemple.

**Comment by fefe78800** [comment]
L'objet exact de ce ticket est le verrouillage des couches ponctuelles en premier plan de la carte interactive, les doublons sont liés à la présence des attributs toplayer="true" dans différentes couches. Ils n'apparaissent que si on sélectionne les couches avec toplayers (ici dans mon exemple les bâtiments communaux et les canisites) et que derrière, on fait apparaître d'autres couches. Pour ma part, j'ai testé sous mozilla, chrome et IE, j'ai toujours le même problème...

**Comment by fefe78800** [comment]
Si je peux encore préciser le problème, la première couche sélectionnée avec un toplayer fonctionne bien. La seconde avec toplayer fonctionne comme si elle n'avait pas cet attribut (donc "normalement") et sera recouverte par les entités surfaciques si elles sélectionnées derrière. Elle entraîne avec elle la couche qui fonctionnait bien avec toplayer, et si l'on déselectionne puis qu'on resélectionne la couche surfacique arrivée en dernier, la première couche marchant bien avec toplayer refonctionne normalement en s'affichant en priorité devant par rapport aux autres. 
C'est à partir d'une troisième couche sélectionnée avec un attribut toplayer qui pose le problème du doublon en légende, et qui en plus, ne fait pas fonctionner l'attribut toplayer dans la couche. Je mets un nouveau code avec les couches ayant toutes un toplayer pour que vous vous en rendiez compte.
`<?xml version="1.0" encoding="UTF-8"?>
<config>
    <application title="Carte de la ville de Houilles" mouseposition="true" logo="" help="https://extranet.ville-houilles.fr/mviewer/mviewer_help_houilles.html" showhelp="false" measuretools="true" exportpng="true" coordinates="false" style="css/themes/vert_de_gris.css" geoloc="true" togglealllayersfromtheme="true"/>    
    <mapoptions maxzoom="19" projection="EPSG:3857" center="243674.82,6262495.96" zoom="15" rotation="true"/>
  

    <baselayers style="default"> 
	<baselayer visible="true" id="OpenStreetMap" thumbgallery="img/basemap/imgHouilles/OpenstreetMapH.png" title="OSM" label="OpenStreetMap" type="OSM" url="https://{a-c}.tile.openstreetmap.org/{z}/{x}/{y}.png" attribution="Données : les contributeurs d'&lt;a href=&quot;https://www.openstreetmap.org/&quot; target=&quot;_blank&quot;&gt;OpenStreetMap &lt;/a&gt;&lt;a href=&quot;https://www.openstreetmap.org/copyright&quot; target=&quot;_blank&quot;&gt;ODbL &lt;/a&gt;"  ></baselayer> 
    <baselayer visible="false" id="Positron" thumbgallery="img/basemap/imgHouilles/PositronH.png" title="CartoDb" label="Positron" type="OSM" url="https://{a-c}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}.png" attribution="Map tiles by  &lt;a href=&quot;https://cartodb.com/attributions&quot;&gt;CartoDb&lt;/a&gt;, under  &lt;a href=&quot;https://creativecommons.org/licenses/by/3.0/&quot;&gt;CC BY 3.0 &lt;/a&gt;"  ></baselayer> 
    <baselayer visible="false" id="Orthophotographie" thumbgallery="img/basemap/imgHouilles/OrthoH.png" title="Esri world imagery" label="Esri world imagery" type="OSM" url="http://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}" attribution="Esri world imagery"  ></baselayer> 
   
	</baselayers>    
    <proxy url=""/>
    <olscompletion url="https://api-adresse.data.gouv.fr/search/?q" type="ban"/>
    <searchparameters bbox="false" localities="false" features="true" />   

    <themes id="houilles"> 
        <theme name="Espaces Publics"  collapsed="true" id="Espaces_publics" icon="building"> 
			<layer id="WGS84_Houilles_EspacesVerts2" 
			class="c"
					name="Espaces verts"
					type="wms"
					visible="false"
					opacity="0.3"
					queryable="true" 
					fields="nom"
					aliases="nom"
                    infoformat="application/vnd.ogc.gml"
					featurecount="1"
					stylealias="WGS84_Houilles_EspacesVerts2"
					attributefilter="false" 
					attributefield="Nom" 
					attributevalues="espaces_co"
					toplayer="false"
                    url="https://extranet.ville-houilles.fr/geoserver/houillesSIG/ows"
                    attribution="Source: Ville de Houilles, DIST et service SIG ©, 2018" 
					metadata="https://extranet.ville-houilles.fr/geonetwork/srv/fre/catalog.search#/metadata/341a0c43-2932-45bd-9cb8-746630bab34a"
					metadata-csw="https://extranet.ville-houilles.fr//geonetwork/srv/fre/csw?SERVICE=CSW&amp;VERSION=2.0.2&amp;REQUEST=GetRecordById&amp;elementSetName=full&amp;ID=341a0c43-2932-45bd-9cb8-746630bab34a">
					<template url="https://extranet.ville-houilles.fr/mviewer/templates/espacesverts.mst"></template> 
			</layer>
              <layer id="wgs84_houilles_cimetieres" 
			  class="c"
					name="Cimetière"
					type="wms"
					visible="false"
					queryable="true" 
					fields="nom"
					aliases="nom"
                    infoformat="application/vnd.ogc.gml"
					featurecount="1"
					stylealias="wgs84_houilles_cimetieres"
					opacity="0.6"
					attributefilter="false" 
					attributefield="nom" 
					attributevalues="adresse" 
					toplayer="false"
                    url="https://extranet.ville-houilles.fr/geoserver/houillesSIG/ows"
                    attribution="Source: Ville de Houilles, service Environnement et service SIG ©, 2018" 
					metadata="https://extranet.ville-houilles.fr/geonetwork/srv/fre/catalog.search#/metadata/a0197537-17c8-4b98-b0e6-697ec37f4c66"
					metadata-csw="https://extranet.ville-houilles.fr//geonetwork/srv/fre/csw?SERVICE=CSW&amp;VERSION=2.0.2&amp;REQUEST=GetRecordById&amp;elementSetName=full&amp;ID=a0197537-17c8-4b98-b0e6-697ec37f4c66">
					<template url="https://extranet.ville-houilles.fr/mviewer/templates/Cimetieres.mst"></template> 
			</layer>
			<layer id="bati_test" 
			 class="a"
					name="Batiments et services communaux"
					type="wms"
					visible="false"
					queryable="true"
					toplayer="true"
					fields="nom"
					aliases="nom"
                    infoformat=" application/vnd.ogc.gml"
					featurecount="1"
		            legendurl="https://extranet.ville-houilles.fr/mviewer/png_test/legendebatib.png"
					attributefilter="false" 
					attributefield="nom" 
					attributevalues="adresse" 
					
                    url="https://extranet.ville-houilles.fr/geoserver/houillesSIG/ows"
                    attribution="Source: Ville de Houilles, DIST et service SIG ©, 2018" 
					metadata="https://extranet.ville-houilles.fr/geonetwork/srv/fre/catalog.search#/metadata/7dc9aaf2-3a94-4e4d-b054-0ea95fc599ff"
					metadata-csw="https://extranet.ville-houilles.fr//geonetwork/srv/fre/csw?SERVICE=CSW&amp;VERSION=2.0.2&amp;REQUEST=GetRecordById&amp;elementSetName=full&amp;ID=7dc9aaf2-3a94-4e4d-b054-0ea95fc599ff">
					<template url="https://extranet.ville-houilles.fr/mviewer/templates/equipements.mst"></template> 
			</layer>
			</theme>                    
		<theme name="Hygiène et propreté"  collapsed="true" id="hygiène" icon="paw"> 
		<layer id="canisites_test_wgs84 " 
		class="a"
					name="Canisites"
					type="wms"
					visible="false"
					queryable="true" 
					fields="adresse"
					aliases="adresse"
                    infoformat="text/html"
					featurecount="1"
					toplayer="true"
					stylealias="canisites_test_wgs84"
					legendurl="https://extranet.ville-houilles.fr/mviewer/png_test/dogd.png"
					attributefilter="true" 
					attributefield="adresse" 
					attributevalues="adresse" 
					
                    url="https://extranet.ville-houilles.fr/geoserver/houillesSIG/ows"
                    attribution="Source: Ville de Houilles, DIST et service SIG ©, 2018" 
					metadata="https://extranet.ville-houilles.fr/geonetwork/srv/fre/catalog.search#/metadata/b59e22ca-f280-4648-ac0a-5cfc8247db33"
					metadata-csw="https://extranet.ville-houilles.fr//geonetwork/srv/fre/csw?SERVICE=CSW&amp;VERSION=2.0.2&amp;REQUEST=GetRecordById&amp;elementSetName=full&amp;ID=b59e22ca-f280-4648-ac0a-5cfc8247db33">
					<template url="https://extranet.ville-houilles.fr/mviewer/templates/canisites.mst"></template> 
			</layer>
			<layer id="wgs84_houilles_distributeurssacscanins" 
			class="a"
					name="Distributeurs de sacs canins"
					type="wms"
					visible="false"
					queryable="true" 
					fields="adresse"
					aliases="adresse"
                    infoformat="application/vnd.ogc.gml"
					featurecount="1"
					stylealias="wgs84_houilles_distributeurssacscanins"
					legendurl="https://extranet.ville-houilles.fr/mviewer/png_test/poop1.png"
					attributefilter="false" 
					attributefield="adresse" 
					attributevalues="adresse" 
					toplayer="true"
                    url="https://extranet.ville-houilles.fr/geoserver/houillesSIG/ows"
                    attribution="Source: Ville de Houilles, Service environnement et service SIG ©, 2018" 
					metadata="https://extranet.ville-houilles.fr/geonetwork/srv/fre/catalog.search#/metadata/b9fe47df-8f6e-47d8-9d3b-b47e42c2f3e2"
					metadata-csw="https://extranet.ville-houilles.fr//geonetwork/srv/fre/csw?SERVICE=CSW&amp;VERSION=2.0.2&amp;REQUEST=GetRecordById&amp;elementSetName=full&amp;ID=b9fe47df-8f6e-47d8-9d3b-b47e42c2f3e2">
					<template url="https://extranet.ville-houilles.fr/mviewer/templates/Distributeurssacscanins.mst"></template> 
			</layer>
		</theme>  
		<theme name="Stationnement"  collapsed="true" id="stationnement" icon="car"> 
			<layer id="WGS84_Houilles_PlacesHandicapees" 
			class="a"
				name="Places de stationnement handicapées" 
				visible="false"
				queryable="true"
                infoformat="text/html"
                type="wms"
				toplayer="true"
                url="https://extranet.ville-houilles.fr/geoserver/houillesSIG/ows" 
				legendurl="https://extranet.ville-houilles.fr/mviewer/Templatic-map-icons_test/handicap.png"
                attribution="Source: Ville de Houilles, Service voirie et service SIG ©, 2018" 
                metadata="https://extranet.ville-houilles.fr/geonetwork/srv/fre/catalog.search#/metadata/87180283-634d-4ea4-a006-34f8469b9219" 
                metadata-csw="https://extranet.ville-houilles.fr//geonetwork/srv/fre/csw?SERVICE=CSW&amp;VERSION=2.0.2&amp;REQUEST=GetRecordById&amp;elementSetName=full&amp;ID=87180283-634d-4ea4-a006-34f8469b9219">    
            </layer>
			<layer id="WGS84_Voirie_ParkingsVelos" 
			class="a"
				name="Stationnements vélos" 
				visible="false" 
				queryable="true"
                infoformat="text/html"
                type="wms"
				toplayer="true"
                url="https://extranet.ville-houilles.fr/geoserver/houillesSIG/ows" 
				legendurl="https://extranet.ville-houilles.fr/mviewer/png_test/bicycle.png"
                attribution="Source: Ville de Houilles, Service voirie et service SIG ©, 2018" 
                metadata="https://extranet.ville-houilles.fr/geonetwork/srv/fre/catalog.search#/metadata/066513de-5384-45b8-b801-72ef2a6e8372" 
                metadata-csw="https://extranet.ville-houilles.fr//geonetwork/srv/fre/csw?SERVICE=CSW&amp;VERSION=2.0.2&amp;REQUEST=GetRecordById&amp;elementSetName=full&amp;ID=066513de-5384-45b8-b801-72ef2a6e8372"> 
            </layer>
			<layer id="WGS84_Voirie_ParkingsAutoPublics" 
			class="a"
				name="Stationnements automobiles (public)" 
				visible="false" 
				queryable="true" 
				fields=""
				aliases=""
                infoformat="application/vnd.ogc.gml"
				featurecount="1"
                type="wms"
				exclusive="true"
				toplayer="true"
                url="https://extranet.ville-houilles.fr/geoserver/houillesSIG/ows" 
				legendurl="https://extranet.ville-houilles.fr/mviewer/png_test/parking1.png"
                attribution="Source: Ville de Houilles, Service voirie et service SIG ©, 2018" 
                metadata="https://extranet.ville-houilles.fr/geonetwork/srv/fre/catalog.search#/metadata/cd24edba-6640-43a6-8733-95597bb4793f" 
                metadata-csw="https://extranet.ville-houilles.fr//geonetwork/srv/fre/csw?SERVICE=CSW&amp;VERSION=2.0.2&amp;REQUEST=GetRecordById&amp;elementSetName=full&amp;ID=cd24edba-6640-43a6-8733-95597bb4793f">  
				<template url="https://extranet.ville-houilles.fr/mviewer/templates/auto_test.mst"></template> 
			</layer>
			<layer id="WGS84_Houilles_Stationnement_RuesReglementees" 
			class="b"
				name="Stationnement réglementé sur voirie"
				type="wms"
				visible="false"
				queryable="true"
				toplayer="false"				
				url="https://extranet.ville-houilles.fr/geoserver/houillesSIG/ows"
                attribution="Source: Ville de Houilles, Service Voirie et service SIG ©, 2018">
			</layer>
		</theme>
        <theme name="Territoire"  collapsed="false" id="territoire" icon="map"> 
			<layer 
				id="wgs84_houilles_limitescommunales" 
				class="d"
				name="Limites communales"
				type="wms"
				url="https://extranet.ville-houilles.fr/geoserver/houillesSIG/ows"
				visible="true" 
				queryable="true" 
				infoformat="text/html"
				toplayer="false"
                attribution="Source: IGN©, 2017, BDTOPO" 
                metadata="https://extranet.ville-houilles.fr/geonetwork/srv/fre/catalog.search#/metadata/a1acbbb1-8274-49a9-adb6-fcd45125aa8a" 
                metadata-csw="https://extranet.ville-houilles.fr//geonetwork/srv/fre/csw?SERVICE=CSW&amp;VERSION=2.0.2&amp;REQUEST=GetRecordById&amp;elementSetName=full&amp;ID=a1acbbb1-8274-49a9-adb6-fcd45125aa8a">
			</layer>
            <layer id="wgs84_houilles_quartiers" 
			class="d"
				name="Quartiers" 
				visible="true" 
				opacity="0.9"
				queryable="true"
                infoformat="text/html"
                type="wms"
				toplayer="false"
                url="https://extranet.ville-houilles.fr/geoserver/houillesSIG/ows" 
                attribution="Source: Ville de Houilles, service SIG©" 
                metadata="https://extranet.ville-houilles.fr/geonetwork/srv/fre/catalog.search#/metadata/afbe29f6-eb91-4db0-b271-c2f6b93e130e" 
                metadata-csw="https://extranet.ville-houilles.fr//geonetwork/srv/fre/csw?SERVICE=CSW&amp;VERSION=2.0.2&amp;REQUEST=GetRecordById&amp;elementSetName=full&amp;ID=afbe29f6-eb91-4db0-b271-c2f6b93e130e">
			</layer>
			
        </theme>

    </themes>
</config>
`

**Comment by bchartier** [comment]
Ok, j'ai reproduit le problème.
Merci pour les explications.

**Comment by spelhate** [comment]
La propriété toplayer permet bien pour **une seule couche** de la fixer sur le dessus de la carte.
L'utilisateur peut en outre modifier l'ordre d'affichage des couches en effectuant des glisser/déplacer.

**Comment by fefe78800** [comment]
D'accord ! Donc aucune possibilité n'existe pour casser cet ordre d'apparition? Autrement dit, c'est à l'utilisateur d'arranger à sa guise l'ordre des couches pour visualiser correctement toutes les couches du mieux possible si je comprends bien ?

**Comment by spelhate** [comment]
Oui c'est tout à fait celà. Sinon il faudrait imaginer un système de priorisation pour chaque couche allant de 1 à 3. Toutes les couches de priorités 3 seraient en bas de la pile, les couches de priorité 2 au dessus et celles de priorité 1 tout au dessus de la pile.

**Comment by bchartier** [comment]
Pourquoi limiter à 3 ?

**Comment by spelhate** [comment]
En y repensant, on pourrait effectivement définir une priorité individuelle- et non pas collective - pour chaque couche. La priorité irait alors de 1 à n.

**Comment by fefe78800** [comment]
Oui je vois. Trois serait pour le cas où l'on souhaite définir un ordre selon l'implantation (ponctuelle, linéaire, ou zonale) générale des couches, mais on peut aussi faire de 1 à n selon les couches individuelles. Ce serait en effet une bonne idée à développer. Merci à vous pour vos contributions !

**Comment by Gaetanbrl** [comment]
Je rebondis sur ce ticket. Par défaut, les couches serait dans l'ordre d'inscription dans le config.xml mais si on set l'ordre d'une ou plusieurs couches, alors ces couches seront affichées dans l'ordre saisis, les autres dans l'ordre du config.xml.

Ca irai comme comportement ?

**Comment by Gaetanbrl** [comment]
Je débute les travaux de cette issue pour les besoin de nos utilisateurs.

**Comment by Gaetanbrl** [comment]
Vu avec @spelhate.

Je pense envisager ces comportements pour cette évolution : 
* Par défaut l'ordre des couches sera pris en compte selon l'ordre d'écriture dans le XML

* Si un numéro d'index est précisé pour une couche, alors cette couche sera placé au niveau défini (ex: 3ème en haut)

* Si un XML contient des couches avec et sans numéros : 

-- Les couches avec numéros seront positionnées à la position définie
-- Les couches sans numéros seront positionnées sous les couches avec un numéro défini mais dans l'ordre d'écriture dans le XML

* Le système de topLayer sera maintenu et une topLayer sera au dessus de la pile comme actuellement, donc au dessus d'une couche avec une position = 1

* Si plusieurs couches ont le paramètre topLayer, alors les couches avec le paramètre toplayer='true' seront au dessus de toutes les autres dans l'ordre d'écriture du XML

Qu'en pensez-vous ?

**Comment by Gaetanbrl** [comment]
pop @AnthonyNch

**Comment by spelhate** [comment]
La logique me convient. En complément : l'organisation des couches dans la légende reflétera également le séquençage des couches dans le fichier de configuration contrairement à maintenant où les dernières couches affichées s'intègrent en haut de la légende sans respecter l'empilement des couches dans la carte. Par ailleurs, il sera toujours possible de déplacer les couches manuellement par glisser/déposer.

**Comment by Gaetanbrl** [comment]
- [ ] Par défaut l'ordre des couches sera pris en compte selon l'ordre d'écriture dans le XML

- [ ]  Si un numéro d'index est précisé pour une couche, alors cette couche sera placé au niveau défini (ex: 3ème en haut)

- [ ] Si un XML contient des couches avec et sans numéros :

-- Les couches avec numéros seront positionnées à la position définie
-- Les couches sans numéros seront positionnées sous les couches avec un numéro défini mais dans l'ordre d'écriture dans le XML

- [ ] Le système de topLayer sera maintenu et une topLayer sera au dessus de la pile comme actuellement, donc au dessus d'une couche avec une position = 1

- [ ] Si plusieurs couches ont le paramètre topLayer, alors les couches avec le paramètre toplayer='true' seront au dessus de toutes les autres dans l'ordre d'écriture du XML

- [ ] l'organisation des couches dans la légende reflétera également le séquençage des couches dans le fichier de configuration

**Comment by lecault** [comment]
@Gaetanbrl à clore ? En lien avec l'index https://mviewerdoc.readthedocs.io/fr/stable/doc_tech/config_layers.html?highlight=index#parametres-pour-gerer-l-affichage-de-la-couche

**Comment by Gaetanbrl** [comment]
Je close, merci @lecault
