### ISSUE TITLE
Pb affichage des couches intégrées au WMC dans le layer panel

### ISSUE THREAD

**Issue by hsquividant** [geobretagne/mviewer#11]
Les couches présentes dans le fichier WMC passé en paramètre de l'URL s'affichent bien dans la carte mais pas dans le panel de gauche. cf http://geowww.agrocampus-ouest.fr/mviewer/?wmc=http://geowww.agrocampus-ouest.fr/wmc/bzh_MateriauDominant.wmc

**Comment by spelhate** [comment]
Et Maintenant ?

**Comment by spelhate** [comment]
Le parsing wmc a été amélioré : Prise en compte de l'opacité, des échelles d'affichage & bug Fix CrossOrigin
