### ISSUE TITLE
mviewer & responsive design

### ISSUE THREAD

**Issue by spelhate** [geobretagne/mviewer#111]
A noter, l'application dispose d'un nouveau mode "mobile" depuis cette pull request: #110 
Le mode s'active automatiquement en fonction de la taille du support.
![responsive mviewer](https://kartenn.region-bretagne.fr/img/mviewer/mv-responsive-sm.gif)

**Comment by fefe78800** [comment]
Bonjour
Cette version mobile est vraiment magnifique, bravo ! 
Seulement, je ne sais pas si cela est partagé par d'autres membres, mais tout fonctionne normalement sur tous navigateurs, sauf sur Chrome.
En effet, j'ai quelques bugs, que j'ai eu à la fois sur la version mviewer-master, et sur mon projet où j'ai refais les liens vers les nouveaux dossiers sans problème:
- j'ai mes icônes de theme qui ne sont pas reconnues (carré blanc), même avec fas fa- devant l'icone
- lorsque j'ai des couches visibles dès l'ouverture de la carte, la légende ne les affiche pas
- sur mobile, je reste bloqué carrément au chargement de la page
Cela m'étonne d'avoir ces bugs, sachant que les captures d'écran que vous postez semblent être extraites de Chrome...

**Comment by spelhate** [comment]
Pouvez-vous tester ce lien : https://kartenn.region-bretagne.fr/mv/ avec Chrome ?

**Comment by fefe78800** [comment]
Oui cela fonctionne normalement avec votre lien, sur ordinateur comme sur mobile. Le problème doit venir de chez moi, c'est sûr

**Comment by fefe78800** [comment]
En vérité, la plupart des problèmes étaient liés au cache non vidé, donc des interférences quant à l'affichage des images et de la version mobile.
Merci et encore bravo pour votre travail!
