### ISSUE TITLE
Realisation dataviz avec variation temporelle

### ISSUE THREAD

**Issue by fefe78800** [geobretagne/mviewer#115]
Bonjour,
Je réalise actuellement un projet d'observatoire du foncier qui fait intervenir des variations temporelles de données ainsi que de la datavisualisation en graphiques sur des templates associés aux couches. 
Je n'ai hélas qu'une faible base en javascript, malgré que je comprenne les grandes lignes des scripts. Je suis reparti de l'exemple des résultats de bac par lycée dans les exemples de configuration; cependant, le résultat qui m'intéresse le plus concerne celui que j'ai pu voir avec kartenn territoires, avec les couches de l'emploi total par exemple.
Mon but actuellement est de créer un diagramme type anneau solaire, différenciant l'origine géo des acquéreurs dans la commune où je travaille. Je peux vous joindre le codage du template actuel, étant donné que je me suis basé sur celui des résultats du bac par lycée en bretagne, avec le diagramme qui montrait les effectifs d'étudiants par série. 
Par exemple, je n'ai pas non plus compris certains éléments intervenant dans le codage de ce fichier : à quoi se rapportent les éléments "rne", "id" et l'attribut "effectif_presents_serie_" qui sert à la création du graphique (chart_1) ; je me doute que cela a un lien avec la table attributaire de la couche en question, mais concrètement, quelles sont les valeurs, car on ne retrouve pas, je crois, l'attribut dans l'url des données du template ?

Voici le codage de mon template personnel:
`                                {{#features}}
	                         <li class="item" style="padding-bottom:65px;">		
		                    <div class="title-feature" style="padding-top:10px;">{{nom_du_qua}}
		                  </div>
		                       <div class="panel panel-default">
                                          <div class="panel-body panel-graph"> 
                <canvas class="chart1" id="chart1_{{id_qu}}" ></canvas>
            </div>
        </div>
	</li>		
{{/features}}

<style>
	.title-feature {
		color: #2d4059;
		font-family:"Roboto";
		font-size:23px;
		margin-bottom:3%;
		line-height:1;			
	}
	.panel-graph {
	    color: #3db39e;
	    text-align: center;
	}
			
</style>
<script>
	var houilles_charts = {};
    var getValuesAndLabels = function (obj, scheme) {
        var data = {values: [], labels:[]};
        Object.keys(obj).forEach(function(key) {
             var position = key.indexOf(scheme);
             if (position >= 0) {
                data.values.push(obj[key]);
                data.labels.push(key.substr(position + scheme.length).toUpperCase());
            }
        });
        return data;
    };
 var reOrderValues = function (l1, l2, v2) {
        var orderedArray = [];
        l1.forEach(function (label, nom_du_qua) {
            //find id with same label in l2
            var i = l2.findIndex(function(element) { return element === label; });
            orderedArray.push(v2[i]);
        });
        return orderedArray;
    };
    var drawCharts = function (year) {
        var colors = {
            rgb:[
                [45, 64, 89],
                [61,179,158],
                [255,201,57]
            ],
            rgba1: [],
            rgba2: []
        };
        colors.rgb.forEach(function(rgb) {
            colors.rgba1.push("rgba(" + rgb.join(",") + ",1)");
            colors.rgba2.push("rgba(" + rgb.join(",") + ",0.6)");

        });

        var houilles = [];
        {{#features}}
            houilles.push('{{id_qu}}');
        {{/features}}

        houilles.forEach(function (nom, id_qu) {
         var url = "https://extranet.ville-houilles.fr/geoserver/houillesSIG/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=houillesSIG:quartiers_2010_18&maxFeatures=50&outputFormat=application/json&srsName=EPSG:3857&facet=nom_du_qua&facet=millesime&refine.nom_du_qua="+nom+"&refine.millesime="+year;
        
		  $.ajax({
                success (data) {
				 var stats = data.records[0].fields;
                    var nom = stats.nom_du_qua;
				/* chart1 */
                    var chart1_prop = getValuesAndLabels(stats, "acq_houill");
                    if (houilles_charts["chart1_" + nom]) {
                        //update chart
                        houilles_charts["chart1_" + nom].destroy();
                    }
                    //create chart
                    var ctx1 = document.getElementById("chart1_" + nom);
                    houilles_charts["chart1_" + nom] = new Chart(ctx1, {
                      type: 'doughnut',
                      data: {
                          labels: chart1_prop.labels,
                          datasets: [{
                              label: "Origine des acheteurs",
                              backgroundColor: colors.rgba2,
                              borderColor: colors.rgba1,
                              data: chart1_prop.values
                          }]
                      },
                      options: {
                        responsive: true,
                        title: {
                            display: true,
                            text: 'Origine des acquéreurs de biens immobiliers à Houilles'
                        }
                      }
                    });
            }}); /* end Ajax */
            }); /* end forEach */
        }; /* end */
 if  (typeof Chart === 'function') {
            drawCharts(2018);
    } else {
            $.get('https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.min.js', function() {
                drawCharts(2018);});
    }
</script>`

Je conçois que mon problème est complexe et vague, n'hésitez pas à me demander plus de précisions, si besoin.
Merci beaucoup !

**Comment by spelhate** [comment]
Ci joint un lien vers un mviewer qui traite du foncier et qui a été réalisé par @Agath21 
Ca peut être une bonne source d'inspiration ;-)
https://geobretagne.fr/pub/dreal_b/mviewer/?config=../apps/foncier/config.xml

**Comment by vfabry** [comment]
Un autre exemple ici, basé sur la démo des lycées :
[(https://www.geopicardie.fr/mviewer/?config=tu_captes.xml)]
Certaines couches ne sont pas accessibles si vous n'avez pas de compte sur le portail, mais la couche commune, qui contient les dataviz, est en libre accès (c'est codé avec mes maigres compétences en js, soyez indulgents :-)

**Comment by spelhate** [comment]
C'est super. Merci pour la démo.
