### ISSUE TITLE
Création de plusieurs modes d'affichage

### ISSUE THREAD

**Issue by spelhate** [geobretagne/mviewer#120]
L'idée est de disposer en plus de l'affichage classique du mviewer de 2 affichages simplifiés.
L'objectif est de faciliter le réemploi des applications dans des sites web sous forme d'iframe par exemple. 
On pourrait ainsi disposer :

- d'un mode **simplifié** en supprimant le panneau des thématiques,
- d'un mode **ultra simplifié** en supprimant le panneau des thématiques et la barre de navigation

Dans les 2 cas, la légende serait minifiée.

Le mode par défault serait le mode d'affichage actuel et les 2 autres modes pourraient être activés par configuration ou via l'API.

**Comment by bchartier** [comment]
L'idée c'est de faire en sorte qu'on puisse utiliser mviewer à la place de sviewer par exemple ?

**Comment by spelhate** [comment]
C'est une possibilité oui.

**Comment by spelhate** [comment]
Création depuis l'API mviewer :

- d'un mode simplifié  `mode=s`
- d'un mode ultra simplifié `mode=u`

Ces deux options d'affichage sont disponibles également depuis le panel "Parte de carte"

[Exemple d'utilisation](http://kartenn.region-bretagne.fr/kartoviz/?x=-185379&y=6126339&z=13&l=lycee&lb=ortho1&config=demo%2Ffuse.xml&mode=s&title=mviewer%20-%20mode%20simplifi%C3%A9)

**Comment by bchartier** [comment]
C'est tout prêt tout chaud pour le geOcom.
