### ISSUE TITLE
Sélection automatique d'images raster par critères (date et % de couverture nuageuse)

### ISSUE THREAD

**Issue by MarieJag** [geobretagne/mviewer#121]
Bonjour,

Je travaille actuellement avec mviewer pour mettre à disposition des images satellitaires SENTINEL.
https://geobretagne.fr/mviewer/?config=/apps/sentinel/config.xml
Je n'ai aucune base en développement mais j'ai pu faire un premier visualiseur grâce à la documentation riche du mviewer et l'aide de l'équipe GéoBretagne.
Pour le moment, l'affichage des images SENTINEL est possible via des url (WMS) que je paramètre manuellement sur l'interface de configuration du fournisseur des géoservices (Sentinel Hub, auprès duquel nous souscrivons un abonnement pour avoir une clé).
Sur cette interface de configuration, je crée manuellement une url et un ID de layer pour chaque couche. Je peux ainsi fixer manuellement pour chaque couche la couverture nuageuse maximale et la date ou intervalle entre 2 dates. Dans le cas d'un choix d'intervalle entre 2 dates j'ai le choix d'afficher l'image la plus/moins récente ou celle qui a la couverture nuageuse la plus faible.
Il y a en moyenne une image SENTINEL tous les 5 jours, je ne peux donc pas créer un ID manuellement pour chaque date.

J'aimerais donc automatiser les requêtes et proposer à l'utilisateur de choisir lui-même la date exacte de l'image à afficher.
J'ai pour cela proposé un projet à des élèves ingénieurs de l'IMT Atlantique pour améliorer l'interface de sélection des images à afficher afin de pouvoir sélectionner les images
- par date
- en apliquant un seuil de couverture nuageuse en %

par exemple
- sur un calendrier sont surlignés les jours où une image est disponible
- sur une barre de 0 à 100, l'utilisateur choisit un seuil de couverture nuageuse maximal
- sur le calendrier sont surlignés et entourés les jours où une image est disponible repectant ce sueil de couverture nuageuse
- l'utilisateur clique sur la date et l'image s'affiche
Comme cela est possible sur le visualiseur du fournisseur
https://apps.sentinel-hub.com/sentinel-playground/?source=S2&lat=40.4&lng=-3.730000000000018&zoom=12&preset=1-NATURAL-COLOR&layers=B01,B02,B03&maxcc=20&gain=1.0&gamma=1.0&time=2018-11-01%7C2019-05-13&atmFilter=&showDates=false

Peut-être que quelqu'un aurait des éléments de réponse sur la marche à suivre pour ajouter ces fonctionnalités au mviewer ? Pour la suite je propose aux étudiants de participer directement aux échanges, ils seront plus à même que moi à poser les bonnes questions.

Merci d'avance,

Marie

**Comment by spelhate** [comment]
Bonjour Marie,
merci pour l'intérêt porté au projet et bravo pour ce qui a déjà été entrepris.
Je pense qu'il est possible, assez simplement, de créer dans mviewer deux contrôles (date et couverture nuageuse) afin d'automatiser les requêtes vers le hub Sentinel.  Pour ce faire, il faut pouvoir accéder aux dates disponibles pour chaque image. Je n'ai pas réussi à trouver cette information via les capacités du service WMS comme le standard le prévoit. Existe t'il un autre moyen ?

Ensuite pour ajouter ces fonctionnalités il y a deux possibilités

- en créant un contrôle personnalisé associé aux couches concernées, comme [ici](http://kartenn.region-bretagne.fr/kartoviz/?config=demo/profile.xml)
- en créant quelque chose de plus générique et donc intégré au coeur, si réutilisable avec d'autres services / producteurs.

**Comment by MarieJag** [comment]
Bonjour Sébastien,
Merci pour ton retour,
Pour récupérer les informations sur les dates disponibles et les couvertures nuageuse, il est possible de passer par un autre distributeur des images Sentinel : THEIA, qui propose un programme Pyhton pour sélectionner et télécharger les images
https://github.com/olivierhagolle/theia_download
Dans notre cas inutile de télécharger les données, en revanche on peut obtenir un fichier texte avec les dates disponibles et les taux de couverture nuageuse associés.

**Comment by spelhate** [comment]
Il me semble qu'on pourrait récupérer des informations sur la couverture nuageuse et les dates disponibles pour les tuiles S2A avec une requête de ce type 
https://services.sentinel-hub.com/ogc/wfs/b7b5e3ef-5a40-4e2a-9fd3-75ca2b81cb32?test=1557757243986&service=WFS&version=2.0.0&request=GetFeature&time=2019-04-09/2019-06-30/P1D&typenames=S2.TILE&maxfeatures=100&srsname=EPSG:3857&bbox=-442303,4918684,-388110,4929767&outputformat=application/json

en mettant la bonne clé et la bonne BBOX bien sûr.

**Comment by spelhate** [comment]
Amorce de réponse :
http://kartenn.region-bretagne.fr/kartoviz/?config=demo/sentinel.xml

Cette démo mobilise 3 couchesWMS classiques pointant vers Sentinel Hub et une couche de type **customlayer** utilisant 3 ressources :

- customlayers/s2tile.js
- customcontrols/s2tile.js
- customcontrols/s2tile.html

cette couche "Outils" permet de filtrer dynamiquement les 3 couches d'imagerie à partir des 2 contrôles date et couverture nuageuse"

Il ne s'agit pas d'un produit fini, mais d'une simple illustration des possibilités de mviewer pour ce cas d'usage.

Cette démo utilise les flux OGC WMS et WFS fournis par https://services.sentinel-hub.com

**Comment by MarieJag** [comment]
Merci pour cette réponse qui va vraiment aider les étudiants, on tiendra au courant de la progression dans les semaines à venir !

**Comment by MoMouss** [comment]
Bonjour, 

Je suis un des élèves qui travaille actuellement sur le projet. Merci pour votre récente aide qui nous a été très précieuse. On a cependant besoin d'un petit coup de main additionnel. Je vais essayer d'être le plus clair possible concernant le besoin.

On souhaite permettre à l'utilisateur de ce mviewer de créer son propre produit à afficher, c'est à dire d'affecter une des 13 bandes spectrales à chacun des filtres RGB et de visualiser le résultat . 

Sentinel Hub (notre fournisseur) nous permet pour cela de mettre dans le paramètre WMS EvalScriptURL
l'url d'un fichier JavaScript. . Ce fichier JavaScript doit simplement retourner une liste comprenant les 3 bandes sélectionnées, et doit donc être de la forme 'return [ {valeur1}*{Bande pour le rouge}, {valeur2}*{Bande pour le vert}, {valeur3}*{Bande pour le bleu}];' (par exemple: return [2.5*B01, 2.5*B02, 2.5*B03];)

J'ai opté pour une solution qui nécessite deux couches dans un seul thème sur le mviewer: une couche pour le choix des bandes (avec des contrôles personnalisés), et une couche pour la visualisation du produit généré.

La couche pour la visualisation est une simple couche donc l'url est le flux wms du fournisseur (Sentinel Hub). 

J'ai créé pour la couche de configuration un contrôle avec des listes déroulantes pour le choix des bandes, on retrouve dans le fichier HTML un <form> dont les <select> sont de la forme:
`<label class="col-md-4 control-label" for="green" style="padding-top:8px;" for="green"> Green: </label>
<SELECT id="product-green" NAME="Liste" class="select_green" onChange="mviewer.customControls.s2product.updateBandes()">
				<OPTION label="B01" value="B01"> B01 </OPTION>
				<OPTION label="B02" value="B02"> B02 </OPTION>
				<OPTION label="B03" value="B03"> B03 </OPTION>
				<OPTION label="B04" value="B04"> B04 </OPTION>
				<OPTION label="B05" value="B05"> B05 </OPTION>
				<OPTION label="B06" value="B06"> B06 </OPTION>
				<OPTION label="B07" value="B07"> B07 </OPTION>
				<OPTION label="B08" value="B08"> B08 </OPTION>
				<OPTION label="B09" value="B09"> B09 </OPTION>
</SELECT>`

Et on retrouve dans le fichier JS associé une fonction pour récupérer le choix de l'utilsateur: 
`updateBandes: function() {
            //fonction appellée à chaque fois qu'on change de bande dans la liste des bandes
        	var redBand = $('.select_red').options[$('.select_red').selectedIndex].value;
        	var greenBand = $('.select_green').options[$('.select_green').selectedIndex].value;
                var blueBand = $('.select_blue').options[$('.select_blue').selectedIndex].value;

               _customScript = 'return [2.5*'+ redBand + ', 2.5*' + greenBand + ', 2.5*' + blueBand + '];'

        },`

J'ai créé une variable globale _customScript, qu'on modifie à chaque fois que l'utilisateur change de bande dans la liste déroulante .

Dans ce même fichier, j'ai (dans le constructeur init) modifié le paramètre evalscripturl de la couche de visualisation pour y mettre l'URL du fichier JS de customisation que j'ai créé auparavant: 
`var _layerDefinition = mviewer.getLayers()['CUSTOM_PRODUCTS'];
        var _source = _layerDefinition.layer.getSource();
        //_source.getParams()['EVALSCRIPTURL']='https://geobretagne.fr/apps/sentinel/customcontrols/evalscript.js';
        _source.getParams()['EVALSCRIPT']='return [2*B04, 2*B03, 2*B02];';
        _source.changed()`

Le résultat fonctionne comme voulu et le mviewer affiche des données suivant le produit défini dans evalscript.js.
 
Le but maintenant est de pouvoir remplacer le contenu de ce fichier JS evalscript.js par le contenu de la variable globale _customScript. Le résultat ferait en sorte qu'à chaque fois que l'utilisateur change de bande via les listes déroulantes, on aura une modification du contenu de _customScript, puis du fichier evalscript.js , ce qui fera que les données affichées seront différentes.

Mon souci est que je n'arrive pas à trouver un moyen de modifier le fichier evalscript.js et d'y mettre la variable globale (je suis très débutants dans le domaine du développement web). Avez-vous une solution à proposer ? 
Si quelque chose dans ce que j'ai expliqué n'est pas clair, n'hésitez pas à me le faire savoir

Merci.

PS: Sentinel Hub propose un autre paramètre au lieu de EVALSCRIPURL, appelé EVALSCRIPT, dans lequel on est supposés mettre directement le script JS (return [2.5*B01...), mais il ne semble pas fonctionner (j'ai fait quelques tests).

**Comment by MarieJag** [comment]
Bonjour, 

Je n'avais pas diffusé les résultats des étudiants (mieux vaut tard que jamais).

Voici la démo réalisée par les étudiants (merci à eux) :
https://geobretagne.fr/mviewer/?config=/apps/sentinel/config.xml#
Ajouts : 
- sélection d'une couverture nuageuse maximale (en % de nuage par image, les images étant découpées en tuiles)
- sélection d'une date
Le flux WMS (délivré par Sentinel Hub) affiche l'image la plus proche de la date sélectionnée satisfaisant le critère de couverture nuageuse. Pour connaître la date de l'image, il faut cliquer dessus et le bandeau à droite affiche l'info.
- outils de création d'une composition colorée (en attribuant les canaux RVB à chaque bande spectrale).
Perspectives d'amélioration :
- surligner sur le calendrier les jours où une images est dispo (couleur 1) / où l'image dispo satisfait le critère de couverture nuageuse (couleur 2)
- améliorer l'ergonomie

Les étudiants ont écrit cette doc :
https://cloud.imt-atlantique.fr/index.php/s/eag3pFeW7jrcDnG

Nous poursuivrons le travail avec l'aide d'un stagiaire en 2020.

Merci et à bientôt pour les suites,

Marie
