### ISSUE TITLE
Carousel et template mustache

### ISSUE THREAD

**Issue by fefe78800** [geobretagne/mviewer#122]
Bonjour
Je poste ce message pour un projet sur lequel je travaille. Je programme une application cartographique avec dataviz en template.mst qui puisse s'afficher dynamiquement au clic selon des paramètres de temps et d'espace. 
Mes templates fonctionnent bien, mais néanmoins j'ai une question pour soulever un problème; je n'ai pas énormément de place pour mettre tous mes graphiques sur une même page de template. Par conséquent, je souhaiterais savoir s'il existe une méthode permettant d'avoir un affichage de plusieurs pages sur un même template (selon le modèle du style carousel comme pour des images). J'avais remarqué cette solution notamment dans l'application Kartenn Territoires, dès lors que l'on sélectionnait deux territoires adjacents (sur une limite commune par exemple)...
Merci beaucoup pour vos réponses !

**Comment by fefe78800** [comment]
J'ai pu trouver assez rapidement la réponse finalement. Grâce à bootstrap, j'ai pu faire plusieurs pages de figures sur un même template (à la manière d'un diaporama contrôlé avec des flèches). Pour ceux qui en auraient besoin, voici un exemple de code html indiqué dans le template mst:
`       <div>
            
       <div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="false">
    
        <div class="carousel-inner">
 
    <div class="item active">
      <div class="col-md-4" style="margin-left:190px;">
			<div>
					<canvas id="canvas" width="330" height="240"></canvas>
			</div>
		</div>
		<div class="col-md-4">
			<div>
				<canvas class="chart" id="ConstChart1_{{id}}" width="470" height="300"></canvas> 
			</div>
		</div>
    </div>

    <div class="item">
      <div class="col-md-4" style="margin-left:190px;">
			<div>
				<canvas class="chart" id="ConstChart2_{{id}}" width="360" height="210"></canvas>  </br>
				<span id="text">{{millesime}}</span>            
			</div>
		</div>
    </div>

    <div class="item">
     <div class="col-md-4" style="margin-left:190px;">
			<div>
					<canvas id="canvas2" width="360" height="270"></canvas>
			</div>
		</div>
		<div class="col-md-2" style="margin-left:70px;"> 
            	<img src="https://extranet.ville-houilles.fr/mviewer/SVG/house.svg" style="width:40%; padding:10px;">  
            	<p style="margin:-5px 0px -5px 0px!important;">
            		<p class="title-number">
					 + <span id="nouv_logt_{{id}}" class="number"></span><span class="number" style="font-size:15px;">  logements</span></br>
            	
            	<i>par rapport à l'année précédente</i></span></p>  </p>                                 
        </div>	
    </div>
	<div class="item">
	<div class="col-md-4" style="margin-left:190px;">
			<div>
					<canvas id="canvas3" width="360" height="270"></canvas>
			</div>
			
		</div>
		<div class="col-md-4" style="margin-left:80px;">
			<div>
					<canvas id="canvas4" width="360" height="270"></canvas>
			</div>
		</div>
	 </div>
	 
	 <div class="item">
	 <div class="col-md-4" style="margin-left:190px;">
			<div>
					<canvas id="canvas5" width="360" height="270"></canvas>
					Médiane générale des surfaces de tous types: <font color="red";>{{surf_m2}}</font> m²
			</div>
			
	</div>
		
		<div class="col-md-4" style="margin-left:80px;">
			<div>
					<canvas id="canvas6" width="360" height="270"></canvas>
					Médiane générale des surfaces de tous types: <font color="red";>{{surf_m2}}</font> m²
			</div>
		</div>
  </div>
  </div>

  
  <a class="left carousel-control" href="#myCarousel" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#myCarousel" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right"></span>
    <span class="sr-only">Next</span>
  </a>
</div>`

**Comment by sebastiendiasjacoly** [comment]
@fefe78800 merci pour cette contribution. Vous avez un exemple de réalisation à fournir svp ?
