### ISSUE TITLE
Rendre responsive le template dataviz

### ISSUE THREAD

**Issue by vfabry** [geobretagne/mviewer#124]
Dans _?config=demo/dataviz.xml_, est-ce qu'on peut imaginer de rendre responsive le template avec les dataviz ?

Vincent

**Comment by bchartier** [comment]
A priori oui, le coté responsive devrait pouvoir être géré de 2 manières :
- en utilisant des classes prédéfinies d'un framework css (Bootstrap par exemple puisque c'est utilisé par mviewer). cf. https://getbootstrap.com/docs/3.3/css/#responsive-utilities
- en utilisant du css maison à intégrer dans ta propre feuille de style ou directement dans ton template. Ce qu'il faut utiliser dans CSS ce sont les media query pour indiquer qu'un comportement différent doit être appliquer en fonction de la taille et de l'orientation de l'écran. cf. https://www.w3schools.com/css/css_rwd_mediaqueries.asp par exemple.

Est-ce que ça répond à ta question ?

**Comment by spelhate** [comment]
Je pensais qu'il l'était déjà :

![Screenshot_20190516-155847_Chrome](https://user-images.githubusercontent.com/1793792/57860057-70d14800-77f4-11e9-9394-dfa534e15649.jpg)

**Comment by bchartier** [comment]
@vfabry imaginait peut-être autre chose.

**Comment by bchartier** [comment]
@vfabry : je ferme ce ticket ?

**Comment by vfabry** [comment]
yep
