### ISSUE TITLE
Recherche fuse et problème de zoom éloigné

### ISSUE THREAD

**Issue by fefe78800** [geobretagne/mviewer#125]
Bonjour,
Je poste ce message pour savoir si d'autres personnes avaient déjà entendu parler d'un problème que je n'arrive pas à résoudre. En fait, j'ai deux couches customlayer dans un projet, une polygone et l'autre par points. Les deux couches sont paramétrées pour être interrogées via fuse sur la barre de recherche. 
Lorsque j'effectue une recherche sur une entité zonale de ma première couche, le territoire recherché est bien ciblé et zoomé sur son emprise. Mais pour mes entités ponctuelles, le résultat est bien affiché mais il n'y a pas de zoom sur l'emprise du lieu recherche: au lieu de ça, je me retrouve à un zoom à échelle mondiale, et je suis obligé de rezoomer manuellement sur le lieu en question.
Pour vous donner une idée, voici un lien vers le projet : [https://extranet.ville-houilles.fr/mviewer/Carte_de_la_ville_de_Houilles_batiments.html#](url) (les requêtes sont faites selon le nom des lieux).

Merci pour votre aide !

**Comment by spelhate** [comment]
Bonjour,
oui j'ai déjà eu ce problème. Il s'agit d'un bug qui concerne les entités de type MultiPoint, ce qui est le cas ici. Bug corrigé dans ce commit daté de 9 jours : https://github.com/geobretagne/mviewer/commit/51e8f770d12ec4850c1a9181fc39f1e5bea2ef66

**Comment by fefe78800** [comment]
Super j'ai mis à jour le document. Ca fonctionne, merci beaucoup !
