### ISSUE TITLE
Réaliser une saisie par mots-clés sur une couche à index Elastic search

### ISSUE THREAD

**Issue by fefe78800** [geobretagne/mviewer#127]
Bonjour,
Je poste ce message car je réalise une cartographie inventaire qui doit nécessiter la programmation de l'outil de saisie des entités par mots-clés comme dans la demo ici :(http://kartenn.region-bretagne.fr/kartoviz/?config=demo/els2.xml) . J'ai étudié le codage du programme en Javascript (dans le dossier customlayers/inventaire.js), mais j'avoue avoir encore du mal à m'en servir, d'autant que j'ai des lacunes pour utiliser Elastic search. J'ai néanmoins retenu qu'à un moment, un lien URL est utilisé (qui doit être pour appeler les données manipulées selon l'index). Ma question peut paraître bête, mais comment est généré ce lien exactement ?
Une autre question concerne la barre de recherche du menu : est-il généré par le JS directement ? Ou faut-il programmer en HTML encore ?
Merci pour toutes vos réponses !

**Comment by spelhate** [comment]
Bonjour,
Pour débuter avec **Elasticsearch** je conseille plutôt l'exemple suivant :
 http://kartenn.region-bretagne.fr/kartoviz/?config=demo/els.xml 
qui ne fait pas appel à un customlayer. Le mécanisme de cet exemple est le suivant : pour la partie carto, on utilise des flux WMS, pour la partie recherche, on s'appuie sur une instance Elasticsearch qui indexe la couche WMS utilisée.

L'exemple http://kartenn.region-bretagne.fr/kartoviz/?config=demo/els2.xml 
est plus complexe car on ne s'appuie plus du tout sur WMS/WFS mais uniquement sur un index elasticsearch qui filtre les entités affichées sur la carte dynamiquement. Dans cet exemple le système de requêtage est développé en js dans le **customcontrol** associé au layer. Je pense qu'il s'agit de l'exemple le plus complexe présenté dans les démos.

Et dans tous les cas, il faut quelques connaissances sur la gestion d'un index Elasticsearch.

> Ma question peut paraître bête, mais comment est généré ce lien exactement ?

Il faut disposer d'un service  elasticsearch accessible ex: "https://monserveur/elasticsearch"
et mviewer compose les requêtes qui vont bien. Je conseille la lecture de la doc sur ce sujet : 
https://mviewerdoc.readthedocs.io/fr/latest/doc_dev/config_els.html

Sinon, il existe des possibilités de recherche plus simples à mettre en place comme sur l'exemple suivant : 
http://kartenn.region-bretagne.fr/kartoviz/?config=demo/fuse.xml 
dans ce cas, la source de données (WFS) est indexée directement dans le mviewer grâce à Fuse et le requêtage se fait à partir de la barre de recherche/adresse classique.

**Comment by fefe78800** [comment]
Merci, d'accord je vois un peu. Mon intérêt est de développer dans la démo que j'avais mise l'outil de recherche qui là est basé sur la recherche des éléments patrimoniaux; si j'ai bien compris, ce sont des champs de la couche de données qui sont filtrées par la saisie des mots-clés. C'est ce que j'aimerais appliquer à ma cartographie inventaire pour avoir un affichage des résultats des entités retenues en fonction des termes saisis dans l'outil (et non dans la barre de recherche principale en haut à droite). 

Pour fuse, j'ai compris comment cela fonctionnait avec du customlayer et j'ai su l'appliquer à ma couche dans le XML. C'est une solution plus simple de recherche qu'Elastic search pour la barre de recherche je trouve.

**Comment by spelhate** [comment]
> Pour fuse, j'ai compris comment cela fonctionnait avec du customlayer et j'ai su l'appliquer à ma couche dans le XML. C'est une solution plus simple de recherche qu'Elastic search pour la barre de recherche je trouve.

Complètement d'accord. Pour des données pas trop volumineuses, c'est la solution qu'il faut privilégier.

**Comment by fefe78800** [comment]
Pour Elastic Search, j'essaie de voir pour comment créer l'index et mettre en place un serveur accessible. Pour le moment, j'ai la version 6.4.1 installée sur Windows (j'ai accès au localhost:9200). Après c'est vrai que j'ai du mal à savoir vers où continuer, sachant qu'à la finalité, j'ai mes données de couches qui existent aussi en GeoJSON (je ne sais pas si cela aide ou non)

**Comment by fefe78800** [comment]
Si j'ai bien compris, une fois l'index créé, on a les données qui sont ciblées directement avec l'identifiant de l'objet ? Ou si je pose la question autrement, la série d'attributs pour configurer le moteur de recherche par mots-clés est liée par défaut dans le JS de la démo ou inséré directement dans l'index ?

**Comment by fefe78800** [comment]
Bonjour,
Je reviens pour dire que j'ai trouvé la solution (je pense), concernant l'histoire du lien url. Il m'a été possible de générer un index avec elasticsearch-head sur chrome, et j'ai intégré les données une à une grâce à la requête WFS de la couche sur GeoServer en format GeoJSON (prévisualisation de couche). Maintenant je dois corriger quelques bugs encore dans mon programme js pour voir si cela fonctionne, notamment par rapport au cluster dans l'issue que j'ai posté ici (#130 ).

**Comment by spelhate** [comment]
Bonjour

> Pour le moment, j'ai la version 6.4.1 installée

Je ne connais pas cette version. Nous utilisons en prod une version 5.6.3
Il est donc possible que certaine requêtes ne fonctionnent plus.

> Si j'ai bien compris, une fois l'index créé, on a les données qui sont ciblées directement avec l'identifiant de l'objet 

Oui c'est celà. dans notre architecture, tous les objets géographiques servis par geoserver et indexés par Elasticsearch disposent d'un **id partagé** (champ search_id en base correspond à l'id de l'élément indexé dans Elasticsearch)

**Comment by fefe78800** [comment]
Bonjour, 
Je relance le sujet après avoir réalisé l'index correctement. J'ai une question concernant le paramétrage de la fenêtre de recherche pour dresser des requêtes. Est-elle générée directement par le JS, ou doit-elle être paramétrée ailleurs (comme dans le HTML par exemple) ?

**Comment by fefe78800** [comment]
Si vous avez besoin, le programme en question se trouve ici : 
[https://extranet.ville-houilles.fr/mviewer/customlayers/inventaire_DiST.js](url)

**Comment by fefe78800** [comment]
Finalement j'ai trouvé mon erreur, une erreur un peu bête: je n'ai pas pensé au customcontrol, ni au même attribut dans le XML. Mon outil semble fonctionner maintenant.

**Comment by fefe78800** [comment]
Après consultation, j'ai bien une barre qui s'affiche, mais qui ne se synchronise pas avec la couche lors de la saisie de termes malheureusement...

**Comment by Gaetanbrl** [comment]
Vous voulez-dire que lorsque vous réalisez une recherche, le volet affichant les résultats ne correspond pas avec ce qui est affiché dans la barre de saisie (recherche) mais plutôt à un résultat d'une saisie précédente ?

**Comment by fefe78800** [comment]
Non, lorsque je cherche à filtrer par des mots-clés ma couche, je n'ai absolument aucun changement, j'ai toujours le même nombre d'entités (donc c'est comme si ma barre de requêtes ne fonctionnait pas)

**Comment by fefe78800** [comment]
Oui j'ai bien des flux qui partent visiblement :
![image](https://user-images.githubusercontent.com/47820885/61116522-e2e0a900-a494-11e9-9c31-c91364a8e652.png)

**Comment by Gaetanbrl** [comment]
Quelle est la réponse d'un de ces flux ? Le premier par exemple.

**Comment by fefe78800** [comment]
La réponse est la même que le lien URL vers mon index: même nombre d'entités qu'au départ

**Comment by Gaetanbrl** [comment]
En comparant les flux qui partent, vous avez les mêmes paramètres (ou mêmes URL pour le dire ) pour des saisies différentes ? Ce qui signifierait qu'il n'y a pas de prise en compte de vos saisies, mais d'un paramètre fixé / static.

**Comment by fefe78800** [comment]
C'est ça; au final, aucune prise en compte des requêtes et le résultat de départ ne change pas

**Comment by Gaetanbrl** [comment]
> Si vous avez besoin, le programme en question se trouve ici :
> [https://extranet.ville-houilles.fr/mviewer/customlayers/inventaire_DiST.js](url)

Votre lien est mort, je n'arrive pas à y accéder.

**Comment by fefe78800** [comment]
Je n'arrive pas à insérer un lien valide vers le JS. Vous pouvez consulter le lien en ligne (hors github), pour voir le programme. Sinon, le voici en détail.


`     mviewer.customLayers.dist4 = (function () {

    _filter = false;
    _ready = false;
    _mode = "AND"; /*AND | OR*/
    _maxfeatures = 5000;
    _maxrequestedfeatures = 75;
    _featurescount = null;
    _searchinfields = [ "properties.services", "properties.dossier", "properties.date_debut" ];

    var _els2GeoJSON = function(data) {
        var geojson = {
            "type": "FeatureCollection",
            "features": []
        };
        var getProperties = function(source) {
            var properties = {};
            for (var propertyName in source) {
                if (["geometry", "@timestamp", "@version"].indexOf(propertyName) === -1) {
                    properties[propertyName] = source[propertyName];
                }
            }
            return properties;
        };
		data.hits.hits.forEach(function(item) {
			 var properties = getProperties(item._source);
            properties.type = item._type;
            properties.source = prop.source;
            var feature = {
                "type": "Feature",
                "id": item._id,
                "geometry": item._source.geometry,
                "properties": properties
            };
            geojson.features.push(feature);
        });
        return JSON.stringify(geojson);
    };

    var _elsLoader = function(extent, resolution, projection) {
        var filter = {
            "match_all": {}
        };
        if (_filter) {
            var matchQueries = [];
            _filter.forEach(function(text) {
                var matchQuery = {
                    "match": {
                        "_all": {
                            "query": text,
                            "operator": "and"
                        }
                    }
                };
                if (_searchinfields.length > 0) {
                    matchQuery = {
                        "multi_match" : {
                            "query":    text,
                            "operator": "and",
                            "fields": _searchinfields
                        }
                    };
                }
                matchQueries.push(matchQuery);
            });
            filter = {
                "bool": {
                    "should": matchQueries,
                    "minimum_should_match": (_mode === "AND")? matchQueries.length: 1
                }
            };
        }
        var proj = projection.getCode();
        var e = ol.proj.transformExtent(extent, proj, 'EPSG:3857');
        var url = "http://serv-sig2:9200/mviewer/_search?";
        var geofilter = JSON.stringify({
            "from": 0,
            "size": (_ready)? _maxfeatures: 100,
            "query": {
                "bool": {
                    "must": [
                        filter,
                        {
                            "bool": {
                                "should": [{
                                    "type": {
                                        "value": "dist4"
                                    }
                                }]
                            }
                        }
                    ],
                    "filter": {
                        "geo_shape": {
                            "geometry": {
                                "shape": {
                                    "type": "envelope",
                                    "coordinates": [
                                        [e[0], e[1]],
                                        [e[2], e[3]]
                                    ]
                                }
                            }
                        }
                    }
                }
            }
        });
        var xhr = new XMLHttpRequest();
        xhr.open('POST', url);
        var onError = function() {
            _vectorSource.removeLoadedExtent(extent);
        }
        xhr.onerror = onError;
        xhr.onload = function() {
            if (xhr.status == 200) {
                var json = JSON.parse(xhr.responseText);
                var message = "* Affichage complet - " + json.hits.total + " éléments";
                if (json.hits.total >  json.hits.hits.length) {
                    message = "* Affichage partiel : " +parseInt(json.hits.hits.length/json.hits.total*100) + "% des éléments" ;
                }
                _featurescount = json.hits.hits.length;
                $("#inventaire_search_messages i").text(message);
                _vectorSource.addFeatures(
                    new ol.format.GeoJSON().readFeatures(_els2GeoJSON(json), {
                        dataProjection: 'EPSG:4326',
                        featureProjection: proj
                    })
                );
            } else {
                onError();
            }
        }
        xhr.send(geofilter);
    };



    _legend = { items:[] };
    
	var etude = [ new ol.style.Style({
       image: new ol.style.Circle({
        fill: new ol.style.Fill({
            color: 'rgba(218,221,225,1.0)'
        }),
        stroke: new ol.style.Stroke({
            color: "#ffffff",
            width: 4
        }),
        radius: 9
    })
})];
 _legend.items.push({styles:etude, label: "Etude", geometry: "Point"});
	
	var consultation = [new ol.style.Style({
             image: new ol.style.Circle({
        fill: new ol.style.Fill({
            color: 'rgba(27,132,237,1.0)'
        }),
        stroke: new ol.style.Stroke({
            color: "#ffffff",
            width: 4
        }),
        radius: 9
    })
})];
 _legend.items.push({styles:consultation, label: "Consultation", geometry: "Point"});
	
	var execution = [new ol.style.Style({
          image: new ol.style.Circle({
        fill: new ol.style.Fill({
            color: 'rgba(237,27,27,1.0)'
        }),
        stroke: new ol.style.Stroke({
            color: "#ffffff",
            width: 4
        }),
        radius: 9
    })
})];
 _legend.items.push({styles:execution, label: "Execution", geometry: "Point"});
	
	var acheve = [new ol.style.Style({
             image: new ol.style.Circle({
        fill: new ol.style.Fill({
            color: 'rgba(27,237,27,1.0)'
        }),
        stroke: new ol.style.Stroke({
            color: "#ffffff",
            width: 4
        }),
        radius: 9
    })
})];
_legend.items.push({styles:acheve, label: "Achevé", geometry: "Point"});
	 
	var uniqueStyle = function(feature) {
        var stl;
        if (feature.get('etape')) {           
                switch (feature.get('etape')) {
                     case "Etude":
                        stl = etude;
                        break;
					case "Consultation":
                        stl = consultation;
                        break;
                    case "Execution":
                        stl = execution;
                        break;
                   case "Acheve":
                        stl = acheve;
                        break;					
                    default:
                        stl = etude;
                }
            }            
            return stl;
    };
   
    var manyStyle = function (radius, radius2, size) {
        return [
            new ol.style.Style({
                image: new ol.style.Circle({
                    radius: radius,
                    fill: new ol.style.Fill({
                        color: 'rgba(236, 240, 241,0.7)'
                    })
                }),
                stroke: new ol.style.Stroke({
                    color: 'red',
                    width: 3
              }),
              fill: new ol.style.Fill({
                color: 'rgba(0, 0, 255, 0.1)'
              })
            }),
            new ol.style.Style({
                image: new ol.style.Circle({
                    radius: radius2,
                    fill: new ol.style.Fill({
                        color: 'rgba(255, 147, 0, 0.9)'
                    })
                }),
                text: new ol.style.Text({
                    font: '12px roboto_regular, Arial, Sans-serif',
                    text: size.toString(),
                    fill: new ol.style.Fill({
                        color: '#fff'
                    })
                })
            })
        ];
    };
    _legend.items.push({styles:manyStyle(10,10,7), label: "Groupe de chantiers", geometry: "Point"});

    var clusterStyle = function(feature) {
        var size = feature.get('features').length;
        var max_radius = 40;
        var max_value = 500;
        var radius = 10 + Math.sqrt(size)*(max_radius / Math.sqrt(max_value));
        var radius2 = radius *80 /100 ;
        if (size == 1) {
            return uniqueStyle(feature.getProperties().features[0]);
        } else {
            return manyStyle(radius, radius2, size);
        }
    };

    var _layer = new ol.layer.Vector({
        source: new ol.source.Cluster({
            distance: 50,
            source: new ol.source.Vector({
                url: "https://extranet.ville-houilles.fr/geoserver/houillesSIG/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=houillesSIG:dist4&maxFeatures=50&outputFormat=application%2Fjson",
                format: new ol.format.GeoJSON()
            })
        }),
        style: clusterStyle

    });
    var _handle = function(clusters, views) {
        if (clusters.length > 0 && clusters[0].properties.features) {
            var features = clusters[0].properties.features;
            var elements = [];
            var l = mviewer.getLayer("dist4");
            features.forEach(function(feature, i) {
                elements.push({
                    properties: feature.getProperties()
                });
            });
            var html;
            if (l.template) {
                html = info.templateHTMLContent(elements, l);
            } else {
                html = info.formatHTMLContent(elements, l);
            }
            var view = views["right-panel"];
            view.layers.push({
                "id": view.layers.length + 1,
                "firstlayer": true,
                "manyfeatures": (features.length > 1),
                "nbfeatures": features.length,
                "name": l.name,
                "layerid": "dist4",
                "theme_icon": l.icon,
                "html": html
            });
        }

    };

    return {
        layer: _layer,
		handle: _handle,
        legend: _legend,
        mode: _mode,
        setFilter: function (val) { _filter = val; _ready = true; },
        getFilter: function () { return _filter; }
    };

}());
`

**Comment by fefe78800** [comment]
Je me rends compte aussi en comparaison avec la demo els2.xml, que les flux prennent la méthode POST tandis que pour moi, c'est GET, peut-être que cela a un rapport

**Comment by Gaetanbrl** [comment]
Il serait peut être plus sûr de reprendre dans un premier temps les mêmes éléments que la documentation. Ensuite si tout va bien et que tout est maîtrisé, vous pourrez évoluer avec vos propres modifications.

**Comment by fefe78800** [comment]
Oui, j'en suis parti, et j'avoue que manipuler ELS me semblait assez complexe, je vais revoir. D'autre part, toujours dans les flux, le lien vers lequel est faite chaque requête est le lien JSON de ma couche, et non le lien de l'index ELS

**Comment by fefe78800** [comment]
Bonjour,
Je relance une nouvelle fois le sujet. Avec mon index, j'ai respecté la mise en forme de la démo els2.xml et je suis parvenu à réaliser plusieurs requêtes grâce à mon extension ELS_head. Cela signifie a priori qu'il est en état de marche.
Toutefois, le problème vient toujours du lien vers lequel est fait l'indexation dans le projet. Il semblerait que ce soit la var _layer qui contrôle le lien URL vers lequel faire ces indexations, ce qui explique pourquoi elles sont faites sur le WMS en JSON (du customlayer). Dans la demo, le lien est conditionné par la var _vectorsource, elle-même dépendante de _elsLoader. 
Malheureusement, en suivant cet exemple, je perds le style de ma couche (qui pour l'instant ne fonctionne qu'avec un flux vers GeoServer) et toute indexation est impossible, toute requête n'aboutissant pas

**Comment by spelhate** [comment]
Bonjour,
Avez vous réussi à faire fonctionner l'exemple le plus simple https://github.com/geobretagne/mviewer/blob/master/demo/els.xml en utilisant votre propre instance ELS ? Je pense que c'est un prérequis avant d'aller plus loin. 
Pour rappel, la doc et les données démo à indexer sont disponibles ici : https://mviewerdoc.readthedocs.io/fr/latest/doc_dev/config_els.html

**Comment by spelhate** [comment]
> Oui j'ai bien des flux qui partent visiblement :
> ![image](https://user-images.githubusercontent.com/47820885/61116522-e2e0a900-a494-11e9-9c31-c91364a8e652.png)

Normalement, les requêtes devraient directement taper votre instance ELS et ici ce n'est pas le cas.

**Comment by fefe78800** [comment]
Oui c'est le problème que j'expliquais plus haut. Pour la demo els.xml, j'avais réussi à faire l'index comme tel, en suivant la documentation, à faire des requêtes à travers l'instance ELS_head sur Chrome, mais je n'arrive pas à installer l'index sur Mviewer, le message disant "Problème avec l'instance Elasticsearch. Désactivation du service." dès que je tape dans la barre de recherche en haut à droite

**Comment by spelhate** [comment]
La  version d'ELS est 6.4.1 ?
 l'instance ELS est accessible depuis l'extérieur ?
Pour mette toutes les chance de votre côté, vous pouvez tester avec la version que j'utilise et qui est précisée dans la doc : https://www.elastic.co/fr/downloads/past-releases/elasticsearch-5-6-0

**Comment by fefe78800** [comment]
Oui c'est cette version. Malheureusement, hors de mon PC, l'index n'est pas atteignable non plus (problème d'adresse IP)

**Comment by spelhate** [comment]
Je ne sais pas si ça fonctionne avec la dernière version d'ELS. Vous pouvez tester l'exemple els.xml avvec la version 5.6.0 ?

**Comment by fefe78800** [comment]
Je n'ai pas pu réussir non plus visiblement malheureusement...

**Comment by Jack3113** [comment]
Je suis avec AWS ElasticSearch en version 6.7 et depuis la version 6.0.0 ils ont forcé les headers en application/json du coup il y a une erreur lors du requetage sur l'input de recherche :

> Content-Type header [application/x-www-form-urlencoded; charset=UTF-8] is not supported

**Comment by Jack3113** [comment]
Si ton problème est bien celui que je décris ci dessus, il faut dé-commenter la ligne 513 du fichier search.js : https://github.com/geobretagne/mviewer/blob/master/js/search.js#L513

**Comment by spelhate** [comment]
Et si ça peut aider, Je testerai après la rentrée une version 7 d'ELS.

**Comment by spelhate** [comment]
> Je suis avec AWS ElasticSearch en version 6.7 et depuis la version 6.0.0 ils ont forcé les headers en application/json du coup il y a une erreur lors du requetage sur l'input de recherche :
> 
> > Content-Type header [application/x-www-form-urlencoded; charset=UTF-8] is not supported

Merci pour l'info

**Comment by fefe78800** [comment]
Merci à vous. Je vais voir ce que cela peut donner sur le projet. Il semble aussi que dans mon codage du customlayer, il y ait un conflit entre les URL pour la couche de données de ma légende et l'index, j'ai bien essayé de ne saisir que la catégorisation avec le lien index, mais sans résultat

**Comment by bchartier** [comment]
Je ferme ce ticket ?
