### ISSUE TITLE
Line chart pour chaque territoire

### ISSUE THREAD

**Issue by fefe78800** [geobretagne/mviewer#128]
Bonjour,
Je créé une application pour faire un observatoire du foncier avec des graphiques Chart.js. Je veux faire des graphiques d'évolution de prix au m² entre 2016 et 2018 par maison et par appartement pour chaque quartier d'une commune. 

J'ai compris au travers des exemples sur Kartenn Territoires que la table attributaire ne devait pas s'afficher de la même manière que d'autres graphiques (lorsque je fais des graphiques en barres pour chaque année et territoire, j'ai la table avec une duplication des entités par année) puisqu'ici, ce sont les champs qui sont dupliqués. Le seul problème est que je n'arrive pas à trouver la solution pour appeler les données. Celles-ci sont appelées par des var avant d'être incorporées dans un dataset. 

Voici un extrait de mon code (je suis désolé, je n'ai pas su mettre le codage correctement):
`var aut_ind_15 = [];
        {{#features}}
            aut_ind_15.push('{{app2016}}');
        {{/features}}

  var aut_col_15 = [];
        {{#features}}
            aut_col_15.push('{{app2017}}');
        {{/features}}

  var aut_tot_14 = [];
        {{#features}}
            aut_tot_14.push('{{app2018}}');
        {{/features}}
var aut_tot_15 = [];
        {{#features}}
            aut_tot_15.push('{{log2016}}');
        {{/features}}
var aut_tot_16 = [];
        {{#features}}
            aut_tot_16.push('{{log2017}}');
        {{/features}}
		var aut_tot_17 = [];
        {{#features}}
            aut_tot_17.push('{{log2018}}');
        {{/features}}
//Création du graphique 1
	 var indicateur_a = {};
  indicateur_a.getData = function () {
    var data = {ConstChart2: {labels:["2016", "2017","2018"], data: {datasets:[[aut_col_15,aut_ind_15,aut_tot_14,aut_tot_15,aut_tot_16,aut_tot_17]]}}};
    indicateur_a.drawChart(data);
  };    
  
  indicateur_a.drawChart = function (data) {
			var ctx = document.getElementById("ConstChart2_");
			var ConstChart2 = new Chart(ctx, {
			type: 'line',
			data: {
			labels: data.ConstChart2.labels,
			datasets: [{
							label: 'Part selon le type',
							backgroundColor: [
								"rgba(30,255,255,0.9)",
								"rgba(195,30,255,0.9)",
								"rgba(249,183,0,0.9)"
							],
							hoverBackgroundColor: [
								"rgba(30,255,255,1)",
								"rgba(195,30,255,1)",
								"rgba(249,183,0,1)"								
							],
							borderWidth: 3,
							data: data.ConstChart2.data.datasets[0]
						},{
							label: 'Part selon le type',
							backgroundColor: [
								"rgba(30,255,255,0.9)",
								"rgba(195,30,255,0.9)",
								"rgba(249,183,0,0.9)"
							],
							hoverBackgroundColor: [
								"rgba(30,255,255,1)",
								"rgba(195,30,255,1)",
								"rgba(249,183,0,1)"								
							],
							borderWidth: 3,
							data: data.ConstChart2.data.datasets[0]
						}]
					},	
			options:{
				legend:{
					display: true, 
					labels:{
						fontFamily:'Open Sans',
						fontSize:11,
						boxWidth:15,
						padding:5,
					}
				},
				 title: {
      display: true,
      text: 'Type de résidents',
	  fontSize:14
    },
				tooltips: {
		        	backgroundColor:"rgba(36, 36, 36, 0.85)",
		            callbacks: {
		                label: function(tooltipItem, data) {
		                    return parseFloat(data.datasets[0].data[tooltipItem.index]).toFixed(2).toLocaleString() + " %";
		                }
		            }
		        }
			}
			}); 
	};
    if  (typeof Chart === 'function') {
      indicateur_a.getData();
  } else {
      $.get('https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.min.js', function() {
        indicateur_a.getData();
        
      }); 
  }	` 
Un résultat est donné ici :
![image](https://user-images.githubusercontent.com/47820885/58257403-278f7400-7d71-11e9-9e65-8fb9d0692501.png)

Ce que j'ai fait reprend la configuration du fichier construction.mst du logiciel.

Merci pour vos réponses

**Comment by spelhate** [comment]
> Je veux faire des graphiques d'évolution de prix au m² entre 2016 et 2018 par maison et par appartement pour chaque quartier d'une commune.

Le code suivant me semble étrange 
` data: {datasets:[[aut_col_15,aut_ind_15,aut_tot_14,aut_tot_15,aut_tot_16,aut_tot_17]]};`

Il faudrait quelquechose de la forme :
`data: { datasets: [[ind_16, ind_17, ind_18], [col_16, col_17, col_18]]}` on a un dataset pour l'individuel (3 première valeurs encadrées par des crochets et un pour le collectif (3 autres valeurs encadrées par des crochets.

**Comment by fefe78800** [comment]
Merci pour votre réponse. Malheureusement, cette solution ne semble pas fonctionner (ou du moins, il doit y avoir autre chose à faire; lorsqu'il faut appeler les données (dans la partie drawChart) faut-il appeler par data.ConstChart2.data.datasets[0] et data.ConstChart2.data.datasets[1] ?

Sinon je me suis basé sur un autre exemple, peut-être plus clair dans le codage, mais j'en suis au même résultat qu'avant :  
` var chartColors = {
  red: 'rgb(220,20,60)',
  orange: 'rgb(255, 159, 64)',
  yellow: 'rgb(255, 205, 86)',
  green: 'rgb(50,205,50)',
  blue: 'rgb(0,191,255)',
  purple: 'rgb(128,0,128)',
  grey: 'rgb(231,233,237)'
};
var Year= ["2016","2017","2018"];
var config = {
  type: 'bar',
  data: {
    labels: Year,
    datasets: [{
      label: "Maison",
      backgroundColor: chartColors.red,
      borderColor: chartColors.red,
      data: {datasets:[[log2016,log2017,log2018]]},
      fill: false,
    }, 
	{
      label: "Appartement",
      fill: false,
      backgroundColor: chartColors.blue,
      borderColor: chartColors.blue,
      data: {datasets:[[app2016,app2017,app2018]]},
    }]
  },
  options: {
				legend:{
					display: true, 
					labels:{
						fontFamily:'Open Sans',
						fontSize:11,
						boxWidth:1,
						padding:5,
					}
				},
    responsive: false,
    title: {
      display: true,
      text: 'Evolution du prix médian au m²',
	  fontSize:14
    },

    tooltips: {
     enabled: true,
                mode: 'single',
                callbacks: {
                    label: function(tooltipItems, data) { 
                        return tooltipItems.yLabel + ' €';
                    }
                }
    },
    hover: {
      mode: 'nearest',
      intersect: true
    },
    scales: {
      xAxes: [{
        display: true,
        scaleLabel: {
          display: true
        }
      }],
      yAxes: [{
        display: true,
        scaleLabel: {
          display: true,
          labelString: 'Valeur au m²'
        }
      }]
    }
  }
};
var ctx = document.getElementById("ConstChart2_").getContext("2d");
window.myLine = new Chart(ctx, config);`

**Comment by bchartier** [comment]
Je peux fermer ce ticket ?
