### ISSUE TITLE
Moustache lien hypertexte

### ISSUE THREAD

**Issue by fxduponcheel** [geobretagne/mviewer#129]
Ma question est toute simple : Est t il possible d'activer un lien hypertexte avec moustache ? 
Pour résumer : je souhaite donner la possibilité d'accès à des page internet via le bandeau information. L'adresse étant contenue dans un champs de ma couche ("lien_arrete" dans l'ex ci dessous)

<span style="font-family:'roboto_bold'"> Lien vers l'arrêté préfectoral :</span> {{lien_arrete}} <br/>

ça m'affiche effectivement le lien internet, mais j'aimerai que la page internet s'ouvre en cliquant sur le lien ...

Merci pour vos réponses

**Comment by fefe78800** [comment]
Bonjour,
Peut-être la manière que vous cherchez est la suivante : 
<a href="{{lien_arrete}}" target="_blank">{{lien_arrete}}</a>

**Comment by spelhate** [comment]
Bravo pour la rapidité. C'est tout à fait ça.

**Comment by fxduponcheel** [comment]
Merci je vais essayer de suite

**Comment by fxduponcheel** [comment]
très bien merci
