### ISSUE TITLE
Proxy

### ISSUE THREAD

**Issue by tanguyj** [geobretagne/mviewer#13]
Annoter le fichier config.xml quand on a pas de proxy pour éviter les problèmes d'interrogation qui ne fonctionne pas

Tanguy

**Comment by spelhate** [comment]
Oui

**Comment by Gaetanbrl** [comment]
@spelhate @bchartier cette issue est toujours d'actualité ? @tanguyj

**Comment by bchartier** [comment]
Bonne question.
De mon côté je ne comprends pas ce que ce ticket suggère.
