### ISSUE TITLE
Récupération de l'url de la couche sélectionnée

### ISSUE THREAD

**Issue by MoMouss** [geobretagne/mviewer#134]
Bonjour,

Je travaille actuellement sur un projet dont lequel on réalise un mviewer  qui réponds à certains besoins. 

Un de ces besoins est le téléchargement des images affichées. J'ai donc voulu faire dans la couche principale un contrôle sous la forme d'un bouton  'Download'. L'événement 'onclick' de ce bouton est sensée être la fonction JS window.open('') (sensée ouvrir l'image dans un nouvel onglet afin que l'utilisateur puisse la sauvegarder via un clique droit de la souris). Le paramètre à entrer à la fonction est évidemment la requêtes WMS GetMap avec tous les paramètres adéquats (BBOX, TIME, etc).  

Mon problème, c'est que je ne sais pas comment identifier (via l'id) la couche que l'utilisateur a sélectionné sur le mviewer (ou la couche la plus élevée, s'il a activé plusieurs couches). Comment puis-je faire cela (en JavaScript) ? (je sais que l'objet mviewer possède la fonction getLayers() mais elle renvoie toutes les couches, et pas celle sélectionnée par l'utilisateur). 
De plus, comment pourrai-je récupérer l'url de la requête de cette couche (les paramètres du service WMS), y a t'il une fonction toute prête qui me la retourne en String ? 
Dernier élément, comment récupérer le degré de Zoom ? (L'image que pourra télécharger l'utilisateur devra respecter le zoom qu'l a configuré sur le mviewer) 

Si je n'ai pas été très clair dans la formulation de mes questions, faites-le moi savoir.

Merci d'avance.

Ps: Si vous avez une meilleur suggestion/idée par rapport à la fonction de téléchargement de l'image affichée, je suis preneur.

**Comment by spelhate** [comment]
Bonjour,

> Mon problème, c'est que je ne sais pas comment identifier (via l'id) la couche que l'utilisateur a sélectionné

 

Pour récupérer la couche sélectionnée par l'utilisateur, plusieurs solutions sont possibles.

Vous pouvez utiliser la méthode publique mviewer.getLayers()[layerid] si vous disposez de l'id de la couche. L'id de la couche est présent dans chaque bloc de données via un attribut html :  `data-layerid`

> De plus, comment pourrai-je récupérer l'url de la requête de cette couche (les paramètres du service WMS), y a t'il une fonction toute prête qui me la retourne en String ?

Pas à ma connaissance, mais on peut récupérer tous les paramètres d'URL exemple ;
mviewer.getLayers()[layerid].layer.getSource().getParams()

> Ps: Si vous avez une meilleur suggestion/idée par rapport à la fonction de téléchargement de l'image affichée, je suis preneur.

Il existe nativement une fonction d'export de la carte au format image activable via le paramètre d'application exportpng=true. cf : README;md
