### ISSUE TITLE
Chargement dynamique d'un fichier de type csv avec une information de localisation

### ISSUE THREAD

**Issue by spelhate** [geobretagne/mviewer#135]
L'objectif de cette évolution est de s'ouvrir à des utilisateurs non experts en leur permettant de charger et de visualiser leurs propres données locales de type texte délimité (fichiers csv).

Pour ce faire, je compte utiliser l'API https://adresse.data.gouv.fr afin de géocoder le fichier et ensuite l'afficher dans la carte sous la forme d'une couche de donnée normale.

Etape 1

- le géocodage pourra se faire sur la base d'un fichier disposant d'un code INSEE, d'une adresse...
- le résultat sera un affichage brut du résultat sous forme de points/clusters.

Etape 2 (si opportunité)

- stylage du résultat (forme, couleurs, classes), 
- persistence du résultat

Merci @Gaetanbrl pour la piste. Les remarques et conseils sont les bienvenus.

**Comment by spelhate** [comment]
Travail en cours dans la branche csv : https://github.com/geobretagne/mviewer/tree/csv

Démo ici : http://kartenn.region-bretagne.fr/csv/

**Comment by Gaetanbrl** [comment]
A fermer @spelhate ?

**Comment by spelhate** [comment]
Je le fais. Merci.
