### ISSUE TITLE
Publication d'une nouvelle documentation Mviewer

### ISSUE THREAD

**Issue by fefe78800** [geobretagne/mviewer#138]
Bonjour,
Sous l'accord de @spelhate , je poste ici une première version de fonctionnalités d'outils à coder pour Mviewer.  Vous trouverez entre autres des fonctions de personnalisation de styles avec icônes (pour WMS ou customlayer), comment mettre en place une variation temporelle avec GeoServer, ou bien mettre en place un style, et programmer des graphiques grâce à Chart.js.
[Méthodologie de quelques fonctionnalités Mviewer-Geoserver.pdf](https://github.com/geobretagne/mviewer/files/3358338/Methodologie.de.quelques.fonctionnalites.Mviewer-Geoserver.pdf)

Vos retours et vos remarques sont les bienvenus pour améliorer la documentation.

**Comment by spelhate** [comment]
Merci pour cette contribution. Mes remarques :
Page 6 du document, l'extrait de code surligné ne correspond pas à ce qui est expliqué.
En effet, le controle MousePosition est une fonctionnalité de mviewer qui permet d'afficher les coordonnées lors d'un clic sur la carte, il ne s'agit pas du pointeur sur la carte.
Sur la version mobile, page 8, je suis d'accord, il faut améliorer le cadrage au démarrage en fonction du support utilisé. Ceci justifie la création d'une issue sur Github.
Par contre je comprends mieux pourquoi vous avez eu des soucis avec le passage à la version mobile.
Je comprends en effet que vous avez modifié le fichier index.html, ce qu'il ne faut pas faire si on souhaite rester compatible avec les versions futures.
Avec le seul fichier index.html de mviewer, il est possible d'avoir plusieurs applications différentes tout en conservant l'intégrité du coeur de mviewer.
application 1 = http://monserveur/mviewer/#application1 ou http://monserveur/mviewer/?config=application1xml ou http://monserveur/mviewer/index.html?config=application1.xml
application 2 = http://monserveur/mviewer/#application2 ou http://monserveur/mviewer/?config=application2xml ou http://monserveur/mviewer/index.html?config=application2.xml

Dans le même esprit, sur le shéma de la dernière page je renommerai Carte.html en index.html pour rester fidèle à la philosophie de l'application.
Merci pour votre retour d'expérience, je pense que vos travaux pourront aider de nouveaux utilisateurs.

**Comment by fefe78800** [comment]
Bonjour
Merci pour vos retours. La doc a été mise à jour avec vos remarques, et avec les autres fonctionnalités ajoutées (création d'un carrousel avec les templates, cluster catégorisé)

**Comment by Gaetanbrl** [comment]
Bonjour,
Merci pour cette documentation qui sera utile à beaucoup d'utilisateurs.
Un petit bémol pour la lisibilité du code, c'est peut être mon écran mais je dois faire un zoom fort pour lire le code, ce qui entache un petit peu la qualité.

Une petite question cependant.
Au niveau des clusters, est-il obligatoire de dupliquer du code au niveau des styles ? 
Car selon votre attribut, seuls Fill et Stroke sont modifiés. Un seul style peut suffire à l'aide d'un un "switch" pour conditionner les valeurs de Stroket et Fill, à l'image de ce que vous avez déjà réalisé.

Un exemple pour jouer sur la taille des clusters avec une seule règle de style : 

```
clusterStyle() {
    let cache = {};
    return function(feature) {
        const size = feature.get('features').length;
        let style = cache[size];
        const sizeRules = function(size) {
            if (size === 1) {
                return 10;
            }
            if (size > 1 && size < 16) {
                return 15;
            }
            if (size > 15 && size < 31) {
                return 20;
            }
            if (size > 30 && size < 40) {
                return 25;
            }
            return 30;
        };
        if (!style) {
            if (size > 1) {
                style = createStyle({
                    imageRadius: sizeRules(size), // default 10,
                    strokeColor: '#fff',
                    fillColor: 'rgba(234, 124, 8, 1)',
                    text: size.toString(),
                    textFillColor: '#fff',
                    opacity: 0.5,
                });
            } else {
                style = new Style({
                    image: new Icon({
                        src: './img/star-image.png',
                        scale: 0.4
                    }),
                });
            }
            cache[size] = style;
        }
        return style;
    }
},
```

Un autre exemple hors cluster mais c'est toujours le même principe, pour changer la source d'une icône de l'image selon un attribut et créer une pseudo classification :
_Toujours avec une seule règle de style._
 ```
// fonction qui permet de passer un paramètre "format" spécifique pour la création du style
// utile pour des valeur hors scope (this) de la fonction qui crée le style
featuresStyle: function(format) {
    // création du style avec prise en compte du paramètre "format" inaccessible autrement
    return function(feature) {
        // récupérer la valeur d'attribut en fonction du nom de l'attribut qui peut changer selon la source
        let val = feature.get('Code_Catégorie') ? feature.get('Code') : feature.get('styleUrl');
        let icon;
        let color = 'red';
        let path = './lib/icons/map-icons/';
        // si c'est une source KML -> selon une variable globale
        if (format === 'KML' || val.indexOf('icon') > -1) {
            color = 'orange';
            // test de la valeur pour trouver une catégorie que l'on trouve selon le style présent dans le KML
            // permet de rendre le switch "standard" pour une donnée qui ne l'est pas
            val = val.indexOf('icon-1502') < 0 ? 'DET' : 'CHR';
        }
        switch (val) {
            case 'DET':
                icon = 'store';
                break;
            case 'CHR':
                icon = 'restaurant';
                break;
            case 'ASS':
                icon = 'embassy';
                break;
            default:
                icon = 'other';
        };
        let style = new Style({
            image: new Icon({
                // source dynamique en fonction de l'attribut
                src: path + icon + '-' + color + '.svg',
                scale: 0.8
            })
        });
        return style;
    };
}
```
 
Ce ne sont que des propositions mais cela permet de gagner un peu de temps à l'édition et parfois en lisibilité pour des codes assez dense.

**Comment by fefe78800** [comment]
Vous avez sans doute raison, mes propositions ne sont sûrement que des possibilités de codage parmi d'autres, et j'imagine que des solutions plus simples et rapides peuvent exister. Je n'ai pas beaucoup d'expérience surtout en ce qui concerne le JS, et je conçois bien qu'il puisse exister une manière de coder plus rapide.

Pour les extraits de code, je vais regarder ça de plus près

**Comment by Gaetanbrl** [comment]
> j'imagine que des solutions plus simples et rapides peuvent exister. Je n'ai pas beaucoup d'expérience surtout en ce qui concerne le JS.

Il n'y a en effet jamais qu'une seule bonne solution. Si votre code est fonctionnel et vous convient c'est le plus important. Pour le reste, on est aussi ici pour échanger et partager sur nos pratiques avant tout :) .

**Comment by bchartier** [comment]
Quelle suite donnons-nous à ce ticket ? Est-ce que certains éléments doivent être repris dans la documentation officielle ?

**Comment by Gaetanbrl** [comment]
Je pense que l'on peut fermer ce ticket, on pourra toujours le retrouver avec les nouveaux tag #189 😉

**Comment by bchartier** [comment]
Ok.
