### ISSUE TITLE
Moteur de recherche par adresse ciblé sur une commune

### ISSUE THREAD

**Issue by fefe78800** [geobretagne/mviewer#139]
Bonjour,
Je recherche actuellement pour la carte interactive de la ville de Houilles une méthode permettant de ne retenir pour la barre de recherche principale, les adresses postales dans la commune en elle-même. J'ai constaté dans le script de Mviewer que la BAN ou Geoportail sont utilisés par défaut sur l'ensemble de la France.
Y aurait-il un moyen de ne retenir que les adresses de la commune de Houilles ?

**Comment by Gaetanbrl** [comment]
L'API de la BAN est assez bien réalisée de ce côté.
La documentation montre différents paramètres à ajouter dans la la requête pour réaliser une restriction ou une limite géographique :

![image](https://user-images.githubusercontent.com/16317988/60660093-46485680-9e57-11e9-9e87-bd5481cc60bd.png)

![image](https://user-images.githubusercontent.com/16317988/60660103-4d6f6480-9e57-11e9-84b7-4f94e09e70ee.png)

 Pour la documentation c'est par ici : 
https://adresse.data.gouv.fr/api

**Comment by fefe78800** [comment]
Bonjour
Merci beaucoup pour votre piste ! Je vais la mettre en place sur mon projet.

**Comment by fefe78800** [comment]
Ca fonctionne, merci encore !

**Comment by Gaetanbrl** [comment]
Parfait. Je vous invite dans ce cas à fermer cette issue 🙂
