### ISSUE TITLE
BaseLayer

### ISSUE THREAD

**Issue by tanguyj** [geobretagne/mviewer#14]
Il serait peut-etre judicieux de mettre par défaut dans le fichier config des 'baselayer' qui fonctionne sans les clés IGN

**Comment by spelhate** [comment]
Très juste

**Comment by ebocher** [comment]
This one could be used for world imagery

```xml
<baselayer  type="OSM" id="esriworldimagery" label="World imagery" title="World imagery" thumbgallery="img/basemap/scan.jpg"
            url="http://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}" visible="false" 
            attribution="Tiles &copy; Esri &mdash; Source: Esri, i-cubed, USDA, USGS, AEX, GeoEye, Getmapping, Aerogrid, IGN, IGP, UPR-EGP, and the GIS User Community" />
```

**Comment by spelhate** [comment]
Thanks

**Comment by Gaetanbrl** [comment]
Ou alors un config exemple "baseLayer" qui permet de récupérer tous les fonds. Mais cela existe peut être déjà  🙊

**Comment by spelhate** [comment]
Il y a celui ci, mais il n'est pas exhaustif : http://kartenn.region-bretagne.fr/kartoviz/?config=demo/fonds.xml

**Comment by bchartier** [comment]
L'idée c'est de mettre à jour le fichier config-sample.xml en remplaçant les fonds par ceux de http://kartenn.region-bretagne.fr/kartoviz/?config=demo/fonds.xml ?

**Comment by spelhate** [comment]
Ou de mettre à jour le fichier https://github.com/geobretagne/mviewer/blob/master/demo/fonds.xml.
Qu'est ce qui est mieux d'après vous ?

**Comment by bchartier** [comment]
Je pense qu'on devrait mettre à jour les deux fichiers avec les mêmes fonds.

**Comment by lecault** [comment]
Il s'agirait de mettre les même base layers sur https://github.com/geobretagne/mviewer/blob/master/demo/fonds.xml et https://github.com/geobretagne/mviewer/blob/master/apps/default.xml ?

Si oui, je peux m'en charger.
