### ISSUE TITLE
Disparition de la légende sur une couche avec échelles de visibilités

### ISSUE THREAD

**Issue by pigma** [geobretagne/mviewer#142]
Bonjour,

Dans la légende de mes couches sur lesquelles j'ai mis uns échelle de visibilité, la légende disparaît dès lors que j’agis sur le zoom et que la couches est en mode masquée. Dès que la couche apparaît sur la carte, la légende réapparaît. Au démarrage de l'application toutes les légendes sont présentes.

![affiche_erreur](https://user-images.githubusercontent.com/3725336/62605990-8b025a00-b8fb-11e9-9757-f87c252694b4.png)
![affiche](https://user-images.githubusercontent.com/3725336/62605991-8b025a00-b8fb-11e9-96ec-e64f22850f01.png)

**Comment by spelhate** [comment]
Pouvez-vous joindre le config.xml pour reproduire et tester ?

**Comment by pigma** [comment]
https://www.pigma.org/public/nathdv2/config.xml

**Comment by Gaetanbrl** [comment]
Le "Légende non disponible" s'affiche en raison d'une image "invisible.png" que la carte doit afficher dans la légende mais qui n'existe pas.
![image](https://user-images.githubusercontent.com/16317988/62612764-5a74ed00-b908-11e9-9ab0-6d7becf56e67.png)

En regardant [cette fonction](https://github.com/geobretagne/mviewer/blob/master/js/mviewer.js#L808) de la librairie mviewer.js, il semblerait que ce soit un nom d'image en dur qui s'affiche dans un cas précis en fonction des échelles min et max d'une couche  et de l'échelle de la carte courante.

Pouvez-vous vérifier la configuration de votre échelle max et min pour la couche AMII ?

**Comment by pigma** [comment]
J'ai redéfinie mes échelles mes données s'affichent bien. J'ai l'impression que le souci est au niveau de l'appel de l'image. J'ai dupliqué "nolegend.png" et l'ai renommé en "invisible.png" et j'ai bien l'image "Légende non disponible" qui s'affiche. 

Par contre à l'initialisation de la page, ma couche "Fibre optique (Ftth/Ftte)" affiche la légende avec le symbole de non visibilité puis dès que je zoom "Légende non disponible" s'affiche.

**Comment by Gaetanbrl** [comment]
En effet, il semble que si une couche a une limitation d'échelle, en dehors de ces limites, la légende s'affichent avec ce message si vous n'avez pas défini d'image "invisible.png".
Vous pouvez sûrement palier rapidement à ce problème en définissant une image "invisible.png" (image blanche ou la même que la légende dans ses limites).

@spelhate  est-ce le comportement prévu ?

**Comment by spelhate** [comment]
Pour aider, cette démo utilise des plages de visibilité pour la couche parcelles.
http://kartenn.region-bretagne.fr/kartoviz/?x=-190341&y=6125907&z=15&l=CPCadastralParcel*&lb=ortho1&config=demo%2Fcadastre.xml&mode=d

En dézoomant, la légende est remplacée par un symbole de non visibilité. le paramétrage utilisé côté mviewer est le suivant :` scalemin="0" scalemax="25000"`
Et côté geoserver : `<MaxScaleDenominator>20000.0</MaxScaleDenominator>`

Dans le comportement, invisible.png est une image blanche qui se substitue à la légende normale si la couche est dans la plage d'invisibilité, nolegend.png est une image avec un texte incrusté ""Légende non disponible" qui s'affiche lorsque la légende n'est pas disponible côté serveur carto (geoserver, mapserver...)

**Comment by pigma** [comment]
Merci pour les précisions. 

Est-il possible de forcer l'affichage de la légende pour que celle-ci soit visible même quand la couche n'est pas visible ?

**Comment by spelhate** [comment]
A tester : dans le config.xml, utiliser le paramètre `legendurl="url-de-ma-legende"`

**Comment by pigma** [comment]
Je viens de tester, la légende est toujours masquée lorsque la couche n'est pas visible.

Cela pourrais être une option pour le permettre ?

**Comment by spelhate** [comment]
Ou bien modifier le comportement : si le paramètre legendurl est renseigné, alors la légende est considérée comme statique et systématiquement affichée.

**Comment by pigma** [comment]
le comportement de disparition de l'image "Légende non disponible" lors du zoom n'est pas présent sur Mozilla.

**Comment by bchartier** [comment]
@spelhate @Gaetanbrl : je n'ai pas tout suivi en détail... c'est un bug à corriger ou c'est problème de configuration de la carte ?

**Comment by Gaetanbrl** [comment]
Il faudrait que je me remette dedans, mais cela ressemblait je crois à un comportement indésirable (bug). A vérifier.

**Comment by Gaetanbrl** [comment]
pop pour @pigma .

J'ai 3 couches avec 3 seuils de visualisation différents : niveau régional / niveau départemental / niveau communal : 
* \> 2000000
* 1000001 à 2000000
* 0 à 1000000

J'ai utilisé une l[égende dynamique](https://github.com/geobretagne/mviewer/issues/255) mais visiblement ce n'est pas lié si j'en crois cette issue.

Lorsque je zoom + / zoom - j'avais une erreur car le Mviewer recherche une image `invisible.png` qui par défaut n'existe pas (comme décrit plus haut). 

![image](https://user-images.githubusercontent.com/16317988/79962838-dc05ae80-8488-11ea-8f05-de7cb108658d.png)

J'ai donc placé une image temporairement pour voir dans le répertoire `/img` racine. Ce n'est pas super sexy donc quand une couche n'est pas visible, mais ça fait le boulot.

![image](https://user-images.githubusercontent.com/16317988/79962520-6d285580-8488-11ea-8e42-2e4ebb2fd79b.png)

Je constate que par contre le petit œil à droite qui est géré automatiquement s'affiche.

### **Le problème**

1 - Le petit oeil persiste alors que ma couche est visible : 

![image](https://user-images.githubusercontent.com/16317988/79962682-a52f9880-8488-11ea-9d38-73af538d5c56.png)

2 - Lorsque je zoom +, ma légende reste visible alors que je devrais voir mon image indiquant que la légende n'est pas visible. Mais cela vient probablement de ma gestion de légende dynamique.

Je vais regarder déjà pour le soucis du petit oeil. Je pense qu'on devrait avoir soit l'image soit le petit oeil mais pas les deux car son placement n'est pas optimal.

**Comment by Gaetanbrl** [comment]
Pour le petit oeil qui reste persistant c'est dû à un contrôle qui est fait sur sur un `undefined `: 

https://github.com/geobretagne/mviewer/blob/70fcf195820ab3ba3f2f3df0085d6574a22d0464/js/mviewer.js#L824

En effet, il faut un `scalemin` et un `scalemax` même pour la dernière échelle. Dans mon cas je n'avais pas de `scalemax`, pour toutes les données au dessus de la région (France, Monde) car je ne pensais pas avoir à en mettre une.

**Comment by Gaetanbrl** [comment]
Commit réalisé sur la branche `issue-142` pour ajouter une gestion d'affichage de la légende dynamique (vecteur).

**Comment by spelhate** [comment]
Testé avec la demo vector.xml. Ca fonctionne mais j'ai une erreur 404 sur l'image img/invisible.png qui est censée se substituer à la légende.

**Comment by Gaetanbrl** [comment]
oui on a cette erreur 404 depuis le début. Je n'avais pas d'image invisible.png dans le répertoire mviewer/img.

j'en ai mis une manuellement et c'était bon.

**Comment by Gaetanbrl** [comment]
je confirme qu'il n'y en a pas après le clone GitHub: 
https://github.com/geobretagne/mviewer/tree/master/img

**Comment by spelhate** [comment]
On peut mettre une image transparente de 1px. Auparavant, il me semble que c'était une image avec un texte incrusté "Couche non visible à cette échelle"

**Comment by Gaetanbrl** [comment]
J'aime assez l'idée de mettre une image de manière libre.
Autrement on peut ne rien afficher avec une mécanique de fermeture des actions de la couche qui n'est plus visible.

En attendant on peut rajouter une image standard pour ce bug et passer en évolution le reste @spelhate  ?

**Comment by Gaetanbrl** [comment]
@pigma est-il possible de faire comme suit : 

- Ajouter une image nommée "invisible.png" dans le répertoire /mviewer/img
- Si possible, tester les derniers correctifs de la branche develop

Autrement, on attendra qu'une release soit faite pour que vous puissiez tester les nouveautés / correctifs directement depuis la branche master avant de fermer ce bug (si corrigé).

**Comment by Gaetanbrl** [comment]
Après retour et reprise sur cette issue :
- [ ] Développement + test du code de gestion de la légende vectorielle

- [ ]  il faut ajouter une image `img/invisible.png` standard dans le répertoire `/img` du Mviewer

- [ ] Créer une issue pour le paramétrage de l'image img/invisible.pn standard ou selon l'URL passée par l'utilisateur (+ doc)

**Comment by vfabry** [comment]
Bonjour,
Je n'ai pas bien compris : ce bug a été corrigé, finalement ? Je suis sur la dernière release, et la légende ne s'affiche pas si j'ai un paramètre `scalemax="50000"` dans la définition d'une couche.
Vincent
