### ISSUE TITLE
Timefilter using all kind of data

### ISSUE THREAD

**Issue by Ailurupoda** [geobretagne/mviewer#144]
Hi,
I would like to know if it's possible to call for **postgis** data and if it could be possible then to use the **timefilter** tag.

I've seen on the "test-project" in the github repository, the layer **"population"**, it comes from a WMS service and can be filter in 3 differents level (Communes, EPCI, Pays). All informations come from the WMS layer wich is well configured at start.

Is it possible to reproduce that kind of **filter** using a layer from a **database** (like postgis) or from **file** (geopakage), or it is only possible to do it using WMS service ?

**Comment by spelhate** [comment]
Hi.
Yes it's possible to call postgis data but not directly. mviewer uses OGC standards like WMS, WFS, GeoJson... Actually timefilter is only supported with wms layers.
If you want to use timefilter directly with postgis, you have to code it in customlayer.
Some samples of customlayers are available in demo repo.

**Comment by Ailurupoda** [comment]
Hi,
I saw the customLayer, i tried the demo repo to have a better understanding of mViewer which looks great. 
So i can call a postgis data writing a customLayer in order to read it configure timefilter  ?
If i don't want to have a flux server i can still use my data from postgis or from file using this customLayer configuration ?

Do you have an exemple of a customlayer that use the timefilter ?

Thanks

**Comment by Ailurupoda** [comment]
I think i juste understood the way it works.
If i want to use my postgis data, i can either
 - Use the customLayer, by converting the data into GeoJson.
Or 
- Use a GeoServer and configure the data inside it.

Those are the two "only" options i have to use mViewer, right ?
Seems legit

**Comment by Gaetanbrl** [comment]
`Use the customLayer, by converting the data into GeoJson`
I think this could be done with PHP (not easy if you havn't skills)

`Use a GeoServer and configure the data inside it` 
Maybe the easiest solution if you've already installed a GeoServer

**Comment by spelhate** [comment]
> Do you have an exemple of a customlayer that use the timefilter ?

No. Time filter only works with wms layers actually. Would be  possible with customlayers but it's necessary to code it.

**Comment by Ailurupoda** [comment]
Okay, thanks for the tips :)

**Comment by Gaetanbrl** [comment]
@spelhate what do you think about keep this issue as evol (or create new) ?

**Comment by bchartier** [comment]
@spelhate , @Gaetanbrl : what would be the goal of this enhancement? It is not clear. Applying time filters on which kind of layers?

**Comment by Gaetanbrl** [comment]
Here, the idea is to read a postgis data to create a time filter without WMS (no geoServer).

After consideration, this development is maybe not adapted for the mviewer system and concept... so off topic ?

**Comment by bchartier** [comment]
I don't think we can connect directly to PostgreSQL from javascript.We would need an API.
This API could be WMS, WFS (that's why we use GeoServer) or why not WFS 3, GraphQL...
This is not off topic we just need to determine if the support of a new API in mviewer need to be added to its roadmap.
