### ISSUE TITLE
Affichage Style par catégorie

### ISSUE THREAD

**Issue by tanguyj** [geobretagne/mviewer#15]
Est ce qu'il y aurait une possibilité d'afficher ou de ne pas afficher (cocher) les styles par catégories.
(affichage différencié au sein d'une même couche)

**Comment by spelhate** [comment]
Tu peux détailler s'il te plaît.

**Comment by tanguyj** [comment]
C'est une idée, mais ça peut etre lourd,
c'est de pouvoir cocher ou décocher au sein d'une même couche les themes (Dans la couche zonage PLU par exemple de pouvoir afficher que les  "zones A") alors que dans cette couche tu as  les zones U, A, AU, etc ...

**Comment by spelhate** [comment]
Non on ne peut pas. Par contre tu peux créer un SLD pour Zone A, un SLD pour zone B et afficher la couche zone A et la couche Zone B dans un même thème.
