### ISSUE TITLE
customlayer ArcGIS REST Feature Service

### ISSUE THREAD

**Issue by vfabry** [geobretagne/mviewer#151]
On me demande de pouvoir ajouter une couche provenant de l'API Rest d'ArcGis dans un mviewer (oui, j'ai des demandes bizarres, parfois)
Je me dis que ça doit être possible via un customlayer, en se basant sur cet exemple openlayer : 
[https://openlayers.org/en/latest/examples/vector-esri.html?q=arcgis+rest](url)

J'ai copié le répertoire openlayer trouvé ici : 
[https://github.com/openlayers/openlayers/tree/v5.3.0](url)
Je crée un nouveau custom layer test_esri.js, dans lequel la première ligne est 
`import EsriJSON from '../../../../openlayers-5.3.0/src/ol/format/EsriJSON.js';`

J'obtiens une erreur dans la console de firefox : 
`error custom Layer : SyntaxError: import declarations may only appear at top level of a module`

Est-ce qu'il faut déclarer le module a un autre endroit ?

**Comment by spelhate** [comment]
Dans mviewer, le format EsriJSON est déjà disponible donc il n'y a pas besoin de l'importer.
Tu peux t'inspirer de cet exemple : https://openlayers.org/en/v4.6.5/examples/vector-esri.html?q=esri pour créer ton customlayer.

**Comment by vfabry** [comment]
Du coup, si je n'importe pas le EsriJSON et que je déclare 
`var esrijsonFormat = new EsriJSON();`
J'obtiens cette erreur :
`error custom Layer : ReferenceError: EsriJSON is not defined`

**Comment by spelhate** [comment]
Il faut écrire `var esrijsonFormat = new ol.format.EsriJSON(); `
comme dans l'exemple que je t'ai adressé plus haut.

**Comment by vfabry** [comment]
Merci  !
J'ai réussi à intégrer une couche provenant de l'API Rest d'Arcgis Server / Arcgis Online. Un bout de code, si ça peut servir à d'autre : 
`{
mviewer.customLayers.test_esri_college_80 = {};

var esrijsonFormat = new ol.format.EsriJSON();

mviewer.customLayers.test_esri_college_80.layer = new ol.layer.Vector({
        source: new ol.source.Vector({
            url: 'https://services2.arcgis.com/aYGUaoapooTe49i1/arcgis/rest/services/COLLEGES_PUBLICS_avec_Liens/FeatureServer/0/query?where=&objectIds=&time=&geometry=154415%2C6384802%2C345565%2C6494181&geometryType=esriGeometryEnvelope&inSR=3857&spatialRel=esriSpatialRelIntersects&resultType=none&distance=0.0&units=esriSRUnit_Meter&returnGeodetic=false&outFields=*&returnGeometry=true&featureEncoding=esriDefault&multipatchOption=xyFootprint&maxAllowableOffset=&geometryPrecision=&outSR=2154&datumTransformation=&applyVCSProjection=false&returnIdsOnly=false&returnUniqueIdsOnly=false&returnCountOnly=false&returnExtentOnly=false&returnQueryGeometry=false&returnDistinctValues=false&cacheHint=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&having=&resultOffset=&resultRecordCount=&returnZ=false&returnM=false&returnExceededLimitFeatures=true&quantizationParameters=&sqlFormat=none&f=pjson&token=',
            format: esrijsonFormat
        }),
		style: new ol.style.Style({
				image: new ol.style.Circle({
							fill: new ol.style.Fill({
				color: 'rgba(255, 118, 117,1.0)'
			}),
			stroke: new ol.style.Stroke({
				color: "#ffffff",
				width: 4
			}),
			radius: 9
			})
		})        
});
mviewer.customLayers.test_esri_college_80.handle = false;`

La couche est visible ici : [](https://sig.hautsdefrance.fr/ext/mv_test/?config=test_esri.xml#)

**Comment by spelhate** [comment]
Super !

**Comment by bchartier** [comment]
Avant de fermer ce ticket, est-ce qu'il faut intégrer ce type d'exemple dans la doc de mviewer ?

**Comment by Gaetanbrl** [comment]
Ce serait une bonne issue à créer dans le repo de la doc et à fermer ici.

**Comment by bchartier** [comment]
Ok, c'est fait. Je ferme ici.
