### ISSUE TITLE
Issue with Templates

### ISSUE THREAD

**Issue by mcbaker256** [geobretagne/mviewer#152]
I am wanting to define templates for my WMS.  When Looking at the demo, I noticed that the console logs an error that the templates are not found (404 error).  The path is correct and the files are there.  I added MIME types for the mst files (text/x-tmpl-mustache) but still have the same issue.  I am sure it is some IIS setting but can't seem to get it right.

Any suggestions?

SOLVED:
I posted to soon.  I set the mime type to text/plain and it is working

**Comment by spelhate** [comment]
You are welcome !
