### ISSUE TITLE
Question about templates

### ISSUE THREAD

**Issue by mcbaker256** [geobretagne/mviewer#153]
The WMS I am using has layers the represent water utilities.  So I have water mains (pipes), valves, hydrants, etc.  I really want a template for each type of water feature.  However, I don't want to make multiple calls to the same service.  Is this supported with the current implementation or do I need to modify info.js and build my logic there?

Thanks in advance,
Mike

**Comment by spelhate** [comment]
Actually there is one ajax call per visible and queryable layer. But you can create a WMS layer combining many wms layers. eg id="layer1,layer2" in config.xml.

**Comment by mcbaker256** [comment]
Let me re-word my question ..
I currently have a WMS layer which contains many wms layers, eg id='water_main, water_valve,water_hydrant'.  So based on above, I would have 1 template for that layer.  If I wanted to different templates for these three, then I would need to create 3 WMS layers, correct?  Since mustache has no logic, I couldn't do if or case statements in the template itself.

Thanks for the reply

**Comment by mcbaker256** [comment]
So I modified info.js to add a property where the value is true.  However, I am wondering if I could use the attribute control to do this.  Is there a demo using this?  I would like to know how it should be set.

**Comment by bchartier** [comment]
It is not recommended at all to modify the content of the mviewer source code. Modifying info.js source code would result in real difficulties when you need to apply a new release of mviewer.
Do you have a really good reason to not have each feature type in a separate WMS layer?
If you do need to keep all these feature types in one unique WMS layer you may implement some kind of logic in the CSS you apply to your template.

**Comment by spelhate** [comment]
I agree with @bchartier.  CSS is a good way to do this. 
In complement, small logic is possible in templates with Mustache.js 
```
{{#field1}}
 Visible only if field1 has value
{{/field1}}
{{#field2}}
 Visible only if field2 has value
{{/field2}}
```
