### ISSUE TITLE
barre de recherche

### ISSUE THREAD

**Issue by smevel** [geobretagne/mviewer#159]
- ajouter la possibilité d'activer la barre de recherche dans la version ultra simplifiée
- rendre paramétrable le texte de la barre de recherche (placeholder) : exemples Saisir mon adresse, Rechercher... 
- limiter la recherche d'adresse à l'emprise de la carte

**Comment by spelhate** [comment]
Pour la limitation de la recherche d'adresse à l'emprise de la carte, il y a un paramètre à activer `bbox="true"` dans l'élément de configuration **searchparameters**. Ce paramètrage fonctionne avec l'API de la BAN en donnant une priorité de recherche au centre de la carte.

**Comment by spelhate** [comment]
Nouveau paramètre optionnel à intégrer dans l'élément de configuration **searchparameters** : `inputlabel`. La valeur par défaut est "Rechercher"
Ce paramètre est utilisé pour modifier le texte du title et du placeholder de la zone de saisie recherche.
