### ISSUE TITLE
Présentation de la journée mviewer

### ISSUE THREAD

**Issue by vfabry** [geobretagne/mviewer#160]
Bonjour,

Est-ce qu'on peut trouver quelque part les présentations vues lors de la journée du 02/10 ?

Vincent

**Comment by spelhate** [comment]
Oui c'est prévu pour aujourd'hui ou demain..

**Comment by spelhate** [comment]
https://stockage.region-bretagne.fr/index.php/s/p2jrPpJAfTFtgBE

**Comment by Gaetanbrl** [comment]
Merci pour la diffusion des documents @spelhate .

**Comment by bchartier** [comment]
Est-ce que ferme ce ticket ?
Est-ce qu'on pérennise le lien vers les présentations quelque part (dans le wiki par exemple) ?

**Comment by Gaetanbrl** [comment]
Bonne idée ! Ce sera plus visible qu'une issue pour les personnes qui découvrent le GitHub Mviewer.

**Comment by bchartier** [comment]
J'ai ajouté lien sur la page suivante : https://github.com/geobretagne/mviewer/wiki

**Comment by Gaetanbrl** [comment]
Super merci !
