### ISSUE TITLE
flux gpu indisponibles avec v3.1

### ISSUE THREAD

**Issue by fxduponcheel** [geobretagne/mviewer#161]
Bonjour

Je viens de mettre à jour on mviewer avec la nouvelle version 3.1 et les flux du gpu ne s'affichent pas même en désactivant l'option exportpng.

Le message dans la console indique : Blocage d’une requête multiorigines (Cross-Origin Request) : la politique « Same Origin » ne permet pas de consulter la ressource distante située sur http://wxs-gpu.mongeoportail.ign.fr/externe/vkd1evhid6jdj5h4…2C6150792.119822776%2C-92374.14868263551%2C6194934.503657466. Raison : l’en-tête CORS « Access-Control-Allow-Origin » est manquant.

Ce qui est bizarre c'est que ça marche avec l'ancienne version du mviewer installé il y a un an environ.

Quelqu'un aurait il une idée ?

Accès à l'appli : 
avec ancienne version mviewer : http://geocouesnon.sage-couesnon.fr/geocouesnon
avec nouvelle version mviewer 3.1 : http://geocouesnon.sage-couesnon.fr/geocouesnon2

Merci d'avance

**Comment by spelhate** [comment]
La version 3.1 et celle datée d'un an reposent sur deux versions différentes d'Openlayers.
Ça peut venir de là.

**Comment by fxduponcheel** [comment]
Tu penses vraiment que cela peut venir d'openlayers ? C'est quand même bien embêtant de ne pas pouvoir afficher les données du GPU.

Voici les messages d'erreur : 
![image](https://user-images.githubusercontent.com/43995009/68845811-45a8b200-06cc-11ea-8029-2cf1b5c98f2d.png)

**Comment by fxduponcheel** [comment]
J'ai changé l'url="http://wxs-gpu.mongeoportail.ign.fr/externe/vkd1evhid6jdj5h4hkhyzjto/wms/v?" en https et cela fonctionne.
