### ISSUE TITLE
option geoloc avec gps

### ISSUE THREAD

**Issue by fxduponcheel** [geobretagne/mviewer#162]
J'ai activé l'option geoloc, celle ci ne fonctionne pas sur pc car mon protocole est en http et non en https. Ca j'ai compris et je vais faire le nécessaire pour passer en https.

Par contre lorsque je l'utilise sur une tablette ou sur un mobile (avec le gps activé), ça n'a pas l'air de fonctionner non plus.

Une idée ? Merci d'avance

**Comment by spelhate** [comment]
Dans les deux cas (PC et mobile), il faut accéder à l'application mviewer via https.
