### ISSUE TITLE
emplacement logo lisibilité

### ISSUE THREAD

**Issue by fxduponcheel** [geobretagne/mviewer#163]
Bonjour

Certains logos ne sont pas adaptés pour être afficher à gauche du nom de l'application : trop petit et donc non lisible.

Avec les collègues de Fougères Agglo, nous avons testé d'insérer le logo en bas à droite juste à côté du bouton d'accès aux fonds de carte ? 

Dans mviewer.css, nous avons ajouté :

#logoContainer {
	bottom: 15px;
	right: 100px;
	float: right;
	position: fixed;
    margin-bottom: 0;
}

Puis dans index.htlm, nous avons ajouté :

<div id="logoContainer">
<img src="apps/logo_sage_couesnon_geocouesnon.svg" style="max-height:70px;">
</div>

ça donne ça : http://geocouesnon.sage-couesnon.fr/geocouesnon2

Si cela intéresse plusieurs personnes, peut-être que ça vaudrait le coup de pouvoir le paramétrer dans le config.xml ?

**Comment by spelhate** [comment]
Ok sur le principe. On pourrait avoir un nouveau paramètre du type `logoplacement `avec une valeur par défaut égale à "navbar" et une option égale à "bottom"

**Comment by Gaetanbrl** [comment]
![image](https://user-images.githubusercontent.com/16317988/67014127-95f41a80-f0f4-11e9-8bec-3355faa1abf2.png)

Attention à l'affichage avec l'infobulle.

**Comment by Gaetanbrl** [comment]
@fxduponcheel avez-vous un retour sur la taille optimale d'un logo pour le placer dans la navbar (bar de navigation) ?

**Comment by spelhate** [comment]
Le logo est retaillé en proportion. Sinon une hauteur de 35px est idéale.

**Comment by Gaetanbrl** [comment]
On a constaté que l'affichage des coordonnées, avec le paramètre `mouseposition="true"` dans le config.xml était également dans cette zone de la carte @fxduponcheel. 
Aviez-vous pu voir si c'était le cas ?

**Comment by fxduponcheel** [comment]
![image](https://user-images.githubusercontent.com/43995009/68844444-15601400-06ca-11ea-89ca-b05d39950c1b.png)
Effectivement c'est pas l'idéal.
Mais ce qui est le plus génant en fait c'est la consultation sur smartphone
![image](https://user-images.githubusercontent.com/43995009/68844762-9c14f100-06ca-11ea-8472-da611fb0f758.png)
La taille du logo ne s'adapte pas à la taille de l'écran ...

**Comment by fxduponcheel** [comment]
et d'ailleurs l'affichage des coordonnées se retrouvent également mal placé (en dessous du bouton fond de carte)

**Comment by fxduponcheel** [comment]
La taille idéale pour l'affichage d'un logo dépend de chaque logo. Pour le notre c'est plutôt 50 à 60 pixel

**Comment by Gaetanbrl** [comment]
> Effectivement c'est pas l'idéal.

Il est toujours possible de modifier l'emplacement du composant qui affiche les coordonnées.

> La taille du logo ne s'adapte pas à la taille de l'écran ...

Pour gérer la taille, il faut définir une taille sur la div parente selon la grille Bootstrap (ex : col-xs-3, col-md-2). 
Ensuite rajouter width: 100% sur l'image. La taille de l'image va donc varier selon la taille de la div parente qui variera selon la taille de l'écran.

Le soucis principal est que Bootstrap permet de gérer la taille d'un élément selon les éléments du même niveau et surtout selon la div parente. Hors, ces deux éléments n'ont rien en commun. Il sont réglés pour ne pas prendre en compte les autres (position: fixed).

**Comment by Gaetanbrl** [comment]
Dans la barre de navigation cela ne pose pas de problème car le logo ajuste la taille selon les autres éléments. 

Une solution possible :
Cacher ces éléments pour les mobiles et tablettes si le logo est en bas.
https://getbootstrap.com/docs/3.4/css/#responsive-utilities-classes

**Comment by fxduponcheel** [comment]
Ok je vais regarder ça. Merci

**Comment by Gaetanbrl** [comment]
Après je trouve que ca fait un peu bricolage mais en regardant bien les autres éléments ne se redimensionnent pas et en mode "simple" ou "ultra simplifié" il y a pas mal d'éléments qui sont masqués. Donc ca ne me choque pas vraiment de cacher aussi le logo selon le support de consultation.

**Comment by fxduponcheel** [comment]
Où faut il ajouter .visible-lg-* ? Dans le css ou l'index.html ?

**Comment by Gaetanbrl** [comment]
Voici un exemple au sein du Mviewer : 
https://github.com/geobretagne/mviewer/blob/master/index.html#L241-L252

Dans cet exemple on affiche ce contenu pour les small (sm) ou extra small (xs) écrans en cachant les mediums (md) et large (lg) :
```
<li id="lang-button" class="hidden-lg hidden-md">
   ...
</li>
```
ou on affiche les écrans medium (md) et large (lg) à l'inverse : 
```
<li id="lang-selector" class="dropdown hidden-xs hidden-sm">
   ....
</li>
```

**Comment by fxduponcheel** [comment]
Merci

**Comment by bchartier** [comment]
Est-ce que je peux ferme ce ticket ?

**Comment by Gaetanbrl** [comment]
@fxduponcheel  quelles sont les suites ? Certains tests / développements semblaient en cours.

**Comment by fxduponcheel** [comment]
http://geocouesnon.sage-couesnon.fr/geocouesnon/
Voilà ce que ça donne sur notre mviewer. Il apparait sur écran grande taille (PC) et n'apparait pas sur mobile et tablette.
Ce n'est pas l'idéal, mais c'est mieux que le logo inséré dans le bandeau du haut.

**Comment by Gaetanbrl** [comment]
Je viens de tester, ca fonctionne bien. Après, il reste le conflit avec les coordonnées de la souris à gérer pour proposer un reversement du code (et une revue évidemment 😄).
