### ISSUE TITLE
backend with flask framework

### ISSUE THREAD

**Issue by fvanderbiest** [geobretagne/mviewer#166]
What about using the flask framework for a new backend, to replace or use as an alternative to the current php backend ?

**Comment by bchartier** [comment]
This is what we've done for mviewerstudio for datasud.fr:
https://github.com/neogeo-technologies/idgo-mviewerstudio-proxy

**Comment by Gaetanbrl** [comment]
Awesome issue ! Could be great.

**Comment by spelhate** [comment]
Yes it would be great ! But there is no php backend in mviewer. Perhaps this issue is for mviewerstudio : https://github.com/geobretagne/mviewerstudio wich contains php backend ?

**Comment by fvanderbiest** [comment]
Oops, wrong repo. Sorry about that!

**Comment by fvanderbiest** [comment]
FYI, I'm doing a proposal to geo2france for it.

**Comment by pierrejego** [comment]
still a good idea to use flask :)

**Comment by fvanderbiest** [comment]
See https://github.com/geobretagne/mviewerstudio/issues/38 for the next steps.
