### ISSUE TITLE
[offre de stage] Copernicus Régional : mviewer et données satellitaires

### ISSUE THREAD

**Issue by mJagaille** [geobretagne/mviewer#168]
Bonjour,

BreTel (Bretagne télédétection) recherche un/une stagiaire pour améliorer le mviewer ["Copernicus Régional"](https://geobretagne.fr/pub/dreal_b/mviewer/?config=../apps/teledetection/config.xml#). Voir l'[offre complète ici](https://cms.geobretagne.fr/content/stage-developper-une-application-web-pour-observer-la-bretagne-depuis-lespace) et un résumé ci-dessous

N'hésitez pas à la diffuser dans vos réseaux,

Merci

Le/la stagiaire aura pour mission :
- De réaliser une synthèse de l’offre de service de mise à disposition d’images satellitaires 
- A partir de fournisseurs de données satellitaires conforme aux exigences OCG, et s’appuyant sur l’outil MVIEWER, de mettre en œuvre les chaînes de traitement et scripts permettant de visualiser, sélectionner, interroger, exporter des indices issus des images satellitaires. 
- D’évaluer la faisabilité et mettre en place des services pour combiner les deux types de données imagerie et produits satellitaires raster et données métier vecteur (calcul d’indices spectraux, calcul de statistiques, affichage de ces indices et statistiques sous forme de dataviz, export des statistiques)
- D’améliorer l’apparence générale et l’ergonomie du visualiseur Copernicus Régional
- De partager les développements réalisés avec la communauté MVIEWER et de présenter les résultats à une communauté d’utilisateurs

L’intérêt pour le/la stagiaire sera, à l’issue du stage sera d’être capable de :
- Prendre en main et intégrer des librairies logicielles pour les mettre en œuvre en réponse à un besoin métier ;
- Mettre en place et utiliser des outils de visualisation d'images facilement accessibles ;
- Développer un outil SIG web simple se rapprochant des besoins métiers des utilisateurs gestionnaires des territoires ;
- Présenter cet outil à des utilisateurs potentiels.

Technologies utilisées
- Serveur de cartes : GeoServer
- Flux OGC standards : WMS, WMTS, WPS
- Client web cartographique mviewer : JavaScript, html, css, xml, OpenLayers, bootstrap
- Gestion de version : git

Profil recherché
- Niveau Master 2 ou dernière année d’Ingénieur
- Formation en informatique et/ou SIG
- Connaissance des langages de programmation (javascript, python, xml, html)
- Notions de traitement d’images et de télédétection

Contact et candidature
Pour plus d’informations sur le stage, vous pouvez prendre contact avec Marie Jagaille (GIS BreTel)  bretel-stage@imt-atlantique.fr
Date limite de candidature 29 novembre
Les candidatures sont à envoyer à bretel-stage@imt-atlantique.fr avec en objet “STAGE MVIEWER - NOM Prénom”

**Comment by bchartier** [comment]
La date limite de candidature est dépassée.
Puis-je fermer ce ticket ?

**Comment by spelhate** [comment]
C'est fait
