### ISSUE TITLE
[ Document ] Contributor  guide

### ISSUE THREAD

**Issue by pierrejego** [geobretagne/mviewer#169]
Wokr in progress see geobretagne/mviewer.doc#8

**Comment by bchartier** [comment]
Ce travail est-il toujours en cours ?

**Comment by Gaetanbrl** [comment]
Nous espérons que des lecteurs de la documentation apportent des retours sur ces dernières modifications.

**Comment by bchartier** [comment]
Ok.
Est-ce que vous avez déjà de votre côté solliciter la relecture par le commanditaire de ces travaux ?
Est-ce qu'il faut communiquer auprès de la communauté pour les solliciter ?

**Comment by Gaetanbrl** [comment]
Les commanditaires doivent nous faire des retours.
Je pense que la communauté peut-être  sollicitée également, car les modifications sont déjà sur la branche master de la doc.
Tout retour est donc le bienvenu :)
