### ISSUE TITLE
Orthophoto WMTS

### ISSUE THREAD

**Issue by Ailurupoda** [geobretagne/mviewer#171]
Hi,
I'm trying to add a basemap, i have 2 different URL :
 - http://ts{1-3}.rgd.fr/mapcache/tms/1.0.0/ORTHOPHOTO@Google/{z}/{x}/{-y}.jpeg
 - http://ts1.rgd.fr/mapcache/wmts/?SERVICE=WMTS&request=getcapabilities

On my config.xml, i put a new baselayer : 
```       
<baselayer  
            type="OSM" 
            id="ORTHOPHOTO" 
            label="RGDOrtho" 
            title="ORTHOPHOTO" 
            thumbgallery="img/basemap/cassini.jpg" 
            url="http://ts{1-3}.rgd.fr/mapcache/tms/1.0.0/ORTHOPHOTO@Google/{z}/{x}/{-y}.jpeg"
            visible="true"
            attribution="RGD layer" />
```
When i run my mViewer, i don't manage to display the photo. When i check the network tab, all the tiles are reach, but they are not displayed on the screen.

Do you have any idea on how i could display those ?
Is there a way to use a WMTS as a layer and not a baselayer ?

I also tried to use the WMTS URL as a basemap but i didn't managed to reach anything this way.

**Comment by spelhate** [comment]
Hi,
Two possible reasons:

- tiles are not visibles. In fact this request : http://ts3.rgd.fr/mapcache/tms/1.0.0/ORTHOPHOTO@Google/13/4053/5347.jpeg returns text and no image
- CORS is not enabled on ts{1-3}.rgd.fr

**Comment by Ailurupoda** [comment]
The problem came from the flux server that had no CORS activated on it. 
I managed to regenerate a flux from the WMTS on my QgisServer that contains CORS (Making a flux from a flux).

Thanks for the answer.
