### ISSUE TITLE
Add Popup

### ISSUE THREAD

**Issue by Ailurupoda** [geobretagne/mviewer#172]
Hi,
I'm trying to add a popup when clicking on an entity of my layer. I've used this code :
```
            <layer 
                id="RGD74_12" 
                name="RGD 2012" 
                type="wms" 
                url="http://178.33.241.138:8081/ows/?MAP=rgd.qgs&amp;VERSION=1.3.0"
                style="défaut"
                stylesalias="2012"
                visible="true" 
                infoformat="text/html"
                fields="code12_niv4" aliases="axe"
                queryable="true"
                featurecount="20"
                popup="true">
                <template url="templates/global.lycee.mst"></template> 
            </layer>
```
There is no popup showing, but on the netword tab on my navigator, i manage to reach the html table of my fields.

Is it possible to define a text and a picture for a layer and display it whatever entity is clicked ?
Like display "Hello world" on a rigth or bottom popup when i click somewhere on the layer.

Thank you in advance

**Comment by spelhate** [comment]
In your config, if you use **text/html** format, you can't customize popup.
Instead use `infoformat="application/vnd.ogc.gml"` in combination  with a template like templates/global.lycee.mst configured with your own  features attributes.
See : https://mviewerdoc.readthedocs.io/fr/latest/doc_dev/config_tpl.html#configurer-templates

**Comment by Ailurupoda** [comment]
Rigth i see how to change the display of my popup.
My problem now is to display the popup itself.
I have this them and layer tag
```
        <theme name="Evolutions"  collapsed="false" id="habitant" icon="fas fa-chart-line">
            <layer 
                id="Mutations1215" 
                name="RGD evols 1215" 
                type="wms" 
                url="http://rgd.sirs-fr.com:8081/ows/?MAP=rgd.qgs&amp;VERSION=1.3.0"
                style="défaut"
                stylesalias=""
                visible="false" 
                infoformat="text/html" 
                queryable="true">
            </layer>
        </theme>
```
When i click on my layer, nothing is showing up. When i read the network tab of my browser i see that URL 
http://rgd.sirs-fr.com:8081/ows/?MAP=rgd.qgs&VERSION=1.3.0&SERVICE=WMS&VERSION=1.3.0&REQUEST=GetFeatureInfo&FORMAT=image%2Fpng&TRANSPARENT=true&QUERY_LAYERS=Mutations1215&LAYERS=Mutations1215&STYLES=d%C3%A9faut&INFO_FORMAT=text%2Fhtml&I=50&J=50&CRS=EPSG%3A3857&WIDTH=101&HEIGHT=101&BBOX=671881.4786266991%2C5748523.149214964%2C702762.0380539104%2C5779403.708642175 
But there is no popup.

do you have any ideas ?

**Comment by spelhate** [comment]
It seems to be cross origin problem.
If your mviewer instance has different **origin** ,eg another port, than requested  WMS/WFS providers, you have to activate CORS on this servers or use Ajax proxy with your mviewer. https://mviewerdoc.readthedocs.io/fr/latest/doc_dev/config_proxy.html#configurer-le-proxy

**Comment by Ailurupoda** [comment]
In fact, with CORS activated on the WMS server i get the popup.
Thanks
