### ISSUE TITLE
Thématique - nom trop long

### ISSUE THREAD

**Issue by Gaetanbrl** [geobretagne/mviewer#173]
Lorsque l'on met un texte trop grand comme nom de thématique on obtient un affichage tel quel quand le volet est replié : 
![image](https://user-images.githubusercontent.com/16317988/68285807-4021eb00-0080-11ea-8ca6-bb4f21e87313.png)

**Comment by Gaetanbrl** [comment]
J'ai rajouté un col-sm-3 sur cette ligne :
https://github.com/geobretagne/mviewer/blob/master/js/templates.js#L13

... pour obtenir :
`'<span class="fa-stack fa-lg pull-left col-sm-3">',`

 Le soucis semble corrigé. Testé sur écran large et en vue mobile via les outils du navigateur.

![image](https://user-images.githubusercontent.com/16317988/68286633-b70bb380-0081-11ea-91fe-2382be9ebd59.png)

**Comment by bchartier** [comment]
@Gaetanbrl : quand tu dis que tu l'as corrigé et testé, c'est uniquement en local ou c'est déjà reversé dans le code du projet ?

**Comment by Gaetanbrl** [comment]
C'est en local (issue ouverte), je m'occupe de le reversé cette semaine. Merci du rappel.

**Comment by Gaetanbrl** [comment]
@spelhate peux-tu supprimer la branche feature-173 également stp ? Merci :)

**Comment by Gaetanbrl** [comment]
C'est bon je supprimes les branches à partir de l'interface de la PR. Merci quand même.
