### ISSUE TITLE
Ajouter des fichier JS,HTML sans modifier le index.html

### ISSUE THREAD

**Issue by Gaetanbrl** [geobretagne/mviewer#178]
Des utilisateurs ont ajoutés une fonctionnalité qui nécessite des fichiers JS et HTML supplémentaires.
Ils doivent les intégrer dans le fichier index.html, ce qui pause des conflits lors de la mise à jour de leurs branches.

**Comment by bchartier** [comment]
Je ne comprends pas ce ticket.
Est-ce que tu peux préciser de quels fichiers et de quels conflits tu parles  ?

**Comment by Gaetanbrl** [comment]
Nous avons des utilisateurs qui ont crée un CSS spécifique qui surcharge le mviewer.css. Cela évite de modifier le fichier mviewer.css.
Pour prendre en compte ce nouveau fichier, il est rajouté dans le fichier index.html.

Donc à chaque rebase / update il y a un conflit avec le index.html. C'est pareil si on a nos propres fichier js.

**Comment by Gaetanbrl** [comment]
@spelhate nous a indiqué qu'un système permettait de rajouter des ressources sans avoir à modifier le fichier index.html.

**Comment by spelhate** [comment]
> Nous avons des utilisateurs qui ont crée un CSS spécifique qui surcharge le mviewer.css. Cela évite de modifier le fichier mviewer.css.
> Pour prendre en compte ce nouveau fichier, il est rajouté dans le fichier index.html.

Ce n'est pas nécessaire. Mviewer permet de surcharger mviewer.css via une feuille de style personnalisée. Il faut utiliser le paramètre **style** dans la configuration.

**Comment by spelhate** [comment]
> @spelhate nous a indiqué qu'un système permettait de rajouter des ressources sans avoir à modifier le fichier index.html.

Actuellement il est possible de charger des libs supplémentaires uniquement via le'emploi de customControls ou de templates Mustaches.

**Comment by Gaetanbrl** [comment]
> Mviewer permet de surcharger mviewer.css via une feuille de style personnalisée. 

Le paramètre style permet de substituer la feuille de style initiale (auquel cas il faut reporter les modifications dans cette feuille à chaque mise à jour)  ou c'est pour la surcharger ?

**Comment by bchartier** [comment]
>> Mviewer permet de surcharger mviewer.css via une feuille de style personnalisée.

> Le paramètre style permet de substituer la feuille de style initiale (auquel cas il faut reporter les modifications dans cette feuille à chaque mise à jour) ou c'est pour la surcharger ?

Substitution d'après la doc : `style: style à utiliser || css/themes/default.css`

On peut imaginer plusieurs approches pour éviter de toucher aux fichiers de mviewer :
- utiliser le mécanisme actuel de mviewer
- utiliser des imports dans les feuilles de styles
- faire en sorte que le fichier index.html ne fasse pas partie de mviewer. Il faudrait alors injecter en dynamique mviewer dans n'importe quelle page html via un snippet javascript (comme le fait Mapbox GL par exemple).

**Comment by spelhate** [comment]
> Substitution d'après la doc : `style: style à utiliser || css/themes/default.css`

Mviewer charge par défaut 2 feuilles de styles : mviewer.css & css/themes/default.css
Le paramètre style permet d'utiliser un style personnalisé à la place de css/themes/default.css.

**Comment by Gaetanbrl** [comment]
>faire en sorte que le fichier index.html ne fasse pas partie de mviewer. Il faudrait alors injecter en dynamique mviewer dans n'importe quelle page html via un snippet javascript (comme le fait Mapbox GL par exemple).

Tu peux détailler ? Ca me semble intéressant :)

**Comment by bchartier** [comment]
>> faire en sorte que le fichier index.html ne fasse pas partie de mviewer. Il faudrait alors injecter en dynamique mviewer dans n'importe quelle page html via un snippet javascript (comme le fait Mapbox GL par exemple).

> Tu peux détailler ? Ca me semble intéressant :)

Détailler : non, j'en suis bien incapable. Mais regarde cela : https://docs.mapbox.com/mapbox-gl-js/example/simple-map/
On met dans n'importe quel page web les liens vers les css et javascript, on intègre un div map et le bout de javascript qui va bien.

**Comment by bchartier** [comment]
Quelle suite donnons-nous à ce ticket ?

**Comment by Gaetanbrl** [comment]
Encore un peu de temps ? :)

**Comment by bchartier** [comment]
Bah, pas de problème pour donner du temps. Mais je préfère donner du temps si on envisage de faire quelque chose. Le ticket permet alors de suivre les actions qu'on envisage. Perso, je vois une action relativement simple (même si elle peut être chronophage) : clarifier les bonnes pratiques dans la doc d'mviewer pour éviter que trop d'utilisateurs fassent des modifs dans le cœur de l'outil.

**Comment by Gaetanbrl** [comment]
> Perso, je vois une action relativement simple (même si elle peut être chronophage) : clarifier les bonnes pratiques dans la doc 

On a inséré des explications ici sur l'organisation des fichiers dans les derniers ajouts :
[Bonnes pratiques](https://mviewerdoc.readthedocs.io/fr/latest/doc_dev/config_practices.html#organisation-des-fichiers-de-carte)

**Comment by bchartier** [comment]
D'autres actions à envisager ?

**Comment by Gaetanbrl** [comment]
Je ferme, on a ce qu'il faut dans la doc et via les plugins.
