### ISSUE TITLE
Formatage des fichiers

### ISSUE THREAD

**Issue by Gaetanbrl** [geobretagne/mviewer#179]
Afin de faciliter les PR et dans le cadre des bonnes pratiques #169 nous aimerions fixer des règles de formatage pour éditer les fichiers et améliorer les échanges.

Si nous fixons des règles, il sera nécessaire de réaliser une PR pour la modification du formatage sur tous les fichiers.

**Comment by Gaetanbrl** [comment]
Plusieurs standards existent à ce sujet :
https://codeburst.io/5-javascript-style-guides-including-airbnb-github-google-88cbc6b2b7aa

**Comment by Gaetanbrl** [comment]
Le standard airBnb me semble pas mal. 
https://github.com/airbnb/javascript

**Comment by bchartier** [comment]
Je serais effectivement très favorable à ce que l'on applique des règles de formatage au fichiers du projet. Je n'ai pas l'habitude de règles particulières sur les projets javascript. Donc, je suis plutôt ouvert sur ce sujet.

Par contre, je pense qu'il est important de choisir des règles qui sont facilement configurables dans les outils de développement de chacun. Il n'est pas impossible que certains utilisent Atom, d'autres VS Code ou d'autres (comme moi PyCharm - oui, désolé).

On peut aussi voir si dans les processus d'intégration continue (menu "actions" de Github) on ne peut pas aussi faire des tests sur le formattage du code.

**Comment by Gaetanbrl** [comment]
> Par contre, je pense qu'il est important de choisir des règles qui sont facilement configurables dans les outils de développement de chacun.

Oui ce serait le mieux mais aujourd'hui, ils sont tous configurables. Propre à chacun de choisir l'outil qu'il maîtrise et peut paramétrer le mieux après...

> On peut aussi voir si dans les processus d'intégration continue (menu "actions" de Github) on ne peut pas aussi faire des tests sur le formattage du code.

Le Mviewer utilise les actions ? Où cela concerne les utilisateurs qui peuvent l'utiliser dans leurs projets ?

**Comment by bchartier** [comment]
> > Par contre, je pense qu'il est important de choisir des règles qui sont facilement configurables dans les outils de développement de chacun.
> 
> Oui ce serait le mieux mais aujourd'hui, ils sont tous configurables. Propre à chacun de choisir l'outil qu'il maîtrise et peut paramétrer le mieux après...
> 
Oui, je comprends mais c'est mieux si la configuration des outils existent déjà sous forme d'un fichier à télécharger par exemple. Après je me débrouillerai sans doute ou au pire je changerai d'outil de dev.

> > On peut aussi voir si dans les processus d'intégration continue (menu "actions" de Github) on ne peut pas aussi faire des tests sur le formatage du code.
> 
> Le Mviewer utilise les actions ? Où cela concerne les utilisateurs qui peuvent l'utiliser dans leurs projets ?

Non, pas encore. Cela concerne les pilotes du projet. Il s'agit de fonction d'intégration et de déploiement continue. Les actions de Github peuvent être déclenchées à la réception de pull requests j'imagine.

**Comment by bchartier** [comment]
Sinon concrètement, faudrait qu'on vote pour le règles de formatage du code et qu'on essaie de les appliquer.

**Comment by Gaetanbrl** [comment]
J'ai proposé quelques standards existants. N’hésites pas si tu en à d'autres règles que tu trouves plus adaptées :)

L'avantage du standard airBnb, c'est qu'il est déjà bien documenté ;) 
L'inconvénient c'est qu'il utilise des syntaxes ES6 (array functions par exemple). Mais on est pas obligé de tout reprendre peut-être...

**Comment by bchartier** [comment]
> J'ai proposé quelques standards existants. N’hésites pas si tu en à d'autres règles que tu trouves plus adaptées :)

Ben, non, je n'en connais pas vraiment et je les applique actuellement encore moins. J'essaie juste de me fondre dans le code existant.

Je propose qu'on fasse avec une des règles que tu as citées.

**Comment by Gaetanbrl** [comment]
Je reviens sur ce ticket après la réalisation d'un petit test avec le package EsLint via npm : [eslint-config-airbnb-base](https://www.npmjs.com/package/eslint-config-airbnb-base)

### Quel est l’intérêt ?

EsLint va parcourir le code JavaScript du Mviewer et remonter les erreurs / syntaxes à modifier en accord avec les règles définies. Les règles peuvent être personnalisées et / ou suivre un standard de formatage de code comme [airbnb](https://github.com/airbnb/javascript).

On gagne en lisibilité, en propreté et donc en qualité de code. Que du bon en soit ! 👍 

### Les test : installation et analyse EsLint

Pour la réalisation du test : 
- Créer un dossier `mviewerairbnb` et se positionner dans ce dossier
`cd mviewerairbnb`
- Installer npm via `node.js >=13.x`
- initialiser un fichier package.json avec la commande : 
`npm init `

Ici il n'a d'intérêt que pour l'installation du module Eslint et des dépendances. Vous pouvez mettre n'importe quel nom de fichier dans "main".
Mon fichier aura par exemple cette forme :
```
{
  "name": "eslintinit",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC"
}
```


- on installe eslint et les dépendances
`npm install eslint --save-dev`

- on initialise eslint et sa configuration "simple" pour le style airbnb (par exemple) avec les réponses plus bas en **bleu** :

`eslint --init
`

![image](https://user-images.githubusercontent.com/16317988/83109638-023eef80-a0c2-11ea-9c41-46ec833b9003.png)

- On a maintenant un fichier .eslintrc pour la configuration des règles eslint

- On va cloner le mviewer dans notre dossier courant `mviewerairbnb`

`git clone https://github.com/geobretagne/mviewer.git`

- On lance l'analyse du code :
`eslint mviewer`

✖ 423587 problems (415414 errors, 8173 warnings)
  341288 errors and 0 warnings potentially fixable with the `--fix` option.

On voit qu'il y a pas mal d'éléments....

- On utilise --fix option pour que eslint fix lui-même certaines règles JS : 
npm --fix mviewer

✖ 74466 problems (68782 errors, 5684 warnings)
  172 errors and 0 warnings potentially fixable with the `--fix` option.

C'est un peu mieux mais il reste pas mal de boulot.

- Le mieux est d'analyser les erreurs / warnings et affiner la configuration (.eslintrc)  si on juge que certaines ne doivent pas être prises en compte. 

Pour plus d'infos sur la config : 
https://www.synbioz.com/blog/tech/un-code-js-impeccable-grace-a-eslint

### Conclusion

On peut améliorer le JS du Mviewer via cet outil maintenant très courant qu'est EsLint.
On prendra garde aux erreurs remontées afin d'en ignorer certaines si besoin (on fait quand même ce qu'on veut !).

Ce type d'analyse est surtout à destination des développeurs (coeur Mviewer).

**Comment by spelhate** [comment]
Intéressant. Peux-tu nous faire ressortir quelques erreurs détectées et avérées stp ?

**Comment by Gaetanbrl** [comment]
Pour le fichier mviewer/js/search.js : 

- Exemples à potentiellement corriger  ou à prendre en compte selon le standard airbnb que j'ai mis par défaut : 

128:9   error    Unexpected dangling '_' in '_searchparams'
187:21  error    Expected '===' and instead saw '==
259:11  error    All 'var' declarations must be at the top of the function scope
373:1   error    This line has a length of 117. Maximum allowed is 100
384:13  error    Identifier 'result_label' is not in camel case
407:73  error    'i' is defined but never used
270:19  error    'zoo' is assigned a value but never used
276:19  error    'zoom' is not defined


- Exemples que l'on peut ignorer (ou dû ) écriture >= ES6 : 

1:1   error    Unexpected var, use let or const instead
187:30  error    '$' is not defined
515:9   error    'jQuery' is not defined
526:32  error    'ol' is not defined

Beaucoup d'erreurs dû à des appels de variables "globales" mais c'est aussi dû aux systèmes d'import de modules via `require `ou `import {} from` qui sont plus communérment utilisés.

Ces erreurs ont un type en bout de ligne comme  `no-var` qui peuvent ensuite être ignorés via le fichier de config `.eslintrc`.

**Comment by spelhate** [comment]
Ok. Merci pour les infos.
Ca peut marcher avec ça : https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint ?

**Comment by Gaetanbrl** [comment]
Je crois que le plugin est à lier avec le module eslint et permet dans vscode de formatter un fichier à la sauvegarde. Du moins c'est comme cela que je l'avais utilisé pour un projet typé reactjs.

**Comment by Gaetanbrl** [comment]
@bchartier

**Comment by Gaetanbrl** [comment]
Une première PR vient d'être réalisée afin de pouvoir contrôler le code sur la forme et surtout, le faire selon des règles réutilisables facilement par tous les développeurs mviewer.

A voir ensuite si on souhaite aller plus loin avec un linter pour vérifier le code sur le fond.

**Comment by Gaetanbrl** [comment]
Je ferme cette issue qui concernait surtout le formatage des fichiers.
