### ISSUE TITLE
Panneau de gauche fermé au démarrage de l'application

### ISSUE THREAD

**Issue by vfabry** [geobretagne/mviewer#180]
Est-ce qu'il existe un paramètre qui permet d'ouvrir l'application avec le panneau de gauche replié ? (celui avec les couches)

Vincent F

**Comment by pierrejego** [comment]
Oui c'est le paramètre mini de themes

<themes mini="" />

**Comment by vfabry** [comment]
Hum, en fait c'est le panneau qui est entouré en rouge sur ma capture d'écran, que je voudrai fermer
![image](https://user-images.githubusercontent.com/15424976/69431693-8c378580-0d38-11ea-8418-adb6a93b44c7.png)

**Comment by pierrejego** [comment]
Normalement c'est bien ça, il y a un exemple en ligne :
http://kartenn.region-bretagne.fr/kartoviz/?config=demo/fonds.xml

La subtilité (si je me rappelle bien) c'est que tous les thèmes en dessous doivent-être en collapsed="true" , on va faire un test chez nous pour voir si il n'y a pas une régression avec la nouvelle version

**Comment by pierrejego** [comment]
Je viens de vérifier sur une instance plus récente, (mais pas encore la dernière version), https://gis.jdev.fr/mviewer/#spotit , ça semble fonctionner correctement.

**Comment by vfabry** [comment]
Merci Pierre, c'est parfait !
