### ISSUE TITLE
timefilter : choisir les années affichée au démarrage de l'appli

### ISSUE THREAD

**Issue by vfabry** [geobretagne/mviewer#181]
Dans cet exemple : https://www.geo2france.fr/mviewer/?config=extension_urbaine.xml# j'ai activé le timefilter entre 1900 et 2017, mais j'aimerai qu'au démarrage, le curseur min soit sur 2000 et le curseur max sur 2014. J'ai tenté avec les paramètres _timemin_ et _timemax_ mais ça n'a pas l'air d'être ça. Une autre idée ?

Vincent F

**Comment by bchartier** [comment]
Est-ce qu'on a un spécialiste de cette fonction dans la salle ?

**Comment by spelhate** [comment]
Salut,
peux-tu tester avec `timecontrol="slider"`  à la place de **slider-range** et `timevalues="2014,2017"` ?

**Comment by vfabry** [comment]
Le top serait d'avoir une combinaison des deux. Avec timecontrol="slider" timevalues="2014,2017", ça fait le job, mais on perd les années précédentes et suivantes.
Merci d'avoir regardé en tout cas. Je pense qu'on peut fermer.
