### ISSUE TITLE
Légende - symbole rogné

### ISSUE THREAD

**Issue by t29leo** [geobretagne/mviewer#182]
Bonjour,
Novice sur le MViewer, je n'arrive pas à faire apparaître à 100% le picto dans la légende et sur la carte. En effet, le symbole svg est rogné sur une partie. 
Voici le picto :
![image](https://user-images.githubusercontent.com/34102284/69635465-be0c5d00-1054-11ea-87ed-f149a1292c07.png)

Et voici le résultat dans la légende sur MViewer (idem sur la carte) :
![image](https://user-images.githubusercontent.com/34102284/69635419-9cab7100-1054-11ea-8671-3263e367c0ba.png)

J'ai "joué" sur la taille dans le .sld, mais rien n'y fait. Le picto diminue en fonction, mais le rognage est toujours présent.
Avez-vous une idée de paramétrage pour supprimer ce rognage ? Merci

**Comment by bchartier** [comment]
Est-ce que nous pourrions avoir l'URL de la couche ?
Cela pourrait nous permettre de reproduire et de voir ce qu'il se passe.

**Comment by t29leo** [comment]
Voici les éléments : vous pouvez prendre l'exemple des pompiers (dans la section "Services publics")
https://geobretagne.fr/mviewer/?config=/pub/paysfouesnantais/apps/config.xml#
https://geobretagne.fr/pub/paysfouesnantais/apps/config.xml
https://geobretagne.fr/pub/paysfouesnantais/apps/style/pompiers.sld

**Comment by spelhate** [comment]
Est ce que ça le fait dans un autre viewer ?
J'ai en effet l'impression que ça vient de geoserver.
________________________________
De : tleo <notifications@github.com>
Envoyé : mardi 26 novembre 2019 14:56:57
À : geobretagne/mviewer
Cc : Subscribed
Objet : Re: [geobretagne/mviewer] Légende - symbole rogné (#182)


Voici les éléments : vous pouvez prendre l'exemple des pompiers (dans la section "Services publics")
https://geobretagne.fr/mviewer/?config=/pub/paysfouesnantais/apps/config.xml#
https://geobretagne.fr/pub/paysfouesnantais/apps/config.xml
https://geobretagne.fr/pub/paysfouesnantais/apps/style/pompiers.sld

**Comment by t29leo** [comment]
Autre exemple sur le mviewer du sdis29 : Points de débarquement (section Nautique) ou zone d’atterrissage pour hélicoptères (section Divers) :
https://geobretagne.fr/mviewer/?config=/pub/sdis29/apps/sdis29.xml#

**Comment by hsquividant** [comment]
Un MViewer sur le pays Fouesnantais. En voilà une bonne nouvelle !

Une solution : utiliser une image PNG plutôt que SVG qui ne semble pas plaire au GeoServer.
L'image : http://geowww.agrocampus-ouest.fr/pompiers.png
Le SLD modifié : http://geowww.agrocampus-ouest.fr/pompiers.sld
Le résultat de la requête WMS avec le camion en entier : https://geobretagne.fr/geoserver/paysfouesnantais/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=equipement_public_cc_pays_fouesnantais&STYLES=&CQL_FILTER=type%3D%27Pompiers%27&SLD=http%3A%2F%2Fgeowww.agrocampus-ouest.fr%2Fpompiers.sld&CRS=EPSG%3A3857&WIDTH=2881&HEIGHT=1075&BBOX=-472715.2468011369%2C6078912.649349105%2C-417661.4771787387%2C6099455.100700745
.. au lieu de la requête avec le camion tronqué : https://geobretagne.fr/geoserver/paysfouesnantais/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=equipement_public_cc_pays_fouesnantais&STYLES=&CQL_FILTER=type%3D%27Pompiers%27&SLD=https%3A%2F%2Fgeobretagne.fr%2Fpub%2Fpaysfouesnantais%2Fapps%2Fstyle%2Fpompiers.sld&CRS=EPSG%3A3857&WIDTH=2881&HEIGHT=1075&BBOX=-472715.2468011369%2C6078912.649349105%2C-417661.4771787387%2C6099455.100700745

Ça n'explique pas pourquoi ça ne marche pas avec l'image du camion au format SVG mais au moins, ça fonctionne.

**Comment by t29leo** [comment]
Merci pour votre aide, je vais partir sur du PNG. 
Va falloir patienter un peu, j'ai encore du boulot avant de finaliser mon Mviewer...
