### ISSUE TITLE
Orthophoto Swipe

### ISSUE THREAD

**Issue by Ailurupoda** [geobretagne/mviewer#183]
Hi,
Is there a way to build a swipe interface to watch difference between 2 orthophoto. To see for example the changes between different date by navigation on 2 orthophotos.

Did someone already made a viewer like that ?

Thanks

**Comment by bchartier** [comment]
https://www.geo2france.fr/public/tools/tools/compare_slider/index.html

**Comment by bchartier** [comment]
May I close this issue or do you have any additional question related to this subject?
