### ISSUE TITLE
pbm affichage

### ISSUE THREAD

**Issue by fxduponcheel** [geobretagne/mviewer#184]
Bonjour

Le wms débits moyen journaliers de la DREAL Bretagne ne s'affiche pas lorsque je sélectionne la couche dans mon mviewer. Par contre elle apparait lorsque je mets en route la console de firefox.

http://geocouesnon.sage-couesnon.fr/geocouesnon
La couche se trouve dans la rubrique "Débits des rivières"

Des idées d'où peut provenir le pbm ?

Merci d'avance

**Comment by fxduponcheel** [comment]
idem avec google chrome

Vraiment bizarre

**Comment by hsquividant** [comment]
Bonjour François-Xavier,
Essaie un tiled="true" dans les paramètres de la couche hydrometrie_qmj, ça a fonctionné chez moi.
a+

**Comment by hsquividant** [comment]
Bonjour François-Xavier, 
Essaie un tiled="true" dans les paramètres de la couche hydrometrie_qmj, ça a fonctionné chez moi 
a+ 
Hervé 


De: "fxduponcheel" <notifications@github.com> 
À: "geobretagne/mviewer" <mviewer@noreply.github.com> 
Cc: "Subscribed" <subscribed@noreply.github.com> 
Envoyé: Mardi 3 Décembre 2019 17:43:59 
Objet: [geobretagne/mviewer] pbm affichage (#184) 



Bonjour 

Le wms débits moyen journaliers de la DREAL Bretagne ne s'affiche pas lorsque je sélectionne la couche dans mon mviewer. Par contre elle apparait lorsque je mets en route la console de firefox. 

[ http://geocouesnon.sage-couesnon.fr/geocouesnon | http://geocouesnon.sage-couesnon.fr/geocouesnon ] 
La couche se trouve dans la rubrique "Débits des rivières" 

Des idées d'où peut provenir le pbm ? 

Merci d'avance

**Comment by bchartier** [comment]
Je viens de trouver la raison : il s'agit d'une limite de taille de l'image que le serveur impose.
En réduisant la taille de la fenêtre du navigateur la couche s'affiche et lorsqu'on l'agrandit elle ne se met plus à jour. Cela explique le fait que le paramètre tiled=true est efficace. Sinon il faut voir avec l'administrateur de votre serveur préféré pour autoriser des requêtes plus importante. Ceci dit, tiled=true est une bonne idée pour des questions de performance.

**Comment by fxduponcheel** [comment]
Bonjour Hervé et Benjamin
Tiled="true" resout le problème
Merci à vous !
