### ISSUE TITLE
Transparence du fond de carte

### ISSUE THREAD

**Issue by Xueimuohtreb** [geobretagne/mviewer#186]
Bonjour,

Afin de rendre une carte plus lisible, j'ai ajouté un paramètre "opacity" qui permet d'ajouter de la transparence au fond de carte.

Opacity = 1
![opacity_1](https://user-images.githubusercontent.com/35642025/70333482-e01b9180-1843-11ea-801a-d1636a317327.PNG)

Opacity = 0.5
![opacity_0 5](https://user-images.githubusercontent.com/35642025/70333492-e3168200-1843-11ea-9ab9-340deb06b659.PNG)

Voici les modifications apportées:
https://github.com/geobretagne/mviewer/compare/master...Xueimuohtreb:ajout-de-l'option-baselayer-opacity

Est-ce que cela vous semble intéressant? 
Voyez-vous des choses à modifier, ou à ajouter?

Bonne journée

**Comment by Gaetanbrl** [comment]
Merci pour la proposition,
C'est un paramètre qui peut je pense être utile.

Pour le code, il serait plus élégant de passer par une fonction et ne pas répéter la condition :
`if (baselayer.opacity != 'undefined')`

Par exemple au début de `_createBaseLayer`: 

```
var _createBaseLayer = function (baselayer) {
...
function setBaseOpacity(layer, value){
    if(layer && value) {
        layer.setOpacity(value);
    }
}
...
setOpacity(l,baselayer.opacity);
```

**Comment by bchartier** [comment]
Je pense que seules les couches thématiques avaient cette option parce qu'elles étaient les seules qui pouvaient masquer quelque chose en arrière-plan. Maintenant, je ne vois pas d'inconvénient à y ajouter de la transparence si ça peut rendre certaines cartes plus jolies.

Par contre, rendre cette option paramétrable dans mviewerstudio c'est plus compliqué (l'IHM actuelle n'est pas adaptée).

**Comment by Xueimuohtreb** [comment]
C'est en effet assez pratique pour des cartes thématiques assez denses, et mettre plus en avant les overlays.

Toutefois, je me rend compte maintenant qu'il est nécessaire de rajouter une propriété css, pour masquer le quadrillage en fond

`#map {
    background: url(../img/blank.gif) repeat scroll center top #fff!important;
}
`

**Comment by bchartier** [comment]
> Toutefois, je me rend compte maintenant qu'il est nécessaire de rajouter une propriété css, pour masquer le quadrillage en fond
> 
> `#map { background: url(../img/blank.gif) repeat scroll center top #fff!important; }`

Quel est l'effet de cette modification dans la feuille de style ? Rendre invisible le cadrillage même lorsqu'aucune transparence n'est activée sur la couche de fond ?

**Comment by spelhate** [comment]
Qui se sert du quadrillage du fond ? Pour rappel, il s'agit du background associé à la div #map. Ce background devient visible si aucun fond de plan n'est visible ou si on utilise un fond de plan **fake** comme dans cette exemple : http://kartenn.region-bretagne.fr/kartoviz/?x=-184901&y=6126583&z=16&l=lycee*&lb=fake&config=demo%2Ffonds.xml&mode=d.
On peut le supprimer si nécessaire et le remplacer par un fond neutre..

**Comment by bchartier** [comment]
> Qui se sert du quadrillage du fond ? Pour rappel, il s'agit du background associé à la div #map. Ce background devient visible si aucun fond de plan n'est visible ou si on utilise un fond de plan **fake** comme dans cette exemple : http://kartenn.region-bretagne.fr/kartoviz/?x=-184901&y=6126583&z=16&l=lycee*&lb=fake&config=demo%2Ffonds.xml&mode=d.
> On peut le supprimer si nécessaire et le remplacer par un fond neutre..

Ben, moi il me sert juste à savoir s'il y a un problème d'affichage du fond de carte.
C'est plutôt accessoire.
Si c'est plus simple on peut imaginer le supprimer.

**Comment by lionelbargeot** [comment]
Bonjour
Nous avons été confronté à l'utilisation de ce paramètre pour une couche en WMTS. 
Pour que ca fonctionne nous avons été obligé de forcer le type du paramètre opacity dans mviewer.js :
1144:                    setBaseOpacity(l,Number(baselayer.opacity));

**Comment by Gaetanbrl** [comment]
Bonjour @lionelbargeot, 
avez-vous plus d'informations (logs du navigateur par exemple) ? Quelle est le cas que vous avez rencontré ? le flux, la valeur, etc..

**Comment by lionelbargeot** [comment]
Voici la conf du fond de plan : 
```
<baselayer
        type="WMTS"
        id="ign_orthophoto"
        label="Photos aériennes IGN"
        title="Photos aériennes IGN"
        thumbgallery="apps/common/img/basemap/ign_orthophoto.png"
	url="https://wxs.ign.fr/choisirgeoportail/geoportail/wmts?"
	layers="ORTHOIMAGERY.ORTHOPHOTOS"
	fromcapacity="false"
	format="image/jpeg"
	attribution="Données cartographiques :©IGN"
	style="normal"
	matrixset="PM"
        visible="false"
        opacity="0.75"
        />
```
sous firefox 84.0.1, les logs 

```Uncaught AssertionError: Assertion failed. See https://openlayers.org/en/v6.3.1/doc/errors/#64 for details.
    e AssertionError.js:33
    st asserts.js:11
    setOpacity Base.js:281
    setBaseOpacity mviewer.js:1079
    _createBaseLayer mviewer.js:1144
    _load configuration.js:342
    _load configuration.js:338
    success (index):558
    jQuery 7
    _complete configuration.js:197
    jQuery 2
    _complete configuration.js:194
    success (index):568
    jQuery 7
    _getExtensions configuration.js:124
```
