### ISSUE TITLE
Git Workflow

### ISSUE THREAD

**Issue by bchartier** [geobretagne/mviewer#188]
Pour les développeurs de mviewer : 
Est-ce que vous seriez favorables à utiliser le Git Workflow ?
cf. https://www.nicoespeon.com/fr/2013/08/quel-git-workflow-pour-mon-projet/#le-principe
cf. https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow

Je préfèrerais qu'on évite d'écrire directement dans la branche master.

**Comment by spelhate** [comment]
Ok pour moi.

**Comment by bchartier** [comment]
Les conséquences organisationnelles :
- on crée une branche develop qui évolue au quotidien en y intégrant les travaux validés des uns et des autres
- la branche master ne contiendrait que le code des releases officielles
- le travail de correction et d'évolution du code se fait dans des branches temporaires qui sont ensuite fusionnées dans develop une fois que leur fonctionnement est validé

Les pullrequests devront donc être fusionnées dans develop après validation et non dans master.

**Comment by spelhate** [comment]
Ok. Je crée la branche develop. Il faut également créer les branches releases, et hotfix comme sur cette illustration ?

![image](https://user-images.githubusercontent.com/1793792/70606989-f63ba000-1bfd-11ea-8da9-6347e3b748c3.png)

**Comment by bchartier** [comment]
Non, en fait, seules les branches master et develop sont permanentes. Les autres sont à créer en fonction des besoins et à supprimer après que la fusion dans master ou develop a été réalisée avec succès.
On ne va pas avoir de branche "feature" en tant que tel par exemple. On aura des branches "feat-machin" et "feat-truc" le temps des développements des fonctions "machin" et "truc". Mais ce sera plutôt dans le dépôt d'un des développeurs. Pareil pour release : ce sera une branche temporaire pour une release particulière.

**Comment by Gaetanbrl** [comment]
Petit complément à bchartier, ls hotfix sont à créer pour rajouter, par exemple, une résolution rapide / à chaud (hot) d'un bug (fix). Ca évite de passer dans tout le process Feature -> dévelop -> release -> master.
Le schéma est très clair en tout cas ! :)

**Comment by bchartier** [comment]
> Petit complément à bchartier, les hotfix sont à créer pour rajouter, par exemple, une résolution rapide / à chaud (hot) d'un bug (fix). Ca évite de passer dans tout le process Feature -> dévelop -> release -> master.

Oui et non :
- les hotfixs sont appliqués directement sur master car ils ont appliqués en cas d'urgence. Genre, on a un bug rédhibitoire qui empêche l'utilisation de la branche master. C'est une procédure d'urgence en somme.
- mais les hotfixs doivent être également appliqués à develop selon la procédure usuelle pour les autres bugs et évolutions.
Pour les hotfixs on a bien une flèche qui part vers la branche master et une autre vers develop. C'est plus de boulot mais en réduisant le temps d'attente pour trouver la correction dans master.

**Comment by spelhate** [comment]
Je viens de créer la branche **develop**. Il n'y a plus qu'à.

**Comment by bchartier** [comment]
J'ai donc changé sur toutes les pullrequests en attente la branche destination : c'était master ; c'est maintenant develop.

**Comment by spelhate** [comment]
Je viens de merger la PR #195 dans la branch develop.
@Gaetanbrl , il faut peut-être communiquer le git flow dans la doc comment contribuer ?

**Comment by Gaetanbrl** [comment]
@spelhate je peux m'en occuper semaine prochaine.

**Comment by lecault** [comment]
A clore ?

**Comment by Gaetanbrl** [comment]
Oui je pense @lecault
