### ISSUE TITLE
Labels des issues

### ISSUE THREAD

**Issue by bchartier** [geobretagne/mviewer#189]
Pour info, j'ai converti les labels "Evolution" en "enhancement" avant de supprimer "Evolution" pour éviter d'avoir deux tags équivalents et privilégier les tags par défaut de Github.

J'ai également créé les labels suivants :
- technical assistance : les questions sur l'usage de l'outil
- organisation : les tickets relatifs à l'organisation du projet (par exemple le présent ticket et celui sur l'usage du Git workflow)

**Comment by bchartier** [comment]
En complément :
- j'essaie d'affecter des labels à tous les tickets ouverts
- l'idée c'est de faciliter la revue des tickets pour leur affectation voire leur fermeture

**Comment by bchartier** [comment]
J'ai ajouté un label "communication" pour les annonces en tout genre.

**Comment by bchartier** [comment]
Est-ce que j'ajoute un label "documentation" pour marquer tous les tickets en rapport avec la mise à jour de la doc ?

**Comment by spelhate** [comment]
Good job !
