### ISSUE TITLE
Paramètre "styles" à la place de "style"

### ISSUE THREAD

**Issue by bchartier** [geobretagne/mviewer#192]
En lisant le code existant j'ai l'impression que nous avons une incohérence.
A certains endroits nous utilisons un paramètre `layer.styles` et à d'autres `layer.style` pour les thématiques.
La doc de mviewer mentionne `layer.style` : https://mviewerdoc.readthedocs.io/fr/latest/doc_dev/config_layers.html#syntaxe-layer
la doc de GeoServer mentionne aussi un paramètre `STYLE` au singulier :
https://docs.geoserver.org/stable/en/user/services/wms/get_legend_graphic/index.html

Quelques exemples d'utilisation de layer.styles qui me semblent erronés :

- https://github.com/geobretagne/mviewer/blob/master/js/mviewer.js#L332-L335
- https://github.com/geobretagne/mviewer/blob/master/js/mviewer.js#L2031-L2036

Ce qui m'étonne c'est que personne ne semble avoir remarqué d'anomalie lié à cela.
Est-ce que je corrige cela ?

**Comment by spelhate** [comment]
Il ne s'agit pas d'une anomalie mais d'une modification d'un comportement originel qui peut effectivement entraîner une difficulté de lecture.
`Layer.style` est alimenté par le paramètre de configuration` style="monstyle"`
si le paramètre style contient plusieurs styles (c'est là qu'est l'évolution)  ex : ` style="monstyle1,monstyle2"`, alors
la propriété `layers.styles="monstyle1,monstyle2"` **est créee** et la propriété  `style="monstyle1"` contient alors le style courant appliqué à la couche.
Ce mécanisme est utilisé lorsqu'on souhaite proposer un sélecteur de styles sur une couche.

**Comment by bchartier** [comment]
Ok. Pas évident de comprendre cela effectivement.
Bon, du coup, je pense que j'ai commis une ânerie dans une de mes dernières pullrequests :
https://github.com/geobretagne/mviewer/pull/193/files#diff-4c92f58ddafebd1177bd43818a697300R329

Il va falloir que je corrige alors.
