### ISSUE TITLE
Site

### ISSUE THREAD

**Issue by smevel** [geobretagne/mviewer#196]
Site (développé sur [Hugo](https://gohugo.io/) et hébergé sur netlify), créé à l'issue des rencontres mviewer :
![téléchargement](https://user-images.githubusercontent.com/22056698/80419193-f69cb500-88d8-11ea-9020-f54c2a4513d7.png)
https://mviewer.netlify.com/

A faire [maj : 27/04/2020] :
- version multilingue ~~fr / en~~ / es / de / sk... ?
- intégrer une carte avec les organismes ayant déployé des applications
- ~~un portfolio avec un résumé des projets~~

Vos remarques et demandes d'améliorations sont les bienvenues

**Comment by bchartier** [comment]
Très  sympa.

**Comment by pierrejego** [comment]
Pareil j'ai beaucoup aussi. 

Qu'est-ce que tu vas pouvoir mettre comme page derrière "Bien démarré" ?

Et merci pour la partie "ils contribuent et développent"

**Comment by hsquividant** [comment]
Joli ! 
Peux-tu ajouter l'INRA et l'UMR SAS à la rubrique "Ils réutilisent" ? logos ici : https://www6.rennes.inra.fr/umrsas/ 
et aussi le WPS à "Compatible avec les standards de l’OGC..."
Merci

**Comment by bchartier** [comment]
> et aussi le WPS à "Compatible avec les standards de l’OGC..."

Sur la partie "compatibilité" : 

On site à la fois les standards et certaines implémentations (GeoServer et GeoNetwork). On essaie (en tout cas c'est mon cas) de faire en sorte que mviewer soit opérationnel avec le maximum d'implémentations possibles et respecte autant que possible les standards. Du coup, j'aurais tendance à ne pas limiter les exemples à une seule implémentation.

Pour WPS, c'est particulier car le cœur de mviewer ne contient pas de code relatif à ce standard. C'est juste qu'on peut utiliser n'importe quelle API web dans des customcontrols et customlayers. En termes, de compatibilité ça nous fait un terrain de jeu super large.

Ma tendance à tout compliquer me pousse à suggérer à séparer en deux :
- les standards implémentés dans le cœur de l'outil
- les standards dont on sait qu'ils fonctionnent bien avec mviewer parce qu'on les a mis en œuvre dans des exemples d'implémentation

Mais on peut aussi rester simple et tout mettre dans le même paquet...

**Comment by bchartier** [comment]
j'oubliais : "standards et OGC" ne sont pas super vendeurs de nos jours et en même temps restrictifs. Peut-être que nous ferions mieux de parler d'interopérabilité au travers de standards (tout court) et d'API. Cela permettrait de caser la recherche d'adresses de la BAN (https://geo.api.gouv.fr/adresse).

**Comment by Gaetanbrl** [comment]
Je proposerai de passer "ils réutilisent" par "ils l'on adopté" ou bien "ils l'ont choisi"

**Comment by Gaetanbrl** [comment]
Pour la partie design / graphique c'est super joli (vraiment) mais je relèverai seulement deux petites choses :
- La police en blanc (petite taille) sur fond jaune ne facilite pas la lecture, soit un blanc en gras (`font-weight :bold`) soit du noir / gris. j'ai testé ca rend pas mal.
- Les logos en fin de page serait plus jolis en couleur en adéquation avec le reste super punchy que je trouve très sympa ! :wink:

Ce ne sont que des retours perso après... 🙈

**Comment by Gaetanbrl** [comment]
Pour rebondir sur ce que disait @bchartier `Interopérable` à la place de `Compatible avec les standards de l’OGC` c'est, je pense aussi, plus vendeur.

Par contre `Installation simple et rapide` suivi de `Paramétrage en XML` ca m’interpelle si je me met à la place de profils plus enclins à utiliser le mviewer studio. Peut être que parler de quelque chose comme `paramétrage avancé` ou d'un `mode administrateur (xml)` serait moins effrayant ?

**Comment by Gaetanbrl** [comment]
Une idée au passage, ce serait faisable de faire un carrousel de Mviewer dans la partie des démonstrateurs "Les réutilisateurs en carte" ?

**Comment by SylvainMassol** [comment]
Super ! Cela va augmenter la visibilité du projet. Le site est joli et très clair, félicitation !
Si vous souhaitez, vous pouvez nous ajouter en tant que ré-utilisateur :
Communauté d'agglomération de l'albigeois
https://carto.ic2a.net/
logo : https://carto.ic2a.net/img/logo/Grand-Albigeois_logo.jpg

**Comment by hsquividant** [comment]
> 
> 
> j'oubliais : "standards et OGC" ne sont pas super vendeurs de nos jours et en même temps restrictifs. Peut-être que nous ferions mieux de parler d'interopérabilité au travers de standards (tout court) et d'API. Cela permettrait de caser la recherche d'adresses de la BAN (https://geo.api.gouv.fr/adresse).

Effectivement les standards et encore plus le WPS ne sont pas très vendeurs !
Si on veut être complet, on peut mettre en avant l'interopérabilité et les API d'une part, les standards implémentés au cœur du MViewer d'autre part en peut-être finir avec les standards implémentés dans des exemples via les extensions permises par les customLayers/customControls.

**Comment by smevel** [comment]
Version modifiée avec prise en compte des propositions :
- ajout des logos (INRA @hsquividant , Grand Albigeois @SylvainMassol) en noir et blanc sinon c'est l'arlequin ;) @Gaetanbrl 
- "interopérabilité" et xml @bchartier & @Gaetanbrl
- css "font-weight-normal" @Gaetanbrl

**Comment by smevel** [comment]
version 0.2 avec prise en charge de multilingue (fr/en)

**Comment by smevel** [comment]
version 0.3 avec menu modifié et ajout du lien Github (icone et menu)

**Comment by smevel** [comment]
_Version 0.4 à venir avec ajout du portfolio_

Pour avis, proposition de portfolio :
![portfolio](https://user-images.githubusercontent.com/22056698/79580779-cfb8d480-80c9-11ea-9002-53da5f2d4a0b.png)
- possibilité de filtrer par type de mviewer [ simple / avancé ] ou autre choix ?
- résumé court et nom du producteur
- lien vers le site ou application

basé sur le tableau de recensement des mwievers existant, vous pouvez le compléter : https://lite.framacalc.org/9g6e-mviewer_porfolio
il permettra ensuite de créer une carte avec tous les mviewers

**Comment by Gaetanbrl** [comment]
@smevel on a réalisé un catalogue un peu sur la même idée :

https://gis.jdev.fr/mviewer/catalogue/

Derrière, on a une recherche Fuse mais c'est un JSON qui est alimenté comme fichier de config. J'aime bien l'idée du framacalc, c'est adaptable.

**Comment by smevel** [comment]
> Derrière, on a une recherche Fuse mais c'est un JSON qui est alimenté comme fichier de config. J'aime bien l'idée du framacalc, c'est adaptable.
on utilise framacalc pour alimenter le store du mviewer avec un csv
pour le site, ici je génére un json pour les screenshots automatiquement (pupeeter) et du yaml pour alimenter le porfolio via Hugo

**Comment by smevel** [comment]
> Derrière, on a une recherche Fuse mais c'est un JSON qui est alimenté comme fichier de config. J'aime bien l'idée du framacalc, c'est adaptable.

pour le site, ici je génére un json pour les screenshots automatiquement (pupeeter) et du yaml pour alimenter le porfolio via Hugo

**Comment by Gaetanbrl** [comment]
>  ici je génére un json pour les screenshots automatiquement (pupeeter)

Ca fonctionne avec des flux protégés ?

**Comment by smevel** [comment]
> Ca fonctionne avec des flux protégés ?

non

**Comment by Gaetanbrl** [comment]
Pour le portfolio Mviewer ca me semble bien :)

**Comment by Gaetanbrl** [comment]
Ca semble fonctionner avec une authent HTTP :

```
page.authenticate(credentials)

    credentials <?Object>
        username <string>
        password <string>
    returns: <Promise>

Provide credentials for HTTP authentication.

To disable authentication, pass null.
```

**Comment by smevel** [comment]
**version 0.4** avec ajout du portfolio en Fr/En
et bonus le lien du site web d'Agathe Adam :)

**Comment by Gaetanbrl** [comment]
Très sympa @smevel ! 

Deux petites remarques : 
- Est-il possible de paginer le portfolio en catégorie "Tous" ? Ca fait une page super longue sur mobile et sur PC je trouve que ca rogne un peu le côté  synthétique et concis de la page.
- Toujours pas de couleur en bas après le portfolio ? :p

**Comment by spelhate** [comment]
Merci @smevel 
Je propose de remplacer le lien dans la description de mviewer sur la page principale du dépôt github  (http://kartenn.region-bretagne.fr/kartoviz/) par ce site (https://mviewer.netlify.com/)

**Comment by Gaetanbrl** [comment]
@smevel si on rajoute un Mviewer dans le fichier framacalc, ca se met à jour automatiquement sur le site directement ou bien il faut attendre une certaine heure de la journée la mise à jour ?

**Comment by smevel** [comment]
> @smevel si on rajoute un Mviewer dans le fichier framacalc, ca se met à jour automatiquement sur le site directement ou bien il faut attendre une certaine heure de la journée la mise à jour ?

non il faut lancer un script à la demande et une opération semi-manuelle pour les screenshot

**Comment by Gaetanbrl** [comment]
Ca marche, est-ce que vous pouvez réaliser cette opération pour prendre en compte les nouveaux (s'il y en a d'autres) ?

merci :)

**Comment by smevel** [comment]
oui à la demande et suivant la pertinence ;)

**Comment by Gaetanbrl** [comment]
J'en ai rajouté un avec plein d'informations graphique (le dernier ARS).
Je pense que vous serez les plus à même de juger de la pertinence de chacun avec ce que vous souhaitez montrer.

**Comment by smevel** [comment]
> J'en ai rajouté un avec plein d'informations graphique (le dernier ARS).
> Je pense que vous serez les plus à même de juger de la pertinence de chacun avec ce que vous souhaitez montrer.

Fait ajout de l'ARS et PIGMA ;)

**Comment by Gaetanbrl** [comment]
Merci @smevel
