### ISSUE TITLE
Impossible d'afficher une couche de GéoCompiégnois avec une version récente de mviewer

### ISSUE THREAD

**Issue by bchartier** [geobretagne/mviewer#199]
Avec les évolutions récentes de mviewer (aussi bien sur master que develop) impossible d'afficher des couches de GéoCompiégnois en http alors que cela fonctionnait auparavant.

Avec une version récente on obtient des erreurs du type :
`configuration.js:737 Mixed Content: The page at 'https://www.geo2france.fr/mviewer-develop/?config=apps/geocompiegnois.xml' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://geo.compiegnois.fr/geoserver/ows?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=geocompiegnois%3Adocurba&STYLES=&CRS=EPSG%3A3857&WIDTH=2869&HEIGHT=1468&BBOX=290068.9677137083%2C6332693.137884425%2C344893.4262512509%2C6360745.527265085'. This request has been blocked; the content must be served over HTTPS.
`

Démonstration avec un ancien mviewer :
https://www.geo2france.fr/mviewer/?config=apps/geocompiegnois.xml

Démonstration avec un nouveau mviewer :
https://www.geo2france.fr/mviewer-develop/?config=apps/geocompiegnois.xml

Le problème semble résider dans ce code :
https://github.com/geobretagne/mviewer/blob/develop/js/configuration.js#L713-L737

La modification de ce code pourrait être liée à ce commit :
https://github.com/geobretagne/mviewer/commit/c92cb07938c488d97f659e1c9c384696ab09b32

**Comment by spelhate** [comment]
Je confirme cette régression. Nous arrivons à contourner le problème lorsque le serveur distant est disponible en **https**.

**Comment by spelhate** [comment]
@bchartier . On peut fermer ce ticket ?

**Comment by bchartier** [comment]
oui
