### ISSUE TITLE
[mustache templates] loop through all attributes

### ISSUE THREAD

**Issue by jeanpommier** [geobretagne/mviewer#205]
Hi,
In freemarker templates, one can easiliy loop through available values this way:
```
<#list feature.attributes as attribute>
    <#if !attribute.isGeometry>
      <td>${attribute.value}</td>
    </#if>
  </#list>
```
Is there a similar way using Mustache ?

My issue is I'm having some geoserver layers with year columns. As new years pass by, I'll have more year columns, so I don't want to hard code them, but I'd like to pass their values for use in a graph.

An alternative would be to be able to get the whole serialized feature as a separate attribute, so that I can pass the whole serialized feature to my graph js. What do you think ?

**Comment by Gaetanbrl** [comment]
Mustache is logic-less. You can't realize if/else condition or loop.

"if" condition is not directly insert with Mustache. You have to use this syntax to display something only if an attribute exist:

```
  {{#attribute_name}}
    <li><strong>{{name}}</strong></li>
  {{/attribute_name}}
```

To insert more logic, you could use <script> into template.js to execute some operations. You could use ID in you html template.js file as target for you'r same template <script> code. However, it's more difficult if your are a beginner with JS/HTML.

**Comment by Gaetanbrl** [comment]
Here an example : [click](https://codepen.io/johnsonshara/pen/mPzbBO).

**Comment by jeanpommier** [comment]
Thanks Gaetan. 

I think you didn't get my point (or I didn't get yours). 

I working on the display of data retrieved from a getFeatureInfo, so on the mst template that is rendered in https://github.com/geobretagne/mviewer/blob/master/js/info.js#L663 . So I don't have the control over the object that is passed (unless I change upstream code), only on the Mustache templating.

My aim is to be able to iterate through all the attributes (key/values), but I don't know in advance which might be the keys. I want to list values for all years. Supposing I know when it starts, I still don't know when it ends. Today, I have data up to 2018, but in a few months, I might also have data about 2019. And next year 2020 too. I don't want to hardcode the keys, I don't want to have to update my code every year.

One way would be to get the javascript object using {{.}} in a script tag and generate my html dynamically, but I didn't manage to do this (retrieve the object in js script tag). If you have an example, I'll gladly have a look.

BTW, I'm no beginner with JS/HTML. But total newbie on Mustache.

For now, the only way I found to do what I wanted is to serialize the whole feature and add it in the attributes list. This allows me then to get the attribute (One name, I can hardcode it no pb), deserialize and then loop over my values how I want. But this means changing a bit the code in https://github.com/geobretagne/mviewer/blob/master/js/info.js which I'm obviously reluctant to do.

**Comment by spelhate** [comment]
Hi,

Another way is modify [applyTemplate](https://github.com/geobretagne/mviewer/blob/master/js/info.js#L663) to construct a list named "**fields**" like for **features** list. By this way it could be possible to loop over each field with this code :
```
<#fields>
...
</fields>
```
This evolution needs a PR.

**Comment by jeanpommier** [comment]
Hi,
Thanks for the idea. It would allow to iterate through the values, but would it be possible to also get the keys ? (years in my case, quite necessary)

What do you think of my proposal to add the serialized feature in the attributes list of the feature ? I'd do a PR, no pb.
Just needs to add one line in [applyTemplate](https://github.com/geobretagne/mviewer/blob/3d21b02c2390e8c25f85412d3db02f5beb51c072/js/info.js#L663):
```
olfeatures.forEach(function(feature){
            if (activeAttributeValue) {
                feature.properties[activeAttributeValue] = true;
            }
            feature.properties['serialized'] = encodeURIComponent(JSON.stringify(feature.properties));
            obj.features.push(feature.properties);
        });
```
![Sélection_223](https://user-images.githubusercontent.com/4491521/72165238-67ba6a00-33c7-11ea-93a7-5724f1b0869e.png)

**Comment by Gaetanbrl** [comment]
Serialized could be a solution but this is a solution for your very specific case. From my point of view, use {{#features}} could be a more accessible approach for each others user / administrator and it's more uniform with actual logic.

But why don't you catch every keys with `Object.keys(jsObject)` and use a `for` loop over your parse getFeatureInfos objects to get values ? The `handle `available with a customcontrol allow you to prepare data according to a template when you click on a feature. So, you don't have to know anything about the keys or values. @spelhate, is it a possible approach ?

Apart from this, @jeanpommier, I invite you to explore the [contributor guide](https://mviewerdoc.readthedocs.io/fr/latest/doc_contrib/contrib.html) to propose your final solution. Thanks 😉!

**Comment by jeanpommier** [comment]
Hi @Gaetanbrl , thanks for your help.
Can you specify what you mean by {{#features}} ? You are referencing @spelhate 's proposal just above ?

I don't understand your suggestion about Object.keys(jsObject), I guess I'm too green on mviewer. I'll try to dig with that in mind

**Comment by jeanpommier** [comment]
Oh, OK, you're suggesting me to write a customcontrol to deal with my specific use case.  I'd have to have a customcontrol file for each similar layer, which makes some redundancy, but why not. Problem is, for now, I don't really understand how custom controls integrate into mviewer. Is there some documentation about customcontrols ? I found the examples, but I'd rather not reverse-engineer the whole thing.

**Comment by jeanpommier** [comment]
I'm preparing a PR, to come very soon this afternoon. Thanks for your help !

**Comment by jeanpommier** [comment]
See PR #206

**Comment by spelhate** [comment]
Merged. Thank's @jeanpommier & @Gaetanbrl.
We have to document this new capabilities in Read the doc.

**Comment by jeanpommier** [comment]
@spelhate thanks. I can document it, no pb. Where do you want it ? In the [template](https://mviewerdoc.readthedocs.io/fr/latest/doc_dev/config_tpl.html) page as a fifth paragraph ?

**Comment by Gaetanbrl** [comment]
> Where do you want it ? In the template page as a fifth paragraph ?

First, i think in [this page](https://mviewerdoc.readthedocs.io/fr/latest/doc_dev/config_tpl.html#configurer-templates).

Next, insert something in "ce qu'il faut savoir de Mustache" about mustache function as property.

To finish, maybe add a `{{fields_kv}}` reference inside "Explications: [...]" to explain that is possible to loop over features and fields.

What do you think about that ?

**Comment by jeanpommier** [comment]
Are you sure this s a good idea to dispatch the information about this functionality into several places ? In my perspective, "ce qu'il faut savoir de Mustache" is more a Mustache 101, while function generators are advanced stuff. A template user does not really need to know how it works, but rather what is available.

I've made a [PR](https://github.com/geobretagne/mviewer.doc/pull/25) where I regrouped all information related to these 2 virtual fields in a separate paragrah. I think this is more clear that way, please let me know what you think of it

**Comment by Gaetanbrl** [comment]
I will check you PR and come back later :)

**Comment by spelhate** [comment]
Can we close this ?

**Comment by jeanpommier** [comment]
I guess so. thanks !
