### ISSUE TITLE
Mustache -  out of <li>

### ISSUE THREAD

**Issue by Gaetanbrl** [geobretagne/mviewer#207]
Vu pendant les tests de la PR #206. Cette PR n'est pas liée au comportement décrit ci-dessous.

J'ai testé de rajouté du contenu Mustache en dehors de la liste pour le [template des lycées](https://github.com/geobretagne/mviewer/blob/master/templates/global.lycee.mst). 

Le comportement est très étrange... le contenu ne s'affiche pas pour le premier résultat et ne s'affiche pas non plus si on clique sur un seul lycée.

Voici mon code dans le template :

```
{{#features}}
	<li class="item" style="width:238px;">
		<h3 class="title-feature">{{nom}}</h3>
		<p class="text-feature">
			<h4 class="sub-title">Localisation</h4>		
			<span style="font-family:'roboto_bold'"> Commune :</span> {{libelle}}<br/>
			<span style="font-family:'roboto_bold'"> Code postal :</span> {{code_postal}}<br/>
			<span style="font-family:'roboto_bold'"> Adresse :</span> {{adresse}}<br/><br/>
			<h4 class="sub-title">Caractéristiques</h4>
			<span style="font-family:'roboto_bold'"> Type :</span> {{type_etabl}}<br/>
			<span style="font-family:'roboto_bold'"> Secteur :</span> {{secteur_li}}<br/>
			<span style="font-family:'roboto_bold'"> Réseau :</span> {{reseau_lib}}<br/>			
		</p>
		{{#photo}}
			<img src="{{photo}}" class="img-responsive" style="margin-top:5%;" />
		{{/photo}}
		
	</li>
	<li>
		test
		<h3 class="title-feature">{{nom}}</h3>

	</li>
{{/features}}
``` 

Etapes de test : 

1. Ajouter le code précédent dans le [template des lycées](https://github.com/geobretagne/mviewer/blob/master/templates/global.lycee.mst).
2. Afficher dans le navigateur le fichier de config.xml déjà présent par défaut à la racine du projet git cloné (renommer confi-sample.xml en config.xml au besoin)
3. Afficher la couche "Lycée" dans l'interface web du mviewer
4. Cliquer sur un lycée seul pour voir la fiche d'informations :
        **Attendu** : Visionner le template comme défini
        **Observé** : Template  corrompu. Les informations ne s'affichent pas correctement, voir même partiellement.
5. Cliquer sur plusieurs lycées pour lire la fiche d'informations des lycées en mode Carousel :
        **Attendu** : Visionner le template comme défini
        **Observé** : Template  corrompu. Les informations ne s'affichent pas correctement, voir même partiellement pour le premier résultat.

**Comment by spelhate** [comment]
Je crois savoir d'où ça vient.
La doc ne le précise pas mais les templates doivent retourner des éléments de liste html avec la classe **item**. ex : `<li class="item">...</li>`

**Comment by Gaetanbrl** [comment]
> La doc ne le précise pas mais les templates doivent retourner des éléments de liste html avec la classe item

J'allais chercher dans une direction de ce type. Merci @spelhate.
Donc on ne peut avoir qu'un seul élément `class="item"`, ce qui explique que ce n'est pas pris en compte.

Je ferme l'issue. J'en créée une dans la doc.
