### ISSUE TITLE
intégration tableau interactif dans infopanel

### ISSUE THREAD

**Issue by fxduponcheel** [geobretagne/mviewer#208]
Bonjour

Je souhaite intégrer un tableau interactif de l’Observatoire de l’Environnement de Bretagne (voir url ci-dessous) dans l’infopanel qui s'ouvre lorsque l'on clique sur une station de suivi de qualité d'eau. Est possible ? si oui quel code html utiliser ?
https://public.tableau.com/views/Evolutiondesconcentrationsennitratesdanslescoursdeaubreton_ExportSage/Details_Sage?Libelle_Sage=COUESNON&Code_Site=04163250&:showVizHome=no#13

Je passe par un fichier mustache car le tableau interactif à afficher dépend de la station sélectionnée (sur le lien c’est le tableau interactif de la station 04163250) :

{{#features}}
<li class="item" style="width:238px;">	
		<p class="text-feature">		
		<span style="font-family:'roboto_bold'"> Code Sandre de la station :</span> {{code_sandre}}<br/>
 		</p>

{{tableau_chemin}}

</li>		
{{/features}}

Les url sont stockées dans le champs « tableau_chemin » de la couche interrogée.

Lien vers le mviewer : http://geocouesnon.sage-couesnon.fr/geocouesnon/?x=-139130&y=6189706&z=10&l=v_percentile_nitrate*%252Ccours_eaudbl1*%252Cbassin_versant_couesnon*&lb=osm&mode=d

Merci d’avance pour votre aide

**Comment by spelhate** [comment]
Salut.

Le plus simple est de créer un lien hypertexte qui pointe sur ton tableau.
Exemple : 
```
{{#features}}
    Code Sandre de la station : {{code_sandre}}
    <a href="{{tableau_chemin}}" target="_blank">Tableau interactif"</a>
{{/features}}
```

**Comment by Gaetanbrl** [comment]
Je viens de tester l'intégration de votre page au sein d'une iframe. Mais le rendu n'est pas excellent.

![image](https://user-images.githubusercontent.com/16317988/72878078-922af200-3cfa-11ea-9f8c-454440d4963b.png)


```
<iframe
    width = "80%"
    src="{{tableau_chemin}}"
</iframe>
```

Il faut scroller pour lire les tableaux, la page étant assez grande. Pour l'affichage en mode mobile, ce sera de plus peu esthétique voir pas du tout adapté.

Le mieux est bien de faire un lien, comme présenté par @spelhate ou bien d'intégrer les charts directement avec Chart.Js ou PloltyJs.

**Comment by fxduponcheel** [comment]
Salut
Donc cela va être compliqué, notamment pour que cela soit compatible avec les tablettes et mobile ...
Je pense que je vais dans un premier temps utiliser le lien hypertexte. L'OEB devrait travailler prochainement sur l'adaptation de leur techno avec les mviewer. Chart.Js peut être une piste ...

Ou alors on peut essayer d'avoir les tableaux et graphiques sous forme d'une image fixe mais on aura le même soucis d'affichage avec les mobiles, tablettes ...

Encore merci pour votre aide

A+

**Comment by Gaetanbrl** [comment]
> L'OEB devrait travailler prochainement sur l'adaptation de leur techno avec les mviewer.

Quelles sont leurs technos actuelles ?

**Comment by fxduponcheel** [comment]
Je laisse Elodie Bardon, mon interlocutrice à l'OEB, répondre à cette question.
