### ISSUE TITLE
Légende : faire apparaitre ou non une couche

### ISSUE THREAD

**Issue by t29leo** [geobretagne/mviewer#209]
Bonjour,

J'ai une couche de type "masque" que je souhaite faire apparaitre sur ma carte, mais je ne souhaite pas qu'elle soit listée dans la légende car elle "pollue" la légende. Exemple d'une couche qui masque une partie d'un territoire pour mettre en avant un autre. 

Pour ce type de couches (non thématique), est-il possible de créer une option pour la rendre active ou inactive dans la légende ?
Cette demande fait écho avec l'issue #24 : "Option Thematique"

Je vous remercie.

**Comment by Gaetanbrl** [comment]
> @spelhate a raison : on a des demandes plus récentes sur lesquelles nous devons travailler. On ferme et n rouvrira si besoin.

Pop @bchartier @spelhate .

**Comment by Gaetanbrl** [comment]
> est-il possible de créer une option pour la rendre active ou inactive dans la légende ?

Bonjour @t29leo ,

Oui il est toujours possible de rajouter une option dans le config pour qu'une couche ne soit pas visible dans la légende.

Pour créer un effet de masque, vous pouvez appliquer un style disposant d'un filtre CQL (geoserver) afin de mettre en évidence une entité / un objet spécifique sur la carte.

http://kartenn.region-bretagne.fr/kartoviz/?config=demo/cql.xml

**Comment by t29leo** [comment]
Ok pour la création d'un masque via un filtre CQL, mais la couche (masque) apparait toujours dans la légende. Je souhaiterais justement que ce masque n'apparaisse pas dans la légende.
Si vous avez une solution, je suis très intéressé.

**Comment by Gaetanbrl** [comment]
> Si vous avez une solution, je suis très intéressé.

C'est un développement à réaliser comme précisé dans l'issue #24 . Il nous faut dégager un peu de temps pour la réaliser. Si vous souhaitez faire cette évolution ce sera avec plaisir que nous pourrons vous aider à la réaliser.

N’hésitez-pas à lire le [guide de contribution](https://mviewerdoc.readthedocs.io/fr/latest/doc_contrib/contrib.html).

**Comment by t29leo** [comment]
Ok. je vous remercie. Je vais regarder ça, même si mes compétences en développement sont très limitées, voire inexistantes...

**Comment by Gaetanbrl** [comment]
> Ok. je vous remercie. Je vais regarder ça, même si mes compétences en développement sont très limitées, voire inexistantes...

Un seul retour sur notre documentation sera déjà bénéfique si vous ne vous sentez pas à réaliser une contribution en développement 😉

**Comment by t29leo** [comment]
Je peux faire au moins ça!

**Comment by lecault** [comment]
Nous avons ce besoin à la région pour par exemple mettre en fond un contour EPCI non enlevable.

Nous allons faire une proposition.

**Comment by spelhate** [comment]
Travaux menés sur branche f209 avec la création d'un nouveau paramètre de couche :  **showintoc**

Par défaut ce paramètre a la valeur true. Pour désactiver l'affichage d'une couche dans la légende et l'arborescence des thématiques, il faut attribuer la valeur false à ce paramètre.
