### ISSUE TITLE
Mviewer et smartphone

### ISSUE THREAD

**Issue by tanguyj** [geobretagne/mviewer#21]
Quand on utilise un smartphone, la croix pour fermé le volet de gauche est presque invisible, il faudrait décalé le volet de gauche de quelques pixel ...

**Comment by tanguyj** [comment]
Dans le fichier mobile-panel-size.less.css à la 3eme ligne passer de 28em à 26.6em et ça passe

**Comment by spelhate** [comment]
Le bouton de fermeture a été déplacé
