### ISSUE TITLE
Intitulés menus mode responsive

### ISSUE THREAD

**Issue by lecault** [geobretagne/mviewer#211]
Hello,

Je souhaiterai soumettre au débat de la communauté le nommage des intitulés des menus en mode responsive. En effet, cela ne parle pas aux utilisateurs du mviewer à la région.

![image](https://user-images.githubusercontent.com/5269430/73060634-8ecd6d00-3e98-11ea-8b08-d6838b45361a.png)

Actuellement on a 3 intitulés : 
- Données : affiche les thématiques pour cocher/décocher les couches
- Affichage : affiche la légende et les options supplémentaires sur les couches
- Aide : affiche la pop up d'aide ou d'informations supplémentaires sur l'application

Propositions : 
- Données : les utilisateurs verraient bien "Filtre" qui pour nous ne parle pas. Données semble parlant ou Thématiques pour reprendre l'intitulé de la popup.
- Affichage : il semblerait logique de le remplacer par Légende même si les possibilités sont plus grandes.
- Aide : le champ d'action de ce contenu est plus large que la seule aide. On propose Ressources ou A propos.

**Comment by fxduponcheel** [comment]
Légende pour remplacer affichage, ok
A propos pour remplacer aide, ok
Par contre données est pour moi bien adapté

**Comment by t29leo** [comment]
Je vote pour :
- Données ou Thématiques
- Légende
- A propos

**Comment by bchartier** [comment]
Mon impression :
* Filtre : non, je n'aime pas du tout
* A propos : très bien
* Les deux premiers menus concernent tous les 2 les données : les données disponibles et les données activées. Mais c'est trop long dans un titre responsive sans doute. S'il faut être court autant choisir Thématiques et Légendes.

**Comment by fxduponcheel** [comment]
"Les deux premiers menus concernent tous les 2 les données : les données disponibles et les données activées. Mais c'est trop long dans un titre responsive sans doute. S'il faut être court autant choisir Thématiques et Légendes."

oui je suis d'accord

**Comment by lecault** [comment]
Merci de vos avis.

Si je fais la synthèse, on part sur :
- Thématiques
- Légende
- A propos

Je vais faire la modif sur la branche develop
