### ISSUE TITLE
"cnn is not defined" lors de l'interrogation d'une couche

### ISSUE THREAD

**Issue by jbdesbas** [geobretagne/mviewer#212]
Bonjour,

J'ai un petit problème lors de l'interrogation d'une couche WMS. J'obtiens le message d'erreur suivant dans la console : `ReferenceError: cnn is not defined` (et le panneau ne s'affiche pas).
Ce qui est curieux c'est que pour d'autres couches ça fonctionne très bien avec la même configuration, je ne vois pas ce qui peut provoquer ça. Apparement c'est un problème au moment où les attributs xml sont parsés (https://github.com/geobretagne/mviewer/blob/3309d79eef80c6ecdbe98329f5e2008c4bf20864/lib/jquery/base/plugins/xml2json/jquery.xml2json.js)

Une idée ?

**Comment by spelhate** [comment]
Bonjour,
Vous avez un lien vers la couche qui pose problème ?
Visiblement, il s'agit d'un problème de parsing xml de la réponse du serveur carto. Quel est le serveur carto utilisé : geoserver, mapserver ArcGis server ?

**Comment by jbdesbas** [comment]
Tout est dispo ici : http://lutea.clicnat.fr/
C'est la couche "atlas chiro" qui pose soucis (j'ai testé en désactivant la temporalité, ca ne change rien).
Les flux sont servis via geoserver depuis une source postgis.
Merci pour l'aide.

**Comment by jbdesbas** [comment]
Solution sale : en commentant la ligne suivante ça fonctionne. Le pourquoi et le comment reste un mystère pour moi. 
https://github.com/geobretagne/mviewer/blob/3309d79eef80c6ecdbe98329f5e2008c4bf20864/lib/jquery/base/plugins/xml2json/jquery.xml2json.js#L87

Issue à fermer ou à creuser ?

**Comment by spelhate** [comment]
Je ne reproduis pas le problème. Testé avec FireFox et Chrome.

**Comment by bchartier** [comment]
Est-ce que votre souci est toujours d'actualité ?
J'ai l'impression que http://lutea.clicnat.fr/ ne répond plus.
Si votre souci est toujours d'actualité, est-ce que vous pourriez indiquer quelle est la requête http/https envoyée par mviewer dont la réponse lui pose un problème d'interprétation ?
Vous devriez la voir passer dans l'onglet réseau/network des outils de dev de votre navigateur.

**Comment by jbdesbas** [comment]
Bonjour,
J'ai appliqué le patch ci-dessus, et aucun problème. Le bon lien est maintenant https://oursin.clicnat.fr 
Exemple de requête qui posait soucis : 
https://www.geo2france.fr/geoserver/picardie_nature/ows?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetFeatureInfo&FORMAT=image%2Fpng&TRANSPARENT=true&QUERY_LAYERS=temporal_atlas&LAYERS=temporal_atlas&STYLES=&CQL_FILTER=id_atlas%3D2&INFO_FORMAT=application%2Fvnd.ogc.gml&I=50&J=50&CRS=EPSG%3A3857&WIDTH=101&HEIGHT=101&BBOX=287326.78932397754%2C6334412.97102084%2C302767.0690375832%2C6349853.25

Je vais retester plus en détail pour reproduire le bug

**Comment by spelhate** [comment]
Le résultat de la requête geoserver est étrange : on trouve des éléments de ce type : `<picardie_nature:cdnom_parent>[Ljava.lang.Integer;@113eb627</picardie_nature:cdnom_parent>`

**Comment by jbdesbas** [comment]
Ce champs est de type "array integer" (interger[] ) peut-être un lien avec cette bizarrerie ?
Je ne pense pas que ca ai un rapport avec le problème initial, car à l'origine ce champs était un integer.

**Comment by bchartier** [comment]
On a aussi une valeur de champ plutôt complexe :
[{"cd_nom": 60479, "lb_nom": "Pipistrellus pipistrellus", "nom_vern": "Pipistrelle commune"}]
Je ne sais pas si ça peut poser problème à JQuery.
En tout cas la couche vient du GeoServer de geOrchestra de Géo2France. Je vais pouvoir regarder cela avec l'admin du portail.

Même si vous avez contourné le souci en retirant une ligne de code. Je pense qu'on a intérêt à identifier correctement la cause du problème soit pour corriger mviewer (s'il y a lieu) soit aboutir à des bonnes pratiques au niveau de la publication des données.

**Comment by bchartier** [comment]
J'ai réussi à reproduire l'anomalie.
C'est la lib jquery.xml2json.js qui produit l'erreur ReferenceError: cnn is not defined à la ligne 87.
Effectivement la variable ccn n'est pas définie dans le scope de la ligne 87.
J'ai vraiment l'impression que c'est un big de cette lib.
Elle me semble plutôt artisanale et elle n'a pas été mise à jour depuis 6 ans.

L'erreur se produit avec un une réponse GetFeatureInfo de la forme :
```
<?xml version="1.0" encoding="UTF-8"?>
<wfs:FeatureCollection xmlns="http://www.opengis.net/wfs" xmlns:wfs="http://www.opengis.net/wfs"
                       xmlns:picardie_nature="https://www.geo2france.fr/picardie_nature"
                       xmlns:gml="http://www.opengis.net/gml" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                       xsi:schemaLocation="http://www.opengis.net/wfs https://www.geo2france.fr/geoserver/schemas/wfs/1.0.0/WFS-basic.xsd https://www.geo2france.fr/picardie_nature https://www.geo2france.fr/geoserver/picardie_nature/wfs?service=WFS&amp;version=1.0.0&amp;request=DescribeFeatureType&amp;typeName=picardie_nature%3Aatlas_macrommam_hdf">
    <gml:boundedBy>
        <gml:Box srsName="http://www.opengis.net/gml/srs/epsg.xml#3857">
            <gml:coordinates xmlns:gml="http://www.opengis.net/gml" decimal="." cs="," ts=" ">
                280132.511094,6362422.483976 287862.105364,6370174.016193
            </gml:coordinates>
        </gml:Box>
    </gml:boundedBy>
    <gml:featureMember>
        <picardie_nature:atlas_macrommam_hdf fid="atlas_macrommam_hdf.fid--753ea2dc_170af62e60a_3043">
            <gml:boundedBy>
                <gml:Box srsName="http://www.opengis.net/gml/srs/epsg.xml#3857">
                    <gml:coordinates xmlns:gml="http://www.opengis.net/gml" decimal="." cs="," ts=" ">
                        280132.511094,6362422.483976 287862.105364,6370174.016193
                    </gml:coordinates>
                </gml:Box>
            </gml:boundedBy>
            <picardie_nature:fid>26928</picardie_nature:fid>
            <picardie_nature:id_atlas>13</picardie_nature:id_atlas>
            <picardie_nature:code_atlas>MACROMAMM</picardie_nature:code_atlas>
            <picardie_nature:lbnom_parent>Macro-Mammifères</picardie_nature:lbnom_parent>
            <picardie_nature:cdnom_parent>[Ljava.lang.Integer;@5a0f2d94</picardie_nature:cdnom_parent>
            <picardie_nature:n_sp>10</picardie_nature:n_sp>
            <picardie_nature:relative_n_sp>0.5555555555555556</picardie_nature:relative_n_sp>
            <picardie_nature:ref_year>2020-12-31T22:59:59.999Z</picardie_nature:ref_year>
            <picardie_nature:area_code>5kmL93E0665N6935</picardie_nature:area_code>
            <picardie_nature:type_code>M5</picardie_nature:type_code>
            <picardie_nature:detail_especes>[{"cd_nom": 61057, "lb_nom": "Capreolus capreolus", "nom_vern": "Chevreuil
                européen, Chevreuil"}, {"cd_nom": 60015, "lb_nom": "Erinaceus europaeus", "nom_vern": "Hérisson
                d'Europe"}, {"cd_nom": 61678, "lb_nom": "Lepus europaeus", "nom_vern": "Lièvre d'Europe"}, {"cd_nom":
                60674, "lb_nom": "Martes foina", "nom_vern": "Fouine"}, {"cd_nom": 60636, "lb_nom": "Meles meles",
                "nom_vern": "Blaireau d'Europe"}, {"cd_nom": 60716, "lb_nom": "Mustela nivalis", "nom_vern": "Belette"},
                {"cd_nom": 60731, "lb_nom": "Mustela putorius", "nom_vern": "Putois"}, {"cd_nom": 61714, "lb_nom":
                "Oryctolagus cuniculus", "nom_vern": "Lapin de garenne"}, {"cd_nom": 60981, "lb_nom": "Sus scrofa",
                "nom_vern": "Sanglier"}, {"cd_nom": 60585, "lb_nom": "Vulpes vulpes", "nom_vern": "Renard roux"}]
            </picardie_nature:detail_especes>
            <picardie_nature:geom>
                <gml:MultiPolygon srsName="http://www.opengis.net/gml/srs/epsg.xml#3857">
                    <gml:polygonMember>
                        <gml:Polygon srsName="EPSG:3857">
                            <gml:outerBoundaryIs>
                                <gml:LinearRing>
                                    <gml:coordinates xmlns:gml="http://www.opengis.net/gml" decimal="." cs="," ts=" ">
                                        280179.555551,6362422.483976 280132.511094,6370130.169635
                                        287821.781142,6370174.016193 287862.105364,6362466.254152
                                        280179.555551,6362422.483976
                                    </gml:coordinates>
                                </gml:LinearRing>
                            </gml:outerBoundaryIs>
                        </gml:Polygon>
                    </gml:polygonMember>
                </gml:MultiPolygon>
            </picardie_nature:geom>
        </picardie_nature:atlas_macrommam_hdf>
    </gml:featureMember>
</wfs:FeatureCollection>
```

L'anomalie semble se produire à la lecture de cette attribut : ` fid="atlas_macrommam_hdf.fid--753ea2dc_170af62e60a_3043"` lorsque un élément possède nommé fid existe déjà par ailleurs. La lib se prend alors les pieds dans le tapis.

Il faut donc se débrouiller pour ne pas avoir de champ "fid" en même temps qu'un attribut "fid" au niveau de l'objet en lui-même. Je sais pas si c'est très clair.

**Comment by spelhate** [comment]
Merci @bchartier pour ces investigations

**Comment by Gaetanbrl** [comment]
@bchartier l'issue a été ré-ouverte. C'est côté Mviewer que le correctif doit être fait ? Vous êtes en attente de quelque chose ?

**Comment by MoulinZ** [comment]
Personnellement j'avais ce problème également, avec un champ "fid" créé automatiquement par un geopackage, et en le supprimant (il ne m'était pas utile), le problème a été résolu.

**Comment by Gaetanbrl** [comment]
@bchartier on peut fermer cette issue (pas de retour depuis le 06/03/2020) ?

**Comment by Gaetanbrl** [comment]
Sans nouvelles depuis le 06/03/2020, je ferme cette issue.
