### ISSUE TITLE
Config - afficher la legende sans le panneau de couche

### ISSUE THREAD

**Issue by Gaetanbrl** [geobretagne/mviewer#216]
Lorsque j'arrive sur ma carte, je souhaite que seul ma légende soit visible sans voir la liste des couches.
J'ai essayé `mini="false"` mais le volet de légende est masqué également.

J'ai regardé les différents modes d'affichage `mode=u` et `mode=s` mais cela ne correspond pas non plus.

Je pensais avoir déjà vu ce type de configuration... sinon je peux faire une évolution ?

**Comment by bchartier** [comment]
Est-ce que c'est `<themes mini="">` que tu cherches ?

**Comment by Gaetanbrl** [comment]
Je cherche à obtenir ce type d'affichage par défaut : 

![image](https://user-images.githubusercontent.com/16317988/74154042-24dff200-4c12-11ea-8d88-47825ae2c2b0.png)


`<themes mini="">` sembler déplier la liste des thème et la légende.
`<themes mini="true">` semble replier les deux.

**Comment by spelhate** [comment]
La ligne qui empêche le comportement souhaité se situe ici : https://github.com/geobretagne/mviewer/blob/c950bbdce65bc6f8f7d24c3132bda25e091ac7b7/js/mviewer.js#L789

**Comment by Gaetanbrl** [comment]
Merci @spelhate, ca vous va si je rajoute un paramètre legendMini ? 

Autrement je peux rajouter une valeur pour le paramètre panelMini.
Vu que c'est un contrôle sur une chaîne en guise de booléen (`if (panelMini && (panelMini === 'true')) {`), c'est réalisable avec le code en place.

J'adapterai le readme / readsthedoc en conséquence.

**Comment by Gaetanbrl** [comment]
Je propose deux choses : 
1 - Modifier le paramètre "mini" pour accepter une autre valeur supplémentaire à "true"/"false".

Le positif : pas de énième paramètre. Ca reste compatible avec les Mviewer déjà existants.
Le négatif: ce n'est plus vraiment un booléen, ce n'est plus très cohérent mais on peut toujours changer la doc.

2 - Ajouter un paramètre "legend" de type booléen true/false. Si legend == true et que mini == true alors on affiche la légende même si le volet des couches et replié.

Le positif : C'est plus cohérent qu'un paramètre qui peut prendre true/false/valeurX.
Le négatif: un paramètre de plus.

**Comment by bchartier** [comment]
J'aurais tendance à préférer la solution 2.
Néanmoins, je pense qu'il faut éviter autant que possible de casser les applications existantes.
Je n'ai pas regardé quelle solution limiterait le plus la reprise des XML existants. Est-ce que tu sais ?

**Comment by Gaetanbrl** [comment]
> Néanmoins, je pense qu'il faut éviter autant que possible de casser les applications existantes.

* Ce qu'implique la solution 1

Le paramètre mini attend un string. Il est contrôlé comme tel dans le JavaScript : 
https://github.com/geobretagne/mviewer/blob/a6d9e0713837611d4c52e0abeddab67310fda124/js/mviewer.js#L787

On peut donc rajouter une autre valeur sans trop de risque.
On devra adapter la doc car ce n'est plus un booléen et ca fonctionnera quand même avec d'autres XML déjà existants car les valeurs "initiales" seront toujours prises en compte. C'est seulement une autre condition du type : 

```
        var panelMini = configuration.getConfiguration().themes.mini;
        if(panelMini === "middle") {
            mviewer.toggleMenu(false);
        } else if (panelMini && (panelMini === 'true')) {
            mviewer.toggleMenu(false);
            mviewer.toggleLegend(false);
        }
```

* Solution 2

C'est un paramètre supplémentaire à prendre en compte. Les XML qui n'ont pas ce nouveau paramètres fonctionneront de façon "classique" :

```
        var panelMini = configuration.getConfiguration().themes.mini;
        var legendMini = configuration.getConfiguration().themes.legend;
        if (panelMini && (panelMini === 'true')) {
            mviewer.toggleMenu(false);
            mviewer.toggleLegend(false);
        }
        if(legendMini && (legendMini === "false")) {
            mviewer.toggleLegend(true);
        }
```


Dans les deux cas, ca n'impliquerai, sauf erreur de ma part, aucune reprise des XML.

**Comment by bchartier** [comment]
Du coup, je suis le seul à avoir un avis ? une préférence pour la solution 2 ?

**Comment by Gaetanbrl** [comment]
@bchartier Je préférerai ne pas avoir d'autre paramètre de mon point de vue mais c'est peut être plus "propre" avec un nouveau :)

==> Réponse de normand non ?

**Comment by bchartier** [comment]
En fait, j'aimerais bien ne pas ajouter de nouveaux paramètres mais je préfère quand chaque paramètre ne mélange pas plusieurs concepts. C'est pour cela que j'ai préféré la solution 2 qui est moins économique mais peut-être plus simple à comprendre.

**Comment by spelhate** [comment]
> Du coup, je suis le seul à avoir un avis ? une préférence pour la solution 2 ?

J'ai également une préférence pour la 2e solution. On y gagne en clarté.

**Comment by Gaetanbrl** [comment]
Solution 2 adoptée donc.

**Comment by Gaetanbrl** [comment]
@spelhate sais-tu pourquoi on force l'affichage du menu des couches ici : 
https://github.com/geobretagne/mviewer/blob/a6d9e0713837611d4c52e0abeddab67310fda124/lib/simple-slidebar/slidebar_menu.js#L19

Cette ligne passe après l'initialisation du menu. Le paramètre "mini" n'est donc pas pris en compte car on force à "true" l'affichage du panneau des couches.

**Comment by spelhate** [comment]
`mviewer.toggleMenu(true); ` ne force pas l'affichage mais fait bien une bascule afficher/masquer.
Le paramètre **true** indique qu'il faut activer une transition/animation au moment de la bascule.

**Comment by Gaetanbrl** [comment]
Ok je vois, le true n'es là que pour gérer l'animation. Mais l'appel de fonction déclenche l'animation et fera l'inverse de l'état actuel (si ouvert alors le ferme, sinon le ferme).

Donc avec le "mini = true" on a la classe toggled-2, on passe donc ans la condition et on déclenche donc l'animation (on le voit en testant la fonction dans la console).
https://github.com/geobretagne/mviewer/blob/a6d9e0713837611d4c52e0abeddab67310fda124/lib/simple-slidebar/slidebar_menu.js#L18-L20


Dites moi si le paramètre "mini" fonctionne pour vous ?

**Comment by Gaetanbrl** [comment]
Autant pour moi,
Le paramètre mini ne fonctionne que si tous les paramètres "collapsed" sont sur "true".

J'ai rajouté ce prérequis dans le README.

**Comment by Gaetanbrl** [comment]
@spelhate peux-tu supprimer la branche 216 et 216_develop qui sont liées ?
Je n'ai pas les droits pour cela. Merci :)

**Comment by Gaetanbrl** [comment]
J'ai supprimé la feature-216_develop depuis l'interface de la PR. Il reste la branche feautre-216 que je ne peux pas supprimer. C'est bon pour les autres ;)

**Comment by spelhate** [comment]
@Gaetanbrl  peux-tu mettre à jour la doc avec le nouveau paramètre legendmini et ce que tu as rajouté dans le README.md ? Merci.

**Comment by Gaetanbrl** [comment]
J'ai créé une issue pour le faire, c'est prévu mais je n'ai vraiment pas eu le temps de le faire, désolé.

**Comment by Gaetanbrl** [comment]
C'est dans le README[sur develop](https://github.com/geobretagne/mviewer/commit/cf19ab527aba47aa86a3de14548d3ba14e76d5c4#diff-04c6e90faac2675aa89e2176d2eec7d8R274) actuellement. Désolé...

**Comment by spelhate** [comment]
@Gaetanbrl  Je le fais si tu veux.

**Comment by Gaetanbrl** [comment]
Si vous êtes sur la doc pourquoi pas. Merci.

**Comment by spelhate** [comment]
Ok.

**Comment by spelhate** [comment]
C'est fait. Par contre à l'usage, ce paramétrage n'est pas évident. 2 exemples pour illustrer cela.

### Exemple 1 : réduire la légende
![image](https://user-images.githubusercontent.com/1793792/78117803-6321b280-7406-11ea-9a44-9ec7ce027673.png)

Je souhaite déployer le panneau de gauche (thématique) et réduire la légende. c'est possible avec ce paramétrage de thématique : `mini = false legendmini="true"`  --> logique

### Exemple 2 : Afficher la légende tout en réduisant le panneau de gauche.
![image](https://user-images.githubusercontent.com/1793792/78118071-bdbb0e80-7406-11ea-900b-0467d3c17ba2.png)
Je souhaite replier le panneau de gauche (thématique) et forcer l'affichage de la légende. c'est possible avec ce paramétrage de thématique : `mini = true legendmini="true"`  -->  pas très logique. Naturellement, j'aurais fait un `legendmini="false"`

### Exemple 3 : je souhaite tout réduire

possible avec ce paramétrage de thématique : simplement  `mini = "true" `  ou `mini = true legendmini="false"`  -->  pas très logique. 

La bonne nouvelle c'est que ça marche. Par contre le paramétrage n'est pas très intuitif. Qu'en pensez-vous ? Ne faudrait-il pas renommer **legendmini** en quelquechose de plus compréhensible ?

**Comment by Gaetanbrl** [comment]
> Ne faudrait-il pas renommer legendmini en quelquechose de plus compréhensible ?

`hidelegend` serait mieux ? On aurait ces cas d'utilisation : 

> Je souhaite déployer le panneau de gauche (thématique) et réduire la légende. c'est possible avec ce paramétrage de thématique : mini = false legendmini="true" --> logique

`hidelegend = true` -> me semble autant logique

> Je souhaite replier le panneau de gauche (thématique) et forcer l'affichage de la légende

`hidelegend="false"` -> me semble + logique

> je souhaite tout réduire
`mini = "true"` ou` mini = true hidelegend="true"` -> me semble + logique

**Comment by Gaetanbrl** [comment]
Je m'étais déjà fait la remarque @spelhate après coup, merci de ce retour.

**Comment by Gaetanbrl** [comment]
Modification faite. L'utilisation du paramètre "legendmini" est maintenant plus logique.

**Comment by spelhate** [comment]
Merci @Gaetanbrl . Il faut une mise à jour de la doc pour expliquer cette logique ?

**Comment by Gaetanbrl** [comment]
Non c'est de l'amélioration de code suite à tes retours car pour conserver le fonctionnement initial (avec juste le paramètre mini) la 1ère PR n'était pas pleinement satisfaisante.

**Comment by spelhate** [comment]
J
