### ISSUE TITLE
Problème d'affichage de la légende vectorielle

### ISSUE THREAD

**Issue by MoulinZ** [geobretagne/mviewer#219]
Bonjour, 
J'ai constaté que l'affichage de la légende vectorielle variait selon les ordinateurs où l'on ouvrait l'application. En effet si sur le poste d'un collègue la légende apparait proprement :

![image](https://user-images.githubusercontent.com/45661333/74843744-a6c7cd80-532c-11ea-8c43-5c3f216166ad.png)

Ce n'est pas le cas sur mon poste ou sur celui d'autres collègues : 

![image](https://user-images.githubusercontent.com/45661333/74843589-6ec08a80-532c-11ea-87bc-a0872cf8fe90.png)
![image](https://user-images.githubusercontent.com/45661333/74843628-797b1f80-532c-11ea-9849-d75db221a746.png)
![image](https://user-images.githubusercontent.com/45661333/74843664-84ce4b00-532c-11ea-9f2d-26166058122b.png)

Ça semble lié à la résolution de l'écran. Y a t'il un paramètre pour modifier ça ?
Merci beaucoup !

**Comment by Gaetanbrl** [comment]
Merci pour ce retour @MoulinZ.
Quels sont vos navigateurs / versions / OS ?
La légende provient du style de la couche depuis GeoServer directement ?

**Comment by MoulinZ** [comment]
Non c'est légende produite en JS par une customlayer. 
Plusieurs test sur Windows/Ubuntu/Mac et sur Firefox/Opéra/Chrome. Mais la première image qui fonctionne bien c'est du Windows/Firefox alors que la 3ème aussi. Ce qui à l'air de changer, c'est vraiment la résolution de l'écran. 2560x1600 pour la première contre 3840x2160 pour la 3ème.

**Comment by Gaetanbrl** [comment]
En effet, je reproduis sur Firefox. Je n'ai même aucun label pour la légende.
![image](https://user-images.githubusercontent.com/16317988/74864786-5b271b00-5350-11ea-87aa-1b215d42ee47.png)

**Comment by bchartier** [comment]
Le code qui produit cette légende est visible où ?

**Comment by Gaetanbrl** [comment]
@MoulinZ  c'est disponible ?

**Comment by bchartier** [comment]
C'est bon j'ai trouvé : https://github.com/geobretagne/mviewer/blob/master/js/mviewer.js#L364

**Comment by bchartier** [comment]
Malheureusement, je ne connais pas la manipulation des canvas pour voir ce qui cloche en fonction des caractéristiques de dimension/résolution de la page du navigateur.

**Comment by spelhate** [comment]
J'ai le même souci. Il faudrait pouvoir tester avec d'autres valeurs (taille police, padding) sur différents écrans.

**Comment by spelhate** [comment]
Corrigé. Merci @Sfoucheur
