### ISSUE TITLE
Add geojson (vector) support

### ISSUE THREAD

**Issue by spelhate** [geobretagne/mviewer#22]
Add new layer type (geojson) in theme panel.
geojson could be loaded with a specific type layer in config xml or
with an url parameter  pointing to the source.

**Comment by spelhate** [comment]
Fait

**Comment by vfabry** [comment]
Bonjour Sébastien,
Dans la doc, il est indiqué que les couches geojson peuvent stylisées en utilisant le fichier lib/featurestyles.js
Mais j'ai l'impression que ce fichier fait référence à des couches open layers...
Est-ce qu'il y a moyen de styliser une couche geojson avec un fichier sld par exemple ?
Vincent

**Comment by spelhate** [comment]
Salut,
les couches vecteur peuvent être stylisées via javascript. Le SLD, qui est un profil de WMS n'est pas géré.
Je t'invite à regarder cet exemple : http://kartenn.region-bretagne.fr/kartoviz/?config=demo/vector.xml

**Comment by vfabry** [comment]
OK, merci !
