### ISSUE TITLE
Bug d'affichage

### ISSUE THREAD

**Issue by MoulinZ** [geobretagne/mviewer#222]
J'ai constaté un bug d'affichage sur les templates. La partie du bas n'est pas visible. C'est le cas ici : 

![image](https://user-images.githubusercontent.com/45661333/75017575-954a0700-548d-11ea-9261-1c2b75a6f390.png)

Je ne peux pas descendre plus bas, le reste n'est pas visible, et pourtant il manque quelques lignes du lorem ipsum : 
`dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.`

Si je mets juste une div dans mon template.mst, j'ai même pas de curseur et possibilité de descendre plus bas. Si je mets la div dans une balise `<li class="item"></li>` j'ai le curseur comme sur la capture, mais je ne peux pas descendre jusque tout en bas. 

Je précise que le bug est présent sur plusieurs navigateurs (Firefox/CHrome/Opéra) et sur plusieurs postes.
Il n'existe pas en revanche sur mobile.

**Comment by bchartier** [comment]
Le problème concerne le texte affiché dans la fiche d'information d'un objet sélectionné, c'est ça ?

**Comment by Gaetanbrl** [comment]
J'ai pu constater sur un autre exemple qui ma été fourni. Il semblerai que la fiche d'information n'affiche pas tout le contenu. On ne peut pas scroller plus vers le bas alors qu'il reste des choses à lire. Donc, le texte tout en dessous est inaccessible.

@MoulinZ a peut-être une URL de démo à partager pour voir le comportement ?

**Comment by MoulinZ** [comment]
C'est compliqué pour moi pour l'instant de vous partager une démo, mon serveur n'étant pas encore raccroché à un domaine. Mais si vous prenez un mviewer le plus basique qui soit, et que vous ajoutez suffisamment de texte dans le template.mst pour remplir le panneau de droite vous pouvez reproduire l'erreur facilement.

**Comment by spelhate** [comment]
Je pense que le problème peut être contourné via css en indiquant un padding-top de 80px pour la div principale de votre template : `padding-bottom: 80px;
`
Une solution plus pérenne consisterait à effectuer ce réglage dans mviewer.css.

**Comment by bchartier** [comment]
La solution pérenne que tu évoques c'est mettre `padding-bottom: 80px;` dans mviewer.css. Ou c'est autre chose ?

**Comment by spelhate** [comment]
Oui c'est ça.

**Comment by MoulinZ** [comment]
Où est ce qu'il faut mettre ce `padding-bottom: 80px;` exactement ? 
D'ailleurs le problème est le même pour le panel de la légende. 
Merci !

**Comment by MoulinZ** [comment]
C'est bon j'ai trouvé où c'était. Sur firefox avec l'affichage des curseurs c'est pas très propre mais bon. Beaucoup mieux sur chrome où les curseurs sont cachés.

**Comment by spelhate** [comment]
ici : https://github.com/geobretagne/mviewer/blob/master/css/mviewer.css#L681

**Comment by MoulinZ** [comment]
Ah moi ça ne marche à cette ligne, je l'ai fait sur celle-ci : https://github.com/geobretagne/mviewer/blob/master/css/mviewer.css#L661

**Comment by spelhate** [comment]
@MoulinZ  Merci pour l'info.

**Comment by bchartier** [comment]
Est-ce qu'on modifie le code source de mviewer pour prendre cela en compte ?

**Comment by Gaetanbrl** [comment]
Ce serait pas mal, @MoulinZ  est-ce fonctionnel suite à ta modification ? As-tu une démo qu'on puisse tester ?

**Comment by MoulinZ** [comment]
Alors c'est fonctionnel, mais il y a un curseur vertical et un horizontal qui s'affichent, c'est pas très propre. Je peux pas vous donner de démo toujours parce que mon geoserver est verouillé et en plus le serveur où sont les photos semble down ^^ bref désolé. Sur chrome c'est bien plus propre.

**Comment by MoulinZ** [comment]
ah et j'ai mis un padding bottom de 120px pour le right-panel et de 80px pour le panel des légendes à la ligne https://github.com/geobretagne/mviewer/blob/master/css/mviewer.css#L1280

**Comment by MoulinZ** [comment]
pour illuster : 
![image](https://user-images.githubusercontent.com/45661333/77055225-d07a2000-69d0-11ea-8eda-c2c93df1905c.png)

**Comment by Gaetanbrl** [comment]
As-tu pu tester sur mobile ?

**Comment by MoulinZ** [comment]
en vue adaptative sur firefox ça n'ouvre pas le contenu du panel : 
![image](https://user-images.githubusercontent.com/45661333/77056325-8abe5700-69d2-11ea-9807-5a5ee59c3386.png)

**Comment by spelhate** [comment]
> en vue adaptative sur firefox ça n'ouvre pas le contenu du panel :


Même en cliquant à nouveau sur un point ?

**Comment by spelhate** [comment]
> Est-ce qu'on modifie le code source de mviewer pour prendre cela en compte ?

Oui c'est prévu. Qui sera le plus rapide @Sfoucheur ou @MoulinZ  ?

**Comment by MoulinZ** [comment]
Oulah je vous laisse faire, je débute avec GitHub je comprend pas encore tout ^^ je vais me former à ça

**Comment by spelhate** [comment]
> en vue adaptative sur firefox ça n'ouvre pas le contenu du panel :
> ![image](https://user-images.githubusercontent.com/45661333/77056325-8abe5700-69d2-11ea-9807-5a5ee59c3386.png)

Ca ressemble à un bug. Je viens de créer un ticket pour  cette issue : #234

**Comment by Gaetanbrl** [comment]
Je viens de tester les deux solutions, c'est à dire : 

```
#right-panel .item.active {
   overflow-y: auto;
   padding-bottom: 80px;  
}

```
et

```
#right-panel .popup-content {
  overflow-y: hidden;
  overflow-x: hidden;
  position: absolute;
  left: 0px;
  height: 100%;
  width: 100%;
  padding: 0 0 0 0;
  padding-bottom: 80px;  
}
```

Dans les deux cas, c'est FF qui n'affiche pas correctement les informations. Sur Chrome c'est OK.

Voici ce que j'ai obtenu au mieux :
![image](https://user-images.githubusercontent.com/16317988/77520309-538ff000-6e81-11ea-94e3-56e38f2bdd3b.png)

Ce qui a fonctionné pour moi c'est l'ajout d'un autre padding-bottom : 

```
#right-panel .item.active {
   overflow-y: auto;
  padding-bottom: 40px;  
}
#right-panel .active {
  padding-bottom: 40px; 
}
```
![image](https://user-images.githubusercontent.com/16317988/77520848-1841f100-6e82-11ea-98fc-7fe047c14967.png)

**Comment by MoulinZ** [comment]
N'y a t'il pas un problème horizontal également ? J'ai toujours un curseur horizontal sur firefox et c'est pas très propre.
![image](https://user-images.githubusercontent.com/45661333/77521617-470c9700-6e83-11ea-848b-f067ab984270.png)

**Comment by Gaetanbrl** [comment]
> 
> 
> en vue adaptative sur firefox ça n'ouvre pas le contenu du panel :
> ![image](https://user-images.githubusercontent.com/45661333/77056325-8abe5700-69d2-11ea-9807-5a5ee59c3386.png)

Je ne reproduis pas.
![image](https://user-images.githubusercontent.com/16317988/77521656-54298600-6e83-11ea-979d-ff6d64ea155c.png)


@MoulinZ peux-tu tester avec ma proposition ? (clic sur le commit ci-dessous)
https://github.com/geobretagne/mviewer/commit/dea676b9c4a43d59bcb8145abf1cc2f0e12b1077

**Comment by Gaetanbrl** [comment]
> N'y a t'il pas un problème horizontal également ? 

Il y a des éléments Bootstrap qui ne sont pas totalement ISO avec FF.
@MoulinZ j'en ai un également mais pas comme le tiens, j'ai l'impression que l'on a pas les mêmes vertsions de FF. Quelle est ta version FF ?

**Comment by MoulinZ** [comment]
74.0 (64 bits), la dernière d'après ce qu'il me dit. Pour ce qui est de l'affichage en vue adaptative, c'est à priori lié aux clusters. @spelhate à ouvert une issue dédiée #234 .

**Comment by Gaetanbrl** [comment]
On a donc pourtant la même version ^^

**Comment by MoulinZ** [comment]
En faisant ta modification je n'ai pas le curseur horizontal. En revanche 40px ne suffisent pas pour moi : 
![image](https://user-images.githubusercontent.com/45661333/77523123-8fc54f80-6e85-11ea-9137-09c5da2efd84.png)

Avec 80px c'est bon, et sans le curseur horizontal mieux que la modif que j'avais faite.

**Comment by Gaetanbrl** [comment]
par contre 180px en plus ca commente à faire long.

**Comment by MoulinZ** [comment]
Et on ne fait pas également la modification pour le panel des légendes ? Sur cette ligne là : https://github.com/geobretagne/mviewer/blob/master/css/mviewer.css#L1280

**Comment by Gaetanbrl** [comment]
C'est une autre issue ?

**Comment by MoulinZ** [comment]
non on en a pas ouvert d'autre, c'est un peu le même problème

**Comment by Gaetanbrl** [comment]
@MoulinZ  je n'ai pas suivi, tu peux me détailler le soucis avec la légende ?

**Comment by MoulinZ** [comment]
Bah c'est le même problème que pour le panel de droite, tu pas pas scroller jusqu'en bas. Du coup j'ai rajouté aussi un `padding-bottom: 80px; `

Je pose la question comme ça, mais de manière générale la div de la map "déborde". En témoigne mon swipper sur http://193.48.28.84/mviewer/?config=apps/balayage.xml# qui n'arrive qu'à la valeur 94 sur 100 en étant à 100% de width. Est-ce normal ?

**Comment by Gaetanbrl** [comment]
Au passage, très girly cette petite étoile ;) 
![image](https://user-images.githubusercontent.com/16317988/77528508-6230d400-6e8e-11ea-9c7e-575e85bd81c0.png)

Si tu observes bien, tu vois que la map fait 100% de la largeur tout comme la barre du haut (navbar).

Pour rajouter le bandeau latéral de gauche pour les couches, il faut une div supplémentaire. La div de gauche + la map on est > largeur total de l'écran. Donc ca déborde. C'est le fonctionnement souvent normal avec ce type d'interface (wrapper) bootstrap.

![image](https://user-images.githubusercontent.com/16317988/77529127-5bef2780-6e8f-11ea-81d5-33aef1fe59ee.png)

Je pense que c'est une explication, mais je me trompe peut-être.

**Comment by MoulinZ** [comment]
ahah tu remarquera que c'est encore plus beau maintenant : 
![image](https://user-images.githubusercontent.com/45661333/77530888-4a5b4f00-6e92-11ea-9676-23b13a2f2d93.png)

Oui je comprend bien pourquoi ça déborde, mais est-ce que c'est pas pour ça qu'on a nos problème de scrolling, et est-ce que ça serait pas plus efficace de solutionner ça. Je pense par exemple à un moment donné j'ai voulu récupérer les coordonnées du centre de ma map. Bah c'est pas possible vu que le centre de la div map n'est pas le centre de ce que je vois.

**Comment by Gaetanbrl** [comment]
>  et est-ce que ça serait pas plus efficace de solutionner ça

Ce n'est pas si simple, c'est une modification structurante de l'application (Bootstrap).

**Comment by spelhate** [comment]
> > en vue adaptative sur firefox ça n'ouvre pas le contenu du panel :
> > ![image](https://user-images.githubusercontent.com/45661333/77056325-8abe5700-69d2-11ea-9807-5a5ee59c3386.png)
> 
> Ca ressemble à un bug. Je viens de créer un ticket pour cette issue : #234

Le bug est propre au customMayer cluster.js. Il faut appliquer le correctif disponible  b499911b5610ac2f061fc4ad1e05331a0a09ba77  dans votre propre customLayers.

**Comment by spelhate** [comment]
> C'est une autre issue ?

Je viens de créer l'issue #243

**Comment by Gaetanbrl** [comment]
Ca marche merci @spelhate

**Comment by spelhate** [comment]
On en est où sur cette issue ?

**Comment by Gaetanbrl** [comment]
A fermer ? @MoulinZ @spelhate

**Comment by spelhate** [comment]
Oui pour moi.
