### ISSUE TITLE
Bug modal Bootstrap dans template.mst

### ISSUE THREAD

**Issue by MoulinZ** [geobretagne/mviewer#223]
Je partage ici un bug qui m'a cassé la tête un moment. Lorsque l'on veut mettre un modal bootstrap dans un template, avec la méthode classique, le modal arrive en grisé, et il n'est plus possible de rien faire mise à part reload la page : 

```
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
            Launch demo modal
</button>
```
![image](https://user-images.githubusercontent.com/45661333/75022939-40ab8980-5497-11ea-8c92-bae528dc67d8.png)

**Comment by MoulinZ** [comment]
La solution que j'ai trouvé, grâce à un collègue que je remercie, c'est de renvoyer virtuellement la div du modal vers index.html (enfin c'est comme ça que je l'ai compris) où là le modal marche bien (en témoigne le modal de l'aide) : 

```
<script>
function modalStep(id) {
  var modalErreur = document.getElementById(id);
  document.body.appendChild(modalErreur);
  $('#exampleModal').modal('toggle');
}
</script>
<button type="button" class="btn btn-primary" data-toggle="modal" 
onClick="modalStep('exampleModal')">
            Launch demo modal
</button>
```

![image](https://user-images.githubusercontent.com/45661333/75023607-62f1d700-5498-11ea-8afc-27a2b43c1102.png)

**Comment by Gaetanbrl** [comment]
Pour compléter, selon la [documentation Mozilla](https://developer.mozilla.org/fr/docs/Web/API/Node/appendChild) : 

`La méthode Node.appendChild() ajoute un nœud à la fin de la liste des enfants d'un nœud parent spécifié.`

En inspectant le code on doit pouvoir donc voir que la modal n'est pas rajoutée au bon endroit lors du chargement du template. 
La méthode appendChild "ajoute" le html de la modal à la fin du body en dehors des autres div (qui ont leurs propres règles CSS pouvant bloquer cet affichage).

**Comment by Gaetanbrl** [comment]
Merci pour le partage de cette solution ;)

**Comment by bchartier** [comment]
Comme je n'ai pas tout suivi, je pose une question peut-être idiote : c'est un bug ou c'est juste qu'il faut savoir comment faire ?

**Comment by bchartier** [comment]
S'il s'agit de partager un savoir-faire, ça vaudrait peut-être le coup d'en faire une carte de démo dans le réerptoire "demo", non ?

**Comment by Gaetanbrl** [comment]
C'est une astuce en effet pour contourner un comportement. Je ne pense pas que ce soit un bug.

>S'il s'agit de partager un savoir-faire, ça vaudrait peut-être le coup d'en faire une carte de démo dans le réerptoire "demo", non ?

Ca peut être intéressant. Ou bien d'insérer ce type de fonctionnalité dans une démo existante qui touche au template ?

Ex : 
https://kartenn.region-bretagne.fr/kartoviz/?config=demo/template_rightpanel.xml

Par contre il semble y avoir des erreurs sur cette démo...

**Comment by spelhate** [comment]
> Ex :
> https://kartenn.region-bretagne.fr/kartoviz/?config=demo/template_rightpanel.xml
> 
> Par contre il semble y avoir des erreurs sur cette démo...

Il ne s'agit pas d'un bug. Nous sommes passés hier en full https et certains styles sld avec des svg appelés en http posent problème. On les corrige.

**Comment by spelhate** [comment]
@MoulinZ on peut fermer cette issue ?

**Comment by Gaetanbrl** [comment]
Sans retour, je clos l'issue.
@MoulinZ pourra la ré-ouvrir si besoin. Merci.
