### ISSUE TITLE
Demo CSV - Lien fichier cassé

### ISSUE THREAD

**Issue by Gaetanbrl** [geobretagne/mviewer#227]
- Observation : 
Le lien vers le fichier a été modifié ou ne semble plus exister :
[https://adresse.data.gouv.fr/static/exemples/search.csv](https://adresse.data.gouv.fr/static/exemples/search.csv)

- Proposition :
Remplacer par le fichier GitHub Mviewer : [lien](https://github.com/geobretagne/mviewer/blob/master/demo/demo.csv).

**Comment by Gaetanbrl** [comment]
- [X] Branche [issue-227](https://github.com/geobretagne/mviewer/tree/issue-227) créée.
- [X] Commit réalisé
- [ ] PR réalisée

**Comment by bchartier** [comment]
Tu as besoin de quelque chose de plus pour faire la PR ?

**Comment by Gaetanbrl** [comment]
J'attendais 1 ou 2 jours pour voir s'il y avait une quelconque réaction avant de la réaliser.
Sinon rien de spécifique.

**Comment by Gaetanbrl** [comment]
PR #228  en attente.
