### ISSUE TITLE
Paramètre customlayerpath

### ISSUE THREAD

**Issue by bchartier** [geobretagne/mviewer#232]
J'ai noté dans la documentation de mviewer la présence du paramètre customcontrolpath. Je me demande s'il ne serait pas judicieux de prévoir également un paramètre customlayerpath pour avoir la possibilité de spécifier un chemin particulier pour le code d'un customlayer de manière similaire à ce que l'on peut faire pour un customcontrol.
Cela permettrait d'organiser comme on le souhaite l'ensemble des fichiers spécifiques à une carte particulière : le fichier de configuration mviewer, le code des customcontrols et le code des customlayers.

**Comment by spelhate** [comment]
Dans le cas d'un **customlayer**, le paramètre **url** précise déjà le path. 
Pour un customlayer, la règle est la suivante :

- url renseignée --> le fichier js correspondant à l'url est chargé
- url non renseignée --> l'url est fabriquée à partir de l'id de la couche : customLayers/**layerid**.js 

Ce n'est pas harmonisé, mais ça fonctionne quand même. Avec ce mécanisme, nous réalisons des addons comme dans cet exemple de configuration : https://github.com/region-bretagne/mviewer-apps/tree/master/patrimoine/addons/napoleon

**Comment by bchartier** [comment]
Bah, cool ; j'avais compris.
Faut juste mettre à jour la doc pour que ce soit plus clair, alors ?

**Comment by Gaetanbrl** [comment]
@bchartier je peux insérer un complément sur ce volet dans la doc via la modification que j'ai prévu avec l'[issue-26](https://github.com/geobretagne/mviewer.doc/issues/26). 

Il faudra juste rajouter une issue dans mviewer.doc et faire référence à cette issue pour que je n'oublie pas.

**Comment by bchartier** [comment]
@Gaetanbrl: volontiers

@spelhate: Oups dans mon précédent message il fallait lire "j'avais **pas** compris".
Désolé pour al confusion.

**Comment by spelhate** [comment]
Merci pour la précision @bchartier . On évite ainsi une crise diplomatique.

**Comment by Gaetanbrl** [comment]
Branche [feature-232](https://github.com/geobretagne/mviewer/tree/feature-232) créée pour cette issue.
