### ISSUE TITLE
Layer Swippe

### ISSUE THREAD

**Issue by MoulinZ** [geobretagne/mviewer#237]
Salut,

Est-ce que quelqu'un à déjà essayé de faire un swippe de couches sur mviewer ? Comme dans cet exemple de openlayer : https://openlayers.org/en/latest/examples/layer-swipe.html 

J'essaye, je n'ai pas d'erreur, mais ça ne marche pas pour autant.
J'ai déclaré dans mon customlayer une couche (un ortho) nommée "aerial".
Ensuite mon customcontrol ressemble à ça : 
```
mviewer.customControls.ortho = (function() {
    /*
        * Private
        */
       var _idlayer = 'ortho';

       var _zoomlevel = false;

       var _collection = false;

       var swipe;

       var _mapChanged = function (e) {
           var newZoomlevel = mviewer.getMap().getView().getZoom();
           if ( _zoomlevel && (newZoomlevel > _zoomlevel)) {
           }
           _zoomlevel = newZoomlevel;
       };


       var _initSlider = e => {
         swipe = $("#swippe");

         $("#swippe").slider({
             id: 'sliderSpatial',
             value: [0,100],
         });

         console.log(swipe);

         if($("#swippe").slider()){
           $("#swippe").slider().on('slideStop', (e) => {
               var value = sliderJquery.slider('getValue');
               console.log(value);
           });
         }
         mviewer.customLayers.ortho.aerial.on('prerender', function(event) {
           var ctx = event.context;
           var mapSize = mviewer.getMap().getSize();
           var width = mapSize[0] * (swipe.value / 100);
           var tl = getRenderPixel(event, [width, 0]);
           var tr = getRenderPixel(event, [mapSize[0], 0]);
           var bl = getRenderPixel(event, [width, mapSize[1]]);
           var br = getRenderPixel(event, mapSize);

           ctx.save();
           ctx.beginPath();
           ctx.moveTo(tl[0], tl[1]);
           ctx.lineTo(bl[0], bl[1]);
           ctx.lineTo(br[0], br[1]);
           ctx.lineTo(tr[0], tr[1]);
           ctx.closePath();
           ctx.clip();
         });

         mviewer.customLayers.ortho.aerial.on('postrender', function(event) {
           var ctx = event.context;
           ctx.restore();
         });

         $("#swipe").on('input', function() {
           mviewer.getMap().render();
         }, false);
         //var swipper = document.getElementById("divswipe");
         //parent = document.getElementById("page-content-wrapper");
         //parent.append(swipper)
       };




       return {
           /*
            * Public
            */

           init: function() {
             _initSlider();
               // mandatory - code executed when panel is opened
           },

           destroy: function() {
               // mandatory - code executed when panel is closed
               mviewer.getMap().un('moveend', _mapChanged);

           }
       };

   }());

```

**Comment by spelhate** [comment]
@MoulinZ  merci pour le partage. Démo disponible quelque part ?
En lien avec #183

**Comment by spelhate** [comment]
cette ligne m'intrigue : `sliderJquery.slider`
Cette ressource est disponible dans le code ?

**Comment by MoulinZ** [comment]
Avec le code que j'ai partagé, j'ai ça : http://193.48.28.84/mviewer/?config=apps/balayage.xml# Bon encore une fois j'ai un ortho d'un geoserver fermé. Mais comme on le voit pas de toute façon... Il y a un ortho sur geobretagne pour que je puisse remplacer le miens ?

**Comment by Gaetanbrl** [comment]
@spelhate je tombe sur une 503 pour votre GeoNetwork

Sinon @MoulinZ ca devrait se trouver dessus :)

**Comment by MoulinZ** [comment]
> 
> 
> cette ligne m'intrigue : `sliderJquery.slider`

En effet j'avis repris ça d'un autre code, mais je l'ai appelé ici swippe, ça fait donc `swipe.slider`

**Comment by spelhate** [comment]
> @spelhate je tombe sur une 503 pour votre GeoNetwork
> 
> Sinon @MoulinZ ca devrait se trouver dessus :)

On est en plein changement d'hébergeur. Il y a quelques services dont Geonetwork en souffrance.

**Comment by spelhate** [comment]
Je vais regarder ça de plus près.

**Comment by spelhate** [comment]
> Est-ce que quelqu'un à déjà essayé de faire un swippe de couches sur mviewer ? Comme dans cet exemple de openlayer : https://openlayers.org/en/latest/examples/layer-swipe.html

Ca ne peut pas marcher car l'exemple utilisé ne correspond pas à la version d'Openlayers utilisée dans mviewer. Il faut plutôt utiliser cette version : https://openlayers.org/en/v5.3.0/examples/layer-swipe.html?q=swipe

J'ai en stock une démo simple qui reprend à minima l'exemple Openlayers. Je peux la verser dans démo si ça vous intéresse.

**Comment by Gaetanbrl** [comment]
> J'ai en stock une démo simple qui reprend à minima l'exemple Openlayers

Il me semblait bien avoir vu un jour un exemple de ce type avec le Mviewer 😃 ! Ce serait une super démo.

**Comment by spelhate** [comment]
Démo visible ici : https://kartenn.region-bretagne.fr/kartoviz/?config=demo/swipe/swipe.xml
Code disponible ici : https://github.com/geobretagne/mviewer/commit/362982e9dd0361594ea29a18e24bf60ad962ae3c

Il reste maintenant à adapter cet exemple avec le beau slider de @MoulinZ

**Comment by Gaetanbrl** [comment]
J'espère qu'il remettra la petite étoile 😄

**Comment by MoulinZ** [comment]
Oh formidable, merci ! Je vais adapter mon appli avec ça ! Et non l'étoile ne reviendra pas @Gaetanbrl... Navré... Si quelqu'un sait en revanche comment centrer mon handle shape custom ça me ferait plaisir ;)

**Comment by MoulinZ** [comment]
Désolé c'est clos, mais pour mettre une layer à gauche aussi, une idée ?

**Comment by spelhate** [comment]
> Désolé c'est clos, mais pour mettre une layer à gauche aussi, une idée ?

Je ne suis pas sûr de comprendre la question ?
Dans l'exemple crée, il y a une couche de fond qui est affichée et au dessus une couche d'imagerie satellite disposant du contrôle swipe permettant d'effectuer le balayage.

Pour info, j'ai amélioré le rendu final dans la démo : https://kartenn.region-bretagne.fr/kartoviz/?config=demo/swipe/swipe.xml

**Comment by MoulinZ** [comment]
L'idée c'est que je vais refaire une app comme j'avais fait ici : https://umrlisa.univ-corse.fr/appli_balayage/ qui n'est pas fonctionnelle actuellement et pas très responsiv. 
L'utilisateur peut choisir l'ortho de gauche et l'ortho de droite, afin de voir l'évolution du paysage entre deux dates. 
Il faut malgré tout conserver un fond de carte pour les endroits où il n'y a pas d'ortho. Par exemple pour nous vu le travail d'ortho-rectification on l'a fait que sur 3 secteurs très urbanisés de Corse pour 1975, 1982 et 1996.

**Comment by spelhate** [comment]
Intuitivement, ce qu'il est possible de faire à partir d'exemple existant, c'est d'ajouter au contrôle existant une liste déroulante pour sélectionner la couche dans la partie droite et éventuellement d'ajouter une seconde liste de choix permettant de sélectionner la couche de fond (baselayer) qui s'affiche dans la partie gauche.
C'est une piste parmi d'autres.
