### ISSUE TITLE
Logo dans le contrôle de couche

### ISSUE THREAD

**Issue by eprouteau** [geobretagne/mviewer#238]
Bonjour,

Je souhaites pouvoir ajouter un logo en tant que source dans le contrôle de couche . J'ai essayé via l'option attribution avec un bout de code html vers une image mais sans succès.

Faut-il obligatoirement passer par un contrôle de couche personnalisé ?

Cordialement,

**Comment by Gaetanbrl** [comment]
Bonjour,

>  ajouter un logo en tant que source dans le contrôle de couche

Est-ce l'ajout d'un logo dans la légende entre l'opacité et l'attribution dont il est question ?

**Comment by eprouteau** [comment]
Le but serait d'avoir un logo en plus ou à la place du texte d'attribution.

**Comment by Gaetanbrl** [comment]
C'est out à fait possible via un code de ce type : 

`attribution="Une image dans les attributions :&lt;br> &lt;img style='width:30%' src='https://mviewerdoc.readthedocs.io/fr/latest/_static/mviewer_logo_nb.png' Données : les contributeurs />"`

...qui donnera : 

![image](https://user-images.githubusercontent.com/16317988/77435270-66071c80-6de2-11ea-84b5-2ce9419dd5fb.png)


Vous devez utiliser `&lt;` à la place de `<`. 
Donc `<img/>` devient `&lt;img/>`.

Il y a un exemple ici : [doc mviewer](https://mviewerdoc.readthedocs.io/fr/latest/doc_dev/config_baselayers.html).

**Comment by eprouteau** [comment]
Super, merci Gaetan. Je n'avais pas penser à prendre le code html des < et >
