### ISSUE TITLE
Lien vers le site parent

### ISSUE THREAD

**Issue by bchartier** [geobretagne/mviewer#239]
Un utilisateur me demande de pouvoir intégrer dans l'IHM de mviewer un lien/bouton pour revenir facilement au site hôte de mviewer. C'est vrai qu'une fois qu'on est dans mviewer on n'a aucun menu ou pied de page qui permet d'intégrer un lien vers d'autres outils.

Typiquement quand on est là : https://kartenn.region-bretagne.fr/kartenn/
on aimerait bien avoir un lien pour revenir à la page d'accueil de Kartenn par exemple.

J'aimerais bien pouvoir le faire sans passer par un fork de index.html et sans utiliser d'iframe.

Est-ce que cela vous paraît également pertinent qu'on intègre ce genre de chose ?

**Comment by Gaetanbrl** [comment]
Pour modifier le contenu du `navbar` je passe par le customLayer / customControl. Bon si il n'y en a pas ça tombe à l'eau...
Par contre le titre peut accueillir un lien, tout comme le logo ou la fenêtre d'aide.

Si c'est seulement pour un lien vers un site parent ça peut être suffisant sans rien modifier.

Sinon il y a moyen de rajouter un bouton du type HOME (lien qui sera à définir dans le config) : 
![image](https://user-images.githubusercontent.com/16317988/77446544-d3b94580-6dee-11ea-8d51-0f31dd491a08.png)

Ou plus lourd en terme de dev, rendre  modifiable le navbar via un template ou un code HTML...

**Comment by bchartier** [comment]
> Pour modifier le contenu du `navbar` je passe par le customLayer / customControl. Bon si il n'y en a pas ça tombe à l'eau...

Oui, là ça tombe à l'eau car la majorité des cartes vont être produites par mviewerstudio. Dans la plupart des cas il n'y aura pas de custom control. En tout cas on ne peut pas garantir la présence d'un custom control. Et puis ça me dérange un peu d'utiliser les custom controls de manière très détournée. (idée intéressante néanmoins même si dans le cas présent cela ne me paraît pas approprié)

> Par contre le titre peut accueillir un lien, tout comme le logo ou la fenêtre d'aide.

Oui, j'y ai pensé mais le problème c'est que le titre et l'image pourraient ne pas avoir de lien direct avec l'URL qu'on y mettrai. Typiquement, un acteur local fait une carte avec le nom et le logo de sa collectivité et lorsque l'on clique dessus on s'attendrait à arriver sur le site de la collectivité et non le portail régional de la donnée (c'est pour un portail régional qui offre ce type de service aux collectivités, services de l'Etat...). J'ai donc abandonné cette possibilité.

> Si c'est seulement pour un lien vers un site parent ça peut être suffisant sans rien modifier.

> Sinon il y a moyen de rajouter un bouton du type HOME (lien qui sera à définir dans le config) :
> ![image](https://user-images.githubusercontent.com/16317988/77446544-d3b94580-6dee-11ea-8d51-0f31dd491a08.png)

C'est l'idée qui me plaît le plus pour l'instant.
Mais l'icône home ressemble trop au bouton qui est dans la carto -> confusion possible.

> Ou plus lourd en terme de dev, rendre modifiable le navbar via un template ou un code HTML...

Ce serait sans doute la solution la plus intéressante mais qui demanderait le plus d'investissement.

Je me rends compte que pour un site particulier il faudrait que toutes les cartes mviewer aient le même lien au même endroit. S'il faut modifier à la main chose fichier de configuration ça va être infernal. Cela voudrait dire d'avoir ce genre de configuration au niveau du code de mviewer et non au niveau de la config de chaque carte. Donc un template mustache pour la navbar par exemple serait sans doute la solution la plus pertinente (ce qui ne m'arrange pas vraiment).

**Comment by spelhate** [comment]
Dans l'exemple : https://kartenn.region-bretagne.fr/kartoviz/?config=demo/geobretagne.xml , le logo est associé à un lien vers le site de GéoBretagne. 
Ca se configure avec le paramètre **home** comme l'a indiqué @Gaetanbrl

**Comment by bchartier** [comment]
> Dans l'exemple : https://kartenn.region-bretagne.fr/kartoviz/?config=demo/geobretagne.xml , le logo est associé à un lien vers le site de GéoBretagne.
> Ca se configure avec le paramètre **home** comme l'a indiqué @Gaetanbrl

Oui, j'ai bien compris cette possibilité.
Le truc qui m'ennuie un peu avec cela c'est que l'on a deux notions qui se téléscopent :
- le logo qu'on veut associer à la carte qui dans mon esprit est plutôt représentatif de thématique de la carte ou du producteur de la carte. J'imagine plutôt que les créateur de la carte vont mettre le logo de leur organisation plutôt.
- le lien vers un site web qui n'est pas forcément un lien vers un site ne lien avec la thématique ni celui de l'organisation productrice de la carte.

Le fait de cliquer sur un logo qui représente quelque chose et d'arriver sur un truc qui n'est pas en lien direct risque de surprendre les utilisateurs : cliquer sur le logo de la DREAL pour arriver sur le site d'IDéO BFC par exemple je trouve cela moyen. A moins que l'on impose sur le site d'IDéO BFC que toutes les cartes aient le même logo, celui d'IDéO BFC et que le lien pointe vers le site d'IDéO BFC quel que soit le producteur et la thématique de la carte.

Je vais déjà proposer cela à IDéO BFC.

**Comment by Gaetanbrl** [comment]
>  S'il faut modifier à la main chose fichier de configuration ça va être infernal

Je reviens sur cette idée @bchartier . Le soucis c'est que si çà devient une conf globale, comment créer des cartes thématiques avec plusieurs liens vers des sites parents différents ? Il faudrait de toute façon le modifier dans le config pour surcharger la config globale.

Imaginons un producteur qui fait des cartes sur le cadastre pour le service Urba (le lien "home" va vers le site urba) et que après il fait à côté une carte sur les localisations des cantines scolaires (site parent "home" différent). Je ne vois pas comment permettre cela dans une config globale vu qu'on est dans des thématiques différentes.

> Le truc qui m'ennuie un peu avec cela c'est que l'on a deux notions qui se téléscopent

C'est très vrai.
Personnellement, je crois que si je devais faire une carte avec ces deux informations, je ferai un lien dans le titre + dans l'aide vers le même site parent et un autre lien pour le logo vers le site du producteur de la carte.

**Comment by Gaetanbrl** [comment]
Je viens de me rendre compte que le lien n'est pas modifiable pour le titre. Je pensais pouvoir ajouter un <a> dans le paramètre "title" mais en fait non ^^

**Comment by Gaetanbrl** [comment]
@bchartier pour info, on vient de me demander s'il était possible de rajouter un bouton à gauche du point d'interrogation vers un site externe (qui n'est pas vers une page Home mais on met ce qu'on veut derrière).

Si c'est vraiment pertinent je peux faire un développement et si ca vous intéresse je partagerai.

**Comment by bchartier** [comment]
> > S'il faut modifier à la main chose fichier de configuration ça va être infernal

> Je reviens sur cette idée @bchartier . Le soucis c'est que si çà devient une conf globale, comment créer des cartes thématiques avec plusieurs liens vers des sites parents différents ? Il faudrait de toute façon le modifier dans le config pour surcharger la config globale.
> 
> Imaginons un producteur qui fait des cartes sur le cadastre pour le service Urba (le lien "home" va vers le site urba) et que après il fait à côté une carte sur les localisations des cantines scolaires (site parent "home" différent). Je ne vois pas comment permettre cela dans une config globale vu qu'on est dans des thématiques différentes.

Mon idée c'est d'avoir des paramètres propres à la carte et d'autres différents qui seraient globaux mais qui n'interfèreraient pas. Néanmoins, on pourrait aussi imaginer que certains paramètres soient définis de manière globale et que la conf de la carte les surcharge éventuellement s'ils sont redéfinis.

> @bchartier pour info, on vient de me demander s'il était possible de rajouter un bouton à gauche du point d'interrogation vers un site externe (qui n'est pas vers une page Home mais on met ce qu'on veut derrière).
> 
> Si c'est vraiment pertinent je peux faire un développement et si ca vous intéresse je partagerai.

Pour ce qui est de ta proposition, c'est intéressant effectivement. Perso je pense qu'on aurait intérêt à pouvoir personnaliser le bandeau de navigation avec un template mustache. Hum, mais c'est pas la solution la plus triviale.

Finalement, la proposition d'utiliser le paramètre `home` a été retenue par IDéO BFC. Il faudra néanmoins que j'ajoute ce qu'il faut pour le configurer dans mviewerstudio.

**Comment by spelhate** [comment]
> Finalement, la proposition d'utiliser le paramètre `home` a été retenue par IDéO BFC. Il faudra néanmoins que j'ajoute ce qu'il faut pour le configurer dans mviewerstudio.

Super.

**Comment by Gaetanbrl** [comment]
du nouveau sur cette issue @bchartier ? :)

**Comment by Gaetanbrl** [comment]
A fermer @bchartier @spelhate ?
