### ISSUE TITLE
Option Thematique

### ISSUE THREAD

**Issue by tanguyj** [geobretagne/mviewer#24]
Bonjour, 

Est-il possible d'avoir une option pour qu'une couche soit visible sur la carte mais qu'elle n'apparaisse pas dans les thématiques  ?
Par exemple ma couche de communes qui reste à demeure sur la carto mais qu'on ne voit pas dans la légende à gauche ...

Merci

**Comment by Gaetanbrl** [comment]
@spelhate , cette issue est toujours d'actualité ?

**Comment by spelhate** [comment]
Je ne sais pas. @tanguyj  qu'en penses-tu ?

**Comment by bchartier** [comment]
Avis perso : cela pourrait avoir un intérêt.

**Comment by bchartier** [comment]
En fait ce type de couche qui resterait à demeure n'aurait pas grand-chose à voir avec une couche thématique : elle n'apparaitrait pas dans les thématiques ni la légende, on ne pourrait pas la désactiver et on ne pourrait pas en modifier les options d'affichage. Ça ressemblerait plus à une couche de fond car elle serait sous les couches thématiques mais elle ne serait affectée par le changement de fond de carte et elle devrait être affichées de manière transparente (les couches de fond sont par défaut opaques.)

**Comment by Gaetanbrl** [comment]
Si je comprends bien ca permettrai d'enrichir un fond de plan sans pouvoir y accorder des modifications ?

Une option "opacity" à été proposée pour les fonds plan. Je serai d'avis de pouvoir au moins proposer cette modification sur la couche #191 .

Le créateur de la carte peut en effet décider de créer une carte selon ses paramètre. Mais l'utilisateur, dans un but de présentation, peut vouloir masquer cette couche ou bien la rendre plus visible, comme on pourra le faire avec des fonds de plan habituels.

On reste là dans de l'optimisation du moins...

**Comment by spelhate** [comment]
On ferme ?

**Comment by bchartier** [comment]
Perso, ça ne me dérangerait pas de ne pas avoir cette fonctionnalité.
Mais il y a peut-être une demande autour de cela.

**Comment by spelhate** [comment]
Oui mais la demande n'a pas été renouvelée ou étayée depuis 3 ans.

**Comment by Gaetanbrl** [comment]
N'étant pas l'utilisateur final quotidien c'est difficile de juger mais comme dit @bchartier c'est pour moi du "nice to have"... à voir après selon les utilisateurs.

**Comment by bchartier** [comment]
@spelhate a raison : on a des demandes plus récentes sur lesquelles nous devons travailler. On ferme et n rouvrira si besoin.
