### ISSUE TITLE
Threshold Fuse

### ISSUE THREAD

**Issue by Gaetanbrl** [geobretagne/mviewer#242]
Je remarque que le paramètre par défaut dans les options est peut-être un peu trop restrictif.
Par défaut Fuse le propose à 0.6 et dans les options Mviewer il est de 0.3.

https://github.com/geobretagne/mviewer/blob/a6d9e0713837611d4c52e0abeddab67310fda124/js/search.js#L594-L602

J'ai des recherches qui ne remontent pas certains résultats pourtant simples et sans occurrences. En modifiant cette option de 0.3 à 0.5, je trouve enfin mes features.

@spelhate est-ce qu'il y a un inconvénient pour laisser à 0.3 cette option `Threshold ` de Fuse ?

Quel est l'impact sur ELS ?

**Comment by spelhate** [comment]
Je n'ai pas d'avis. @bchartier qui est l'origine de ce réglage saura probablement nous éclairer.

**Comment by Gaetanbrl** [comment]
> Quel est l'impact sur ELS ?

Je me répond à moi même pour cette question -> `aucun `
on est dans un switch et pour Fuse uniquement sur ces options.

**Comment by bchartier** [comment]
> Je n'ai pas d'avis. @bchartier qui est l'origine de ce réglage saura probablement nous éclairer.

Oui, effectivement @spelhate n'y est pour rien.
En fait, quand on a intégré Fuse.js on a fait des tests avec différents seuils sur des jeux de données relativement simples. Typiquement sur des couches de données d'établissements avec un nom (Nom de lycée, nom de gymnase typiquement) et un nom de commune... la recherche porte sur ces deux noms de champs pour les exemples que j'ai en tête. Et cela fonctionne très bien de mémoire avec le seuil que j'ai choisi de manière unilatérale.

D'ailleurs j'ai l'impression que cela fonctionne bien dans la démo qui est intégrée à mviewer :
`?config=demo/fuse.xml`

Maintenant, je comprends que dans certaines cas le seuil fixé dans le code puisse poser problème. Est-ce que tes données ont quelque chose de particulier ? Ce ne sont pas des noms que tu cherches ?

Changer le seuil dans le code risque de donner des résultats étranges avec des applications existantes. Je propose donc qu'on réfléchisse à rendre ce seuil paramétrable dans le fichier de la carte avec un seuil par défaut qui resterait dans le code.

> > Quel est l'impact sur ELS ?

> Je me répond à moi même pour cette question -> aucun
> on est dans un switch et pour Fuse uniquement sur ces options.

Exactement. A un moment j'ai eu peur que tu cherches à brancher Fuse sur des réponses renvoyées par ELS. Me voilà soulagé.

**Comment by Gaetanbrl** [comment]
> Est-ce que tes données ont quelque chose de particulier ? Ce ne sont pas des noms que tu cherches ?

Ce sont des nom d'établissement de santé. Des noms d’hôpitaux / clinique. Rien de spécifique je pense.

> Exactement. A un moment j'ai eu peur que tu cherches à brancher Fuse sur des réponses renvoyées par ELS. Me voilà soulagé.

Non non désolé j'étais dans le jus j'ai regardé rapidement sans aller plus loin mais ça me paraissait déjà étrange d'avoir les mêmes options ^^.

> Je propose donc qu'on réfléchisse à rendre ce seuil paramétrable dans le fichier de la carte avec un seuil par défaut qui resterait dans le code.

Merci pour la transition, c'était ma question d'après :) !

**Comment by spelhate** [comment]
Ok pour le paramètre **Fuse**. Ce sera un paramètre propre à la carte (application) ou propre à chaque couche ?

**Comment by bchartier** [comment]
j'ai l'impression que ce serait mieux de gérer cela par couche mais c'est sans doute plus complexe à gérer au niveau du code.

**Comment by bchartier** [comment]
un attribut de la couche au même titre que `fusesearchkeys` et `fusesearchresult`.

**Comment by Gaetanbrl** [comment]
>j'ai l'impression que ce serait mieux de gérer cela par couche 

Je pense également, étant donné qu'on peut visiblement avoir des résultats différents selon la couche recherchée.

> c'est sans doute plus complexe à gérer au niveau du code.

Je n'ai pas encore regardé dans le détail. Mais à partir de la config on peut modifier les options par couche. Donc ca ne doit pas être trop complexe.

https://github.com/geobretagne/mviewer/blob/a6d9e0713837611d4c52e0abeddab67310fda124/js/search.js#L629

**Comment by Gaetanbrl** [comment]
> un attribut de la couche au même titre que `fusesearchkeys` et `fusesearchresult`.

`fusethresold `ca peut faire barbare mais au moins c'est clair face aux options. Sinon `fusematch` plus parlant.

**Comment by spelhate** [comment]
J'ai une préférence pour `fusesearchthresold`

**Comment by Gaetanbrl** [comment]
> J'ai une préférence pour fusesearchthresold

Adopté donc !

Je viens donc de créer [une branche](https://github.com/geobretagne/mviewer/tree/feature-242) que j'alimenterai pour cette évolution.

**Comment by Gaetanbrl** [comment]
Inutile de préciser que c'est documentation comprise ;)

**Comment by bchartier** [comment]
Je propose `fusesearchthreshold`.

**Comment by Gaetanbrl** [comment]
Modification faite dans ce commit https://github.com/geobretagne/mviewer/commit/d79a67d5e0add9001fb48ab6b6824652bc0752ac. 

Je met à jour la branche suite à #259 et je fait la PR.

La branche feature-242 contient l'update du README également.

**Comment by spelhate** [comment]
> Modification faite dans ce commit [d79a67d](https://github.com/geobretagne/mviewer/commit/d79a67d5e0add9001fb48ab6b6824652bc0752ac).
> 
> La branche `feature-242` contient l'update du README également.

Et pour la doc readthedoc ? C'est maintenant la doc prioritaire.

**Comment by Gaetanbrl** [comment]
ok je fait la modif.

**Comment by pierrejego** [comment]
Hello, une petite question, 
sur les site https://gis.jdev.fr/mviewer/?config=apps/donneesplages/donneesplages.xml
 Si je fais une recherche du mot prairie je n'ai rien, mais si je cherche baignade je trouve bien Baignade plan d'eau de la grande prairie. 

Est-ce que ça peut être lié ?

**Comment by Gaetanbrl** [comment]
Oui ça peut être lié. C'est ce type de comportement que j'avais.

**Comment by Gaetanbrl** [comment]
Je viens de faire un test et avec un threshold 0.5 on a bien un résultat : 

![image](https://user-images.githubusercontent.com/16317988/79229921-160cfa00-7e64-11ea-8aac-19d74c00e473.png)
