### ISSUE TITLE
Refactorisation du couple customlayer/customcontrol

### ISSUE THREAD

**Issue by spelhate** [geobretagne/mviewer#244]
A l'usage, la créations d'addons, de contrôles personnalisés ou bien de couches personnalisée n'est ni intuitive, ni robuste et mérite une refactorisation ainsi qu'une documentation dédiée.

### Mode opératoire actuel
Adaptation à partir des exemples fournis qui ne sont pas harmonisés (singletons, closures, objets).
L'utilisateur copie un exemple qui fonctionne et l'adapte à ses besoins

### Proposition : refactoriser la création des customslayers et customscontrols

- [x] Création de classes customLayer & customControl
- [x] Elaboration d'un guide de création
- [x] Elargissement de la logique de customControl (actuellement le customcontrol est associé à une couche)
- [ ] Bonus : lancement d'un grand concours de création de customcontrols et customlayers (Effets Jacky appréciés) :-))

**Comment by bchartier** [comment]
Très bonne idée.
Juste une interrogation : qu'est-ce que tu envisages pour "Elargissement de la logique de customControl" ? Tu envisages des custom controls qui ne seraient liés à aucune couche ou à plusieurs couches. Où l'interface graphique de ces custom controls  apparaitrait ? Toujours dans la légende ?

**Comment by spelhate** [comment]
J'envisage un nouveau type de customControl qui pourrait être rendu n'importe où dans l'interface via un paramètre de type target="#div". Pour cela, je pense créer un nouveau type d'élément dans le fichier config.xml : `<customcontrol render="#madiv" src="manifest.json" />`

De cette façon, on pourrait par exemple:

- afficher un logo personnalisé sur la carte,
- Créer un nouveau bouton dans la navbar avec une action personnalisée...

Si vous avez des idées ou des suggestions, elles sont bienvenues. Je n'ai pas commencé cette évolution.

**Comment by spelhate** [comment]
Ou dans ce dernier cas un truc du genre `<extension render="#madiv" src="config.json" />`
Ce moyen permettrait en outre de charger des librairies non disponibles nativement dans mviewer pour les rendre disponibles pour fabriquer des templates ou autre chose.

**Comment by bchartier** [comment]
Ok. Très bien.
Pour ce qui est de simplement l'adaptation de l'interface graphique est-ce qu'on pourrait envisager la possibilité de définir des templates mustache personnalisés ? Ce serait peut-être plus simple que de faire un custom control.

**Comment by Gaetanbrl** [comment]
> Tu envisages des custom controls qui ne seraient liés à aucune couche ou à plusieurs couches.

Ce serait top de pouvoir intégrer des customcontrols "partagés" et des customcontrols propre à une couche.

Ce qui me vient à l'esprit c'est une configuration globale qui permet de définir pour un customcontrol à quelles layers ou layer il s'applique (un paramètre array = [layer1, layer2]) et à quel application Mviewer il peut potentiellement s'appliquer.

Dans cette idée, les customcontrols, s'ils sont partagés peuvent être localisés dans le dossier "app/customcontrols" ou bien dans un autre dossier. Le chemin pourra être renseigné dans une configuration pour préciser les customcontrol à prendre en compte. Ca peut être pratique pour dire que pour une application on prend ce dossier de custom. Ou alors, la configuration du customcontrol pourra préciser les Mviewer qui peuvent le charger.

Si vous voulez faire une séance d'échanges (téléphonique) pour échanger des idées je suis intéressé ! :)

**Comment by spelhate** [comment]
> Ok. Très bien.
> Pour ce qui est de simplement l'adaptation de l'interface graphique est-ce qu'on pourrait envisager la possibilité de définir des templates mustache personnalisés ? Ce serait peut-être plus simple que de faire un custom control.

Tu penses à ce qui s'affiche dans la légende ? Tu souhaiterais avoir la possibilité de tout modifier via un template (image de la légende, slider opacité, attributions) ou juste avoir la possibilité d'ajouter quelque chose ?

**Comment by spelhate** [comment]
> > Ok. Très bien.
> > Pour ce qui est de simplement l'adaptation de l'interface graphique est-ce qu'on pourrait envisager la possibilité de définir des templates mustache personnalisés ? Ce serait peut-être plus simple que de faire un custom control.
> 
> Tu penses à ce qui s'affiche dans la légende ? Tu souhaiterais avoir la possibilité de tout modifier via un template (image de la légende, slider opacité, attributions) ou juste avoir la possibilité d'ajouter quelque chose ?

@bchartier Un paramètre `toctemplate="template_de_la_legende.mst"` pourrait te convenir  ?
Si c'est le cas, je crée une issue dédiée.

**Comment by bchartier** [comment]
> > > Ok. Très bien.
> > > Pour ce qui est de simplement l'adaptation de l'interface graphique est-ce qu'on pourrait envisager la possibilité de définir des templates mustache personnalisés ? Ce serait peut-être plus simple que de faire un custom control.
> > 
> > 
> > Tu penses à ce qui s'affiche dans la légende ? Tu souhaiterais avoir la possibilité de tout modifier via un template (image de la légende, slider opacité, attributions) ou juste avoir la possibilité d'ajouter quelque chose ?
> 
> @bchartier Un paramètre `toctemplate="template_de_la_legende.mst"` pourrait te convenir ?
> Si c'est le cas, je crée une issue dédiée.

Ah, désolé, je n'avais pas vu ta question/question précédente.
Non, je ne pensais pas au contenu de la légende mais au `<nav class="navbar navbar-default no-margin navbar-fixed-top>`.

**Comment by spelhate** [comment]
WIP

Nouveau noeud **extensions** créé dans le config.xml.
Ce nœud peut accueillir deux types d’extensions

- **javascript** - les ressources sont chargées par mviewer  et rendues disponibles pour les templates, les custom controls...

``
    <extension type="javascript" src="monfichier1.js"/>``

- **component**

```
<extensions>
    <extension type="component" id="graph3d" path="demo/addons"/>
</extensions>
```

L'extension de type **component** charge le fichier requis config.json depuis le répertoire précisé dans l'attribut path et charge toutes les ressources (**js,** **css**, **html**) ciblées dans ce fichier.
Le composant est ensuite créé dans la div précisée par la propriété **target** du fichier de config.json. Exemple de fichier config.json
```
{
    "js": [
        "vis-graph3d.min.js",
        "main.js"
    ],
    "css": "style.css",
    "html": "3d.html",
    "target": "map",
    "options": {
        "title": "3D"
    }
}
```

**Comment by spelhate** [comment]
PR #262

**Comment by pierrejego** [comment]
Je cherche une idée pour faire un test avec un effet Jacky.... :)

**Comment by spelhate** [comment]
> Je cherche une idée pour faire un test avec un effet Jacky.... :)

C'est très facile tu verras. Il faut de la couleur, que ça clignote ...

**Comment by pierrejego** [comment]
Hello, petite question, 
Dans le config.json, la seule option que l'on peut mettre pour l'instant c'est title ? 

Je ne trouve null part dans le code d'autres références à options que là https://github.com/geobretagne/mviewer/blob/develop/js/custom.js#L123 

Imaginons que je veuille rajouter une url vers une doc ou une image, il faut que je le mette directement dans le code source. 

Tiens j'ai un cas concret en tête, si je veux faire un addons pour mettre un logo supplémentaire sur la page (un peu comme PIGMA) mais que je veux que cet addons soit réutilisable par d'autres. Ou est-ce que je peux mettre l'url de l'image ?

**Comment by spelhate** [comment]
Tu peux mettre toutes les options que tu veux dans options.
Ensuite tu y accèdes en faisant mviewer.customcomponents.mycomponent.options.

**Comment by spelhate** [comment]
Ou en faisant a = new CustomComponent(mycomponent);
Options = a.options.

**Comment by spelhate** [comment]
@pierrejego , je te propose un exemple avec logo demain.

**Comment by spelhate** [comment]
@pierrejego l'exemple est ici : https://github.com/geobretagne/mviewer/commit/ea6bfdb6e0f630397201090d1ee62a9696258442
C'est un des cas d'usage les plus simples puisque qu'on peut le faire sans javascript.

**Comment by bchartier** [comment]
@spelhate : dans la description du cas 3) dans la PR tu mentionnes un configuration.js j'ai l'impression que c'est config.js plutôt à la lecture des exemples et du code. Tu as reversé ce que tu as mis dans la description de la PR dans la doc ?

**Comment by spelhate** [comment]
Merci pour le signalement. @bchartier en fait c'était **confi.json**. C'est corrigé dans le descriptif de la PR. Je mets à jour la doc.

**Comment by spelhate** [comment]
@bchartier : La doc est à jour : https://mviewerdoc.readthedocs.io/fr/latest/doc_dev/config_extensions.html

**Comment by bchartier** [comment]
merci

**Comment by Gaetanbrl** [comment]
@spelhate la branche f244 peut être supprimée ?

**Comment by spelhate** [comment]
> @spelhate la branche f244 peut être supprimée ?

Oui.
