### ISSUE TITLE
github actions - pas d'image latest prévue ?

### ISSUE THREAD

**Issue by pmauduit** [geobretagne/mviewer#245]
En relisant la PR introduisant une construction automatique d'images docker via Github-Actions (#236), je me rends compte que j'ai oublié le cas des traditionnelles images docker taggées "latest".

Généralement, les images docker destinées à être reconstruites très souvent à des fins de tests sont "taggées" latest, qui est de fait un tag "flottant" (c'est aussi le tag par défaut utilisé par docker lorsque non spécifié, par exemple lors d'un `docker pull`). J'aurais pensé utiliser la branche master pour cela, toutefois en regardant le fonctionnement du dépot, je me demande si cela ne serait pas plus pertinent d'opter pour adopter la convention suivante: Un commit dans develop déclenchera une construction et une mise à jour sur docker-hub d'une image `mviewer/mviewer:latest`.

Qu'est ce que vous préféreriez ? Dans tous les cas, je peux refaire une PR pour corriger cela et adopter l'une (branche git master -> tag docker latest) ou l'autre (branche git develop -> tag docker latest) des conventions.

**Comment by Gaetanbrl** [comment]
>adopter l'une (branche git master -> tag docker latest) ou l'autre (branche git develop -> tag docker latest) des conventions

La branche master est censé être potentiellement plus stable que la branche develop. Si je ne me trompe pas, c'est master qui contient le code de release. C'est peut-être mieux de partir dessus ?

Ou bien est-ce mieux de créer une branche par version (comme geOrchestra) et de réaliser le build sur la branche qui correspond à la dernière version (latest) ?

**Comment by pmauduit** [comment]
> Ou bien est-ce mieux de créer une branche par version (comme geOrchestra) et de réaliser le build sur la branche qui correspond à la dernière version (latest) ?

Je ne pense pas qu'il y ait une meilleure formule, mais en lisant ton commentaire, j'ai finalement l'impression que le mapping master -> latest est le plus pertinent (surtout dans la mesure où on retrouvera de toute facon le tag develop issu de la branche du même nom). @spelhate un avis ?

**Comment by spelhate** [comment]
master -> latest me semble bien. Ok pour la PR.

**Comment by pmauduit** [comment]
> Ok pour la PR.


ok, c'est fait: #246
