### ISSUE TITLE
Fuse search Error if no feature geom exists

### ISSUE THREAD

**Issue by Gaetanbrl** [geobretagne/mviewer#250]
Il peut arriver que des données publiées par GeoServer ne disposent pas de géométrie.
Dans ce cas, si la recherche Fuse est activée, cela génère une erreur et bloque l'ensemble de la recherche.
![image](https://user-images.githubusercontent.com/16317988/78145543-4fd80c80-7431-11ea-95fb-a14a9ef78020.png)

Cette ligne recherche en effet d'obtenir la géométrie de la feature (qui n'existe pas) :
https://github.com/geobretagne/mviewer/blob/a6d9e0713837611d4c52e0abeddab67310fda124/js/search.js#L621

Une condition sur la géométrie permet de ne pas rajouter cette feature à la recherche Fuse et donc ne pas être "bloquant" pour pouvoir tout de même utiliser la recherche.

```
features.forEach(function(feature) {
     if(feature.getGeometry()) {
        ...
        var wgs84Geom = feature.getGeometry().clone().transform(mapProj, "EPSG:4326");
        ...
     }
})
```

**Comment by bchartier** [comment]
Il me semble que cette erreur avait déjà été corrigée.

**Comment by bchartier** [comment]
cf. #185

**Comment by Gaetanbrl** [comment]
Autant pour moi sur la branche develop c'est le cas.
https://github.com/geobretagne/mviewer/blob/develop/js/search.js#L622

**Comment by Gaetanbrl** [comment]
merci @bchartier

**Comment by bchartier** [comment]
C'est pour cela qu'il faudrait faire rapidement une release (pour rendre accessibles tout un tas de corrections et de nouveautés).

**Comment by pierrejego** [comment]
:) bientot pour la doc de release, mais je t'avoue être une peu sous l'eau.

Par contre rien ne vous empêche de faire un merge entre la branche dev et la master

**Comment by Gaetanbrl** [comment]
En attendant, il peut peut-être y avoir des doc déjà écrites en ligne intéressantes.

https://help.github.com/en/github/administering-a-repository/managing-releases-in-a-repository

**Comment by pierrejego** [comment]
Oui c'est mais il faut rajouter les versions dans le code mviewer et mviewer studio et aussi lister l'ensemble des issues de la version mais dans l'idée c'est ça. J'ai commencé le readthedoc, mais je n'ai pas encore eut le temps de finir

**Comment by spelhate** [comment]
Je m'y colle vendredi.
