### ISSUE TITLE
Upgrade Openlayers

### ISSUE THREAD

**Issue by spelhate** [geobretagne/mviewer#251]
Mise à jour de la lib Openlayers 5.3.0 vers Openlayers 6.2.1

**Comment by pierrejego** [comment]
Bonjour,
je viens de faire une mise à jour de la version OL vers la 6.3.1. J'ai essayé de tester toutes les démos en local, je pense avoir géré tous les cas suite à la mise à jour, mais je pense que ça demande plus de tests.

**Comment by spelhate** [comment]
@pierrejego tu es parti des notes de la release pour adapter le code de mviewer et notamment ceci : https://github.com/openlayers/openlayers/releases/tag/v6.0.0 ?

**Comment by pierrejego** [comment]
Non pas vraiment, et c'est un tord... j'ai modifiée la version, et essayé toutes les demos et tous les configuration que j'avais sous la main pour voir si le comportement était le même et corriger les erreurs que je voyais dans la console. 
Mais il y a effectivement des cas à vérifier comme getFeaturesAtPixel  ou map.forEachLayerAtPixel

Je referais une passe ce soir à partir des releases notes, une à une

**Comment by pierrejego** [comment]
https://github.com/openlayers/openlayers/releases/tag/v6.0.0 -> OK

Pas d'occurence de forEachLayerAtPixel, ontouchstart dans le code donc pas d'impact.

Pour geolocation, pas d'impact, la démo fonds.xml fonctionne bien (même si il y a une erreur lié au flux http) mais pour geolocation c'est bon.

Pas d'occurence de forEachCorner, LRUCache ou de forEachInExtent

Pour moi pas d'impact sur l'ajout de contraintes pour setCenter, setResolution et setRotation, les contraintes sont logiques et je n'ai vu nullpart dans le code de tentative d'entrée des valeurs qui seraient incohérentes.
The constraints
setCenter, setResolution and setRotation can be used to change the states of the view, but any constraint defined in the constructor will be applied along the way.
A View object can have a resolution constraint, a rotation constraint and a center constraint.
The resolution constraint typically restricts min/max values and snaps to specific resolutions. It is determined by the following options: resolutions, maxResolution, maxZoom and zoomFactor. If resolutions is set, the other three options are ignored. See documentation for each option for more information. By default, the view only has a min/max restriction and allow intermediary zoom levels when pinch-zooming for example.
The rotation constraint snaps to specific angles. It is determined by the following options: enableRotation and constrainRotation. By default rotation is allowed and its value is snapped to zero when approaching the horizontal.
The center constraint is determined by the extent option. By default the view center is not constrained at all.

Pas d'occurence de getSnapToPixel, setSnapToPixel, tileLoadFunction ,  tileUrlFunction, renderMode 

Pas d'impact sur le changement d'event precompose et postcompose, c'est toujours valable pour map. Et je n'ai trouvé aucune occurence sur une couche.

getVectorContext, j'ai déjà fait la modification 

Layers can only be added to a single map ( je ne savais même pas qu'on pouvait le faire, quand j'en avais besoin je faisais un clone...)

Pas d'occurence de getLastExtent

Change of the behavior of the vector source's clear() and refresh() methods
The ol/source/Vector#clear() method no longer triggers a reload of the data from the server. If you were previously using clear() to refetch from the server, you now have to use refresh().
Les instances de clear() que j'ai trouvé dans le mviewer (isochrone et profile) ne sont pas utilisés pour recharger les données, mais bien pour néttoyer la couche.

getGETFeatureInfoUrl -> getFeatureInfoUrl déjà corrigé

Hit detection over styled Circle geometry and Circle and RegularShape styles is now consistent with that for styled Polygon geometry. There is no hit detection over the interior of unfilled shapes. To get the previous behavior, specify a Fill style with transparent color.
Je vois bien l'impact possible, mais je n'ai pas trouvé de cas dans les démos de polygon vide pour faire un test.

https://github.com/openlayers/openlayers/releases/tag/v6.0.1 -> OK
https://github.com/openlayers/openlayers/releases/tag/v6.1.0 -> OK
https://github.com/openlayers/openlayers/releases/tag/v6.1.1 -> OK
https://github.com/openlayers/openlayers/releases/tag/v6.2.0 -> OK
https://github.com/openlayers/openlayers/releases/tag/v6.2.1 -> OK
https://github.com/openlayers/openlayers/releases/tag/v6.3.0 -> OK
https://github.com/openlayers/openlayers/releases/tag/v6.3.1 -> OK

**Comment by pierrejego** [comment]
Donc pour moi c'est bon, j'ai refait des tests, mais je suis toujours preneur de plus de tests :)

**Comment by spelhate** [comment]
> Pas d'occurence de getSnapToPixel, setSnapToPixel, tileLoadFunction , tileUrlFunction, renderMode

j'ai une occurence de tileLoadFunction ici : https://github.com/geobretagne/mviewer/blob/4a5117f5f3a66829a727c90daf804e7fa669579a/js/configuration.js#L680

**Comment by spelhate** [comment]
> Pas d'impact sur le changement d'event precompose et postcompose, c'est toujours valable pour map. Et je n'ai trouvé aucune occurence sur une couche.

J'en ai ici, mais difficile à trouver ;-):

https://github.com/geobretagne/mviewer/blob/develop/demo/swipe/layer/swipe.js#L15

**Comment by spelhate** [comment]
et Merci @pierrejego  pour tout ce travail bien utile !

**Comment by pierrejego** [comment]
> > Pas d'impact sur le changement d'event precompose et postcompose, c'est toujours valable pour map. Et je n'ai trouvé aucune occurence sur une couche.
> 
> J'en ai ici, mais difficile à trouver ;-):
> 
> https://github.com/geobretagne/mviewer/blob/develop/demo/swipe/layer/swipe.js#L15

Effectivement, par contre je ne peux pas tester, j'ai une invalid key sur la démo : 
https://gis.jdev.fr/mviewer/?config=demo/swipe/swipe.xml

Du coup je fais le changement un peu à l'aveugle, est-ce que tu pourras tester ?

**Comment by spelhate** [comment]
> Du coup je fais le changement un peu à l'aveugle, est-ce que tu pourras tester ?

Oui. je gère celui là.

**Comment by Gaetanbrl** [comment]
On peut fermer ?

**Comment by spelhate** [comment]
Oui
