### ISSUE TITLE
tooltipcontent mise en forme des infobulles

### ISSUE THREAD

**Issue by aguenec** [geobretagne/mviewer#252]
Bonjour,

Je souhaiterai mettre en forme l'infobulle pour à minima:
- Insérer des sauts de lignes entre deux champs
- Mettre en gras

Je n'ai pas trouvé d'exemple mais peut être ai-je mal cherché...

La syntaxe html n'est pas prise en compte dans le tooltipcontent. Y-a t-il un autre moyen?

Merci et bonne journée!

Antoine

**Comment by spelhate** [comment]
Bonjour.
C'est tout à fait possible, mais pas très simple. Il faut utiliser la syntaxe propre à mustache et surtout échaper tous les caractères html dans le config.xml.
Exemple on souhaite utiliser ce template html : `<div>Titre: </br> {{nom}} </div>`.
Le problème c'est qu'on ne peut pas saisir cette expression dans un fichier xml. Il faut donc échaper cette chaine (j'utilise personnellement un outil en ligne).
Ce qui donne : `tooltipcontent="&lt;p&gt;titi: &lt;/br&gt;{{nom}}&lt;/p&gt;&quot;"`

**Comment by MoulinZ** [comment]
Tiens je me posais la question également. Et puisque on est dans les tooltipcontent, est-ce possible de gérer la multiplicité des points pour les clusters ? Sur l'exemple de cluster c'est "{{titre}} et {{mv_clustercount}} autre(s) dossier(s)" mais du coup quand il n'y a qu'une entité ça affiche aussi le "autres dossier(s)".

**Comment by Gaetanbrl** [comment]
> est-ce possible de gérer la multiplicité des points pour les clusters ?

Je ne crois pas que Mustache puisse gérer la multiplicité (logic-less), en HTML.

> mais du coup quand il n'y a qu'une entité ça affiche aussi le "autres dossier(s)"

Ca n'affiche pas `1 autres dossier(s)` ?

**Comment by MoulinZ** [comment]
Non ça affiche "nom du site et autre(s) dossier(s)"

**Comment by MoulinZ** [comment]
Ah bah si j'ai trouvé, il suffisait de mettre "{{titre}} {{#mv_clustercount}} et {{mv_clustercount}} autre(s) dossier(s){{/mv_clustercount}}" 
Peut être faudrait-il le faire sur la démo de clusters, c'est quand même plus propre.

**Comment by Gaetanbrl** [comment]
> Peut être faudrait-il le faire sur la démo de clusters

Toutes contributions sont les bienvenus :)

**Comment by aguenec** [comment]
> 
> 
> Bonjour.
> C'est tout à fait possible, mais pas très simple. Il faut utiliser la syntaxe propre à mustache et surtout échaper tous les caractères html dans le config.xml.
> Exemple on souhaite utiliser ce template html : `<div>Titre: </br> {{nom}} </div>`.
> Le problème c'est qu'on ne peut pas saisir cette expression dans un fichier xml. Il faut donc échaper cette chaine (j'utilise personnellement un outil en ligne).
> Ce qui donne : `tooltipcontent="&lt;p&gt;Titre: &lt;/br&gt;{{nom}}&lt;/p&gt;&quot;"`

Merci! ça fonctionne comme il faut!

**Comment by Gaetanbrl** [comment]
@aguenec puis-je fermer le ticket ?

**Comment by aguenec** [comment]
Désolé, je clos

**Comment by Gaetanbrl** [comment]
Aucun soucis :)

**Comment by bchartier** [comment]
On ferme mais il faudrait qu'on arrive à consolider ces informations dans une sorte de FAQ ou de tuto à terme.

**Comment by spelhate** [comment]
Doc mise à jour.
![image](https://user-images.githubusercontent.com/1793792/78691206-ab563e80-78f8-11ea-9413-32d6cdbdc251.png)
