### ISSUE TITLE
Icone lors de la recherche via api BAN et Geoportail

### ISSUE THREAD

**Issue by eprouteau** [geobretagne/mviewer#253]
Bonjour tous le monde,

lors de la recherche sur entités, après avoir cliqué sur un résultat j'ai un icone de localisation : 
![image](https://user-images.githubusercontent.com/1401902/78564364-986e3c00-781c-11ea-9d67-beff63f0831f.png)

Lors d'une recherche via l'api BAN ou Geoportail, je n'ai pas cet icone. Savez vous comment serait-il possible pour l'avoir sur ce type de recherche ?

Bonne journée

**Comment by spelhate** [comment]
Bonjour.
Il faudrait modifier le code existant dans `mviewer.zoomToLocation() ` pour ajouter la ligne qui permet d'afficher l'indicateur.

**Comment by eprouteau** [comment]
Merci Sébastien, je regarde ça.

Bonne journée

**Comment by spelhate** [comment]
Si le besoin est partagé par d'autres utilisateurs, on pourra traiter cette demande en évolution à envisager.

**Comment by bchartier** [comment]
+1 pour cette évolution

**Comment by Gaetanbrl** [comment]
@eprouteau des travaux ont-ils déjà été commencé sur ce point ?

**Comment by Gaetanbrl** [comment]
Traité dans la branche [feature-316](https://github.com/geobretagne/mviewer/tree/feature-316) @eprouteau .

> Il faudrait modifier le code existant dans mviewer.zoomToLocation() pour ajouter la ligne qui permet d'afficher l'indicateur.

* Traité directement dans l'event onclick et permet de conserver la méthode zoomToLocation sans affichage forcé de la punaise.

* Traité avec #316

**Comment by Gaetanbrl** [comment]
@eprouteau - La correction est disponible dans la branche develop.
Vous pouvez tester le correctif et fermer cette issue si résolue.

**Comment by eprouteau** [comment]
Je vais tester ça dès que j'ai un moment

Merci en tout cas
