### ISSUE TITLE
Changer l'icon de la couche dans le panneau de légende

### ISSUE THREAD

**Issue by Ailurupoda** [geobretagne/mviewer#254]
Bonjour,

Je souhaiterais savoir s'il est possible de modifier l'icon affiché à gauche du nom de la couche dans le panneau de légende et comment y parvenir dans ce cas. 
Voici en image, l'icon dont je parle :
![mviewer_layericon](https://user-images.githubusercontent.com/10120833/78654357-b0999600-78c4-11ea-88f3-1cbb3e0f2b95.png)

Merci d'avance :)

**Comment by Gaetanbrl** [comment]
Bonjour,
La modification est possible dans votre Mviewer de votre côté : 
https://github.com/geobretagne/mviewer/blob/a6d9e0713837611d4c52e0abeddab67310fda124/js/templates.js#L55

Vous pouvez remplacer l'icône par une [icône Font-Awesome](https://fontawesome.com/icons?d=gallery) de votre choix en remplaçant la class CSS du tag `<i class="xxxx"> </i>`.

C'est par contre un élément du `coeur` du Mviewer. Nous déconseillons fortement les modification sur les fichiers du coeur.

Pour avoir plus d'informations sur le coeur Mviewer vous pouvez lire cette documentation : 
https://mviewerdoc.readthedocs.io/fr/latest/doc_contrib/contrib.html#le-coeur-de-mviewer

**Comment by Ailurupoda** [comment]
Super, merci :) 
J'ai une ancienne version de mViewer, j'ai copié la dernière version du template.js
J'ai ce que je voulais :+1:
