### ISSUE TITLE
Update vector legend on customLayer change

### ISSUE THREAD

**Issue by Gaetanbrl** [geobretagne/mviewer#255]
En lien avec #88 , je souhaiterai pouvoir recharger ma légende après affichage.

J'ai réalisé un customControl qui permet de changer le style des données selon un attribut et qui permet de filtrer les géométries selon d'autres attributs à l'image de ce qui se fait avec le SLD (dont je me suis inspiré pour la partie IHM).

![image](https://user-images.githubusercontent.com/16317988/78786371-f4fe6200-79a8-11ea-9690-db380643dbc8.png)

J'aimerai que, au changement du filtre, la légende se recharge.

Je ne crois pas que ce soit réalisable actuellement.
Voici ma question pour m'en assurer : cette mécanique existe-t-elle déjà ? 

Si non, je vais réaliser un développement spécifique si ce n'est pas le cas.
Merci.

**Comment by spelhate** [comment]
Tu dois pouvoir faire un `mviewer.drawVectorLegend()` avec les paramètres qui vont bien depuis ton customControl.

**Comment by Gaetanbrl** [comment]
Ok merci je vais regarder ca de plus près d'ici peu et je fais un retour.

**Comment by Gaetanbrl** [comment]
Exemple d'utilisation de `mviewer.drawVectorLegend()` :

https://github.com/geobretagne/mviewer/blob/a6d9e0713837611d4c52e0abeddab67310fda124/js/csv.js#L216

**Comment by Gaetanbrl** [comment]
@spelhate  `mviewer.drawVectorLegend()` est bien ce qu'il me fallait. Merci beaucoup !
