### ISSUE TITLE
Doubles ascenseurs mode ultra

### ISSUE THREAD

**Issue by lecault** [geobretagne/mviewer#256]
Bonjour à tous,

Lorsqu'on passe un mviewer en mode ultra, un phénomène désagréable de doubles ascenseurs apparaît comme ici par exemple : https://kartenn.region-bretagne.fr/vn/?x=-162234&y=6132627&z=10&l=voie_navigable*voie_navigable_proprietaire%252Cecluse_trafic*ecluse_proprietaire&lb=plan2&mode=u

Cela vient d'un max-height à 600px dans le CSS :
#accordion .panel-collapse.collapse.in{
  overflow-y: auto;
  max-height:600px;
}

Je ne vois pas l'utilité d'avoir cette taille maximale que je propose de supprimer. Le rendu serait comme ici : https://kartenn.region-bretagne.fr/patrimoine/?x=-304627&y=6088159&z=9&l=etude_patrimoine_simpledbl1**type_dossier%2520like%2520%27%2525OeuvreArchitecture%2525%27&lb=osm1&mode=u

Merci de vos avis,

**Comment by Gaetanbrl** [comment]
@lecault as-tu fais un test avec un contenu très dense ? 
Voir bug #222  avec similarité sur cette issue.

**Comment by Gaetanbrl** [comment]
Testé avec contenu type [Lorem Ipsum](https://fr.lipsum.com/ ) .

RAS ca semble bien s'afficher. On ne retrouve pas le comportement de l'issue référencé dans le commentaire précédent.

Merci @lecault .

**Comment by lecault** [comment]
Oui ça ressemble à la #222 .
Du coup tu as enlevé le max-height @Gaetanbrl ?

**Comment by Gaetanbrl** [comment]
Non j'ai testé le rendu avec un contenu dense sur l'exemple que tu as fourni : 

https://kartenn.region-bretagne.fr/patrimoine/?x=-304627&y=6088159&z=9&l=etude_patrimoine_simpledbl1**type_dossier%2520like%2520%27%2525OeuvreArchitecture%2525%27&lb=osm1&mode=u

Je pensais qu'un avis était souhaité et que tu ferai la modification directement. C'est réalisable directement dans GitHub et autrement la doc permet de faire ses premiers pas avec Git. Ce type de modification est un bon exercice très simple.

Je peux faire la modification si personne d'autres ne peut évidemment ;)

**Comment by spelhate** [comment]
@lecault . Je n'arrive pas à reproduire le double ascenseur.
Dans quel contexte utilises-tu cet exemple mviewer ? 
Dans une iframe ? si c'est dans une iframe, y a t'il une hauteur de fixée ?

**Comment by spelhate** [comment]
@lecault tu utilises un navigateur en particulier ?
En utilisant ton lien, j'obtiens le résultat suivant 
![image](https://user-images.githubusercontent.com/1793792/79315339-0c869f00-7f03-11ea-8db3-73b42309f08d.png)

Et je ne vois pas le double ascenseur.

**Comment by Gaetanbrl** [comment]
De mon côté j'avais un seul ascenseur uniquement avec FF et il n'y était plus dans la modification proposée.

Rien sur Chrome autrement, j'ai le même résultat que toi @spelhate .

**Comment by Gaetanbrl** [comment]
@lecault quelle est la résolution de ton écran ?

**Comment by lecault** [comment]
Oui sur Chrome on ne voit pas les ascenseurs mais ils sont là. C'est plus flagrand sur Firefox si. Du coup la difficulté est pour accéder au bas de la fiche.

Résolution 1920x1080

![image](https://user-images.githubusercontent.com/5269430/79340483-add51b80-7f2a-11ea-82c0-e88645cc08ea.png)

**Comment by spelhate** [comment]
> la difficulté est pour accéder au bas de la fiche.

Ca ne marche pas avec la molette ?

**Comment by lecault** [comment]
Si mais c'est embêtant. Il faut être au niveau de la fiche pour un ascenseur et en dehors pour l'autre.

**Comment by lecault** [comment]
En fait si on enlève l'option pour tout, ça posera des soucis en mode normal.
Pour ma part, je l'ai juste enlevé dans un CSS spécial mode ultra.

Donc on contourne.
