### ISSUE TITLE
Affichage/Désaffichage de la tooltip

### ISSUE THREAD

**Issue by pigma** [geobretagne/mviewer#263]
Bonjour,

En manipulant les paramètres de la tooltip dans le config.xml je me suis rendu compte que malgré un `tooltip="false"`, si le `tooltipcontent` est renseigné, alors le tooltip s'affiche au survol. Il faut que le `tooltipcontent` ne soit pas renseigné pour que le `tooltip="false"` soit bien effectif.

Bonne soirée,

**Comment by Gaetanbrl** [comment]
Travaux débutés sur la branche [issue-263](https://github.com/geobretagne/mviewer/tree/issue-263).

**Comment by Gaetanbrl** [comment]
En attente de revue de la Pull Request + merge.

**Comment by Gaetanbrl** [comment]
Correction à tester et issue à fermer suite à la PR.
Merci @pigma .

**Comment by Gaetanbrl** [comment]
merci @spelhate
