### ISSUE TITLE
Développement d'un outil de filtrage de couches vecteurs

### ISSUE THREAD

**Issue by pigma** [geobretagne/mviewer#264]
Bonjour,

Pour information, un outil de filtrage de couches vecteurs est en cours de développement avec la société JDEV. 

Cet outil doit permettre de filtrer une couche vecteur définie dans un custom layer au format geojson (Flux ou fichier) et mettre à jour l'affichage des données de la carte . Les filtres seront en intéraction les un avec les autres et l'outil sera paramétrable : 

- Champs filtrés
- Type de représentation du filtre par champ(Date, liste déroulante, ...)

Ces paramètres seront définie de telle sorte que la configuration de l'outil ne nécessitera pas de développement particulier.

Ces développements se font dans le cadre d'un partenariat entre le GIP Littoral et le GIP ATGeRi avec la mise en place d'une base de données plages de Nouvelle-Aquitaine.

Bonne journée,

**Comment by pierrejego** [comment]
La réalisation de cette évolution vient de commencer, il peut être suivi ici : https://github.com/jdev-org/donneesplages/projects/1

Et un environnement de démo est en cours de réalisation : https://gis.jdev.fr/mviewer/?config=apps/donneesplages/donneesplages.xml

On propose soit d'utiliser le nouveau système d'extension, soit de modifier le coeur pour rajouter le filtrage, un peu comme la recherche est ajoutée actuellement.
N'ayant pas encore analyser le tout nouveau système d'extension, pour l'instant on part sur une modification du coeur pour ajouter la nouvelle fonctionnalité, mais ça peut changer pendant les développements.

**Comment by bchartier** [comment]
> On propose soit d'utiliser le nouveau système d'extension, soit de modifier le coeur pour rajouter le filtrage, un peu comme la recherche est ajoutée actuellement.
> N'ayant pas encore analyser le tout nouveau système d'extension, pour l'instant on part sur une modification du coeur pour ajouter la nouvelle fonctionnalité, mais ça peut changer pendant les développements.

Peux-tu nous expliquer ce qui justifierait de modifier le cœur et que l'on ne peut pas réaliser aujourd'hui avec les notions de customcontrol et customlayer ?

**Comment by Gaetanbrl** [comment]
> et que l'on ne peut pas réaliser aujourd'hui avec les notions de customcontrol et customlayer

C'est possible (à voir en plus selon les nouveautés). Mais centraliser ce type de fonctionnalité permet d'éviter une duplication car gérer ce type d'action / UI par un `customcontrol/layer` revient à dupliquer N fois un code qui peut être assez lourd et surtout pour des profils moins techniques.

Si la recherche Fuse / ELS était au niveau d'un `customcontrol/layer`, donc au niveau de chaque couche à rechercher, rien qu'au niveau de l'interface ce ne serait vraiment pas ergonomique. J'imagine que filtrer une seule couche ferai prendre tout la hauteur de l'écran à la légende alors que nos retours d'utilisateur sont plus vers la simplification de cet élément graphique. Je ne parlerai même pas du côté développement ce serait très redondant et un peu contre productif.

Donc à l'usage (ergonomie) et pour une mise en place récurrente (développement) le `customcontrol/layer` ne me semble pas être une bonne solution si je met à la place de nos admins / users qui ne sont pas des développeurs.

C'est du moins une approche et puis comme dit plus haut :D : 
> ça peut changer pendant les développements

**Comment by pigma** [comment]
En tant qu'utilisateur avancé, avoir la possibilité de configurer ce type de fonctionnalité dans le config.xml plutôt que de dupliquer autant de fois que de couche des fichiers en quand même beaucoup plus intéressant, mais je ne suis pas développeur. 

Le fait d'avoir ce type de configuration directement dans le config.xml ne facilite t-il pas également le suivi de cette fonctionnalité dans le temps avec les montés de version ?

**Comment by spelhate** [comment]
Je vous invite à regarder la pr #262 qui vient d'être mergée . Elle donne une grande souplesse pour développer de nouvelles fonctionnalités sans modifier le cœur.

**Comment by pierrejego** [comment]
@spelhate je teste justement :)
