### ISSUE TITLE
Release v3.2

### ISSUE THREAD

**Issue by spelhate** [geobretagne/mviewer#267]
Je viens de publier la nouvelle release.
Si vous souhaitez une mise en lumière de certaines évolutions, vous pouvez amender cette page.
https://github.com/geobretagne/mviewer/releases/tag/v3.2
Merci aux participants !
@pmauduit, @bchartier, @Gaetanbrl , @pierrejego, @Sfoucheur, @jeanpommier , @fvanderbiest

**Comment by Gaetanbrl** [comment]
Merci @spelhate.

**Comment by Gaetanbrl** [comment]
Question sur le nouveau système customcontrols :

Sont-ils compatible avec le système de customcontrols précédent ou bien la migration en 3.2 nécessite une refonte des customcontrols ?

**Comment by spelhate** [comment]
C'est compatible ! Tu peux conserver l'ancienne façon de faire. Je vais également tenter de documenter cette partie.

**Comment by spelhate** [comment]
J'ai fait une PR https://github.com/geobretagne/mviewer.doc/pull/37 en lien avec la documentation sur la création de composants personnalisés.

**Comment by Gaetanbrl** [comment]
Merci @spelhate

**Comment by Gaetanbrl** [comment]
je ferme ce ticket avec l'arrivée d'une nouvelle release.
