### ISSUE TITLE
Demo Swipe custom error with FF

### ISSUE THREAD

**Issue by Gaetanbrl** [geobretagne/mviewer#269]
Aucun soucis sur Chrome, mais une erreur sur FF :

![image](https://user-images.githubusercontent.com/16317988/79557391-c405e780-80a2-11ea-89f5-e3d021acfa33.png)

**Comment by spelhate** [comment]
@Gaetanbrl , @pierrejego , @bchartier 
J'ai une question. Comment fait-on pour Fixer un bug et l'appliquer à la release 3.2 ?

**Comment by pierrejego** [comment]
on ne fait pas :) il faut faire un autre release 3.2.1.
C'est une des règles sur les tags, il ne faut jamais les modifier.

Et concrètement, soit : 
1- tu fais une branche hotfix que tu merges sur la master et sur la develop pour ensuite refaire une release.
2 - tu fais une branche que tu merges dans develop puis dans develop dans master. 

Mais dans tous les cas il faut refaire une release.

Tu es sur que ce bug n'existait pas déja avant ?

**Comment by Gaetanbrl** [comment]
> Tu es sur que ce bug n'existait pas déja avant ?

Difficile de vérifier avant car sorti dans la v.3.2. Mais j'imagine que ca devait être le cas avant.

> Comment fait-on pour Fixer un bug et l'appliquer à la release 3.2 

Ce bug est peut-être surtout à prendre comme une évolution et l'adapter au nouveau système de custom et ne pas se pencher sur cette version < 3.3 ?

Donc pour la prochaine release v3.3 je suppose.

Après ça peut potentiellement intéresser des utilisateurs de la 3.2.

**Comment by pierrejego** [comment]
oui surtout que ça ne touche pas le coeur, mais une démo

**Comment by spelhate** [comment]
> Tu es sur que ce bug n'existait pas déja avant ?

Oui.
Ok je fais une release 3.2.1
