### ISSUE TITLE
Maintenance && Url externe

### ISSUE THREAD

**Issue by pierrejego** [geobretagne/mviewer#270]
Bonjour,
je voulais votre avis sur un point.

Le mviewer fonctionne super bien et depuis un moment. Certaines personnes ne mettent pas à jour régulièrement et n'en ont pas le besoin. 

Par contre les version des libs utilisés par mviewer évoluent aussi de leur côté et des urls d'anciennes versions ne sont plus disponible et du coup le mviewer ne fonctionne plus

Dans les imports css et js, nous avons les deux, soit la lib est récupérée et servit par le même serveur que le mviewer soit la lib est une url cdn.

```
<script src="https://cdnjs.cloudflare.com/ajax/libs/mustache.js/2.3.0/mustache.min.js"></script>
<script type="text/javascript" src="lib/proj4js/2.3.6/proj4.js"></script>
```
L'avantage ne pas héberger les dépendances JS c'est que ça limite les accès aux serveurs, le désavantages c'est la dépendance externe.
ça me fait penser à un autre cas (très très rare), ou l'utilisateur est en interne sans accès à internet.

Pour les prochaines montées en version de lib quel serait pour vous la stratégie à suivre ?
url cdn ou répertoire lib ?
 
Perso, même si je ne trouve pas que ça soit le plus beau, dans notre contexte, je penche pour le répertoire lib.

**Comment by spelhate** [comment]
Je suis également pour internaliser les ressources.

**Comment by Gaetanbrl** [comment]
Je rebondis sur cette issue ce jour.

Les appels vers l'URL `https://cdnjs.cloudflare.com/*` semblent revenir en erreur : 

```
net::ERR_SSL_VERSION_OR_CIPHER_MISMATCH
net::ERR_SSL_VERSION_OR_CIPHER_MISMATCH
```

Exemple avec le fichier mustache.js

[mustache.min.js](https://cdnjs.cloudflare.com/ajax/libs/mustache.js/2.3.0/mustache.min.js)

**Comment by Gaetanbrl** [comment]
Dans l'attente du retour de #370  je commence les travaux sur cette issue.

**Comment by Gaetanbrl** [comment]
- [ ] https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.4.3/css/flag-icon.css

- [ ] https://cdnjs.cloudflare.com/ajax/libs/bootstrap-tagsinput/0.8.0/bootstrap-tagsinput.css

- [ ] https://cdnjs.cloudflare.com/ajax/libs/mustache.js/2.3.0/mustache.min.js

- [ ] https://cdnjs.cloudflare.com/ajax/libs/bootstrap-tagsinput/0.8.0/bootstrap-tagsinput.min.js

- [ ] https://cdnjs.cloudflare.com/ajax/libs/PapaParse/4.6.3/papaparse.min.js

**Comment by Gaetanbrl** [comment]
Je ferme cette issue @pierrejego suite à l'intégration des ressources externes vi merge de la PR #371 .
