### ISSUE TITLE
Maquette du projet sur le visualiseur dans le cadre de mon Stage  

### ISSUE THREAD

**Issue by hugobruyas** [geobretagne/mviewer#273]
Bonjour,
J'ai réalisé une présentation de mon profil dans une précédente issue.
À la suite de cette présentation, j'ai eu une réunion en vidéoconférence avec Sébastien Pelhate et Marie Jagaille. 
Cette réunion a eu pour but de me clarifier plusieurs éléments sur le code du visualiseur "Copernicus Régional" avec le fichier config.xml.
Différentes explications comme les custom layers et custom controls ont également étaient expliquées.

Voici le mviewer "Copernicus Régional" actuel : https://geobretagne.fr/mviewer/?config=/apps/teledetection/config.xml 
Ce visualiseur doit par la suite évoluer et posséder dans un premier temps une fonction calendrier, couverture nuageuse, composition colorée, luminosité et contraste. Ses fonctions ont déjà était réalisées par des étudiants de l'IMT Atlantique de l'année dernière : https://geobretagne.fr/mviewer/?config=/apps/sentinel/config.xml#

À la suite de cet échange, nous avons convenu qu'il fallait réaliser une maquette du visualiseur idéal dans sa forme finale.
C'est pour quoi après avoir réalisé un état de l'art, j'ai pu produire une maquette que je vous fais parvenir afin que vous puissiez me guider et m'informer sur la faisabilité de ce projet.
Cordialement,

Maquette : 
[Maquettes du Mviewer - Copernicus Régional.pptx](https://github.com/geobretagne/mviewer/files/4504133/Maquettes.du.Mviewer.-.Copernicus.Regional.pptx)

Hugo BRUYAS
hugo71dm@gmail.com
hugo.bruyas@imt-atlantique.fr

**Comment by Gaetanbrl** [comment]
Merci pour ce partage @hugobruyas.
C'est une belle maquette  ;) !

2 questions me viennent dans l'immédiat au sujet des templates prévus (en bas et à droite): 
- Un affichage mobile est-il prévu ? Si oui, j'ai un doute le comportement à l'affichage du template droite + inférieur en version mobile.
- L'ouverture simultané de ces deux templates est-il prévu pour une seule couche ? Je ne suis pas certains que deux templates ce soit gérable sans changement du coeur du code Mviewer.

Mais il très probable que @spelhate en sache plus :)

**Comment by hugobruyas** [comment]
De rien et merci pour votre retour !
Une version mobile serait effectivement prévue pour cette application.
Pour la conception de la maquette je me suis servi notamment notamment de cette maquette mais je ne connais pas son comportement exact ainsi que son adaptation à une version mobile (https://geobretagne.fr/mviewer/?config=/apps/obsfoncier/config.xml#).

Sinon, je vous propose une autre maquette beaucoup plus simplifiée mais peut-être qu'elle sera plus simple à adapter à une version mobile : 
![image](https://user-images.githubusercontent.com/62612382/79982158-23e6fe80-84a6-11ea-95f0-c75ae8193a76.png)

Pour cette maquette, on peut garder :
- une fenêtre avec les choix d'affichage et d'image
- un seul bandeau latéral avec toutes les infos. Par exemple comme l'image ci-dessus.

Hugo BRUYAS
hugo71dm@gmail.com
hugo.bruyas@imt-atlantique.fr

**Comment by spelhate** [comment]
Bonjour visuellement, cette maquette me semble plus facilement réalisable.
Pour nous aider à nous prononcer, il faudrait détailler le parcours utilisateur imaginé.

**Comment by hugobruyas** [comment]
Bonjour, 
Je vous fait part du parcours utilisateur imaginé pour l'application Copernicus Régionale.
[Parcours utilisateur imaginé pour la future plateforme Copernicus régionale.pdf](https://github.com/geobretagne/mviewer/files/4559286/Parcours.utilisateur.imagine.pour.la.future.plateforme.Copernicus.regionale.pdf)

**Comment by spelhate** [comment]
Je vais essayer de donner un coup de main sur ce projet début juin.

**Comment by hugobruyas** [comment]
C'est d’accord, merci.

**Comment by hugobruyas** [comment]
Bonjour, j’espère que vous vous portez bien.
Je reviens vers vous suite à la proposition que vous aviez faite pour me donner un coup de main sur mon projet. 
Bien, cordialement,

**Comment by Gaetanbrl** [comment]
@hugobruyas @spelhate 

Puis-je fermer cette issue ?
