### ISSUE TITLE
Titre de la fenêtre Help "DOCUMENTATION"

### ISSUE THREAD

**Issue by pigma** [geobretagne/mviewer#275]
Bonjour,

Le titre "DOCUMENTATION" est écrit en dur dans le index.html. 

Souhaitant utiliser cette page pour faire la présentation des projets sans le terme DOCUMENTATION, il pourrait être intéressant de laisser le paramétrage de ce titre directement dans le fichier .html.

Pour ne pas modifier le cœur je vais dans un premier temps faire une modification de ce titre à la volé.

Cordialement,

**Comment by spelhate** [comment]
Bonjour le paramètre ``titlehelp`` dans le fichier de config permet déjà de modifier ce titre. De même il est possible de modifier l'icone du bouton.

exemple 
`<application title="Démo" help="help.html" showhelp="true" titlehelp="Mon Titre" iconhelp="" />`

**Comment by spelhate** [comment]
La doc mentionne ce paramétrage : https://mviewerdoc.readthedocs.io/fr/latest/doc_dev/config_app.html#configurer-application

**Comment by pigma** [comment]
Merci pour l'info
