### ISSUE TITLE
Problème de désactivation du scrolling de zoom par souris

### ISSUE THREAD

**Issue by pigma** [geobretagne/mviewer#276]
Bonjour, 

Que ce soit sur Chrome ou Firefox, après la fermeture d'une fiche d'informations ou bien toute autre action de clic autre que sur la carte (affichage couche, accéder à l'opacité), désactive le scrolling de zoom avec la souris. il est nécessaire de cliquer dans le vide sur la carte pour le réactiver.
De même pour le déplacement deux clics sont nécessaires.

Est ce un comportement que vous observez également ?

Cordialement,

**Comment by Gaetanbrl** [comment]
C'est étrange en effet. Je ne reproduis pas de comportement et je ne l'ai jamais rencontré.

Peux-tu décrire si tu as des erreurs dans ta console ? (pour y accéder appuyer sur F12 et cliquer sur "console" dans les onglets).

Le Mviewer en question est accessible pour que l'on puisse jeter un oeil ?

**Comment by vfabry** [comment]
Même comportement chez Géo2France. Pas d'erreur dans la console. Firefox 75.0
Par exemple ici : https://www.geo2france.fr/mviewer/?config=apps/transport_hdf.xml#

**Comment by Gaetanbrl** [comment]
@vfabry @pigma avez-vous touché au CSS du mviewer pour avoir un thème personnalisé ou autre ?

**Comment by pigma** [comment]
Pas de notre côté

**Comment by Gaetanbrl** [comment]
Rien dans le coeur non plus ? Je n'arrive pas à reproduire sur un mviewer autre.

**Comment by pigma** [comment]
Je reproduit sur le mviewer de dev de données plages sur votre serveur

**Comment by Gaetanbrl** [comment]
> Je reproduis sur le mviewer de dev de données plages sur votre serveurEn conservant votre 

Etant en chantier je ne considère pas qu'il soit un bon élément de test pour ce type de bug.

Avec votre environnement initial, pouvez-vous reprendre un mviewer "neuf" depuis le github et tester ? 

On va pouvoir identifier déjà une version ainsi.

**Comment by pierrejego** [comment]
Pas sur de comprendre vos échanges :) l'application https://gis.jdev.fr/mviewer/?config=apps/donneesplages/donneesplages.xml tourne sur la dernière version de mviewer. Mais effectivement ce n'est pas le même css.

**Comment by vfabry** [comment]
> 
> 
> @vfabry @pigma avez-vous touché au CSS du mviewer pour avoir un thème personnalisé ou autre ?

j'appelle apps/css/themes/g2f.css qui est un css maison basé sur le css mviewer

**Comment by Gaetanbrl** [comment]
J'ai reproduis ce comportement sur la master sans aucune modification. Si vous avez fait l'upgrade suite à la dernière `release `ca provient potentiellement de là.

**Comment by spelhate** [comment]
Je confirme ce fonctionnement depuis la version 3.2. J'ai l'impression que ça a un rapport avec la version qui est nouvelle d'Openlayers.

**Comment by spelhate** [comment]
Lié à la version 6.0  : https://github.com/openlayers/openlayers/pull/10187

et 
https://github.com/openlayers/openlayers/issues/10109

**Comment by spelhate** [comment]
Corrigé sur la branche develop.

**Comment by Gaetanbrl** [comment]
Super, merci @spelhate

**Comment by bchartier** [comment]
Est-ce qu'on peut envisager de préparer une release qui prenne en compte cette correction ? Ça éviterait à ceux qui ont déployé la dernière release de se trainer ce bug.

**Comment by spelhate** [comment]
Oui. La semaine prochaine en principe.

**Comment by vfabry** [comment]
Je viens d'installer la 3.3 est j'ai l'impression que le problème persiste dans Firefox 77.0.1 (c'est OK dans chrome).

**Comment by Gaetanbrl** [comment]
Je viens de tester avec FF 77.0.1 (64 bits) et je ne reproduis pas.

**Comment by Gaetanbrl** [comment]
avec Mviewer 3.2* je précise

**Comment by vfabry** [comment]
sur cette appli, par exemple : 
https://www.geo2france.fr/mviewer/?config=apps/dev_eco.xml#

**Comment by Gaetanbrl** [comment]
Je viens de tester avec votre appli et je ne reproduis toujours pas.

![image](https://user-images.githubusercontent.com/16317988/84905398-e622e280-b0b0-11ea-8149-88a31ab2b141.png)

Est-il possible d'avoir le détail de vos action depuis le chargement du Mviewer pour savoir ce qui provoque ce comportement chez vous ?

**Comment by bchartier** [comment]
@vfabry : Question bête : ça peut être un souci de cache dans ton navigateur ?

**Comment by vfabry** [comment]
olala, bien vu c'était le cache... désolé pour le temps passé et merci !
