### ISSUE TITLE
QGIS Server : FI_POINT_TOLERANCE 

### ISSUE THREAD

**Issue by vfabry** [geobretagne/mviewer#280]
Bonjour,
Dans pas mal de mes mviewer, je consomme des flux produits par un QGIS server. Or, le _getfeatureinfo_ de qgis server est un peu casse-pied : si on ne clique pas pile au centre du picto dont on veut voir les attributs, la requête ne renvoie rien. Heureusement, on peut surcharger la requête avec un paramètre `FI_POINT_TOLERANCE  = 10` (en px) (par exemple). Comment faire pour l'autoriser dans mviewer ?

**Comment by bchartier** [comment]
Aujourd'hui on ne peut pas le faire.
Il faudrait modifier le code pour faire quelque chose de similaire à ce que nous avions fait avec le paramètre owsOptions : ajout de paramètres par défaut à la requête GetMap. Là, ce serait un paramètre uniquement pour GetFeatureInfo.

**Comment by spelhate** [comment]
Bon ce n'est pas l'idéal, mais si dans l'url du service, au lieu de mettre `url="https://monqgisserver/wms"`
, tu écris : `url="https://monqgisserver/wms?FI_POINT_TOLERANCE=10&"`

Ca pollue les requêtes GetMap, mais ça peut fonctionner.

Le plus propre serait de rajouter un paramètre  owsoptions comme l'a suggéré @bchartier ou une url spécifique pour le **GetFeatureInfo**.

**Comment by vfabry** [comment]
Merci, l'astuce de rajouter le paramètre dans l'URL fonctionne parfaitement !

**Comment by Gaetanbrl** [comment]
Je complète ce ticket,
Depuis plusieurs version il est possible d'utiliser le paramètre de couche owsoptions pour compléter les paramètres d'URL du WMS.

**Exemple** : 

`owsoptions="FI_POINT_TOLERANCE:10"`

**Exemple complet** :

```
            <layer
                id="transp_gares"
                name="Gares ferroviaires"
                url="https://qgisserver.hautsdefrance.fr/cgi-bin/qgis_mapserv.fcgi?MAP=/var/www/data/qgis/applications/sraddet_2020_08.qgz"
                type="wms"
                owsoptions="FI_POINT_TOLERANCE:10"
                visible="true"
                queryable="true"
                infoformat="application/vnd.ogc.gml"
                metadata="https://www.geo2france.fr/datahub/dataset/8252be87-f664-4573-a1a4-e372fe624f0f"
                attribution="Région Hauts-de-France" />
```
