### ISSUE TITLE
Faire cohabiter des couches hors groupe et dans des groupes dans le même theme

### ISSUE THREAD

**Issue by pbarille** [geobretagne/mviewer#284]
Bonjour,

Je souhaiterais avoir l'arborescence suivante dans un de mes mviewers :
<theme A>
     <layer 1>
     <layer 2>
     <layer 3>
<group a>
     <layer 4>
     <layer 5>
</group a>
</theme>

Malheureusement avec cette syntaxe, les layers 1, 2 et 3 ne s'affichent pas.
Est-ce une configuration possible ?
Si oui y-a-t-il une subtilité syntaxique qui m'échappe ?

D'avance merci !
Bonne journée,
Pascal

**Comment by Gaetanbrl** [comment]
Bonjour @pbarille , si l'objectif est de forcer un ordre d'affichage je ne pense pas que cela soit possible.
Cette syntaxe ne fonctionne pas car <layer n> (où n est un numéro) n'est pas un élément attendu puisque le Mviewer recherchera strictement <layer>.

Si ce n'est pas existant, ce peut être une évolution.

**Comment by pbarille** [comment]
Bonjour @Gaetanbrl 
Merci pour la réponse rapide. 
Les numéros que j'ai mis derrière les layers n'ont pas vocation à montrer une hiérarchie, seulement à les identifier pour l'exemple. Et je viens de me rendre compte que des éléments de mon exemple ne sont pas passé à la publication de mon message.
Je reprends donc.

J'aimerais pouvoir utiliser cette organisation : 
`<theme A> `
`<layer 1>`
`<layer 2>`
`<layer 3>`
`<group a>`
`<layer 5>`
`<layer 6>`
`</group a>`
`</theme A>`

Plutôt que : 
`<theme A> `
`<group a>`
`<layer 1>`
`</group a>`
`<group b>`
`<layer 2>`
`</group b>`
`<group c>`
`<layer 3>`
`</group c>`
`<group d>`
`<layer 5>`
`<layer 6>`
`</group d>`
`</theme A>`

Mais quand j'utilise la syntaxe souhaitée, mes layers 1, 2 et 3 ne s'affichent pas...

**Comment by Gaetanbrl** [comment]
Donc si je comprend bien c'est pour afficher un sous-groupe ?

**Comment by pbarille** [comment]
C'est pour éviter d'avoir des groupes avec une seule couche dedans

**Comment by Gaetanbrl** [comment]
Je comprend merci pour ces détails.
Je ne pense pas que ce soit actuellement réalisable.

**Comment by pbarille** [comment]
Ok, tant pis...
Merci !

**Comment by pbarille** [comment]
Si ça peut intéresser d'autres personnes, j'ai trouvé une solution de contournement en utilisant l’agrégation de couches de geoserver à la place de mon groupe.

**Comment by Gaetanbrl** [comment]
> j'ai trouvé une solution de contournement

Un peu plus de détails ? Merci pour le partage :)

**Comment by pbarille** [comment]
Oui bien sûr.
Pour le contexte, je réalise un viewer de PLUi.
J'ai un `<theme>` qui correspond aux annexes de mon PLUi. j'essaye d'avoir un `<layer>` par annexe pour retrouver la logique du document .
Mais mon annexe 'Eaux usées' est constituée de données surfaciques, linéaires et ponctuelles réparties sur 3 couches différentes.
J'imaginais donc utiliser un `<group>` pour associer mes 3 couches d'où ma question initiale.

Dans le menu "données" de Geoserver, il y a une rubrique "Agrégation de couches" qui permet de créer une sorte de couche virtuelle issue de la combinaison de plusieurs couches. J'ai donc créé une couche virtuelle "eaux_usées" composée de "eau_usées_surf", "eaux_usées_lin" et "eaux_usées_pct" (on peut d'ailleurs choisir le style à associer à chaque couche lors de la création de l'aggrégat).
J'appelle ensuite cette couche virtuelle comme un `<layer>` classique dans le mviewer.

La légende du mviewer reprend cependant le nom de chaque couche, il faudra que je la remplace par une image.

En espérant avoir été clair :)

**Comment by Gaetanbrl** [comment]
> En espérant avoir été clair :)

Je pense que c'est assez clair pour être reproduis.

Si l'issue n'a plus lieu d'être je laisse @pbarille la fermer.

merci.
