### ISSUE TITLE
Format Date et Librairie moment.js

### ISSUE THREAD

**Issue by Gaetanbrl** [geobretagne/mviewer#285]
### Moment.js

Une petite note pour retrouver une librairie très pratique  très très pratique qui pourra être utile dans des Mviewer avec manipulation de données temporelle (ex WFS) :   

[moment.js](https://momentjs.com/)

Cette librairie très légère permet  de manipuler des dates facilement. 
L'API Date de JavaScript ne permettant pas de préciser le format de date en entrée contrairement à d'autres langages (Python, Java, etc.).

Voici des exemples pour vous savoir si cela peut vous être utile ou non...

### Lecture des dates

**API JS Date :**

❌ `new Date ("21/04/2020 16:30")` 
❌ => Invalid Date {}
❌ => Format français classique invalide,
😠 => Obligation de créer une fonction spécifique pour ce format type : 
```
function dateToTs(date) {
    split = date.split(' ');
    // return Date instance
    return new Date(split[0].split('/').reverse().join('-') + 'T' + split[1]);
}
```

✔️ `new Date ("2020/04/21")`
💂‍♂️
=> Tue Apr 21 2020 00:00:00 GMT+0200 (heure d’été d’Europe centrale) {}

**Moment.js**
😮🙀😮
✔️ `moment("2020/04/20");` 
✔️ `moment("2020/04/20", "MM/DD/YYYY");`
✔️ `moment("21/04/2020", "MM/DD/YYYY");`

### Formatage des dates vers un format 05/01/20

**API JS Date :**
👀🙈
```
var date = new Date ("2020/04/21");
var d = date.getDate();
var m = date.getMonth() + 1;
var year = date.getFullYear();

var day = d < 10 ? ("0" + d) : d; // afficher un 0 devant. Ex : 01.02.20
var month = m < 10 ? ("0" + m) : m; // afficher un 0 devant. Ex : 01.02.20
var formatedDate = [day, month, year].join("/");  // affiche 01/02/2020
```

**Moment.js**
`moment("2020/04/20", "MM/DD/YYYY").format("DD/MM/YY");`
Cela vous paraît normal ? Ça ne l'est pas avec JavaScript.
🙀🔥😍

### Comparaison
**API JS**
Une complexité ++ dont on souhaiterai se passer pour des opérations telles que 'ma date est elle avant cette date ? Est-elle après ? Est-elle la même ?'

**Moment.js**
Je vous laisse juger par vous-même 😉 : [Doc moment.js sur les query](https://momentjs.com/docs/#/query/). 

🎉🎉🎉

**Comment by jbdesbas** [comment]
Moment.js offre des possibilités assez sympa pour afficher facilement des dates de façon "pretty" (ex : il y a deux jours, il y a 3 mois, etc..)

**Comment by Gaetanbrl** [comment]
@jbdesbas si vous avez des exemples de réalisation avec la librairie `moment.js`, n'hésitez-pas à les poster ici en commentaire. Cela pourra probablement donner des exemples à ceux qui peuvent en avoir besoin.
