### ISSUE TITLE
emplacement des flèches précédent et suivant

### ISSUE THREAD

**Issue by pbarille** [geobretagne/mviewer#288]
Bonjour,

J'affiche un template mustache dans un infopanel paramétré en bottom-panel et lorsque plusieurs objets sont présents à l'interrogation j'ai des flèches et un item 1/x qui apparait dans ma fiche, ce que je trouve très pratique.

Je m'interroge sur l'emplacement de ces flèches et de l'item 1/x.
Est-il possible de le paramétrer ?

Merci !

**Comment by Gaetanbrl** [comment]
Bonjour,

Dans le template, vous pouvez ajouter une règle CSS du type :

```
.carousel-control {
    height: 70% !important;
    top: 30% !important;
    color: rgba(52,152,219, 0.6) !important;
}
``` 
Ainsi, je modifie la couleur, le placement, etc...

**Comment by pbarille** [comment]
C'est parfait !
Merci beaucoup @Gaetanbrl
