### ISSUE TITLE
Déménagement de la documentation readthedoc

### ISSUE THREAD

**Issue by spelhate** [geobretagne/mviewer#289]
Je propose de déplacer les sources de la documentation depuis https://github.com/geobretagne/mviewer.doc.git vers https://github.com/geobretagne/mviewer.git dans un dossier appelé docs.
L'avantage sera de disposer d'un seul repo pour **mviewer** et la **doc** et on pourra gérer plus facilement les releases de doc.
Je pense pouvoir faire cette manipulation en conservant l'historique des commits sur la doc.

**Comment by spelhate** [comment]
https://mviewerdoc.readthedocs.io/fr/latest/ pointe actuellement sur la branche **develop** de mviewer.
Lors de la prochaine release, la doc pointera sur la branche **master**.

Pour les issues relatives à la doc, je propose de les préfixer par **[Documentation]**.
A noter que les issues en cours sur le dépôt **mviewer.doc** n'ont pas été transférées.

**Comment by Gaetanbrl** [comment]
ok @spelhate  ce fonctionnement convient pour ma part.

**Comment by spelhate** [comment]
@Gaetanbrl la PR relative au nouveau paramètre fuse n'a pas été mergée avant le transfert. Peux-tu la refaire stp. Il y avais 3 lignes de doc. Merci.

**Comment by Gaetanbrl** [comment]
C'est noté, 
Cet après-midi ou demain je pense ;)
