### ISSUE TITLE
Ability to highlight current feature with carrousel in infos results

### ISSUE THREAD

**Issue by jusabatier** [geobretagne/mviewer#29]
I think it can be useful to highlight the current feature displayed in the carrousel of the getFeatureInfo result.

Maybe possible by set an hidden field with the geom in the response html and use it in a "slide" event of the carrousel ?

**Comment by spelhate** [comment]
Yes it would be interesting.

**Comment by bchartier** [comment]
C'est peut-être compliqué de trouver l'info dans la réponse au GetCapabilities :
- ça va dépendre du format utilisé pour le GetFeatureInfo
- j'ai le sentiment que cela va dépendre du modèle de données interne du jeu de données (à vérifier dans la spec WMS et avec des jeux de données différents)
- je ne pense pas qu'il y ait une obligation pour les serveurs WMS de renseigner la géométrie dans le GetFeatureInfo.

Cela ne fonctionnera que pour les couches WMS. Pour les customlayers il faudrait faire autrement.

Bien sûr, ce n'est une opposition à l'idée. Ce sont juste des réflexions sur la difficulté à la mettre en œuvre.

**Comment by jusabatier** [comment]
Ce n'est pas au GetFeatureInfo de renvoyer cette info, mais au visualiseur de la créer avec le caroussel.

Par exemple avec un handler onchange sur la fonction next du caroussel qui appliquerait un style.
différent sur la feature affichée.
Logiquement si on récupère une feature via le caroussel, on a eventuellement sa géometrie, mais au moins son ID qui peut permettre de la retrouver.

**Comment by spelhate** [comment]
Je pense que c'est faisable assez facilement pour les couches de type vectoriel.
En revanche, pour les couches servies en WMS, il faudrait pouvoir récupérer et gérer la géométrie des entitées interrogées, ce qui n'est pas le cas actuellement dans mviewer.

**Comment by jusabatier** [comment]
En effet, j'avais omis les couches WMS.

Pour celles-ci : 
- Stocker les coordonnées interrogées (x,y)
- Récupérer la geometrie de la feature via un GetFeatureInfo avec le bon parametre de layer et un filtre CQL ou OGC adapté (id)

**Comment by Gaetanbrl** [comment]
Je ferme cette issue reportée sur la #315
