### ISSUE TITLE
[Documentation] Duplication README - Readsthedoc

### ISSUE THREAD

**Issue by Gaetanbrl** [geobretagne/mviewer#293]
Lorsqu'un paramètre est ajouté ou modifié, il faut saisir ce paramètre dans le README et dans la doc readsthedoc.

Je me demande, vu le nombre de paramètres s'il ne serait pas mieux de tout concentrer dans readsthedoc et de laisser le README pour la partie installation, note de version et autres détails plus technique ou accès développeur / administrateur (hors créateur de carte) ? 

Je pense notamment qu'il peut être intéressant d'essayer d'avoir des retours de nos utilisateurs sur leurs usages de la doc et le côté pratique / ergo lors de son utilisation ou de la recherche d'éléments.

Voilà, j'ouvre la discussion 😏 ...

**Comment by spelhate** [comment]
C'est fait.
