### ISSUE TITLE
Number of entity by layer in title for Infos result

### ISSUE THREAD

**Issue by jusabatier** [geobretagne/mviewer#30]
Actually, we can navigate over layers results by layers (clicking on the layer title we want to see),
but we have no ideas if there is results for this layer or not.

So I think it can be useful to add results count for each layers with his tisle in navigation.
And maybe show only those with results.

**Comment by bchartier** [comment]
I think this issue is outdated:
- the number of features for the current layer is displayed at the bottom of the carousel
- the info panel only displays a layer tab if this layer contains results

@jusabatier : do you agree or do we need to improve again this part of mviewer?

**Comment by jusabatier** [comment]
It's ok for me, I close the issue. Thanks
