### ISSUE TITLE
[Documentation] - Add legendmini param

### ISSUE THREAD

**Issue by Gaetanbrl** [geobretagne/mviewer#305]
Insert legendmini param - ref to [mviewer PR #231](https://github.com/geobretagne/mviewer/pull/231).

**Comment by Gaetanbrl** [comment]
@spelhate je ne sais plus ce que tu m'avais dit,
c'est à rajouter dans le readme + reads the doc ?

**Comment by spelhate** [comment]
Juste ici : https://github.com/geobretagne/mviewer/tree/develop/docs

**Comment by Gaetanbrl** [comment]
PR réalisée @spelhate
