### ISSUE TITLE
[Documentation] - [Fuse] Add  threshold param

### ISSUE THREAD

**Issue by Gaetanbrl** [geobretagne/mviewer#307]
Just add this new param according to 
https://fusejs.io/api/options.html#basic-options

**Comment by Gaetanbrl** [comment]
@spelhate je ne sais plus ce que tu m'avais dit, 
c'est à rajouter dans le readme + reads the doc ?

**Comment by spelhate** [comment]
Il n'y a plus de doc dans le README.md. Il faut donc juste documenter ce paramètre dans https://github.com/geobretagne/mviewer/tree/develop/docs

**Comment by Gaetanbrl** [comment]
PR réalisée @spelhate
