### ISSUE TITLE
Add lib moment js

### ISSUE THREAD

**Issue by Gaetanbrl** [geobretagne/mviewer#309]
J'avais réalisé une issue #285  en guise de "pour info" sur la lib moment js mais après utilisation diverse, je me demande si ce serait pas plus utile de l'intégrer directement dans Mviewer ? 

Qu'en pensez-vous ?

On pourrait aussi positionner cet lib via un addon mais ce ne serait pas plus utile directement dans le coeur ?

**Comment by spelhate** [comment]
Ok pour moi.

**Comment by Gaetanbrl** [comment]
Ok je fais la PR ;)

**Comment by Gaetanbrl** [comment]
[commit](https://github.com/geobretagne/mviewer/commit/612cb796a96d621c10f444ff90c55cc7c379bcd6) fait.
