### ISSUE TITLE
Proxy et GetCapabilities du service WMTS de osm.geopicardie.fr

### ISSUE THREAD

**Issue by bchartier** [geobretagne/mviewer#31]
En essayant de configurer comme fond de carte une couche du service WMTS de osm.geopicardie.fr (cf. http://osm.geopicardie.fr/mapproxy/demo/), je me suis rendu compte que le proxy utilisé par mviewer n'arrive pas à récupérer les capabilities du service.

Mon paramétrage :
```
		<baselayer
			type="WMTS"
			id="osm-geopic-bright-wmts"
			label="OSM - GéoPicardie bright WMTS"
			title="OpenStreetMap - fond GéoPicardie contrasté"
			maxscale="1000"
			thumbgallery="img/basemap/osm.png"
			url="http://osm.geopicardie.fr/mapproxy/service"
			layers="bright"
			format="image/png"
			visible="false"
			fromcapacity="true"
			matrixset="webmercator"
			attribution="Données : les contributeurs d'&lt;a href='http://www.openstreetmap.org/' target='_blank'&gt;OpenStreetMap &lt;/a&gt;,  &lt;a href='http://www.openstreetmap.org/copyright' target='_blank'>ODbL &lt;/a&gt;"
			/>
```

Le message d'erreur dans la console Python :

`GET http://localhost/proxy/?url=http%3A%2F%2Fosm.geopicardie.fr%2Fmapproxy%2Fservice&SERVICE=WMTS&VERSION=1.0.0&REQUEST=GetCapabilities 404 (Not Found)`

Les capabilities du service sont bien accessibles à l'URL suivante :

http://osm.geopicardie.fr/mapproxy/service?REQUEST=GetCapabilities&SERVICE=WMTS&VERSION=1.0.0

Je soupçonne que la requête envoyée au proxy est erronée.

**Comment by spelhate** [comment]
Il n'y a pas de proxy dans mviewer. Par contre il est possible d'utiliser celui de geOrchestra ou mieux de s'en passer en activant CORS (http://enable-cors.org/) sur ton serveur mapproxy.

**Comment by bchartier** [comment]
Effectivement, j'aurais pu regarder la tête de l'URL pour m'en rendre compte.
Merci pour ta réponse.
