### ISSUE TITLE
Recharger une couche geojson

### ISSUE THREAD

**Issue by eprouteau** [geobretagne/mviewer#311]
Bonjour, 

Je suis entrain tout doucement :) de mettre en place une cartographie participative pour mon groupe citoyen de dordogne. Pour cela je reprends l'exemple qui avait été posté : https://github.com/geobretagne/mviewer/issues/165. La couche de saisie est sur postgres postgis du coup je la rempli bien et la charge bien sur la carte. 

Par contre je n'arrive pas a trouver la méthode pour recharger la couche avec le nouvel élément après la saisie. 

Je voulais mettre le code suivant dans la fonction destroy du customcontrol : 

```
$.ajax('apps/archipel/data/data.php', function(data) {
    var features_poi = geojsonFormat.readFeatures(data, {
        featureProjection: "EPSG:3857"
    });
    console.log('reload-ajax')
    mviewer.customLayers.ma_couche.addFeatures(features_poi);
});
```

après 

`mviewer.customLayers.ma_couche.layer.getSource().clear();` 

mais rien ne se passe. Auriez vous du coup des pistes pour recharger la couche ?

Merci pour votre aide

**Comment by spelhate** [comment]
Ca a changé depuis la version 6 d'Openlayers.
Je crois qu'il faut faire en plus 
```
mviewer.customLayers.ma_couche.layer.getSource().refresh();
mviewer.customLayers.inventaire.layer.getSource().changed();
```

**Comment by eprouteau** [comment]
Avec `refresh()` ca fonctionne

Merci beaucoup

**Comment by Gaetanbrl** [comment]
@eprouteau nous pouvons fermer l'issue ?

**Comment by Gaetanbrl** [comment]
@eprouteau - Je clos cette issue qui semble résolue.
Merci de commenter et rouvrir au besoin.
