### ISSUE TITLE
[Search] - selection / clic style

### ISSUE THREAD

**Issue by Gaetanbrl** [geobretagne/mviewer#315]
### Détails

> Lors que l'on clique sur 1 objet (zoom > 50 000 par exemple) et que l'on zoom très proche de l'entité, les utilisateurs constatent que la "gommette" n'est pas sur le point sélectionné.

**1 - clic**
![image](https://user-images.githubusercontent.com/16317988/82336990-8838a780-99eb-11ea-954e-0e5af0a23886.png)

**2 - zoom**
![image](https://user-images.githubusercontent.com/16317988/82337032-94bd0000-99eb-11ea-87c3-1a2685184281.png)

### Proposition(s) :

* Mettre en surbrillance la / les entité(s) sélectionnée à la place d'une "gommette"

Qu'en pensez-vous ?

**Comment by spelhate** [comment]
Ca pourrait marcher avec toutes les couches interrogeables ?

**Comment by Gaetanbrl** [comment]
> Ca pourrait marcher avec toutes les couches interrogeables ?

C'est un point qui est à éclaircir, notamment pour les WMS. 

Avec une couche vide persistante, on peut rajouter des feautures à la volée selon la géométrie des features retournées sous le clic, et ce, peut importe la couche (voir selon event map clic).

On peut donc afficher dans une symbologie spécifique le résultat (cf. mapfishapp). Il faudra cependant utiliser une surbrillance et non une icône.pour toutes les features.

Une autre optique est d'utiliser l'onglet du template actif. Par défaut, seuls les features du premier onglet sont affichées. Si on change d'onglet, ce sont les features de cet onglet qui sont en surbrillance, etc...

**Comment by lecault** [comment]
C'est une vieille demande chez nous à la région. Après il faut bien sur que ce soit paramètrable.

Sinon je ne comprends pas la 2ème optique.

**Comment by Gaetanbrl** [comment]
Par "optique" j'entends approche / mode de visualisation complémentaire ou optionnel @lecault : 

### Scénario : 

1. L'utilisateur clic sur la carte
2. 3 features de 2 couches différentes -> Le template affiche 2 onglets (car 2 couches)
3. Par défaut le 1er  onglet de la couche A est ouvert, donc le 1er template
4. Sur la carte, seules les features sélectionnées par le clic qui correspondent à cette couche sont en surbrillance sur la carte
5. L'utilisateur clic sur le second onglet -> Le 2ème template de la couche B s'affiche
6. seules les features de la couche B sont en surbrillance -> ceux de la couche A sont en style "normal" comme si elle n'avaient pas étaient sélectionnées
7. L'utilisateur revient sur l'onglet 1 - couche A -> le template de la couche A s'affiche donc, et la surbrillance n'affiche plus que les features de la couche A sélectionnées par le clic

**Comment by lecault** [comment]
C'est bon pigé.
Le scénario 3 ressemble à mapfishapp :).

Dans ma logique, je pense qu'il faut tout afficher. Après le panel a différent mode d'affichage. Je pense à l'accordion qui ne semble plus dans la logique du scénario 2 alors que le mode onglet plus dans la logique 3.

Enfin je n'ai aucune idée de la difficulté de la mise en place comme dit Sébastien avec les flux pures WMS (pour GeoServer ça devrait le faire). 

Il me semble intéressant de travailler sur le scénario 2 pour le moment et voir si besoin d'une sélection de sélection.

**Comment by Gaetanbrl** [comment]
> Enfin je n'ai aucune idée de la difficulté de la mise en place comme dit Sébastien avec les flux pures WMS 

Si le WMS retourne la géométrie, aucun soucis on pourra refaire une entité type vecteur dans une couche vide pour mettre en surbrillance la géométrie de la sélection.

Mais je pense que des tests sont à réaliser pour confirmer ce fonctionnement.

**Comment by Gaetanbrl** [comment]
> Je pense à l'accordion qui ne semble plus dans la logique du scénario 2

L'accordion n'affiche qu'un template à la fois ? je ne vois pas la différence avec l'onglet si c'est le cas.

**Comment by Gaetanbrl** [comment]
Lié à l'issue #29

**Comment by tkohr** [comment]
Est-ce qu'il y a déjà du dév en cours pour ce ticket ?

**Comment by Gaetanbrl** [comment]
Non pas de travaux encore et rien de planifié...

**Comment by tkohr** [comment]
Ok, on va essayer de travailler sur une PR alors ;-)

**Comment by Gaetanbrl** [comment]
Elle fera des heureux 👍

**Comment by bchartier** [comment]
Désolé, j'ai tout suivi et je découvre le sujet...

>> Enfin je n'ai aucune idée de la difficulté de la mise en place comme dit Sébastien avec les flux pures WMS
>
> Si le WMS retourne la géométrie, aucun soucis on pourra refaire une entité type vecteur dans une couche vide pour mettre en surbrillance la géométrie de la sélection.
>
> Mais je pense que des tests sont à réaliser pour confirmer ce fonctionnement.

Ma crainte c'est que cela ne fonctionne que pour les WMS.

Même pour des WMS, je ne suis pas sûr que la réponse du serveur soit bien normalisées. En général, les outFormat des standards de l'OGC sont peu contraints. Faudrait voir si on ne risque pas d'avoir des différences de comportement entre une couche qui vient d'un GeoServer, une autre d'un MapServer et encore autre chose quand c'est du QGIS Server.

Pour des trucs non WMS, genre des customlayers, il faut s'attendre à quoi comme comportement ?

-> j'ai l'impression qu'on n'évitera pas des tests ou au moins de bien réfléchir à ce que l'on fait.

**Comment by tkohr** [comment]
Effectivement il faudra vérifier de bien gérer tous les cas.

* Couches vecteurs (geojson|kml|csv) : Si je vois bien elles devraient être le plus simples à mettre en surbrillance, car on a déjà des features.
* WMS : En effet la spec 1.3.0 dit "The nature of the response is at the discretion of the service provider" concernant getfeatureinfo. Je ne suis pas sûr s'il y a vraiment beaucoup de WMS qui réponds sans géométrie, à vérifier.
* customlayer : Si c'est une couche vecteur, pas de problème, sinon bonne question

Est-ce qu'il serait acceptable de garder le pin comme une fallback pour les rares cas WMS et customlayer qui n'ont pas de géométrie ?

**Comment by tkohr** [comment]
Dans le code (https://github.com/geobretagne/mviewer/blob/master/js/mviewer.js#L456) j'ai vu qu'il existe déjà une couche/source de surbrillance qui est :
* vidée dans zoomToLocation (pour la recherche), mais n'y est pas utilisée (si je vois bien)
* utilisée sur le hover des couches vecteurs (polyline, polygon), mais n'a pas l'air de fonctionner sur tous et reste souvent bloquée sur le dernier élément où la souris est passée

Je propose d'utilisé cette couche pour la surbrillance du getfeatureinfo et enlever la surbrillance sur le hover. Ça me semble plus intuitive.

**Comment by Gaetanbrl** [comment]
> utilisée sur le hover des couches vecteurs (polyline, polygon), mais n'a pas l'air de fonctionner sur tous et reste souvent bloquée sur le dernier élément où la souris est passée

Étrange, on a récemment réalisé des modifications sur la surbrillance + hover et nous n'avons pas constaté de problème.

Je vais regarder la démo vector.xml pour s'en assurer...

**Comment by Gaetanbrl** [comment]
@tkohr peux-tu me donner les étapes de test qui permettent de voir que le hover reste bloqué sur le dernier élément ?

**Comment by Gaetanbrl** [comment]
> vidée dans zoomToLocation (pour la recherche), mais n'y est pas utilisée (si je vois bien)

En effet, la couche est vidée dans cette méthode, elle est également utilisé pour des contrôle if/else mais je ne vois pas quand est-ce qu'elle est utilisée pour contenir des features.

@spelhate c'est du code qui devait être / a été utilisé pour une fonctionnalité spécifique ?

**Comment by tkohr** [comment]
> @tkohr peux-tu me donner les étapes de test qui permettent de voir que le hover reste bloqué sur le dernier élément ?

@Gaetanbrl je constate le problème sur la couche "Intercommunalité" de la `default.xml` sur les branches `master` et `develop`. 

Je viens de comprendre aussi qu'il faut mettre `tooltipenabled="true"` si on veut que la surbrillance fonctionne (sur la couche du même type "Commune" par exemple). Niveau utilisateur ça fait du sens à mon avis, mais niveau config c'est pas très clair avec le paramètre `nohighlight` en plus. Je vais voir pour compléter la doc.

Sur l’exemple `vector.xml` je ne vois pas de surbrillance.

Je me demande s'il vaut mieux
* enlever la surbrillance du hover si on met une surbrillance pour le getfeatureinfo
* utiliser la mème couche/source pour les deux
* prévoir deux couches/sources indépendantes

**Comment by Gaetanbrl** [comment]
> tooltipenabled: Précise la couche prioritaire pour l’affichage des infobulles.

C'est vrai que ca peut être un peu plus clair.

> nohighlight : Booléen précisant, pour les couches de type vecteur (customlayer, geojson ou csv), si la mise en surbrillance est désactivée

La définition me semble assez clair par contre pour la surbrillance.

> Niveau utilisateur ça fait du sens

C'est ce qui est souhaité en priorité.

> Je me demande s'il vaut mieux...

Je pense qu'il faut pouvoir avoir les deux. Imaginons que l'on soit sur une carte de de "localisation" en mode consultation :

1. Je cherche
2. Affichage des résultats avec mise en évidence des résultats
3. Je consulte les résultats
4. "Quelle est cette entité juste à côté qui n'est pas sélectionnée ?" - L'utilisateur ne veut pas masquer le résultat de sa recherche, il veut une information complémentaire
5. Je passe ma souris dessus pour avoir la réponse sans masquer mon résultat et mettre en évidence (dans une autre symbologie) la feature que je survole

Dans le cas d'une couche à forte densité (features très proche donc), la surbrillance au survol peut être très utile pour bien voir ce que la souris survol. Dans le cas de section linéaire également.

**Comment by spelhate** [comment]
> > utilisée sur le hover des couches vecteurs (polyline, polygon), mais n'a pas l'air de fonctionner sur tous et reste souvent bloquée sur le dernier élément où la souris est passée
> 
> Étrange, on a récemment réalisé des modifications sur la surbrillance + hover et nous n'avons pas constaté de problème.
> 
> Je vais regarder la démo vector.xml pour s'en assurer...

Il me semble que lorsque le paramètre **tooltip** n'est pas défini à true, il n'y a pas de surbrillance. Mais c'est à vérifier.

**Comment by spelhate** [comment]
> > vidée dans zoomToLocation (pour la recherche), mais n'y est pas utilisée (si je vois bien)
> 
> En effet, la couche est vidée dans cette méthode, elle est également utilisé pour des contrôle if/else mais je ne vois pas quand est-ce qu'elle est utilisée pour contenir des features.
> 
> @spelhate c'est du code qui devait être / a été utilisé pour une fonctionnalité spécifique ?

`mviewer.getSourceOverlay() `est une méthode publique qui permet d'agir sur la couche des features mises en surbrillance.
C'est utilisé dans search.js et info.js

**Comment by Gaetanbrl** [comment]
@tkohr du coup ca peut être intéressant de réutiliser cette layer et la méthode getSourceOverlay (+ custom si besoin) comme le précise @spelhate

**Comment by tkohr** [comment]
Pour l'instant je suis parti sur une nouvelle couche/source pour rester indépendant du `hover` et permettre les deux en même temps. J'ai mis un premier jet pour l'outil info en draft https://github.com/geobretagne/mviewer/pull/348 (qui ne prend pas encore en compte la recherche).

**Comment by Gaetanbrl** [comment]
> pour rester indépendant du hover et permettre les deux en même temps.

Ok ca peut être plus propre.

Et en y repensant, je pense que ce n'est pas incompatible car le hover va créer un overlay au dessus de la couche je crois. Donc même si tu avais conservé la même couche, l'event aurait pu gérer le hover et le style des features sélectionnées.

On va déjà tester ta PR et on verra à l'usage.

Merci @tkohr ;)

**Comment by Gaetanbrl** [comment]
Thanks @tkohr i close ! ;)
