### ISSUE TITLE
[Search] - Config geopin style

### ISSUE THREAD

**Issue by Gaetanbrl** [geobretagne/mviewer#316]
### Détails

> Certains symboles sont proches du symbole qui affiche l'endroit cliqué, les utilisateurs sont confus.

![image](https://user-images.githubusercontent.com/16317988/82337861-86bbaf00-99ec-11ea-82ab-bd658db10d61.png)

### Proposition(s) :

* Rendre paramétrable l'icône de sélection des features

Qu'en pensez-vous ?

**Comment by Gaetanbrl** [comment]
link #315

**Comment by spelhate** [comment]
Je suis d'accord. Actuellement, il est juste possible de changer la couleur de cette icone mais pas sa forme.

**Comment by lecault** [comment]
+1

**Comment by Gaetanbrl** [comment]
Travaux en cours sur branche feature-316.

**Comment by Gaetanbrl** [comment]
- [x] Remplacer l'identifiant "els_marker" par "mv_marker" >> voir `"TODO"`

- [x] Possibilité d'utiliser un PNG à la place du svg >> paramètre `imgurl`

- [x] Changer la couleur du SVG via la config >> paramètre `svgcolor`

- [x] Changer la taille de l'image si PNG >> paramètre `imgwidth`

- [ ] Documentation

**Comment by spelhate** [comment]
Ok. Il faudra également mettre à jour la doc ici : https://mviewerdoc.readthedocs.io/fr/latest/doc_tech/config_map.html?highlight=els_marker#configurer-les-options-de-la-carte
![image](https://user-images.githubusercontent.com/1793792/82988342-4914e280-9ff9-11ea-81f8-c28f43074e21.png)

Si je comprends bien le paramètre svgcolor fait la même chose que la propriété css ci-dessus ?

**Comment by Gaetanbrl** [comment]
> Si je comprends bien le paramètre svgcolor fait la même chose que la propriété css ci-dessus ?

Exactement. Mais un paramètre dans le config.xml me semble plus accessible pour les utilisateurs.

**Comment by spelhate** [comment]
Ok.
