### ISSUE TITLE
Nouvelle couche WMS invisible

### ISSUE THREAD

**Issue by gpetit** [geobretagne/mviewer#317]
Bonjour à toute l'équipe et bravo pour votre travail.

### Contexte

Nous souhaitons faire évoluer notre site http://mapuce.orbisgis.org qui tourne (très bien) sur une ancienne version de MViewer (voir https://github.com/orbisgis/mapuce.orbisgis.org/tree/gh-pages).
Ayant d'autres projets de recherche à valoriser nous partirions sur l'idée d'avoir une instance de la dernière version 3.2 et autant d'apps que de projets (pour l'instant 3).

J'ai fais mon installation de travail en local sur machine Ubuntu 19.10. (dans ce dossier `/usr/local/tomcat9/webapps/mviewer-3.2/`)

Pour initier le travail, j'ai crée une app nommée Paendora -> `/mviewer-3.2/apps/paendora.xml`. Elle démarre sans problème à l'adresse suivante : `http://localhost:8080/mviewer-3.2/?config=apps/paendora.xml#`

### Problème

Je rencontre un soucis, qui est très probablement trivial, mais que je n'arrive pas à résoudre.

Pour tester, j'ai voulu intégrer des couches WMS venant de http://mapuce.orbisgis.org dans mon app (par exemple la densité de bâti (voir [fichier de conf](https://github.com/orbisgis/mapuce.orbisgis.org/blob/gh-pages/config.xml#L74)))
Je passe donc de cette ancienne version (sur le site Mapuce)

```xml
<layer id="mapuce:usr_indicators_metropole_geom_3857" 
 name="% de surface de bâtiments"  visible="false" 
 style="usr_build_dens" tiled="true"
 url="https://geoclimate.orbisgis.org/geoserver/mapuce/wms"
 metadata=""
 metadata-csw="" />  
```

A celle-ci
```xml
<layer id="mapuce:usr_indicators_metropole_geom_3857" 
 name="% de surface de bâtiments"  visible="false" tiled="true"
 style="usr_build_dens" 
 url="https://geoclimate.orbisgis.org/geoserver/mapuce/wms">
</layer>
```
Il ne semble donc pas y avoir de réelles différences.

Lorsque je rafraîchi MViewer, la couche apparaît bien dans le menu déroulant. De même la légende apparaît bien ... mais je ne vois rien dans la carte.

![image](https://user-images.githubusercontent.com/1871248/82422510-d6e55080-9a82-11ea-8da9-299da914818e.png)
 
J'ai essayé d'intégrer d'autres couches WMS venant de services tiers (comme [Geobretagne](https://cms.geobretagne.fr/services)) et ça fonctionne. Donc je dois passer à côté de quelque chose ... Peut-être que la v3.2 intègre une subtilité que je n'ai pas saisie ?

Merci d'avance pour votre aide
Gwendall

**Comment by spelhate** [comment]
Bonjour Gwendall.

Tu rencontres un problème de **crossorigin**.
 Ton application est sur http://localhost:8080/ alors que ton service WMS est sur https://geoclimate.orbisgis.org. La commuication entre les deux est donc bridée par le navigateur.

3 solutions possibles:
 

- Installer geoserver et mviewer sur le même domaine (serveur)
-  Utiliser un proxy Ajax
- Activer CORS sur Geoserver. C'est ce qui est pratiqué sur GéoBretagne.

**Comment by gpetit** [comment]
Merci Stéphane pour ton retour rapide. Je n'aurais pas trouvé seul !
Nous avons activé CORS sur notre Geoserver (en suivant [ces instructions](https://docs.geoserver.org/latest/en/user/production/container.html#enable-cors) si ça intéresse quelqu'un) et ça fonctionne.
