### ISSUE TITLE
docker images - uniquement sur release ou master

### ISSUE THREAD

**Issue by fvanderbiest** [geobretagne/mviewer#320]
Il faudrait builder des images docker uniquement pour les releases, sinon on va remplir les disques de docker hub ! Actuellement chaque PR génère une image. Je ne pense pas que ce soit utile.

**Comment by spelhate** [comment]
Il me semblait que l'image docker se faisait à partir de master ?

**Comment by spelhate** [comment]
Effectivement, il y a un build pour chaque commit de toutes les branches. @fvanderbiest je ne ais pas comment cibler uniquement master dans hub.docker.com. Merci.

**Comment by spelhate** [comment]
![image](https://user-images.githubusercontent.com/1793792/82986697-98a5df00-9ff6-11ea-909f-312e512261de.png)

**Comment by pmauduit** [comment]
@spelhate il me semble que coté docker-hub, c'est à la création du dépot qu'on choisit s'il s'agit d'un "automated build" ou non, et ce n'est pas le cas pour mviewer. En revanche ce sont les github actions qui poussent une image sur docker-hub:
https://github.com/geobretagne/mviewer/blob/master/.github/workflows/docker-build.yaml#L35-L38

Donc on devrait avoir la main la dessus et limiter la CI aux éléments qui nous intéressent (branches, tag, ...).
