### ISSUE TITLE
[demo] - profile en long

### ISSUE THREAD

**Issue by Gaetanbrl** [geobretagne/mviewer#321]
La démo n'est plus fonctionnelle, il y a une erreur lors de la requête vers le geoserver (vers le wps j'imagine) : 

`Failed to load resource: the server responded with a status of 502 (Bad Gateway)
`

Requête correspondante  :

`https://kartenn.region-bretagne.fr/proxy/?url=https://geobretagne.fr/wps/mnt`

**Comment by spelhate** [comment]
Le service n'a pas été installé sur la nouvelle plateforme geobretagne. Il faut que je m'en occupe.

**Comment by Gaetanbrl** [comment]
Fixé par @spelhate merci :)
