### ISSUE TITLE
Pan dans la carte après une identification d'objet

### ISSUE THREAD

**Issue by frgis** [geobretagne/mviewer#326]
Bonjour,

je suis entrain de tester Mviewer. Tout d'abord je trouve que c'est un applicatif intéressant, facile à déployer, portable, bravo !

J'ai mis en place un exemple pour voir ce que je pouvais arriver à faire. Il y a un comportement dans l'outil, c'est peut-etre lié à mon paramétrage mais je trouve ça gênant et surtout avec un smartphone, je m'explique :

- Ma carte est configurée avec seulement un baselayer (WMTS) et une couche WMS (avec getfeatureinfo paramétré + template de consultation mustache avec juste trois ou quatre attributs, c'est du basique :-) ).
- Lorsque je démarre l'application je déplace la carte et je zoom/recule sans problème.
- Par contre lorsque j'identifie un objet en cliquant dessus (ordinateur ou smartphone), j'affiche la popup pas de problème. Je ferme la popup et si je veux déplacer la carte je n'y arrive pas.
Pour déplacer il faut cliquer n'importe où dans la carte (comme si c'était nécessaire pour sortir du mode popup) et ce n'est qu'après que je peux déplacer la carte.

Sous smartphone c'est encore plus gênant il faut taper sur l'écran de la même façon dans une zone vide et après on reprend le contrôle pour zoomer/dézoomer.

J'avoue que j'ai hésité à le déclarer car j'ai un doute de savoir si ça vient de mon paramétrage.

Est-ce que quelqu'un a déjà rencontré ce comportement ? Est-ce que ça peut être lié au paramètre TOLERANCE que j'ai ajouté dans le Layer du mapfile (pour le GetFetaureinfo sous Mapserver 7) ?
Ou bien est-ce que cela peut être une anomalie selon comment on configure le template ou bien le type de menuaccordion (je veux dire la façon dont le résultat de GetFeatureInfo s'affiche) ?

Merci.

**Comment by Gaetanbrl** [comment]
Bonjour @frgis,

Quelle est la branche que vous avez utilisé ?

Un comportement très proche de votre description a été corrigé dernièrement sur le code de la branche develop (voir l'issue #276). La prochaine release permettra de profiter de cette correction sur la branche master si c'est bien du même problème qu'il s’agit.
