### ISSUE TITLE
accès restreint mviewer

### ISSUE THREAD

**Issue by fxduponcheel** [geobretagne/mviewer#328]
Bonjour
A t il déjà été évoqué l'idée de pouvoir restreindre l'accès d'un mviewer ? 
Accès conditionné par un login et un mot de passe ?
Merci pour vos réponses
A bientôt

**Comment by Gaetanbrl** [comment]
Où seront / sont stockés vos login / mdp ?

**Comment by fxduponcheel** [comment]
Sur le même serveur qui héberge le mviewer ?!?

**Comment by Gaetanbrl** [comment]
> Sur le même serveur qui héberge le mviewer ?!?

Vous pouvez regarder le fonctionnement l'authentification "basique" (ou basic authent) disponibles sur les serveurs web type Apache2.

Vous auriez pu avoir besoin de connecter un annuaire type LDAP à votre Mviewer ou souhaiter le connecter à un système d'authentification centralisé comme cela peut se faire avec une instance type  GeOrchestra...

**Comment by fxduponcheel** [comment]
Merci pour ces pistes ...

**Comment by fxduponcheel** [comment]
J'en conclus que ce n'est pas quelque chose qui peut être implémenter nativement dans mviewer.

**Comment by Gaetanbrl** [comment]
Le Mviewer ne contient aucune logique Backend. C'est une application à déposer dans votre serveur web.

Si vous créez un site internet et que vous le déposez sur votre serveur web, il nécessitera d'ajouter un composant ou une configuration supplémentaire sur votre environnement de publication pour protéger votre site web.
Si ce site nécessite un login / mdp , il vous faudra de toute façon une logique serveur pour le stockage des informations authentification, ce que ne fait pas une application sur un serveur web classique.

**Comment by spelhate** [comment]
Rien à ajouter. merci @Gaetanbrl  pour les explications.

**Comment by fxduponcheel** [comment]
Merci beaucoup pour la réponse.
