### ISSUE TITLE
Hide/Show legend

### ISSUE THREAD

**Issue by Ailurupoda** [geobretagne/mviewer#329]
Bonjour,
Je souhaiterais savoir s'il est possible de cacher la légende d'une couche ou de la faire apparaitre à l'aide d'un bouton ?
Actuellement, lorsque la couche est active sur la carte, le panneau de légende affiche automatiquement le style de la couche. Il est possible de cacher les autres paramètres tel que l'opacité, mais je souhaiterais également que l'image de légende soit caché ou affiché par un click utilisateur.

Est-ce une fonctionnalité déjà existance que j'aurais loupé ?

Je vous remercie

**Comment by Gaetanbrl** [comment]
Est-ce que vous avez essayé le paramètre `expanded `dans la configuration de votre couche ? 

Je ne sais plus si ce paramètre masque également le style ou uniquement les actions (opacités, etc...).

Le paramètre est présenté [ici](https://mviewerdoc.readthedocs.io/fr/latest/doc_tech/config_layers.html?highlight=expanded#parametres-pour-gerer-l-affichage-de-la-couche).

**Comment by Ailurupoda** [comment]
Oui, justement je l'utilise pour certaines couche dont je ne veux pas montrer l'ensemble des actions.
Mais cela ne masque pas la légende, seulement les actions.
L'idéal serait que ce bouton fasse une action en 2 temps : 
 - Afficher la légende et les action
 - Masquer les action
 - Masquer la légende

**Comment by Gaetanbrl** [comment]
Si je comprend bien vous avez besoin d'un "bouton" qui permette de masquer la totalité du panneau de la couche ou le présenter dans l'état (fonctionnement classique avec expanded). C'est cela ?

**Comment by Ailurupoda** [comment]
J'ai réussis à m'en sortir en ajoutant les paramètres suivant : 

First : Ajouter un nouveau bouton dans le template qui appelera une fonction toggle :
https://github.com/geobretagne/mviewer/blob/70fcf195820ab3ba3f2f3df0085d6574a22d0464/js/templates.js#L70

```
        '<a href="#" aria-label="dLegend" onclick="mviewer.toggleLayerLegend(this);" title="Legend" i18n="theme.layers.options" class="icon-options" style="margin-left:230px; position:absolute">',
            '<span class="state-icon-legend glyphicon glyphicon-chevron-down"></span>',

```

Second : Ajouter la fonction toggleLayerLegend
https://github.com/geobretagne/mviewer/blob/70fcf195820ab3ba3f2f3df0085d6574a22d0464/js/mviewer.js#L2430-L2439

```
toggleLayerLegend: function (el) {
            $(el).closest("li").find(".layerdisplay-legend").slideToggle();
            $(el).closest("li").find(".layerdisplay-legend").slider('relayout');
            if ($(el).find("span.state-icon-legend").hasClass("glyphicon glyphicon-chevron-down")) {
                $(el).find("span.state-icon-legend").removeClass("glyphicon glyphicon-chevron-down").addClass("glyphicon glyphicon-chevron-up");
            } else {
                $(el).find("span.state-icon-legend").removeClass("glyphicon glyphicon-chevron-up").addClass("glyphicon glyphicon-chevron-down");
            }
        },
```
Third : Ajouter un nouveau paramètre pour montrer/cacher la légende au démarage
https://github.com/geobretagne/mviewer/blob/70fcf195820ab3ba3f2f3df0085d6574a22d0464/js/configuration.js#L566

```
oLayer.legendDisp =  (layer.legendDisp === "true") ? true : false;
```

Last : Ajouter l'activation de la fonction toggleLayerLegend selon le paramètre
https://github.com/geobretagne/mviewer/blob/70fcf195820ab3ba3f2f3df0085d6574a22d0464/js/mviewer.js#L2342-L2344
```
            if (layer.legendDisp) {
                this.toggleLayerLegend($('.mv-layer-details[data-layerid="'+layer.layerid+'"]')[0]);
            }
```

De ce fait, en ajoutant dans le config un paramètre `legendDisp="true" `
On affiche la légende au démarrage et on a la possibilité de la cacher à tout moment à l'aide du bouton.
Par défaut le paramètres est à "faux"

**Comment by spelhate** [comment]
> Si je comprend bien vous avez besoin d'un "bouton" qui permette de masquer la totalité du panneau de la couche ou le présenter dans l'état (fonctionnement classique avec expanded). C'est cela ?
Savez vous qu'il est également possible de masquer et de réafficher la légende à tout moment en cliquant sur le bouton entouré en noir ?
![image](https://user-images.githubusercontent.com/1793792/83940417-3a41e300-a7e4-11ea-9649-8f41f8dba077.png)

**Comment by Ailurupoda** [comment]
Oui, j'ai bien connaissance de ce bouton. Mais celui-ci montre/cache le panneau de l'égende entièrement pour toutes les couches.
L'idée du bouton est de pouvoir montrer ou cacher l'image de la légende selon l'envie et les couches, tout en ayant la totalité des couches visibles à l'écran dans le panneau visible.

**Comment by spelhate** [comment]
Ok. Je comprends mieux. Merci.
