### ISSUE TITLE
Filtre attributaire - via menu déroulant

### ISSUE THREAD

**Issue by a19ferna** [geobretagne/mviewer#330]
![mviewer écoles images](https://user-images.githubusercontent.com/66411846/83733789-5875da80-a64e-11ea-9007-d84ee2acffaf.jpg)
Bonjour, 
Etudiants et débutants en HTML, nous n'arrivons pas à créer un menu déroulant pour notre mviewer, pourriez-vous nous aider si vous l'avez déjà codé ?
Ci-joint le modèle du résultat attendu.

Merci.

**Comment by Gaetanbrl** [comment]
Bonjour @a19ferna,

pouvez-vous détailler ce que vous souhaitez avoir comme comportement / fonctionnalité avec cette liste déroulante ? (filtrer, les attributs, changer le style... ?

**Comment by Gaetanbrl** [comment]
@a19ferna pour vos prochaines issues, pensez à détailler votre problème en respectant par exemple ce type de structure : 

1. Ce que je souhaite faire, ce que je souhaite reproduire
2. Le problème que je rencontre
3. Le détail pour reproduire mon problème

Cela nous permettra d'avoir des détails et de vous fournir une meilleure aide.

**Comment by a19ferna** [comment]
Bonjour, 

Sur mon mviewer doit s'afficher l'ensemble des écoles de Bretagne sous forme de curseurs et l'utilisateur doit pouvoir en sélectionner une non pas sur la carte mais à l'aide d'un menu déroulant, 
Comme la liste d'écoles est longue, je ne peux donc pas tout afficher dans un menu déroulant (cela prendrait trop de place), 
Je souhaite donc créer plusieurs menus déroulants relatifs aux écoles qui filtreraient celles-ci :
1) tout d'abord un menu déroulant contenant les 4 départements de Bretagne dans lequel l'utilisateur sélectionnerait le département dans lequel son école se trouve
2) un deuxième menu déroulant contenant toutes les communes du département choisi précédemment dans lequel l'utilisateur sélectionnerait la commune dans laquelle son école se trouve
3) puis le dernier menu déroulant dans lequel l'utilisateur choisit son école parmi un ensemble d'écoles qui ont vérifié les filtres des menus déroulants précédents

Merci.

----- Mail original -----
De: "Gaetanbrl" <notifications@github.com>
À: "geobretagne/mviewer" <mviewer@noreply.github.com>
Cc: "Agathe FERNANDES MACHADO" <agathe.fernandes-machado@imt-atlantique.net>, "Mention" <mention@noreply.github.com>
Envoyé: Jeudi 4 Juin 2020 12:25:32
Objet: Re: [geobretagne/mviewer] création menu déroulant (#330)

Bonjour @a19ferna,



pouvez-vous détailler ce que vous souhaitez avoir comme comportement / fonctionnalité avec cette liste déroulante ? (filtrer, les attributs, changer le style... ?

**Comment by Gaetanbrl** [comment]
Donc vous souhaitez un filtre attributaire en cascade.

Vous pouvez récupérer et essayer ce plugin : 
https://github.com/jdev-org/donneesplages/tree/master/addons/filter

Autrement, vous pouvez réaliser un customcontrol pour créér des liste déroulantes et gérer les données dans la couche (customlayers conseillé).µ

Je vous laisse dans un premier temps vous rapprocher des exemples et de la documentation pour l'utilisation des customcontrols, plugin, customlayers.

N'hésitez-pas si vous avez des difficultés.

**Comment by Gaetanbrl** [comment]
@MarieJag cette issue est-elle à fermer ?

**Comment by MarieJag** [comment]
Bonjour, oui on peut fermer.
Pour info on finalise ce mviewer, on partagera les résultats,
Merci,
marie

**Comment by Gaetanbrl** [comment]
@MarieJag Merci pour votre retour.
