### ISSUE TITLE
associer clic et zoom

### ISSUE THREAD

**Issue by a19ferna** [geobretagne/mviewer#331]
Bonjour,

Pour notre mviewer, nous aimerions réussir à zoomer sur un endroit précis lorsqu'on clique sur un curseur de la carte Bretagne, l'auriez-vous déjà fait ?

Merci.

**Comment by Gaetanbrl** [comment]
Il existe une méthode (fonction JavaScript) qui est détaillée dans la documentation qui s'appelle `zoomToLocation`.

Vous pouvez y accéder [ici](https://mviewerdoc.readthedocs.io/fr/latest/doc_dev/public_fonctions.html?highlight=zoomto#zoomToLocation).

A quoi correspond votre curseur ? (bouton, lien, ... ? )

Dans tous les cas, vous pouvez regardez ce que réalise un évènement type onclick et y ajouter une fonction (qu'on appel un callback) qui sera exécutée au click sur un élément.

Pour plus d'informations sur l'event onclick vous pouvez regarder [ici](https://www.w3schools.com/jsref/event_onclick.asp).

Cette fonction sera donc la méthode zoomToLocation.

Voici un exemple avec un lien :

```
<a href="#"
  onclick="mviewer.zoomToLocation(
      coordinates[0], // X en 3857
      coordinates[1], // Y en3857
      10, // à remplacer par votre niveau de zoom
      false
  );
</a>
```

**Comment by spelhate** [comment]
> Bonjour,
> 
> Pour notre mviewer, nous aimerions réussir à zoomer sur un endroit précis lorsqu'on clique sur un curseur de la carte Bretagne, l'auriez-vous déjà fait ?
> 
> Merci.

Avez-vous un exemple en tête qui pourrait nous inspirer ?

**Comment by Augustin59** [comment]
Bonjour,

Je me permets de rebondir sur la question d'Agathe car nous travaillons ensemble.
Notre objectif est de zoomer à un endroit précis sur la carte lorsque l'on clique sur un élément d'un layer :   

![mviewer écoles vigisat](https://user-images.githubusercontent.com/66685179/84161640-c3b91580-aa6f-11ea-90de-6749737c7336.jpg)

J'ai essayé d'utiliser zoomToLocation dans la config de notre mviwewer cependant je ne vois pas où insérer la commande `<element onclick="myscript/>` dans l'arborescence du code, est-ce dans un thème ou un groupe...

Enfin dans l'exemple ci-dessous, si l'on veut appliquer zoomToLocation à un layer doit-on remplacer a par l'id ou le nom du layer ?

`a href="#"
  onclick="mviewer.zoomToLocation(
      coordinates[0], // X en 3857
      coordinates[1], // Y en3857
      10, // à remplacer par votre niveau de zoom
      false
  );
</a>`

**Comment by Gaetanbrl** [comment]
Bonjour @Augustin59 , vous essayez de placer un customcontrol dans le volet de gestion des couches (voir / rendre invisibles).

Les customcontrols vont se positionner automatiquement dans la légende, sous la couche concernée.

Pour ajouter un élément n'importe où dans le Mviewer, vous devez passer par un plugin Mviewer.

Aussi, zoomToLocation ne s'applique pas à un layer mais va réaliser un zoom sur une position XY et pour un niveau de zoom donné. C'est une fonction javascript classique.

Cette méthode déclenche 2 méthodes openlayers : setZoom et setCenter.
Je vous laisse vous rapprocher de la documentation openLayers pour l'objet "view" d'une carte : 
https://openlayers.org/en/latest/apidoc/module-ol_View-View.html

**Comment by Gaetanbrl** [comment]
je clos cette issue.
@Augustin59 ou @a19ferna n'hésitez pas à commenter si c'est une erreur de clore cette issue.
Merci.
