### ISSUE TITLE
Importer CSV avec coordonnées

### ISSUE THREAD

**Issue by tkohr** [geobretagne/mviewer#332]
Actuellement mviewer permet d'importer des fichiers CSV qui contiennent une adresse et de les afficher sur la carte grâce à un geocoding distant.

Il serait intéressant d'éteindre l'outil existant de permettre l'import des fichiers CSV qui déjà contiennent des coordonnées (n'importe le SCR/projection). Pour ce cas une configuration des projections supportées par l'outil me parait utile.

**Comment by spelhate** [comment]
Oui c'est une bonne idée.

**Comment by spelhate** [comment]
Merci pour l'évolution @tkohr
