### ISSUE TITLE
kartenn kartoviz dead link

### ISSUE THREAD

**Issue by Gaetanbrl** [geobretagne/mviewer#337]
Le lien du readme est mort : 

https://kartenn.region-bretagne.fr/kartoviz/

Vous avez un autre lien @spelhate ?

**Comment by spelhate** [comment]
https://kartenn.region-bretagne.fr/kartoviz/demo/

**Comment by Gaetanbrl** [comment]
C'est le lien de la phrase suivante qui est concerné (non les démo je pense)

`Visualiseur géographique Kartenn basé sur OpenLayers 6.3.1 et Bootstrap 3.3.6`

**Comment by spelhate** [comment]
Ok. Je propose cette nouvelle URL : https://kartenn.region-bretagne.fr/demo/ à la place

**Comment by Gaetanbrl** [comment]
ca marche j'essai de faire la modif rapidement ;)
