### ISSUE TITLE
useless attributelabel param from i18n

### ISSUE THREAD

**Issue by Gaetanbrl** [geobretagne/mviewer#339]
### Problème rencontré

Lorsque je défini le paramètre `attributelabel`, le filtre conserve le label "Filtrer".

`attributelabel="Echelle"`

**Retourne :** 

![image](https://user-images.githubusercontent.com/16317988/84910263-f473fd00-b0b6-11ea-8a0e-45b16eaa64de.png)

### Cause

i18n écrase le contenu du rendu Mustache et remplace le contenu du label par la valeur prévue par la traduction : `Filtrer`.

### Analyse
**1. En pas à pas, on inspecte que le paramètre est bien pris en compte**
https://github.com/geobretagne/mviewer/blob/32e51e1471b3dfa1597303f3955584b48416d1ed/js/mviewer.js#L2090

Ici rien à redire tout va bien.

**2. On consulte le résultat du rendu Mustache**
https://github.com/geobretagne/mviewer/blob/32e51e1471b3dfa1597303f3955584b48416d1ed/js/mviewer.js#L2111

Ici rien à redire tout va bien.

**3. On regarde le résultat une fois le Mviewer chargé**

![image](https://user-images.githubusercontent.com/16317988/84910263-f473fd00-b0b6-11ea-8a0e-45b16eaa64de.png)

KO : Ce n'est pas le paramètre qui est affiché.

### Résolution

1. Supprimer l'attribut i18n sur cet élément si le paramètre est renseigné.

**Comment by spelhate** [comment]
@Gaetanbrl  Expertise mviewer niveau 3 atteint ;-)

**Comment by Gaetanbrl** [comment]
Issue non reproduite avec les démo Mviewer (exclusivelayer.xml).
J'ai passé la couche de ce Mviewer dans mon fichier de config et je reproduis l'issue.

J'ai supprimé les paramètres i18n de la config du Mviewer et je ne reproduis pas.

Cela confirme que l'activation de la traduction avec l'ajout des paramètres relatifs à i18n provoquent ce problème.

Par contre, la traduction est forcée même en supprimant l'attribut i18n du label après rendu mustache :

https://github.com/geobretagne/mviewer/blob/32e51e1471b3dfa1597303f3955584b48416d1ed/js/mviewer.js#L2111

**Comment by Gaetanbrl** [comment]
# Synthèse
Si on a pas de langue (ou pas de paramètre `lang`), alors ce n'est pas `Filtrer` qui est affichée comme valeur mais `Attribut`.

Si on défini un `attributelabel` avec une langue alors c'est la valeur de la traduction qui est affichée (`Filtrer` par défaut) et non ce qu'on a défini dans le fichier de configuration.

La ligne suivante va donc toujours affecter une valeur en l'absence d'un `attributelabel`. Ce qui complique le contrôle afin de savoir si `attributelabel` est vide ou non.

https://github.com/geobretagne/mviewer/blob/e35681909dd6fa868fa3c250a087ee9e3d0e7e76/js/configuration.js#L583 

### Porposition  :

Modifier le template sans autre contrôle (_Mustache Power_).

https://github.com/geobretagne/mviewer/blob/e35681909dd6fa868fa3c250a087ee9e3d0e7e76/js/templates.js#L146

1. Si `attributelabel` est défini : pas de traduction possible. Cela veut dire que l'utilisateur forcera toujours cette valeur (même en anglais).

2. Si absence de `attributelabel` sans traduction : affichage de "Attribut" selon le template

3. Si absence de `attributelabel` et traduction : affichage de la valeur selon le fichier de traduction i18n


Voici la syntaxe testé et fonctionnelle pour cette solution. Elle évite de modifier le fichier mviewer.js mais nécessite d'adapter le fichier configuration.js :

**configuration.js:**

`oLayer.attributelabel = layer.attributelabel; 
`
**template.js :**

```
'{{#attributeLabel}}',
    '<label for="{{layerid}}-attributes-selector">{{attributeLabel}}</label>',
'{{/attributeLabel}}',
'{{^attributeLabel}}',
    '<label for="{{layerid}}-attributes-selector" i18n="attribute.control.filter">Attributs</label>',
'{{/attributeLabel}}',
```

Ce comportement convient ?

**Comment by spelhate** [comment]
Merci pour la proposition @Gaetanbrl 👍
