### ISSUE TITLE
Importer shapefile (.shp)

### ISSUE THREAD

**Issue by tkohr** [geobretagne/mviewer#341]
Il serait intéressant de permettre à l'utilisateur l'import d'un shapefile local (de taille raisonnable) comme couche temporaire pour la session active (comparable à l'import csv existant).

Des questions qui se posent sont :
* Serait-il mieux de le développer comme extension ou dans le cœur du code ? (probablement en utilisant une lib comme https://www.npmjs.com/package/shapefile)
* Si le dév était fait dans le cœur, est-ce qu'on choisirait de l'intégrer dans l'import csv pour avoir un outil d'import fichier ? (En cas du shp sans ouvrir la modal si on arrive à transformer le string du .prj en proj4js)
* Sinon, niveau UI il faudrait décider si on passe par une couche temporaire qui s'affiche dans le menu (comme l'import csv) ou un bouton qui ouvre le composant.

Merci pour vos retours sur le sujet.

**Comment by Gaetanbrl** [comment]
> Il serait intéressant de permettre à l'utilisateur l'import d'un shapefile

C'est vrai mais il n'y a quasiment aucun réel besoin en ce qui concerne les utilisateurs que l'on a en direct.
Le CSV / JSON sont de loin les formats les plus demandés car ce sont les plus récupérés depuis les API publics et le moins lourd à échanger. Et autrement ils passent pas Qgis / ArcGis pour récupérer le SHP en JSON.

Comment est-ce tu envisages de lire le SHP avec le JS ?

> Serait-il mieux de le développer comme extension ou dans le cœur du code ?

Je dirai une extension. Le but du Mviewer étant de proposé une carto personnalisable selon le profil. Je sais d'avance que certains voudront virer cette fonctionnalité de l'interface si jugée non utile (si présentée en direct en public par exemple).

> Si le dév était fait dans le cœur, est-ce qu'on choisirait de l'intégrer dans l'import csv pour avoir un outil d'import fichier ?

Ça peut être une piste. Attention cependant, l'import CSV n'est actuellement pas un plugin (cela n'existait pas encore). Il faudrait donc le refaire et je pense que c'est une très bonne option.

> Sinon, niveau UI il faudrait décider si on passe par une couche temporaire qui s'affiche dans le menu 

Ca dépendra si c'est un plugin ou non. SI c'est un plugin alors il faut une couche temporaire créée par le plugins à l'init. Comme dit au dessus, l'outil d'import CSV est à revoir avec le format plugin.

**Comment by tkohr** [comment]
Merci pour ce retour qui explique bien le contexte. 

C'est vrai qu'on peut passer par d'autres outils avec un shapefile, mais il semble toujours bien présent à nos jours. Nous avons un client avec ce besoin pour mviewer en tout cas ;-)

> Comment est-ce tu envisages de lire le SHP avec le JS ?

J'ai vu qu'il existe des libs pour ça (comme celle mentionnée plus haut).

**Comment by Gaetanbrl** [comment]
> C'est vrai qu'on peut passer par d'autres outils avec un shapefile, mais il semble toujours bien présent à nos jours

Oui il existe et persiste surtout auprès des utilisateurs qui demandent un usage avancé. Ca reste le format favoris en SIG (quoi que...).

> J'ai vu qu'il existe des libs pour ça (comme celle mentionnée plus haut).

A tester ;)

**Comment by spelhate** [comment]
Je trouve intéressant l'idée de pouvoir charger dynamiquement une donnée locale. Mais pourquoi shape ?
Je pense qu'il y a d'autres formats plus adaptés et plus facile à charger car ne nécessitant pas de backend (geojson, kml...)

**Comment by spelhate** [comment]
> C'est vrai qu'on peut passer par d'autres outils avec un shapefile, mais il semble toujours bien présent à nos jours. Nous avons un client avec ce besoin pour mviewer en tout cas ;-)

Ok. Je comprends.

**Comment by spelhate** [comment]
+1 avec La proposition de @Gaetanbrl  de créer une extension dédiée au chargement de fichier locaux.

**Comment by Gaetanbrl** [comment]
@tkohr c'est bon de ce côté ?

**Comment by tkohr** [comment]
@Gaetanbrl je pense que oui, je fais un dernier tour sur la PR et sa doc vendredi et confirmerai

**Comment by Gaetanbrl** [comment]
Oups... je pensais qu'elle avait été traité, autant pour moi .

**Comment by tkohr** [comment]
@Gaetanbrl , la PR est bon de mon côté maintenant

**Comment by Gaetanbrl** [comment]
@tkohr à fermer si tout est bon.

**Comment by tkohr** [comment]
ah oui bien vu @Gaetanbrl

**Comment by Gaetanbrl** [comment]
Pas de problème, merci 👍!

**Comment by Heshzer** [comment]
> Je trouve intéressant l'idée de pouvoir charger dynamiquement une donnée locale. Mais pourquoi shape ? Je pense qu'il y a d'autres formats plus adaptés et plus facile à charger car ne nécessitant pas de backend (geojson, kml...)

La conversation date de 2020, mais est-ce que l'ajout de KML en local est aujourd'hui possible ou on reste sur CSV / SHP ?
