### ISSUE TITLE
Amélioration du statut de connexion

### ISSUE THREAD

**Issue by spelhate** [geobretagne/mviewer#343]
Le module d'authentification qui s'appuie sur le security-proxy georchestra n'affiche pas le statut de connexion (connecté/non connecté).
![image](https://user-images.githubusercontent.com/1793792/85149206-4f415c00-b251-11ea-9330-73d3cfffa9c7.png)

Il est donc proposé de modifier l'icone cadenas par une icone "logout" lorsque l'utilisateur est connecté.

**Comment by Gaetanbrl** [comment]
@spelhate penses-tu qu'il est possible d'avoir des informations sur le groupe auquel appartient l’utilisateur ?

**Comment by spelhate** [comment]
Oui je récupère déjà cette information grâce à **who**,  mini backend cgi : https://github.com/geobretagne/mviewer/blob/master/who, activable dans Apache2 avec le .htaccess présent à la racine du dépôt.
Attention, ça fonctionne uniquement lorsque l'application mviewer est servie par le security-proxy de georchestra.

**Comment by Gaetanbrl** [comment]
Le bouton "cadenas" serait pas mal à côté du bouton de la page "documentation"

**Comment by spelhate** [comment]
> Le bouton "cadenas" serait pas mal à côté du bouton de la page "documentation"

Je retiens ta proposition @Gaetanbrl
