### ISSUE TITLE
Option d'application exportPNG ne génère pas l'image souhaité

### ISSUE THREAD

**Issue by cbriand** [geobretagne/mviewer#347]
### Ce que je voulais faire :

Utiliser l'option d'application export png

### Le problème rencontré :

Le clic sur le bouton génère une erreur `TypeError: Cannot read property 'canvas' of undefined` et enregistre un fichier `carte.png` corrompu.

Capture d'écran sur le mviewer sans appel d'application spécifique : 

![image](https://user-images.githubusercontent.com/38095778/85576607-d4a18380-b638-11ea-8aff-07c1cd5b81ef.png)

**Comment by Gaetanbrl** [comment]
Merci pour le retour @cbriand .
Je pense que cette issue est liée à celle-ci l'issue #6  où le format PNG ne fonctionnait pas et le JPG fonctionnait.
Je vais faire quelques tests avec le JPG et voir si jamais cela ne viendrait pas des upgrade de lib.

**Comment by spelhate** [comment]
@cbriand Pouvez vous précisez le navigateur utilisé et la version ?

**Comment by spelhate** [comment]
Je reproduis le bug avec Chrome version 80.0.3987.132

**Comment by Gaetanbrl** [comment]
@cbriand je viens de proposer un correctif. Il sera disponible avec la prochaine release.

https://github.com/geobretagne/mviewer/commit/69ec927e46d642c9b82717a65544b3d27270941b
