### ISSUE TITLE
Info bulle légende : mode simplifié et ultra simplifié

### ISSUE THREAD

**Issue by lecault** [geobretagne/mviewer#351]
Lorsqu'on est en mode simplifié ou ultra-simplifié comme ici : https://kartenn.region-bretagne.fr/kartoviz/?x=-286171&y=6155806&z=8&l=spectacle_vivant*%252Cfestival*%252Cart_contemporain*&lb=positron&config=apps%2Fregion%2Fbretagne_bzh%2Fculture.xml&mode=u

Il serait souhaitable d'avoir une infobulle lorsqu'on passe sur ce bouton en haut à gauche : 
![image](https://user-images.githubusercontent.com/5269430/86369694-1a84ca00-bc7f-11ea-9df6-7ffb1233c477.png)

Si j'ai bien vu, ce bouton est le hamburger visible dans le coin dans le mode normal.

Donc 2 pistes : 
- Soit on ne peut pas différencier le contenu de l'infobulle selon le mode. On pourra mettre "afficher les thématiques".
- Soit on peut différencier le contenu selon le mode : 
    - "afficher les thématiques" en mode normal
   - "afficher la légende" en mode simplifié et ultra-simplifié

**Comment by Gaetanbrl** [comment]
@lecault ce ne sont pas les mêmes boutons. Il est donc possible d'afficher un contenu différent et de réaliser ta seconde proposition.

**Comment by lecault** [comment]
Cool. Je ne sais pas ce qu'en pense la communauté mais en tout cas j'ai eu un retour utilisateur qui ne comprenais pas comment afficher la légende. L'infobulle permettra de leur faire comprendre plus facilement.

**Comment by Gaetanbrl** [comment]
> j'ai eu un retour utilisateur qui ne comprenais pas comment afficher la légende

Nous avons des retours similaires. Les utilisateurs n'ont pas le réflexe de cliquer ou poser la souris sur le bouton. Une tooltip sera en effet la bienvenue mais il faudrait dans ce cas que l'utilisateur aille quand même chercher le bouton pour y placer le curseur, ce qui n'est pas gagné non plus car ils ne comprennent pas la signification de ce bouton et ne vont pas aller dessus.

@Agath21 penses-tu que le picto pourrait évoluer ?

**Comment by lecault** [comment]
Ah oui du coup si ce n'est pas lié, faire évoluer le picto c'est pas mal.

**Comment by Gaetanbrl** [comment]
Je relance @Agath21 sur cette issue :)

**Comment by Agath21** [comment]
On peut remplacer l'icône actuel par un icône représentant des couches comme celui-ci https://fontawesome.com/icons/layer-group?style=solid 
![image](https://user-images.githubusercontent.com/22764056/94840837-60d1fc80-0419-11eb-96b6-926995a38e30.png)

Au delà de la légende, c'est un panel où l'on peut gérer l'affichage des couches (sens, opacité, suppression) et accéder aux infos (attribution et métadonnées). De plus, l'icône layer-group est un icône assez commun dans les visualiseurs cartographiques et les outils SIG/DAO.

**Comment by lecault** [comment]
@Agath21 je trouve ce picto plus clair que le précédent.

Est-ce possible de changer ce picto juste pour les mode simplifiés et ultra-simplifié ?
Car en mode normal, je trouve que ça se comprend avec le côté pivotable du hamburger.

Concernant les intitulés des infobulles si vous avez mieux je suis preneur :).

Merci,

**Comment by Gaetanbrl** [comment]
> Est-ce possible de changer ce picto juste pour les mode simplifiés et ultra-simplifié ?

Oui c'est possible pour le mode simple et ultra simple en remplaçant dans le fichier mviewer.js cette ligne :

https://github.com/geobretagne/mviewer/blob/32e51e1471b3dfa1597303f3955584b48416d1ed/js/mviewer.js#L661

Par :

`'<i class="fas fa-layer-group"></i></a>'].join(""));`
