### ISSUE TITLE
Présentation du projet de mviewer "Mon Environnement vu de l'Espace" (MEVE) - GIS BreTel et Someware

### ISSUE THREAD

**Issue by MarieJag** [geobretagne/mviewer#353]
Bonjour à tous,

Le GIS BreTel mène un projet  « Mon Environnement Vu de l’Espace » (MEVE) qui vise à développer un mviewer à destination d’un public scolaire permettant :
> d’afficher des images satellitaires à différentes résolutions spatiales et à différents niveaux de zoom selon différentes requêtes (ex : clic sur une unité administrative, recherche d’un établissement scolaire) ;
> d’afficher des points d’intérêt (POI) correspondant à des exemples d’applications satellitaires (ex : pollution marine, végétation en ville, étalement urbain, suivi des vagues, suivi des parcelles agricoles, etc.). Au clic sur le POI, un jeu de donnée local s'affiche (avec le bon niveau de zoom) et un bandeau latéral décrit le jeu de données et les applications concrètes ;
> sur le périmètre de la Région Bretagne.

Ce projet a débuté par un travail d’étudiants d’IMT Atlantique (que certains d'entre vous ont pu aider, merci pour cela, cf Issues #330 et #331) et se poursuit aujourd’hui avec la société Someware. Ce projet est coordonné par le GIS BreTel et bénéficie d’un financement Cnes. Il sera dans un premier temps déployé sur GéoBretagne. Des tests seront effectués en Septembre auprès d’enseignants et un déploiement national pourra être proposé au Cnes et à ses partenaires (dans d’autres Régions françaises).

Ce post pour vous présenter le projet, et les développeurs qui travailleront sur le projet MEVE : Bertrand Gervais et David Hervé, qui seront peut-être amenés à échanger ici avec vous. Nous travaillons sur GitLab et partagerons avec vous les résultats de ce projet.

A bientôt,
Marie

**Comment by spelhate** [comment]
Merci pour l'info et la présentation @MarieJag

**Comment by spelhate** [comment]
En complément, je référence ici une nouvelle **démo** disponible ici https://github.com/geobretagne/mviewer/tree/develop/demo/sentinel

et visible là : https://kartenn.region-bretagne.fr/demo/?config=demo/sentinel/sentinel.xml
