### ISSUE TITLE
Param topLayer ne fonctionne pas dans certains cas

### ISSUE THREAD

**Issue by Gaetanbrl** [geobretagne/mviewer#354]
Nous avons des cas où le topParam ne fonctionne pas,
Je pense qu'il y a des tests à réaliser sur ce paramètre.

Bug constaté sur un usage "classique" sans autre manipulation d'ordre.

**Comment by spelhate** [comment]
@Gaetanbrl, tu peux nous donner la recette pour reproduire le bug ?

**Comment by AnthonyNch** [comment]
Bonjour.

Je vais compléter le ticket de Gaëtan.

Test avec une couche customlayer et une couche en wms :
Le "toplayer" appliqué sur une couche wms fige bien celle-ci dans la légende. Mais lorsqu'une autre couche de type customlayer est paramétrée avec un "tooltip", le toplayer ne fonctionne plus en affichage. La couche avec le tooltip prend le dessus.

Test avec deux couche customlayer (une en toplayer et l'autre avec tooltip) :
La couche avec le "toplayer" s'affiche correctement, mais cela prend le dessus sur la fonction tooltip qui n'est plus disponible pour la deuxième couche. A moins que l'utilisateur coche l'infobulle dans la légende. 

Merci !!

**Comment by Gaetanbrl** [comment]
> @Gaetanbrl, tu peux nous donner la recette pour reproduire le bug ?

Merci @AnthonyNch pour le détail.

**Comment by Gaetanbrl** [comment]
@spelhate je complète :

On a rien de spécifique, un customLayer et un WMS. 
Le top Layer n'est pas toujours en topLayer. Je n'ai pas d'étape de test spécifique...

**Comment by spelhate** [comment]
Si je comprends bien c'est la fonctionnalité d'overlay et de tooltip qui perturbe le fonctionnement du paramètre toplayer.
La gestion des overlays et des tooltips a été modifiée récemment. C'est peut-être une piste.

**Comment by Gaetanbrl** [comment]
Ce serait lié à mes dernières modif donc ? 

Il me semblait que notre soucis était liés sur une version sans ces modif, mais c'est une piste que je vais analyser ! merci

**Comment by Gaetanbrl** [comment]
en y repensant on a une autre issue sur ce sujet avec une réponse de @AnthonyNch qu ia pu contourner ce soucis en utilisant le permalien du partage de la carte.

**Comment by spelhate** [comment]
Pour alimenter les tests, le fichier apps/default.xml disponible dans mviewer utilise une couche (intercommunalité - customlayer) avec le paramètre **toplayer**. Cet exemple semble fonctionner correctement.

https://kartenn.region-bretagne.fr/demo/?config=apps/default.xml

**Comment by Gaetanbrl** [comment]
Issue reproduite ce jour, topLayer ne semble pas pris en compte.

**Comment by Gaetanbrl** [comment]
> Issue reproduite ce jour, topLayer ne semble pas pris en compte.

Après avoir vidé le cache, le top layer est repris en compte.

**Comment by Gaetanbrl** [comment]
@AnthonyNch 

> Le "toplayer" appliqué sur une couche wms fige bien celle-ci dans la légende. Mais lorsqu'une autre couche de type customlayer est paramétrée avec un "tooltip", le toplayer ne fonctionne plus en affichage. La couche avec le tooltip prend le dessus.

Je viens de tester avec ton cas https://santegraphie.fr/mviewer3/app/cpts_v2.xml, mais qu'on soit avec ou sans tooltip, le `toplayer `ne fonctionne pas.

J'ai testé avec la dernière version Mviewer, j'ai rajouter également toplayer="true" pour la couche à mettre en toplayer mais ca ne change rien. Ca confirme le soucis.

**Comment by Gaetanbrl** [comment]
Je ferme, cette issue est redondante avec l'issue #109 - une PR étant en cours.
