### ISSUE TITLE
Localisation adresse via api Google

### ISSUE THREAD

**Issue by eprouteau** [geobretagne/mviewer#355]
Bonjour,

Un partenaire nous demande si il est possible à la place du geoportail et de la BAN de brancher la recherche d'adresses google sur le mviewer.

Bonne journée,

Emeric,

**Comment by spelhate** [comment]
Certainement, mais je ne connais pas les limites d'utilisation de l'API de Google.

**Comment by bchartier** [comment]
Je complète ce qu'a écrit @spelhate pour qu'il n'y ait pas d'ambiguïté :
* aujourd'hui le code de mviewer ne supporte que le service OpenLS de l'IGN et l'API de BAN
* brancher l'API de Google nécessiterait de compléter le code de Mviewer.

**Comment by eprouteau** [comment]
Merci de vos réponses

Bonne journée,

**Comment by lecault** [comment]
Est ce qu'on clos ce genre de demande ? Pour moi oui, la réponse laisse à penser que l'option n'est pas envisagée.

**Comment by Gaetanbrl** [comment]
Je clos sur cette réponse : 

Ce type de modification nécessite un développement dans le code. L'API Google nécessitant une Clé, ce n'est pour moi pas une ressource à privilégier.

En clair, ce n'est actuellement pas possible mais c'est faisable.
