### ISSUE TITLE
Problème de communication mviewer/elasticsearch

### ISSUE THREAD

**Issue by roms52** [geobretagne/mviewer#356]
Bonjour,

Je souhaite mettre en place dans mviewer une couche avec la recherche Elasticsearch. L'index Elastic est fonctionnel, l'appel au serveur web l'hébergeant se fait bien mais je suis confronté à un problème.
En effet, la couche ne se charge pas : "Error 406 Not Acceptable" , la réponse est : **"Content-Type header [text/plain;charset=UTF-8] is not supported"**
Après avoir consulté de nombreux sites, je pense que le problème vient de la version trop récente d'ElasticSearch (7.8.0) qui n'accepte plus les en-têtes de requêtes "Content-Type | text/plain;charset=UTF-8". 
Je suis donc bloqué car les features n'apparaissent pas, je cherche donc un moyen de solutionner ce problème.

**Comment by gryckelynck** [comment]
J'ai fait un test pour forcer le "content-type" de la requête en ajoutant `xhr.setRequestHeader('Content-Type', 'application/json');` dans le script de "customlayers", après `xhr.open('POST', url);` comme par exemple au niveau de https://github.com/geobretagne/mviewer/blob/master/customlayers/inventaire.js#L121
On obtient alors une erreur 400 avec:
```
{"error":{"root_cause":[{"type":"parsing_exception","reason":"unknown query [filter]","line":1,"col":42}],"type":"parsing_exception","reason":"unknown query [filter]","line":1,"col":42,"caused_by":{"type":"named_object_not_found_exception","reason":"[1:42] unknown field [filter]"}},"status":400}
```
Est-ce que cela permet d'avancer?

**Comment by spelhate** [comment]
Ce ticket est à mettre en relation avec #127 et  #147.
Dans ma structure, nous utilisons toujours une vieille version d'ELS (5.6) sans rencontrer de problème.
La difficulté, c'est qu'à chaque changement de version d'ELS, la syntaxe des requêtes changent et qu'il faut à chaque fois réécrire la partie cliente d'ELS. @gryckelynck , c'est ce que je comprends du message d'erreur que tu fait remonter. Peut-être que ceux qui ont fait ce travail peuvent partager leurs résultats ?

**Comment by roms52** [comment]
Effectivement, il a fallu rajouter '**xhr.setRequestHeader('Content-Type', 'application/json');**' dans le customlayer afin qu'il n'y est plus de problèmes d'en-têtes constatés depuis la version 6 d'ELS.

**Comment by roms52** [comment]
Problème réglé : il suffisait juste de forcer le "content-type", merci @gryckelynck

**Comment by spelhate** [comment]
Et donc ça fonctionne avec ELS 6 ? Je réouvre le ticket pour effectuer cette mise à jour du code :
` xhr.setRequestHeader('Content-Type', 'application/json');`

**Comment by roms52** [comment]
Oui, ça fonctionne avec ELS 7.8.0. La modif peut être faite.
Cdlt

**Comment by spelhate** [comment]
Pour info, `xhr.setRequestHeader('Content-Type', 'application/json');` n'est pas compatible avec les versions d'ELS antérieures à 6.0.
Il faut donc connaitre la version d'ELS utilisée pour savoir quel content-Type envoyer.
