### ISSUE TITLE
Affichage de la légende depuis un custom layer

### ISSUE THREAD

**Issue by frgis** [geobretagne/mviewer#357]
Bonjour,

je suis entrain de mettre en place un custom layer et je me heurte a un souci de légende.

J'ai écris ceci pour afficher le layer :

//Initilisasation du formart GeoJSON.
let geojsonFormat = new ol.format.GeoJSON();

//Symbologie (style)
var symbole2 = new ol.style.Style({
        image: new ol.style.Icon({
          anchor: [0.5,0.5],
		imgSize: [235,279],
          size: [235,279],
          offset: [0,0],
          opacity: 1,
          scale: 0.1,
          src: 'apps/equipements_communautaires/img/symbologie/logo_ot.svg'
        }),
		zIndex:2
      });

//Ouverture de la couche GeioJSON sur laquelle appliquer le style définit plus haut
const layer =  new ol.layer.Vector({
    source: new ol.source.Vector({
        url: 'apps/equipements_communautaires/data/office_tourisme.json',
        format: geojsonFormat
    }),
    style: symbole2
});

//La couche est envoyée dans l'application
new CustomLayer('office_tourisme', layer);

Mon problème c'est que la légende ne s'affiche pas - image en piece jointe
![legende](https://user-images.githubusercontent.com/56657014/87694999-33b56c80-c78f-11ea-8714-78f065f329ca.PNG)

Est-ce qu'il y a quelque chose qui manque car je n'arrive pas à trouver de la doc sur ce paramétrage ou alors est-ce qu'il y a une incapacité de mviewer avec ce type de customlayer ?

Dans le xml : 
![config](https://user-images.githubusercontent.com/56657014/87695214-82fb9d00-c78f-11ea-8d24-4ba91924114b.PNG)

Merci, bonne soirée

**Comment by AnthonyNch** [comment]
Bonjour ;

Pour ma part, afin d'afficher la légende, j'ajoute la ligne suivante dans le fichier "js"
**let legend = { items: [] };
legend.items.push({styles:symbole2, label: "libellé de la légende", geometry: "Polygon"});**

Il faut éventuellement modifier la geometry si ce n'est pas sur du polygon

Et ceci pour récupérer la légende
new CustomLayer('office_tourisme', layer, **legend**);

A voir si cela fonctionne.

Bonne journée.

**Comment by frgis** [comment]
Bonjour,

merci.
J'ai finis par m'en sortir mais j'ai un souci, j'ai pas trouvé pour récupérer l'image quand c'est une icone, pour une forme simple ça fonctionne mais un picto. Quelqu'un a-t-il déjà rencontré le problème ?

Bon week-end, merci pour le retour.

**Comment by frgis** [comment]
Bonsoir,

pour le svg tant pis j'ai passé en legendurl ça va comme il faut, c'est plus gênant pour les personnes qui font des couches de symbole qui mélangent icon et circle notamment. En ce qui nous concerne on a placé le circle dans le svg (inkscape) et c'est fini.

Enfin je vous remercie pour la méthode il y a juste une erreur il faut écrire [symbole2]  entre crochet sinon la console firebug envoie une erreur foreach.

Bonne soirée et merci pour votre réactivité.

**Comment by Gaetanbrl** [comment]
@frgis je rebondis sur votre issue,

Il n'est actuellement pas possible pour une couche (et donc une légende) de mélanger de la légende dynamique (comme montré par @AnthonyNch ) et legendurl.

Lors de la définition des items d'une légende, vous pouvez toutefois afficher un type openLayers icon ou bien circle ou bien ce que vous souhaitez tant que cela reste du style Openlayers.

Le style OpenLayers permettant de gérer les SVG par exemple, cela peut convenir.

Ce type de légende dynamique est donc possible : 

0 à 5 - cercle vert
5 à 20 - cercle orange
> à 20 - picto rouge SVG

**Comment by frgis** [comment]
Bonsoir,

pour ma part j'ai eu un souci avec un svg, pas avec un cercle).
Le symbole combinait un cercle vert, et sur le cercle un svg (si je,ne dis pas de bêtise, à force de tester j'ai un doute :-) ).
Tout ça dans le customlayer.

Finalement, j'ai fais un svg qui fait tout et je l'ai ajouté en legendurl j'ai pas de problème.

Après, la syntaxe n'était probablement pas bonne (j'avais le message plus haut) mais j'ai cru que quelque chose était incompatible.

Merci.

**Comment by Gaetanbrl** [comment]
Lié à #354
