### ISSUE TITLE
Rafraichir automatiquement un layer de type customlayer (utilisation du format geojson)

### ISSUE THREAD

**Issue by frgis** [geobretagne/mviewer#359]
Bonjour

j'ai quasiment fini la mise en place de ma première carte, c'est super :)
J'arrive tout au bout et je suis entrain de faire des vérif. J'ai utilisé pour questions de performance des fichiers geojson.

Lorsque l'on démarre la carte, les fichiers sont téléchargés sur l'interface, tout va bien.
Si je rafraîchis la page le fichier est chargé par le cache et non pas redemandé à nouveau au serveur. C'est super du point de vue des perfs mais c'est un souci pour les données qui bougent. 
D'où mon problème, c'est que au moins une de ces couches va se rafraîchir une fois par jour. Est-ce qu'il existe une méthode pour demander dans le customlayer que le fichier geojson soit systématiquement recharge depuis le serveur ?
Dans l'idéal, est-ce qu'il est possible d'utiliser le cache durant un délai inférieur à 24  h puis de recharger le fichier depuis le serveur ?

J'ai observé #311  que quelque chose dans ce type de cas a été évoqué mais je ne sais pas trop comment l'appliquer à un simple layer en affichage.

Si quelqu'un à des infos je suis preneur.

Merci.

**Comment by spelhate** [comment]
> j'ai quasiment fini la mise en place de ma première carte, c'est super :)

Bonjour. Tant mieux si ça vous plaît :-))

> Est-ce qu'il existe une méthode pour demander dans le customlayer que le fichier geojson soit systématiquement recharge depuis le serveur ?

Oui. Dans le customcontrol il faut remplacer l'url statique geojson (monfichier.geojson) par une url "dynamique" du style monfichier.geojson?dc=1254685 où dc est une valeur qui change à chaque requête.

Exemple 

```
dc = new Date().getTime(),
var url = 'monfichier.json?dc=' + dc;
```

**Comment by frgis** [comment]
Bonjour,

merci ça marche super bien :-)

Bonne journée, merci pour votre retour.
