### ISSUE TITLE
Mviewer ne peut pas démarrer sous Internet Explorer

### ISSUE THREAD

**Issue by frgis** [geobretagne/mviewer#360]
Bonjour,

en réalisant les tests je me suis rendu compte que Mviewer (j'utilise la version 3.3) ne démarre pas sous Internet Explorer. Mon poste est en Windows 10 et j'ai essayé sous Internet Explorer version 11.

Voici ce que j'ai en pièce jointe dans la console : 

![issue_mviewer_1](https://user-images.githubusercontent.com/56657014/88263607-985e5300-ccca-11ea-9e62-cce19c5f673c.PNG)

![issue_mviewer_2](https://user-images.githubusercontent.com/56657014/88263619-9c8a7080-ccca-11ea-80c0-01064daf0906.PNG)

A noter : cela ne vient pas de mon application (config), j'ai testé avec des applis de démo.

Ce problème est connu ?

Merci.

**Comment by spelhate** [comment]
Je confirme que ça ne fonctionne pas avec Internet Explorer. Par contre ça fonctionne avec **Edge** l'autre navigateur de Microsoft.

**Comment by frgis** [comment]
Bonjour,

je peux ajouter que ça fonctionne sous Firefox et Chrome. Il me manque Safari pour vérifier, est-ce que quelqu'un qui l'a peut regarder ?

c'est bloquant pour nous car nous souhaitons potentiellement publier pour le grand public et on ne peut pas maîtriser quel navigateur sera utilisé.
Sachant que même si Internet Explorer est de moins en moins utilisé, il l'est encore par pas mal d'utilisateurs (soit cela provient d'habitudes qui ont été prises soit c'est le navigateur par défaut sur leur pc).

Est-ce que vous pourriez évaluer si le problème est compliqué à résoudre ?
C'est très gênant pour nous (je pense que ça risque de bloquer le déploiement).


Merci.
Cordialement.

**Comment by spelhate** [comment]
> Est-ce que vous pourriez évaluer si le problème est compliqué à résoudre ?

Désolé @frgis mais je ne peux pas consacrer de temps à cette demande n'étant ni utilisateur ni expert d'Internet Explorer. Peut-être que d'autres pourront vous renseigner.

**Comment by Gaetanbrl** [comment]
> Sachant que même si Internet Explorer est de moins en moins utilisé, il l'est encore par pas mal d'utilisateurs (soit cela provient d'habitudes qui ont été prises soit c'est le navigateur par défaut sur leur pc).

C'est souvent plus une demande des infrastructures publics plus que des utilisateurs privés qui peuvent changer facilement avec un accompagnement minimale... 

Je peux peut-être regarder 5 min mais je ne suis pas en faveur d'une compatibilité Explorer.

**A noter que Explorer version < 11 n'est plus supportée par Microsoft.**

`Le support pour Internet Explorer (IE) 10 et versions antérieures a pris fin le 12/1/16. Les mises à jour de sécurité, les correctifs de compatibilité et le support technique se poursuivent pour IE 11 sous Windows 7, 8.1 et 10.
`
https://www.microsoft.com/fr-fr/microsoft-365/windows/end-of-ie-support

Il n'est pas garanti que cette version vive encore très longtemps vu les efforts fournis sur Microsoft Edge. Sur ces raisons je ne suis pas plus en faveur pour une compatibilité avec Explorer.

**Comment by Gaetanbrl** [comment]
A noter également par Microsoft : 

`Oui, Internet Explorer 11 est la dernière version majeure d’Internet Explorer. Internet Explorer 11 continuera à recevoir des mises à jour de sécurité et un support technique pour le cycle de vie de la version de Windows sur laquelle il est installé.`
https://docs.microsoft.com/fr-fr/lifecycle/faq/internet-explorer-microsoft-edge

**Comment by Gaetanbrl** [comment]
(@frgis) Explorer ne supporte pas les format `min.map` qui permettent d'avoir du code "minifié".
Pour ne plus avoir les erreurs 404 il faut supprimer les lignes commentés dans les librairies (recherchez .min.map et aussi .min.css.map).
`Ex :  /*# sourceMappingURL=bootstrap-datepicker3.min.css.map */`


Les autres erreur JS sont des erreurs de syntaxe liées au moteur JS d'Explorer.

* HTML1500: La balise ne peut pas se fermer automatiquement. Utilisez une balise de fermeture explicite.

```
<span>
    <path/> <g></g>
</span>
```

Selon la web doc (https://www.w3schools.com/graphics/svg_path.asp) la syntaxe est conforme sauf pour IE.

* SCRIPT1002: Erreur de syntaxe

`class CustomLayer {`

Problème de compatibilité IE avec l’interprétation des classes JavaScript (je dirai non compatible nouveautés EcmaScript).
Firefox a le même soucis avec des versions passées mais c'est aujourd'hui corrigé.

* SCRIPT1002: Erreur de syntaxe
` _element.find("[i18n]").each((i, el) => {`

C'est du JQuery, aucune raison que ça ne fonctionne pas. Seul IE n'en veut pas.

* SCRIPT1014: Caractère incorrect

IE refuse d'interpéter les "littéraux de gabarits" je pense. Dommage c'est maintenant courant...
https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Litt%C3%A9raux_gabarits



Je ne vais pas tous les faire mais jusque là c'est du problème unique IE sur des éléments aujourd'hui répandus et courant dans le JavaScript récent (plus tant que cela d'ailleurs).

Vous pouvez également tout à fait proposer une contribution pour corriger ces problèmes.

**Comment by frgis** [comment]
Bonjour,

merci pour le temps consacré à l'analyse des erreurs.

Il a été accepté de publier les cartes sur le site internet malgré l'incompatibilité Internet Explorer.
C'est récent et on va voir, on va laisser passer un peu de temps pour voir comment ça fonctionne.

Le site internet fonctionne avec Internet Explorer, on ajoute Mviewer à partir d'iframe dans la page.
Je crains un peu qu'à un moment quelqu'un vienne me demander pourquoi la carte marche pas alors que le reste n'a pas de problème à s'ouvrir sur Internet Explorer mais on va voir je me trompe peut-être. Dans tous les cas c'est connu.

J'ai bien compris que les développements basés sur des bibliothèques modernes commencent à ne plus supporter Internet Explorer.
Merci en tout cas pour l'analyse, cela me permet dans le cas ou il y aurait un souci de me rendre compte de l'étendue des modifications que ça représente. Le cas échéant, on réfléchira sur ce qu'il vaut mieux faire.

Merci encore pour votre temps, je clos le ticket.

Note : j'ai testé sous safari version récente ça s'ouvre, Firefox, Chrome, Edge, Brave, Opera aussi.
