### ISSUE TITLE
[Doc] URL des images à modifier

### ISSUE THREAD

**Issue by Gaetanbrl** [geobretagne/mviewer#372]
### Problème

Depuis le passage de la doc vers  le repository geobretagne/mviewer,  certaines images ne s'affichent plus : 
https://mviewerdoc.readthedocs.io/fr/latest/doc_contrib/doc.html

![image](https://user-images.githubusercontent.com/16317988/90119406-d09d0280-dd59-11ea-8987-b6fea011cfed.png)

Ces images s'affichent bien dans l'intereface GitHub cependant : https://github.com/geobretagne/mviewer/blob/develop/docs/doc_contrib/doc.rst

### Analyse

En mode HTML le chemin est le suivant : 

`<img alt="git fork repository" class="align-center" src="../_images/fork1.png">`

Ce qui correspont à l'URL https://mviewerdoc.readthedocs.io/fr/latest/_images/fork1.png.

Cette URL semble correcte mais la documentation ne semble pas vouloir l'afficher...

**Comment by spelhate** [comment]
Je ne reproduis pas : 
![image](https://user-images.githubusercontent.com/1793792/90483154-92765900-e134-11ea-979a-28cfb8e0e695.png)

**Comment by Gaetanbrl** [comment]
Même dans la doc sphinx ?

**Comment by Gaetanbrl** [comment]
Ca viendrait de mon navigateur => je préfère ca ! :)

**Comment by spelhate** [comment]
> Même dans la doc sphinx ?

Pas testé en local. Mais ça semble fonctionner en ligne.

**Comment by Gaetanbrl** [comment]
OK merci je ferme donc.
