### ISSUE TITLE
MVIEWER embarqué en Iframe

### ISSUE THREAD

**Issue by spelhate** [geobretagne/mviewer#373]
La version ultra simplifiée de mviewer (?mode=u) est souvent embarquée en IFRAME sur des sites éditoriaux.

**2 évolutions sont souhaitées pour ce contexte d'utilisation**

- Ajout d'un bouton maximiser afin d'afficher l'application en plein écran
- La désactivation du zoom on scroll lorque la souris est au dessus de l'IFRAME afin de pouvoir scroller sur le contenu édito.

**Comment by spelhate** [comment]
En attendant une éventuelle intégration dans le coeur de mviewer, je vais proposer une démo s'appuyant dur un addon fullscreen.

**Comment by spelhate** [comment]
Exemple d'intégration : https://kartenn.region-bretagne.fr/demo/demo/iframe.html

A noter que le composant détecte si mviewer est intégré en Iframe et désactive l'interaction Zoom molette.
En activant l'affichage de mviewer en mode plein écran via le bouton 
![image](https://user-images.githubusercontent.com/1793792/90789973-d1103d00-e307-11ea-99bf-29f525b8e883.png)

l'intéraction zoom molette est rétabli.

**Comment by Gaetanbrl** [comment]
> A noter que le composant détecte si mviewer est intégré en Iframe et désactive l'interaction Zoom molette.

Est-ce un paramètre ? 
Est-il possible de prévoir une interaction clavier type ctrl + roulette ?

**Comment by spelhate** [comment]
> > A noter que le composant détecte si mviewer est intégré en Iframe et désactive l'interaction Zoom molette.
> 
> Est-ce un paramètre ?
> Est-il possible de prévoir une interaction clavier type ctrl + roulette ?
Actuellement non. Mais je pense que cette fonctionnalité devra intégrer le cœur en étant améliorée et paramétrable.
