### ISSUE TITLE
Où documenter mviewer studio ?

### ISSUE THREAD

**Issue by lvinsonneau** [geobretagne/mviewer#379]
Bonjour,

Je pensais faire une documentation pour utiliser le mwiever studio et faciliter sa reprise en main.
Déjà, peut-être que cela existe déjà sur github (mais je n'ai pas trouvé) ?
Si non, où pourrait-on le mettre ?
Bonne journée à tous.
Lydie.

**Comment by Gaetanbrl** [comment]
Bonjour @lvinsonneau,

C'est une très bonne idée, je ne crois pas en avoir vu une du même format que la doc [Mviewer](https://mviewerdoc.readthedocs.io/fr/latest/).

Je vous encourage à reprendre l'arborescence de la doc Mviewer en ajoutant un répertoire https://github.com/geobretagne/mviewerstudio/docs et à rajouter une doc sphinx.

**Comment by lvinsonneau** [comment]
ouh là, je suis novice en ce domaine...
Quelqu'un peut-il me guider ?

**Comment by Gaetanbrl** [comment]
Je ne sais pas si vous avez déjà déployé une documentation en local mais si cela est inconnu vous pouvez regarder cet explicatif : 
https://mviewerdoc.readthedocs.io/fr/latest/doc_contrib/doc.html#deployer-la-documentation-en-local

Vous pouvez créer une issue "documentation" si elle n'existe pas dans le dépôt GitHub du Mviewer studio (ce dépôt étant consacré au Mviewer).

**Comment by Gaetanbrl** [comment]
> Quelqu'un peut-il me guider ?

L'explicatif (qui a croisé votre message) vous permettra de : 
* Déployer une documentation existante
* Avoir les bases avec le déploiement / utilisation de sphinx
* Comprendre la syntaxe sphinx
* Reproduire le schéma pour créer votre propre documentation

N'hésitez pas au besoin !

**Comment by lvinsonneau** [comment]
OK, j'essaie de me mettre dedans dès que j'ai un peu de temps et si pb, je 
reviens vers vous !
Merci !
