### ISSUE TITLE
Legend slider

### ISSUE THREAD

**Issue by ebocher** [geobretagne/mviewer#38]
Is there a way to display the slider on a WMS legend as on kartenn ?
![slider_legend](https://cloud.githubusercontent.com/assets/1820572/24755237/aa7b606a-1ad9-11e7-9fc3-77f3be8f30a2.png)

**Comment by spelhate** [comment]
What browser used ? Can you send the config file please?

**Comment by spelhate** [comment]
Ok. I can reproduce.
Iin your config file. Set layer id to  unites_urbaines instead of mapuce: unites_urbaines

**Comment by ebocher** [comment]
Sorry. I'm using Firefox 52.02
The config file is the same as https://github.com/geobretagne/mviewer/issues/37
Note http://kartenn.region-bretagne.fr/mviewer-dev/?config=apps/territoire.xml# works well.

**Comment by ebocher** [comment]
Thanks it works.
Could you put this as a bug ?

**Comment by spelhate** [comment]
Using namespace (ns:layername  )in layer id  breaks  opacity sliders

**Comment by spelhate** [comment]
Fixed with @948ce61

**Comment by ebocher** [comment]
Thanks a lot
