### ISSUE TITLE
affichage de l'échelle en numérique (plutôt - ou en plus - qu'une barre d'échelle)

### ISSUE THREAD

**Issue by vfabry** [geobretagne/mviewer#380]
Bonjour,

Est-ce qu'il est possible d'afficher l'échelle de la carte en numérique (1:xx xxx) en plus de la barre d'échelle ?

Vincent

**Comment by Gaetanbrl** [comment]
Je ne crois pas qu'OpenLayers permette ce type d'échelle (format 1:xxx) mais permet seulement l'affichage numérique simple  en différentes unités / formes :

https://openlayers.org/en/latest/examples/scale-line.html
https://openlayers.org/en/latest/apidoc/module-ol_control_ScaleLine.html


Pour afficher avec le `1:` il faudrait un développement. Je pense qu'un plugin est idéal pour un affichage de ce type (affichable ou non).

**Comment by vfabry** [comment]
Dans https://openlayers.org/en/latest/examples/scale-line.html si on choisit "scale bar" dans le menu déroulant, on peut cocher l'option "Show scale text" , ce qui ferait très bien l'affaire !

**Comment by spelhate** [comment]
@vfabry je découvre cette possibilité. Logiquement, Il faudrait donc ajouter un paramètre relatif à l'échelle afin de spécifier le type d'échelle affiché. Je vais tester.

**Comment by Gaetanbrl** [comment]
> ce qui ferait très bien l'affaire !

Ok j'avais compris que vous ne vouliez que le texte.

**Comment by spelhate** [comment]
Ca peut donner ça : 
avec la configuration ol suivante 


```
new ol.control.ScaleLine({
                    units: 'metric',
                    bar: true,
                    steps: 2,
                    text: true,
                    maxWidth: 100,
                  })

```

![image](https://user-images.githubusercontent.com/1793792/94243953-71b1d800-ff18-11ea-81e3-6cf237a747a0.png)

**Comment by Gaetanbrl** [comment]
@spelhate tu as commencé des travaux sur cette issue ?

**Comment by spelhate** [comment]
> @spelhate tu as commencé des travaux sur cette issue ?

Non, j'ai juste remplacé dans le code 
`new ol.control.ScaleLine() `
par 
```
new ol.control.ScaleLine({
                    units: 'metric',
                    bar: true,
                    steps: 2,
                    text: true,
                    maxWidth: 100,
                  })

```

**Comment by Gaetanbrl** [comment]
Ca marche,  je peux faire une PR dans la journée ;)

**Comment by Gaetanbrl** [comment]
@vfabry vous pouvez tester / clore cette issue, la modification est disponible sur la branche develop.

**Comment by vfabry** [comment]
C'est top ! Merci !
Je retiens que :

- il faut que scalebar="true" et  scaletext="true" pour que le texte de l'échelle s'affiche
- ça fonctionne pour une carte en EPSG:3857 mais pas en EPSG:2154 (voir sur l'image ci-dessous)

![image](https://user-images.githubusercontent.com/15424976/95093381-0098ce80-0729-11eb-908b-2c92cadb9442.png)

**Comment by Gaetanbrl** [comment]
> a fonctionne pour une carte en EPSG:3857 mais pas en EPSG:2154

Je pense que ca peut venir de l'unité de mesure, qui je crois n'est pas 'metric' avec de l'EPSG:2154. 

Il faudrait tester avec d'autres unité pour le paramètre `scaleunits`, qui correspond au paramètre d'échelle `units `ol6 :
https://openlayers.org/en/latest/apidoc/module-ol_control_ScaleLine-ScaleLine.html

**Comment by Gaetanbrl** [comment]
J'ai testé avec la démo mais ce n'est pas cela.
https://openlayers.org/en/latest/examples/scale-line.html

> il faut que scalebar="true" et scaletext="true" pour que le texte de l'échelle s'affiche

En effet, c'est pour cela que dans la doc j'ai précisé `au dessus d'une échelle en barre`: 

https://github.com/geobretagne/mviewer/blob/develop/docs/doc_tech/config_map.rst

**Comment by Gaetanbrl** [comment]
@vfabry avez-vous d'autres travaux autour de cette issue ?
