### ISSUE TITLE
[Recherche] - Masquer / personnaliser le marker uniquement sur recherche BAN

### ISSUE THREAD

**Issue by frgis** [geobretagne/mviewer#386]
Bonjour,

je cherche à utiliser un marker distinct pour la recherche adresse (BAN) -> dans l'objectif de faire en sorte qu'aucun marker ne s'affiche depuis l'outil de recherche (localisation BAN)..

J'ai remarqué dans le fichier index.html que c'est le marker svg qui est utilisé par défaut au clic sur la carte.
Ensuite, j'ai trouvé dans la documentation, qu'il est possible dans le xml de configuration de personnaliser le marker utilisé dans la recherche (paramètre imgurl).

Ce que je ne comprends pas c'est que lorsque je définis ce paramètre avec une image, elle est prise en compte pour la recherche ET pour le simple clic sur la carto.

Pouvez-vous m'expliquer pourquoi ce n'est pas dissocié ? Et si possible, comment le dissocier ?

Pour résumer je cherche une solution pour que lorsque l'on réalise une recherche via le menu localisation (BAN) le zoom se déclenche vers l'adresse mais qu'aucun marker ne s'affiche (uniquement le clic sur la carte d'un utilisateur affiche un marker). Je voulais contourner en paramétrant imgurl en ajoutant une image transparente...

Pouvez-vous m'apporter quelques éléments pour savoir si c'est faisable ?
Merci.

**Comment by spelhate** [comment]
Bonjour. Le marker par défaut est le marker svg  disponible dans index.html. Effectivement il est possible de modifier ce marker via paramètre. Pour réaliser ce que vous souhaitez, il faudrait ajouter une option liée à la recherche dans le config.xml pour pouvoir désactiver l'affichage du marker après avoir cliqué sur un résultat de recherche. Actuellement, ce n'est pas le cas.

**Comment by frgis** [comment]
Bonsoir, merci pour votre réactivité.
Ce que je ne comprends pas c'est que le paramètre est bien là
https://mviewerdoc.readthedocs.io/fr/latest/doc_tech/config_search.html?highlight=recherche

le problème c'est que son action est sur la recherche et sur le simple clic qui n'est pas du tout la même fonctionnalité pour moi - le clic sur une carte par un utilisateur c'est l'identification d'objet ; la recherche c'est la boite de localisation -.

Est-ce un dysfonctionnement ?
Si vous ajoutez le param imgurl dans le xml et plus précisément dans la recherche cela change pour le marqueur de la recherche et le marqueur lié au clic.

Le paramètre si il change tout doit être dans le bloc application (si c'est cela qui est recherché dans l'outil).
Dans l'attente de vos précisions je vous souhaite une  bonne fin de weekend

**Comment by Gaetanbrl** [comment]
Bonjour @frgis.

La recherche dont vous parlez est uniquement la fonctionnalité de recherche en mode "Recherche d'adresse".
Mais cette recherche permet également d'avoir accès à la recherche d'un point sur la carte via Fuse ou ElasticSearch afin d'afficher le template Mustache. 

En recherche BAN, il n'y a pas de template à afficher, l'information réside dans la localisation du point même.

Donc nous avons ces comportements :

* Clic => Affichage de la localisation => Affichage du template
* Recherche Fuse / ELS => Saisie => Clic sur le résultat => Affichage de la localisation => Affichage du template
* Recherche BAN => Saisie => Clic sur le résultat => Affichage de la localisation

On est donc bien sur de la fonctionnalité d'affichage d'une feature sur la carte par le clic ou par la recherche. Ce n'est pas à différencier car les utilisateurs considère qu'un clic sur une entité est une action de recherche d'information sur une feature.

Je préfère conserver une icône de localisation de résultat donc, pour simplifier la logique interne et la configuration.

> Le paramètre si il change tout doit être dans le bloc application

Le bloc Application est dédié au fonctionnement de l'application d'ordre général, ici nous sommes dans une logique de recherche /affichage d'information selon un objet sur la carte.

**Actions possibles :**

Je pense que l'on peut à la rigueur ajouter un marker supplémentaire pour la BAN qui par défaut reprend le marker principal, mais si ce paramètre est renseigné, reprend le marker inscrit.

Cette action permettra de customiser le marker de recherche d'adresse. Mais il ne devra pas modifier le marker de recherche d'objet par Fuse ou ELS qui sont proche du comportement au clic.

**Comment by frgis** [comment]
Merci pour votre réactivité.
Je comprends mieux votre façon de proposer la configuration.
J'y vois néanmoins un blocage bien que pas testé par moi-même, je m'explique. En ajoutant le paramètre dans la balise searchparameters est-ce que si un administrateur de l'outil veut modifier le marker par défaut comme indiqué explicitement dans votre précédent paragraphe, il peut le faire sans qu'il active l'outil de localisation ?

Ce n'est pas mon cas actuellement mais cela pourrait l'être car pour les quelques cartes que j'ai fais avec mviewer, je n'ai pas besoin à chaque fois du localisateur.

Pour la BAN, j'ai besoin d'enlever le marker car pour mon cas le localisateur BAN adresse sert optionnellement à l'utilisateur à centrer la carte dans sa rue s'il a du mal à se repérer dans l'espace. Je ne veux pas me fier à la BAN à 100% dans le fonctionnement pour mon cas car selon les communes les adresses sont plus ou moins bien renseignées dans certains endroits et le résultat peut devenir totalement erroné dans certains cas.
L'idée dans mon cas d'application c'est de permettre à l'utilisateur ayant du mal à se repérer de taper  son adresse et que si le numéro adresse n'est pas connu la carte zoome au moins à la voie ce qui marche à priori convenablement (à peu près).
Par contre je ne veux pas de marker (d'où ma première tentative dans la quelle je cherchais à mettre un marker transparent "transparent.png") pour éviter que l'utilisateur croit que l'outil ne fonctionne pas (je veux que la localisation soit dédiée à zoomer et le reste nécessite un clic de l'utilisateur pour obtenir l'information souhaitée).

Donc oui, avoir la possibilité de personnaliser le marker (transparent.png pour mon cas) me serait utile (BAN).

Cela vous semble compliqué à réaliser ?

**Comment by Gaetanbrl** [comment]
>est-ce que si un administrateur de l'outil veut modifier le marker par défaut comme indiqué explicitement dans votre précédent paragraphe, il peut le faire sans qu'il active l'outil de localisation ?

Vous avez le contrôle pour activier / désactiver la recherche d'adresse séparément de la recherche sur les features avec `localities `et `features ` comme ceci :

`<searchparameters bbox="false" localities="false" features="true" static="false"/>`

Ce qui donnera :

![image](https://user-images.githubusercontent.com/16317988/95168372-7f394e80-07b1-11eb-8d5f-4e6929bd0f7e.png)

**Comment by Gaetanbrl** [comment]
> il peut le faire sans qu'il active l'outil de localisation ?

Vous abordez dans cette issue 2 sujets différents : 
* L'affichage du marker différencié pour la BAN
* La personnalisation du marker différencié pour la BAN

Dans votre cas, la personnalisation du marker pour la BAN uniquement ne sert pas, seule la gestion de l'affichage ou non du marker pour la BAN couvrirai votre besoin.

Donc, ce que je propose c'est un paramètre pour masquer le marker de la BAN ou non sans altérer le fonctionnement des autres fonctions de recherche.

**Comment by frgis** [comment]
Ok.
Effectivement pour mon cas ici, c'est masquer le marker pour la recherche BAN uniquement qui correspond à ce dont j'aurais besoin (le marker serait conservé pour le clic sur la carte).

Dans la carte que je cherche à mettre en place la recherche, uniquement BAN pour ce cas, n'est pas le résultat final, je l'utilise pour permettre à un utilisateur qui a des difficultés à se repérer dans la navigation à zoomer directement sur une adresse qu'il connait pour gagner du temps en ayant un cadrage spatial proche de ce dont il recherche.

**Comment by frgis** [comment]
Bonjour,

est-ce que vous pourriez m'indiquer si vous prendrez prochainement en charge cette évolution ?
Si oui, vers quelle période une version incluant cette amélioration sera disponible ?

Dans le cas contraire, qu'est-ce que vous pouvez nous conseiller pour que nous puissions éventuellement participer à cette évolution (nous n'avons pas de ressource dev, cela ne pourrait être que par le biais d'une presta, le cas échéant) ?

Merci

**Comment by Gaetanbrl** [comment]
@frgis est-ce que ceci vous irait ?

Rajouter un paramètre dans le XML : 

* `banmarker = true` ou pas de paramètre `banmarker` ==> affichage du marker
* `banmarker = false` ==> Pas d'affichage du marker à la recherche ban

**Comment by frgis** [comment]
Bonsoir,

oui cela correspond tout à fait.

Bonne soirée,
cordialement.

**Comment by frgis** [comment]
Re bonjour,

je suis entrain de préparer cette carte, est-ce que vous sauriez me dire si cette amélioration apparaitra d'ici fin d'année ?

Ou si il y a une planification ?

Merci.

**Comment by Gaetanbrl** [comment]
> je suis entrain de préparer cette carte, est-ce que vous sauriez me dire si cette amélioration apparaitra d'ici fin d'année ?

C'est possible, mais dans l'immédiat je ne peux le garantir.

**Comment by frgis** [comment]
est-ce que cela nécessite beaucoup de modifications ?

**Comment by frgis** [comment]
J'ai cherché un peu dans le mviewer.js et search.js j'ai l'impression qu'il faut modifier l'action Zoomtolocation, c'est bien cela ?
Ou vous avez une autre idée

**Comment by Gaetanbrl** [comment]
> est-ce que cela nécessite beaucoup de modifications ?

non pas tellement mais il peut y avoir des effets de bord à surveiller.

> J'ai cherché un peu dans le mviewer.js et search.js j'ai l'impression qu'il faut modifier l'action Zoomtolocation

Il faut que je rejette un oeil ce n'est plus très frais depuis mon dernier commentaire.

**Comment by Gaetanbrl** [comment]
@frgis il faut ajouter un nouveau paramètre, donc modifier le config configuraiton.js ainsi que le fichier mviewer.js pour afficher ou non le marker.

Ce n'est pas très compliqué mais il faut bien revoir le code en tenant compte des l'affichage du marker selon Fuse, la Ban, le clic ou la recherche d'objet.

Je vais essayer de prendre un moment pour faire la modif.

**Comment by Gaetanbrl** [comment]
Je viens de faire les modifs avec la PR. Ma branche ne devait pas être propre, je dois refaire la PR à partir d'une branche propre et la modif sera disponible pour être mergée dans develop (en attente de la version 3.5 @frgis ).

**Comment by frgis** [comment]
c'est la 386 je présume. 
D'accord je vais récupérer les search info et mviewer et je vais tester dans la version que j'ai (qui est la version juste avant celle disponible aujourd'hui (celle de novembre)). Je vous tins au courant. Merci beaucoup pour votre réactivité.

**Comment by frgis** [comment]
j'ai passé la version 3.4.1 et j'ai fais les modifications des fichiers:
mviewer.js
info.js
search.js

ça ne fonctionne pas peu importe si banmarker à "false" ou à "true". Lorsque je fais une recherche adresse "ban" le marker s'affiche.
Lorsque j'identifie en cliquant sur la carte j'ai un rond cerclé de jaune qui s'affiche au premier clic mais tous les autres clics sur la carte n'affichent pas de marker ensuite.
Il y a d'autres élements à modifier dans l'installation ?

**Comment by Gaetanbrl** [comment]
Pour les tests uniquement il faut reprendre TOUT le code de la branche pr-issue-386. 

Vous tentez d'utiliser des fichiers d'une branche en avance sur develop vers la branche master. Cette manipulation apportera de base de grand risques de dysfonctionnement, je ne peux donc garantir le résultat attendu avec un mix de version.

Si vous souhaitez récupérer cette modification je vous encourage fortement à attendre le merge de la PR #433 et ensuite de récupérer le code de la branche develop et non celui de la branche master (version  3.4.1).

Si vous tenez à garder le code des release (v3.4.1), alors vous devrez attendre la prochaine release.

**Comment by frgis** [comment]
D'accord, je vais attendre.
Merci !

**Comment by Gaetanbrl** [comment]
Merci @spelhate
