### ISSUE TITLE
[Config] - Layers et détéction automatique du hostname

### ISSUE THREAD

**Issue by Gaetanbrl** [geobretagne/mviewer#389]
⚠️ Cette issue ne s'applique pas pour les cas où les données proviennent d'un autre GeoServer ou pour des ressources externes.

Lors de la migration des Mviewer entre deux environnements (`préproduction` > `production`), les URLs doivent être changées à la main pour les flux WMS/WMFS provenant d'un GeoServer avec le même hostname.

C'est assez redondant et une petite perte de temps.

L'idée serait alors d'ajouter une méthode dans la configuration pour détecter quand une URL d'un `<layer>` du fichier config.xml détient un domaine à détecter dans l'URL du Mviewer directement. On peut par exemple utiliser une syntaxe du type : 

`url= "/geoserver/espace/ows?service=WFS&request=getFeature&..."
`
Dans ce cas, c'est ici dans le fichier `mviewer/js/configuration.js`  que ca peut se jouer :
https://github.com/geobretagne/mviewer/blob/32e51e1471b3dfa1597303f3955584b48416d1ed/js/configuration.js#L474-L475

... Via une petite RegEx afin de détecter le `/` : 
```
if (layer.url) {
  layer.url = /^\//.test(layer.url) ? window.location.hostname : layer.url;
  var getCapRequestUrl = getCapUrl(layer.url);
```

Mais voilà, le seul soucis que je vois c'est pour les développements en local avec un host type localhost. Il faudrait alors pouvoir définir une valeur de substitution à `localhost` si détecté. Soit via une règle de routage (faisable avec apache ?) ou bien via un paramètre dans la config `<app>`:

`<application routeLayerUrl="localhost:geoserver.preprod.fr">`

@spelhate tu as déjà eu cette réflexion ?

**Comment by Gaetanbrl** [comment]
> Si je comprend bien , c'est de changer geoserveraA en geoserverB dans tes fichiers.xml

Oui, c'est bien le nom de domaine qui change, vers un autre geoserver donc (https://host.A.fr/geoserver ==> https://host.B.fr/geoserver). En pensant qu'en local, l'URL est https://localhost/geoserver.

> Nous devons donc indiquer des url absolues

J'ai également des URL d'autres GeoServer. Donc cette partie fonctionnera toujours avec des URL en dur.

> ensuite en local dans ton fichier Host

Le fichier Host ?

**Comment by spelhate** [comment]
Le fichier host te permet de modifier l'adresse IP d'une adresse internet en local
exemple : 127.0.0.1  monsite.com

Et donc dans ton cas, si l'adresse IP de geoserverA est 1.2.3.4, tu ajoutes une ligne
1.2.3.4 geoserverB

Ainsi avec cette configuration, même si geoserverB est référencé dans ton fichier xml, Le host de ta machine réadressera l'URL vers geoserverA

**Comment by Gaetanbrl** [comment]
> Le host de ta machine

OK merci je n'étais pas certain de parler du même fichier :)

**Comment by Gaetanbrl** [comment]
Pour le cas d'usage lié à cette issue, voici la solution retenue afin de laisser un créateur de Mviewer la possibilité de passer un Mviewer d'une instance à l'autre sans avoir forcément besoin d'accéder au host ou à de la config spécifique (profile non admin machine) : 

```
let urlPreprod = 'url.preprod.fr' // url de développement
let host = window.location.hostname != 'localhost' ? window.location.hostname : urlPreprod;
let layerName = 'NOM_LAYER_GEOSERVER';
let  layerUrl = `https://${host}/geoserver/test/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=${layerName}&outputFormat=application%2Fjson`;
```

**Comment by spelhate** [comment]
Merci pour le partage.

**Comment by Gaetanbrl** [comment]
De rien @spelhate.
Je modifie l'intitulé pour préciser que cette solution a été testée et utilisée avec des flux GeoServer uniquement.
