### ISSUE TITLE
Page 404 pour les projets non trouvé.

### ISSUE THREAD

**Issue by RemiDesgrange** [geobretagne/mviewer#392]
Bonjour,

Pour les projets non trouvé (lorsqu'on requête un fichier projet et qu'on a un 404) on pourrait afficher un message d'erreur "projet non trouvé" ou quelque chose du style.

**Comment by Gaetanbrl** [comment]
@RemiDesgrange merci pour cette issue, qui a permis de mettre en avant le bug #393.

Ce qui peut être réalisé, c'est de passer un template ou une page html en cas d'erreur : 

https://github.com/geobretagne/mviewer/blob/32e51e1471b3dfa1597303f3955584b48416d1ed/index.html#L556-L558

**Comment by RemiDesgrange** [comment]
Oui je pense que c'est une très bonne idée.

**Comment by spelhate** [comment]
Actuellement un bug empêche l'affichage du message d'erreur. Il s'agit de cette ligne : 
https://github.com/geobretagne/mviewer/blob/32e51e1471b3dfa1597303f3955584b48416d1ed/js/mviewer.js#L315

Je peux déjà corriger ce bug pour au moins visualiser le message d'erreur?

**Comment by spelhate** [comment]
Linked to #393. Fix proposed here : 3c43d5f

**Comment by RemiDesgrange** [comment]
Nice !!!
