### ISSUE TITLE
Mviewer message alert fail if XML not exists

### ISSUE THREAD

**Issue by Gaetanbrl** [geobretagne/mviewer#393]
### Description

Lorsqu'on recherche un XML qui n'existe pas, le Mviewer ne fini pas de boucler. Le Loader reste actif.

### Attendu

Lorsqu'on regarde dans le fichier index.html, on devrait avoir un message qui averti que le fichier XMl demandé n'existe pas.

https://github.com/geobretagne/mviewer/blob/32e51e1471b3dfa1597303f3955584b48416d1ed/index.html#L556-L558

Mais le script par en erreur et l'alert ne s'affiche pas :

```
mviewer.js:315 Uncaught TypeError: mviewer.tr is not a function
    at _message (mviewer.js:315)
    at Object.alert (mviewer.js:2692)
    at <anonymous>:1:29

```

### Explications

1. La méthode `alert()` fait appel à la fonction `_message()`. 

https://github.com/geobretagne/mviewer/blob/32e51e1471b3dfa1597303f3955584b48416d1ed/js/mviewer.js#L2665-L2666

2. Dans cette fonction `_message`, on utilise la fonction de traduction `mviewer.tr()`.

https://github.com/geobretagne/mviewer/blob/32e51e1471b3dfa1597303f3955584b48416d1ed/js/mviewer.js#L311-L315

2. Cette méthode `mviewer.tr()` est crée dans la fonction `_initTranslate()` 

https://github.com/geobretagne/mviewer/blob/32e51e1471b3dfa1597303f3955584b48416d1ed/js/mviewer.js#L1461-L1462

3. Cette méthode `_initTranslate()` est appelée lors de l'init du Mviewer via `mviewer.init()`.

https://github.com/geobretagne/mviewer/blob/32e51e1471b3dfa1597303f3955584b48416d1ed/js/mviewer.js#L1840-L1842

Hors, cet méthode `mviewer.init()` n'a pas encore été appelée. L'init n'étant pas encore réalisé et ne le sera pas, puisque le XML n'existe pas.

On a donc une erreur car `mviewer.tr()` n'existe pas encore.

### Résolution

Ne pas traduire ce message ou rendre disponible la traduction avant l'init du message.

**Comment by Gaetanbrl** [comment]
> Ne pas traduire ce message ou rendre disponible la traduction avant l'init du message.

La traduction est de toute façon inaccessible, étant donné qu'on défini la langue selon les paramètre dans le XML... qui dans ce cas n'existe pas. On peut directement supprimer le `mviewer.tr()` du message.

**Comment by Gaetanbrl** [comment]
Après un essai, l'alert ne semble pas être visible non plus...

**Comment by spelhate** [comment]
Je vais proposer un fix pour ce bug. Merci @Gaetanbrl  pour tes investigations.

**Comment by Gaetanbrl** [comment]
Top @spelhate ca me va :)

**Comment by spelhate** [comment]
@Gaetanbrl you can test on issue-393 branch

**Comment by Gaetanbrl** [comment]
> @Gaetanbrl you can test on issue-393 branch

Done ! C'est bon pour moi :) merci @spelhate

**Comment by Gaetanbrl** [comment]
Je clos au merge de la PR.

**Comment by spelhate** [comment]
Ok. On attends un retour de @RemiDesgrange.

**Comment by RemiDesgrange** [comment]
> Ok. On attends un retour de @RemiDesgrange.

Désolé. C'est tout bon pour moi, super :+1:
