### ISSUE TITLE
Cluster and highlight 

### ISSUE THREAD

**Issue by Gaetanbrl** [geobretagne/mviewer#397]
@tkohr @fvanderbiest suite à PR https://github.com/geobretagne/mviewer/pull/348

Ce cas de test à été oublié lors de la réalisation et revue de la PR.

### Attendu

Lorsqu'on a une couche vecteur type cluster (démo els2.xml) on s'attend à avoir la feature consultée dans le template en surbrillance. Donc soit une feature sur la carte en jaune et d'autres en bleu si il y a plusieurs features interrogées.

### Observé

Lorsqu'on clic sur un cluster, toutes les features sont en bleu.
Lorsqu'on clic sur une feature isolée, elle apparaît en bleu.

### Analyse

Un cluster est une feature qui regroupe dans ses propriétés (`feature.getProperties()`) plusieurs features.
Lors de la surbrillance, c'est la feature du cluster qui est passée en paramètre. 

Le lien entre la feature dans le template et le cluster n'étant pas faisable :

https://github.com/geobretagne/mviewer/blob/5cca12749e1dd533933f5eec4ab45396395fcacc/js/info.js#L400-L402

... ce ne sont que des surbrillance bleus qui sont réalisées, comme si le template n'était pas ouvert et que l'on avait que des `subFeatures`.

**Comment by tkohr** [comment]
Désolé pour les bogues @Gaetanbrl et merci pour les fixes. Étant en congé de paternité, je vais essayer d'y jeter un œil dès possible.

**Comment by Gaetanbrl** [comment]
Pas de soucis @tkohr ! Ce n'est pour moi pas un bug majeur. Bonne fin de congé :wink: !

**Comment by Gaetanbrl** [comment]
@tkohr je viens de reproduire ce bug mais le template ne semble pas bien s'afficher. Ce n'était pas majeur dès lors que le template s'affichait (ou alors cela provient du customLayers mais le code me semble bon).
