### ISSUE TITLE
Interrogation données WMS carmen : fiche

### ISSUE THREAD

**Issue by lecault** [geobretagne/mviewer#4]
Lorsque l'on interroge une couche issue de carmen : http://ws.carmen.developpement-durable.gouv.fr/WMS/10/Nature_Paysage?

On ne peut pas visualiser la fiche d'information au format application/vnd.ogc.gml.

Voici un extrait de ce qu'on a en sortie : 

<?xml version="1.0" encoding="ISO-8859-1"?>

<msGMLOutput 
	 xmlns:gml="http://www.opengis.net/gml"
	 xmlns:xlink="http://www.w3.org/1999/xlink"
	 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<ZNIEFF1_layer>
	<gml:name>ZNIEFF1</gml:name>
		<ZNIEFF1_feature>
			<gml:boundedBy>
				<gml:Box srsName="EPSG:3857">
					<gml:coordinates>-446250.395765,6166781.798146 -438348.864495,6172356.634628</gml:coordinates>
				</gml:Box>
			</gml:boundedBy>
			<LB_ZONE>HAUTE VALLEE DE L&#39;ELORN-OUEST MENEZ KADOR</LB_ZONE>
			<CD_ZONE>06060002</CD_ZONE>
			<SURFACE_HA>740.165686120610000</SURFACE_HA>
			<TYPE_ZONE>1</TYPE_ZONE>
			<FICHE_PDF>06060002.pdf</FICHE_PDF>
		</ZNIEFF1_feature>
	</ZNIEFF1_layer>
</msGMLOutput>

**Comment by spelhate** [comment]
Done
