### ISSUE TITLE
Manage doc in a collaborative way

### ISSUE THREAD

**Issue by ebocher** [geobretagne/mviewer#40]
Dear all,

We propose to create a repo named doc.mviewer.region-bretagne.fr and use the readthedocs.org tool to manage a collaborative documentation.
You can find an example here http://doc.orbisgis.org/en/latest/ and the repository at this place https://github.com/orbisgis/doc.orbisgis.org

@gpetit

**Comment by spelhate** [comment]
Good idea :+1:

**Comment by ebocher** [comment]
Could you please create a repo on geobretagne, we will fork it and populate it with a doc template.

**Comment by spelhate** [comment]
Done. https://github.com/geobretagne/mviewer.doc
