### ISSUE TITLE
[docker] Github actions fail

### ISSUE THREAD

**Issue by RemiDesgrange** [geobretagne/mviewer#405]
Sur la branch master et la release 3.4 il y a un erreur de syntaxe dans le fichier yaml de github actions.

**Comment by spelhate** [comment]
Et pas dans la branche develop ?
Dernière modification du fichier : 19 juin avec ce commit : https://github.com/geobretagne/mviewer/commit/6aa70cb3d76cf9c8bb3167fe9d6a351becc62f8a

@RemiDesgrange tu peux proposer un Fix ?

**Comment by bchartier** [comment]
Je ne suis pas super au point sur les github actions donc mon intervention ici n'est peut-être pas pertinente...

> Et pas dans la branche develop ?

Dans la version actuelle du fichier docker-build.yaml, j'ai l'impression que le build n'est déclenché que sur la publication d'une release et que sur la modification du code dans la branch master. Depuis la release sur master j'ai l'impression qu'il n'y a eu aucun commit sur la branche develop. Donc on n'a pas encore eu de message d'erreur sur develop. Mais ce n'est juste qu'une question de temps car le problème est le même pour develop.

> Dernière modification du fichier : 19 juin avec ce commit : [6aa70cb](https://github.com/geobretagne/mviewer/commit/6aa70cb3d76cf9c8bb3167fe9d6a351becc62f8a)
> 
> @RemiDesgrange tu peux proposer un Fix ?

Je vois deux problèmes :
- le nom de plusieurs steps sont identiques. Pas gênant pour Github Actions mais le lecteur humain pourrait être perturber. Ça vaudrait le coup de donner des noms différents.
- l'attribut "version" est le même pour plusieurs steps. Il faudrait les rendre différents. C'est ça l'erreur qui est remontée là : https://github.com/geobretagne/mviewer/actions/runs/337742301
Comme cet attribut n'est pas utilisé on pourrait même le supprimer à mon humble avis.
Après dans la version actuelle on a plusieurs steps pour le calcul du tag de l'image pour dockerhub. Le fait de regrouper le calcul de ce tag dans un même step avec des if/else comme c'était avant posait un problème ?

**Comment by RemiDesgrange** [comment]
@spelhate je suis dessus :-)

**Comment by bchartier** [comment]
plus rapide que l'éclair

**Comment by spelhate** [comment]
@RemiDesgrange peux-tu cibler la branche develop pour la PR. Merci.

**Comment by spelhate** [comment]
erreur depuis intégration de la PR #406 dans la branche master ce matin
https://github.com/geobretagne/mviewer/actions/runs/347116777

**Comment by RemiDesgrange** [comment]
J'ai opté pour une autre approche sur la PR #448

**Comment by Gaetanbrl** [comment]
Je ferme la PR a été mergée et il n'y a plus d'erreur. Merci pour les modifications.
