### ISSUE TITLE
feature sub selection not highlighted with layers using template

### ISSUE THREAD

**Issue by spelhate** [geobretagne/mviewer#411]
When getFeatureInfos query returns many features, the next current feature displayed in carousel is not highlighted on the map.
This occurs when a template is used for the layer.
Exemple : https://kartenn.region-bretagne.fr/kartoviz/?config=demo/attributefilter.xml

**Comment by Gaetanbrl** [comment]
Je viens de tester en local avec `/demo/attributefilter.xml` et je ne reproduis pas.

* J'ai crée un template simple : 

```
{{#features}}
	<li id="{{feature_ol_uid}}" class="item" style="width:238px;">
		Nom : {{titre_courant}}
		<br>
		Phase : {{phase}}		
	</li>
{{/features}}
```


* J'ai ensuite testé : j'ai bien une surbrillance jaune qui se déplace selon l'item en lecture

Je crois que ca vient de l'id de la feature qui doit être dans le template pour que cela fonctionne : 

`<li id="{{feature_ol_uid}}" class="item" style="width:238px;">`

**Comment by spelhate** [comment]
Effectivement, c'est parce qu'il manque id="{{feature_ol_uid}}" dans les templates utilisés. On peut en modifiant le stock de templates résoudre le problème.

**Comment by spelhate** [comment]
Il faut peut-être indiquer dans les notes de release, la nécessité de reprendre les templates existants pour ajouter ce paramètre.

**Comment by Gaetanbrl** [comment]
> Il faut peut-être indiquer dans les notes de release, la nécessité de reprendre les templates existants pour ajouter ce paramètre.

Avant ton issu c'est vrai que je n'avais pas fait le lien avec le feature_id nécessaire dans le template. Il faudrait autrement modifier ce comportement et ne pas afficher de rond jaune s'il y en a un. Que des ronds bleus dans ce cas.

D'ailleurs je ne sais même plus si ce style est configurable (rond jaune / bleu) si on ne veut que des contours ?

**Comment by spelhate** [comment]
> faudrait autrement modifier ce comportement et ne pas afficher de rond jaune s'il y en a un. Que des ronds bleus dans ce cas.

👍 

> D'ailleurs je ne sais même plus si ce style est configurable (rond jaune / bleu) si on ne veut que des contours ?

Non ce n'est pas paramétrable et ça m'embête. Je pense que je vais proposer une évolution pour ça.

**Comment by lecault** [comment]
Résolu je ferme
