### ISSUE TITLE
Affichage de la légende : cas d'une couche avec visibilité selon échelle

### ISSUE THREAD

**Issue by lecault** [geobretagne/mviewer#415]
**Description du bug / Describe the bug**

On a une couche avec une visibilité dépendante de l'échelle. Voici un extrait du XML :

<layer id="CP.CadastralBuilding" name="Bâti" scalemin="0" scalemax="25000" visible="false" tiled="true" queryable="false" fields="" aliases="" infoformat="application/vnd.ogc.gml" featurecount="5" style="cadastre_bati_type" legendurl="" url="https://geobretagne.fr/geoserver/cadastre/wms" attribution="DGFIP" metadata="https://geobretagne.fr/geonetwork/srv/eng/catalog.search?node=srv#/metadata/91811bc9-308a-4ddb-9c15-c69b3c0bb067" metadata-csw="https://geobretagne.fr/geonetwork/srv/eng/csw?SERVICE=CSW&VERSION=2.0.2&REQUEST=GetRecordById&elementSetName=full&ID=91811bc9-308a-4ddb-9c15-c69b3c0bb067"/>

**Reproduire le bug / To Reproduce**

Etapes à suivre pour reproduire votre problème du type : 

1. Aller sur la plage https://kartenn.region-bretagne.fr/kartenn/?x=-294180&y=6151264&z=8.666666666666666&l=CPCadastralBuilding*&lb=osm1&config=apps%2Fdefault.xml&mode=d2. 

La légende de la couche s'affiche comme dessous : 
![image](https://user-images.githubusercontent.com/5269430/98363964-2c60ea00-2030-11eb-87c5-7c9cf7fb6fed.png)

2. Je change de zoom : l'affichage de la légende évolue : on ne voit plus le getlegendgraphic

![image](https://user-images.githubusercontent.com/5269430/98364000-44386e00-2030-11eb-845a-cf4c4392a604.png)

**Comportement attendu / Exptected behavior**

Garder le comportement d'affichage par défaut avec la légende et le picto qui signale que la couche n'est pas visible.

**Environnement / Desktop**

Merci de remplir ces informations si connues :
 - OS: Windows
 - Navigateur / browser : Chrome, Firefox
 - Version mviewer : 3.4.1

**Comment by lecault** [comment]
Dans la class class="mv-legend" le src passe de 

https://geobretagne.fr/geoserver/cadastre/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetLegendGraphic&SLD_VERSION=1.1.0&FORMAT=image/png&WIDTH=30&HEIGHT=20&LEGEND_OPTIONS=fontName%3AOpen%20Sans%3BfontAntiAliasing%3Atrue%3BfontColor%3A0x777777%3BfontSize%3A10%3Bdpi%3A96&TRANSPARENT=true&LAYER=CP.CadastralBuilding&STYLE=cadastre_bati_type

à

https://kartenn.region-bretagne.fr/kartenn/img/invisible.png

**Comment by Gaetanbrl** [comment]
En regardant le comportement de la démo, en effet la légende ne devrait pas être visible à l'ouverture du Mviewer.

**Comment by Gaetanbrl** [comment]
Le code passe bien dans la condition comme attendu. Par contre le DOM semble partiellement affecté.
Le même code lancé dans la console au chargement de la carte cache bien la légende pourtant...

https://github.com/geobretagne/mviewer/blob/34a9c009bc7e4fa099f0e078a9acfaa88e762763/js/mviewer.js#L951-L952

**Comment by Gaetanbrl** [comment]
Le soucis vient de ces lignes :

https://github.com/geobretagne/mviewer/blob/68611d50b809e00b1e74aebe60d6cf706608ea03/js/mviewer.js#L2461-L2462

Alors qu'on a bien géré l'affichage de la légende (voir commentaire précédent), l'ajout sur la carte et dans la légende de la couche va ensuite change l'image dans la légende pour afficher l'image prévue dans le config.xml.

**Comment by lecault** [comment]
J'ai trouvé quelque chose : j'ai le soucis quand il y a un style de défini qui n'est pas le style par défaut. Exemple tu utilises la couche parcelle on a le comportement normal.

**Comment by spelhate** [comment]
Ca progresse. Je pourrai regarder ça lundi.

**Comment by lecault** [comment]
La correction de Gaetan fonctionne, je teste si pas de downgrade.
