### ISSUE TITLE
Multi tooltip ?

### ISSUE THREAD

**Issue by Gaetanbrl** [geobretagne/mviewer#417]
### Description

Le fonctionnement des infobulles permet de ne voir les infobulles que d'une seule et unique couche à la fois.
L'issue #323 explique bien les échanges sur ce sujet et sur la quasi dernière grosse issue sur les tooltip.
Ce sujet ne semble cependant pas tout à fait terminé.

Par @spelhate :

```
En fait et c'est ancien, c'est le fonctionnement de la case à cocher "Afficher les infobulles" qui n'est pas logique. Pour être plus précis, il faudrait afficher "Afficher uniquement les infobulles de cette couche".
Je propose de valider la PR en l'état et on pourra revenir sur ce disfonctionnement qui n'est pas lié à l'évolution plus tard.
```

### Question
Concernant la dernière phrase, quels sont les travaux à prévoir ?
Il s'agit de renommer "Afficher les infobulles" par "Afficher uniquement les infobulles de cette couche" uniquement ?

**Comment by Gaetanbrl** [comment]
ok @spelhate je viens de voir la PR que tu avais fait :

https://github.com/geobretagne/mviewer/commit/0211e5bea85541181b7de3127767b5541d641b97

### Question 2

Des utilisateurs me demandent s'il est possible d'afficher les infobulles de plusieurs couches en même temps ?

merci ;)

**Comment by spelhate** [comment]
> Concernant la dernière phrase, quels sont les travaux à prévoir ?
> Il s'agit de renommer "Afficher les infobulles" par "Afficher uniquement les infobulles de cette couche" uniquement ?

Pas de travaux en cours de mon côté. Renommer le texte associé à la fonctionnalité permettrait, à moindre frais, de ne pas induire l'utilisateur en erreur.

**Comment by spelhate** [comment]
> ### Question 2
> Des utilisateurs me demandent s'il est possible d'afficher les infobulles de plusieurs couches en même temps ?
> 
> merci ;)

Non pas actuellement.

**Comment by Gaetanbrl** [comment]
Merci @spelhate sujet clos.
