### ISSUE TITLE
Improve height of help panel

### ISSUE THREAD

**Issue by gpetit** [geobretagne/mviewer#42]
Hi,
Currently, the height of the "help" panel is fixed in all the .css files as following :

```
/* Help panel */

#help .modal-content{
	font-family: 'roboto_regular', Arial, Sans-serif!important;
	height: 880px;
}
```

To suit in a better way the content of each tabs and to avoid big white page when you just have one line of text, it will nice to replace the height parameter by ```auto```

```
#help .modal-content{
	font-family: 'roboto_regular', Arial, Sans-serif!important;
	height: auto;
}
```
To illustrate this issue, you can see the potential result here : http://mapuce.orbisgis.org/

If you think this modification is interesting for the MViewer community, I can make a PR.

**Comment by spelhate** [comment]
Yes You can make a PR.
Thank's.

**Comment by gpetit** [comment]
Thanks
