### ISSUE TITLE
Mise en évidence d'une entité (customlayers) persistante après survol.

### ISSUE THREAD

**Issue by eprouteau** [geobretagne/mviewer#422]
**Description du bug**

Suite à la dernière MAJ, sur une customlayers, lors du survol avec tooltip sur la version précédente, la mise en évidence s'effaçait lorsque le curseur n'était plus sur l'entité. Avec la dernière mise à jour, lorsque le curseur survol une entité, la mise en évidence reste effective.

**Reproduire le bug**

Version déployée en local pour le moment.

**Comportement attendu**

Lorsque le curseur n'est pas sur une entité que la dernière entité survolée ne reste pas en évidence (comportement de la précédente version)

**Screenshots**

Comportement sur l'ancienne version : http://emeric-prouteau.alwaysdata.net/gis/?config=apps/rando_dordogne/rando_dordogne.xml#

Capture sur la nouvelle : 

![image](https://user-images.githubusercontent.com/1401902/99379709-4d93c700-28c9-11eb-8dc2-4a41d82567b8.png)

**Environnement**

Merci de remplir ces informations si connues :
 - OS: Windows 10
 - Navigateur Chrome
 - Version mviewer 3.4.1

**Informations complémentaires**

Problème suite à la nouvelle version 3.4.1

**Comment by Gaetanbrl** [comment]
@eprouteau lorsque tu survol une entité, la surbrillance ne s'enlève pas c'est cela ? 
Je n'arrive pas à reproduire sur le lien que tu as mis dans l'issue.

http://emeric-prouteau.alwaysdata.net/gis/?config=apps/rando_dordogne/rando_dordogne.xml#

**Comment by eprouteau** [comment]
Le lien est basé sur l'ancienne version avec le comportement à mon avis fonctionnel. Je reproduis l'erreur sur mon espace dev en local. Je vais voir pour le passer sur mon serveur

**Comment by Gaetanbrl** [comment]
Ok merci @eprouteau la surbrillance de la dernière feature survolée semble effectivement ne pas être supprimée.

**Comment by Gaetanbrl** [comment]
@eprouteau fix apporté et testable sur develop.

**Comment by eprouteau** [comment]
@Gaetanbrl Test réalisé en local et fonctionnel. Au top pour la réactivité

Bonne journée

**Comment by Gaetanbrl** [comment]
Merci du retour @eprouteau je clos les deux issues.
