### ISSUE TITLE
Push pin à chaque clic sur la carte

### ISSUE THREAD

**Issue by eprouteau** [geobretagne/mviewer#424]
**Description du bug**

Dans la nouvelle version lors d'un clic sur la carte hors entité, une push Pin apparait. Ce comportement n'était pas présent sur la précédente version. 

**Reproduire le bug**

Bug reproduit sur la démo suivante : 

https://kartenn.region-bretagne.fr/kartoviz/?config=demo/vector.xml

**Comportement attendu**

Ne pas avoir de push pin qui s'affiche à chaque clic sur la carte

Lien vers une application dans l'ancienne version ne présentant pas ce comportement : 

http://emeric-prouteau.alwaysdata.net/gis/?config=apps/rando_dordogne/rando_dordogne.xml#

**Screenshots**

![image](https://user-images.githubusercontent.com/1401902/99406794-9d38b980-28ee-11eb-91b9-a97649da30ba.png)

**Environnement / Desktop**

 - OS: Windows 10
 - Navigateur Chrome
 - Version 3.4.1

**Informations complémentaires**

Problème apparu sur la nouvelle version 3.4.1

**Comment by Gaetanbrl** [comment]
je pense que c'est dû à cette PR qui avait été réalisée pour corriger un soucis de marker suite à l'ajout de la surbrillance.

https://github.com/geobretagne/mviewer/pull/396

je vais jeter un oeil.

**Comment by Gaetanbrl** [comment]
Le problème provient de cette condition : 

https://github.com/geobretagne/mviewer/blob/68611d50b809e00b1e74aebe60d6cf706608ea03/js/info.js#L428-L432



* Pour une recherche Fuse => Ok
* Pour une recherche BAN on doit afficher le marker sur aucune données (comme un click)
Donc pour la BAN c'est ce morceau qui permet de savoir si on a des données ou non pour afficher le marker sur l'adresse : 
`(!_queriedFeatures.length && !_firstlayerFeatures.length)`

Sauf que les conditions sont les mêmes pour un clic sans data sous les coordonnées.

Je vais compléter ce contrôle.

**Comment by Gaetanbrl** [comment]
@eprouteau fix apporté et testable sur develop.

**Comment by eprouteau** [comment]
@Gaetanbrl Test réalisé en local et fonctionnel. Au top pour la réactivité

Bonne journée
