### ISSUE TITLE
Bug affichage fiche d'info si aucune géométrie retournée

### ISSUE THREAD

**Issue by spelhate** [geobretagne/mviewer#428]
Bug introduit par le commit cae978de3c2ac6e2a5c88f110b3b66e280676579

Les 2 lignes posant problème :https://github.com/geobretagne/mviewer/blob/68611d50b809e00b1e74aebe60d6cf706608ea03/js/info.js#L320-L322

Le bloc de code permettant d'afficher le contenu de la réponse n'est pas exécuté si  cette réponse ne contient pas de géométrie

**Comment by Gaetanbrl** [comment]
> Le bloc de code permettant d'afficher le contenu de la réponse n'est pas exécuté si cette réponse ne contient pas de géométrie

En effet c'était souhaité, (si pas de geom, rien à mettre en surbrillance, pas de géopin). Quel est comportement prévu s'il n'y a pas de géométrie ?

**Comment by spelhate** [comment]
Que la fiche d'info s'affiche quand même ;-)

**Comment by spelhate** [comment]
cette partie du code n'est pas exécutée si abscence de géométrie dans la réponse GetFeatureInfo
https://github.com/geobretagne/mviewer/blob/68611d50b809e00b1e74aebe60d6cf706608ea03/js/info.js#L324-L330

**Comment by spelhate** [comment]
C'est juste l'accolade fermante du bloc if qui est à déplacer.

**Comment by Gaetanbrl** [comment]
> cette partie du code n'est pas exécutée si abscence de géométrie dans la réponse GetFeatureInfo

C'est vrai qu'on a eu des soucis avec geoserver et/ou openLayers lors d'affichage de données avec des features sans geom, donc je pensais que ce cas était de base non fonctionnel à l'init du layer.

**Comment by spelhate** [comment]
Je propose un Fix.

**Comment by Gaetanbrl** [comment]
merci @spelhate

**Comment by Gaetanbrl** [comment]
@spelhate on peut fermer ?

**Comment by spelhate** [comment]
Yes
