### ISSUE TITLE
Lien temporalité et template Mustache

### ISSUE THREAD

**Issue by pbarille** [geobretagne/mviewer#434]
**Description / Describe**

Bonjour,
Je souhaiterais pouvoir créer un lien entre la barre de slide temporalité présente dans la légende et la fiche d'information (template Mustache).

**Description détaillée / Detailed description**

Voici le comportement souhaité :
- Lors de la modification de la date dans la barre de slide, la carte est actualisée (fonctionnalité déjà existante) et si une fiche d'information est ouverte elle est actualisée également (fonctionnalité à développer).
- De la même manière il serait intéressant que la temporalité puisse apparaître dans la fiche d'information et que la modification de la date entraine la mise à jour de la fiche, de la carte et de la barre de slide

**Informations complémentaires / Additional context**

Je peux essayer d'y consacrer un peu de temps si vous pensez que ça peut être fait sans toucher au cœur de l'application. J'ai peur que mes connaissances en développement ne me permettent pas d'aller plus loin...

Merci !

**Comment by Gaetanbrl** [comment]
Bonjour, @pbarille ,

C'est réalisable en utilisant les événement du slider (voir la doc de la lib utilisée pour plus d'infos sur cet event - ou dans le code Mviewer).

A partir de là, vous pouvez ensuite ajouter dans le Mustache du JavaScript pour que la fiche écoute les modification faites sur slider. 

Le JavaScript permettra de modifier une `<div>` du template via l'ID de la div. Ex non du concept dont la syntaxe est à adapter selon la doc du slider pour la gestion de l'event et la récupération de la valeur : 

```
$(slider).change(function() {
  $('#id_de_ma_div').val($(slider).val());
})
```

Pour ajouter du JS dans la fiche il faut une syntaxe de ce type :

```
{{#features}}
<div id="random-{{ID}}">

<script>
// affiche l'attribut ID dans la console
$(slider).change(function() {
  $('#{{ID}}').val($(slider).val());
})
</script>
{{/features}}
```

:exclamation: Attention  :warning: :

Si vous  cliquez sur plusieurs items et que le template affiche le carousel (les flêches pour changer d'objet), alors dans ce context Mustache est JavaScript s'embrouille dans les contexte. Il faut donc faire attentionn que l'ID récupéré via la syntaxe `{{ID}}` dans le JavaScript soit bien l'ID de la div ciblée !

**Comment by pbarille** [comment]
Merci @Gaetanbrl pour ces pistes et pour la rapidité de réponse une fois de plus ! 
Je regarde ça et je vous fait un retour dès que j'arrive à quelque chose.

**Comment by Gaetanbrl** [comment]
@pbarille cette issue est-elle toujours d'actualité ?

**Comment by pbarille** [comment]
Bonjour,
Je n'ai malheureusement pas eu le temps de me pencher sur le sujet et je n'aurais pas le temps dans les prochaines semaines.
Je clos et je rouvrirais si besoin par la suite, mais je pense que j'ai tous les éléments dans ta réponse @Gaetanbrl

**Comment by pierrejego** [comment]
Je vais certainement avoir le même besoin a développer dans les quelques semaines à venir.

**Comment by Gaetanbrl** [comment]
L'issue #378 est probablement liée
