### ISSUE TITLE
Multilinguisme icône drapeau manquante

### ISSUE THREAD

**Issue by t-loree** [geobretagne/mviewer#437]
**Description du bug / Describe the bug**

Bonjour, depuis la version 3.4 du mviewer les drapeaux à l'intérieur des boutons permettant de changer de langue n'apparaissent plus.

**Reproduire le bug / To Reproduce**

https://kartenn.region-bretagne.fr/kartoviz/?config=demo/lang.xml#

**Environnement / Desktop**

 - Navigateur : Firefox, Chrome

Bonne journée

**Comment by Gaetanbrl** [comment]
Le dossier contenant les drapeau SVG est manquant depuis l'internalisation de la lib (Mviewer non dépendant des fluxs CDNJS).

https://github.com/lipis/flag-icon-css/tree/master/flags

**Comment by Gaetanbrl** [comment]
Testé sur branche develop et appli /lang.xml

![image](https://user-images.githubusercontent.com/16317988/101633053-0495e500-3a27-11eb-9703-6948e5310ea0.png)

**Comment by Gaetanbrl** [comment]
@t-loree  Vous pouvez tester la branche develop et fermer l'issue si cela fonctionne bien chez vous.

**Comment by t-loree** [comment]
Tout fonctionne chez moi, merci.
