### ISSUE TITLE
Numéro de version visible - Loader ou autre

### ISSUE THREAD

**Issue by Gaetanbrl** [geobretagne/mviewer#440]
**Description détaillée / Describe**

En tant qu'utilisateur, 
Je souhaiterai pouvoir voir clairement le numéro de version que j'utilise,
Afin de pouvoir communiquer ce numéro dans une issue quand je dois en créer une,
Sans ouvrir la console, 

**Description détaillée / Detailed description**
Propositions : 

* Sur la page du loader au démarrage sous le titre.
* A côté de la source du fond de plan 
![image](https://user-images.githubusercontent.com/16317988/102365374-c87afb00-3fb7-11eb-911f-a6a57a394cd4.png)

* Via un bouton de la toolbar spécifique type "A propos"
* Via un bouton type "Aide" pour voir les informations type navigateur utilisé (si possible), la version Mviewer, le lien vers le HitHub pour déposer une issue, poser une question, le lien vers la doc >> Ce dernier point peut-être une nouvelle issue.

**Comment by spelhate** [comment]
La proposition la plus rapide à mettre en œuvre : sur la page du loader.

**Comment by spelhate** [comment]
En complément : ajout de la mention mviewer.
Exemple **Propulsé par mviewer 3.5.1**

**Comment by Gaetanbrl** [comment]
Proposition @lecault @spelhate - c'est plus discret comme ca ? 

![image](https://user-images.githubusercontent.com/16317988/109633496-71151180-7b48-11eb-9899-0dbc282bfd9b.png)


Vue mobile : 

![image](https://user-images.githubusercontent.com/16317988/109633553-81c58780-7b48-11eb-9c96-853b40d26589.png)

**Comment by lecault** [comment]
moi ça me va

**Comment by bchartier** [comment]
Au niveau de l'apparence parfait.
Au niveau du nom on avait dit tout en minuscules.

**Comment by Gaetanbrl** [comment]
> Au niveau du nom on avait dit tout en minuscules.

Désolé, j'avais oublié que ca concerné également le nom...

C'est corrigé @bchartier
