### ISSUE TITLE
How to use WMTS and XYZ flux

### ISSUE THREAD

**Issue by Ailurupoda** [geobretagne/mviewer#446]
Hi,

I have 2 questions : 
  - First about the WMTS : 
I would like to use a WMTS as basemap and also as a layer.
How can i configure the basemap to be able to display my WMTS ? What are the needed parameters to this kind of flux ?
If i want to use a WMTS as a layer, is it possible ? Do i need to create a customLayer for this ?

  - Second about the XYZ
 I already manage to use XYZ as basemap, but to use as a layer it's not the same.
 Is it possible to use that kind of flux as a Layer ? Does this need to be created as a customLayer ?
 
 Is there some solutions, or do we need to have only WMS, or geojson file if we want to display layer ?
 
 Thanks in advance

**Comment by bchartier** [comment]
clarification: XYZ layer = TMS layer in this issue, not XYZ elevation file

**Comment by Ailurupoda** [comment]
Yes, indeed, XYZ for TMS :)

**Comment by Gaetanbrl** [comment]
@Ailurupoda

* To use WMTS as new basemap you could check the doc part about baseLayer: 

https://mviewerdoc.readthedocs.io/fr/latest/doc_tech/config_baselayers.html?highlight=WMTS

* To use WMTS as layer, not sur it's possible

* To use XYZ service as customlayer Tilelayer (best solution i guess) :  

https://openlayers.org/en/latest/examples/xyz.html

**Comment by Gaetanbrl** [comment]
@Ailurupoda could we close this issue ?

**Comment by bchartier** [comment]
> @Ailurupoda
> 
> * To use WMTS as new basemap you could check the doc part about baseLayer:
> 
> https://mviewerdoc.readthedocs.io/fr/latest/doc_tech/config_baselayers.html?highlight=WMTS
> 
> * To use WMTS as layer, not sur it's possible
> * To use XYZ service as customlayer Tilelayer (best solution i guess) :
> 
> https://openlayers.org/en/latest/examples/xyz.html

For XYZ you suggest to create a custom layer using the OpenLayer API, that's right?

**Comment by Gaetanbrl** [comment]
> For XYZ you suggest to create a custom layer using the OpenLayer API, that's right?

That's depend what you need ? If you need more than a basemap it maybe the best solution. 

I had already use a WMS / XYZ as customLayer and that works. Great to change WMS properties dynamically as CQL, SLD... if you don't need WFS (more consumptive).

**Comment by bchartier** [comment]
@Gaetanbrl: I misunderstood your suggestion. My comment was useless. Sorry.
