### ISSUE TITLE
Not able to see Mviewer on Chrome locally

### ISSUE THREAD

**Issue by gpetit** [geobretagne/mviewer#45]
Not sure this is really a bug, but this "behaviour" is a bit strange.

When I'm editing MViewer on my machine, I'm not able to see the result in Chrome and I have the following error message : 
```
Fichier de configuration : config.xml non trouvé ou incorrect !
```
In the meantime, the same index.html file works well on Firefox (on the right side in the screenshot below)

![mviewer](https://cloud.githubusercontent.com/assets/1871248/25736875/e6078738-3174-11e7-9410-1ad883084f45.png)

Note that : 
- All the files are readable and writable
- When the website is online, it works perfectly on Chrome

**Comment by spelhate** [comment]
Mviewer uses` http://` protocol to load config.
 `file://` is not http protocol.
However you can customize Chrome to allow localy files access with tis parameter :  --allow-file-access-from-files. See https://chrisbitting.com/2014/03/04/allow-local-file-access-in-chrome-windows for more details.

**Comment by gpetit** [comment]
Many thanks for the tip. It works well with this parameter
