### ISSUE TITLE
Zoom sur une geometry

### ISSUE THREAD

**Issue by Arcko-03** [geobretagne/mviewer#450]
Bonjour,

J'ai fait un custom control avec des liste déroulantes successives pour effectuer une recherche cadastrale, mais je n'arrive pas à faire en sorte que cela zoom sur la parcelle qui a été sélectionné. J'ai essayé le code qui est dans les exemple mais cela ne fonctionne pas et des fonctions ne sont pas reconnus. je récupère l'ID de la feature comment je peux faire pour effectuer le zoom avec cela ?

Ma fonction de zoom actuellement:
`var zoomCad = function(){`
`        let feature = getFeatureById(formulaire.choixNum.value)`
`        let res = mviewer.getMap().getView().getResolutionForExtent(feature.getGeometry().getExtent());`
`        let zoom = mviewer.getMap().getView().getZoomForResolution(res);`
`        mviewer.getMap().getView().fit(feature.getGeometry(), {maxZoom: zoom - 5});`
`    }`

Merci d'avance de votre aide

**Comment by Gaetanbrl** [comment]
Bonjour @Arcko-03.

> J'ai essayé le code qui est dans les exemple

Quels sont les exemples que vous avez vu ?
Si vous avez des erreurs de fonctions inconnues, alors il faudrait nous préciser lesquelles ?


D'après votre code, la fonction `getFeatureById` doit en effet exister. Elle permet de récupérer toute la feature à partir de son ID pour ensuite récupérer sa géométrie et se placer sur sont étendue.

**Comment by Arcko-03** [comment]
Bonjour, merci de votre réactivité, 
Je me suis inspiré de l'exemple: [https://kartenn.region-bretagne.fr/kartoviz/?config=demo/cad/cad.xml](url)

Oui normalement elle existe, mais j'ai cette erreur:
![Capture](https://user-images.githubusercontent.com/61544853/107615308-335d5100-6c4c-11eb-8a37-38f1a9757a37.PNG)

**Comment by Gaetanbrl** [comment]
En effet il manque la fonction `getFeatureById`.

Je ne vois cependant pas dans le code de cad.xml cet appel de fonction.

Il vous faut la créer donc. Cette fonction qui prend en paramètre d'entré un ID permet de parcourir toute la couche et d'obtenir la feature qu ia le même ID (dans le cas d'un customLayer).

Si la couche n'est pas un customLayer mais est chargée en WMS (image), vous devrez faire un appel WFS type GetFeature avec un filtre CQL et l'ID pour récupérer la feature et donc sa géométrie pour ensuite zoom sur l'extent.

# Exemple

Voici un exemple pour parcourir une couche (vector - customLayer) et récupérer la feature à partir de son ID : 

```
getFeatureById(layer, id) {
    let findFeatures =  layer.getSoruce().getFeatures().map( feature => feature.getProperties().id === myID);
    return findFeatures.length ? findFeatures[0] : null;
}

const layerId = 'myCustomLayerId';
const layer = mviewer.getLayer(layerId);
const idFeature = 23548;
let myFeature = getFeatureById(layer, idFeature);

if (myFeature) {
    // zoomToExtent
}
```

L'exemple est sûrement à adapter je n'ai plus toutes les syntaxes en tête mais c'est classique pour OpenLayers et Mviewer.

**Comment by Arcko-03** [comment]
Merci beaucoup pour votre réponse, je vais essayer tout ça.

> Si la couche n'est pas un customLayer mais est chargée en WMS (image), vous devrez faire un appel WFS type GetFeature avec un filtre CQL et l'ID pour récupérer la feature et donc sa géométrie pour ensuite zoom sur l'extent.

Oui ma couche est chargé en WMS, ce n'est pas un customLayer.
Si j'utilise par exemple ce lien WFS avec le filtre sur l'id de la feature: [https://sig-test.hauteloire.fr/geoserver/cd43/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=cd43%3Apci_parcelles&outputFormat=application/json&featureId=pci_parcelles.3](https://sig-test.hauteloire.fr/geoserver/cd43/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=cd43%3Apci_parcelles&outputFormat=application/json&featureId=pci_parcelles.3)

Dans mon custom control, je récupère juste toutes la partie geometry du WFS dans un tableau et j'utilise une fonction fit pour zoomer sur ma geometry ? cela fonctionnerai comme cela ?

Merci

**Comment by Gaetanbrl** [comment]
> Dans mon custom control, je récupère juste toutes la partie geometry du WFS dans un tableau et j'utilise une fonction fit pour zoomer sur ma geometry ? cela fonctionnerai comme cela ?

A partir de votre requête vous pouvez en effet faire une requête Ajax et à partir de la réponse récupérer la géométrie pour faire un fit.

Tableau ou pas, ca c'est à vous de voir mais ce ne sera pas forcément utile car vous obtenez directement la feature avec featureId (si l'ID est bien une valeur unique).

**Comment by spelhate** [comment]
En complément de l'assistance apportée par @Gaetanbrl , je précise que la démo cad n'utilise pas de fonction `getFeatureById`  et utilise 2 sources de données différentes
 * les flux wms de cadastre.gouv.fr pour l'affichage du fond de plan
 * les flux wfs des couches (communes, sections et parcelles) du cadastre.
Le requêtage se fait via wfs et la requête OGC WFS GetFeature
