### ISSUE TITLE
Modification du style de sélection d'un polygone

### ISSUE THREAD

**Issue by lecault** [geobretagne/mviewer#451]
**Description détaillée / Describe**

Suite à une remarque d'un utilisateur, je souhaite modifier le style de sélection d'un polygone qui est orange par défaut
![image](https://user-images.githubusercontent.com/5269430/107757162-7808eb00-6d25-11eb-9839-071d57e986e7.png)

**Evolution proposée**

Je sais que l'on peut modifier ce style (je ne sais pas où) dans le cœur du code.
Mon souhait d'évolution serait d'extraire cela du cœur du code pour un fichier de configuration propre à ma structure qui ne soit pas modifié lors des git pull de mon mviewer.

**Comment by Gaetanbrl** [comment]
Cette évolution peut également concerner les couches fonctionnelles et autres overlays donc.

On pourrait utiliser des variables spécifique propres à une couche cible. Ce serait donc un fichier à préciser comme paramètre dans le <app> du config.

Sinon passer par un plugin et ne rien changer dans le coeur / mécanique actuelle pour surcharger les styles de couche par défaut.

**Comment by spelhate** [comment]
Je propose dans un premier temps de définir globalement les styles (point, ligne, poly) dans le config.xml - section mapoptions.

Dans un second temps, il sera possible de surcharger cette configuration couche par couche.

**Comment by Gaetanbrl** [comment]
> Je propose dans un premier temps de définir globalement les styles (point, ligne, poly) dans le config.xml 

Uniquement pour les couleurs ? Quelles autres options tu envisagerai sans que ce soit trop lourd dans le config ?

**Comment by lecault** [comment]
Epaisseur et transparence ? Ca peut dépendre du fond de plan utilisé et de ce qu'on veut en faire.

Ici par exemple, ils veulent faire des imprims écran donc voir ce qu'il y a derrière.

**Comment by spelhate** [comment]
Comme le suggère @lecault , les options pourraient être
* couleur
* transparence
* épaisseur

exemple :
```
<highlightstyle>
    <style type="point" fillcolor="#ff0000" opacity="0.5" strokecolor="ffffff" strokewidth="1" />
    <style type="line" color="#ff0000" opacity="0.5" strokecolor="ffffff" strokewidth="1"
    <style type="polygon" color="ff0000"opacity="0.5" strokecolor="ffffff" strokewidth="1"
</highlightstyle>
```

**Comment by spelhate** [comment]
Actuellement, les styles Points, Ligne et polygones sont générés automatiquement à partir de la fourniture d'un code couleur pour la sélection et d'un code couleur pour la sous sélection.
 * Les points sont des cercles de **radius** 7 , **opacité** 50% pour la couleur intérieure et **contour** de même couleur avec une **opacité** 100% et une **largeur** de 4
 * Les lignes ont **contour** de 4 avec une **opacité** de 100%
 * Les polygones ont une opacité de 50% pour la couleur intérieure et **contour** de même couleur avec une **opacité** 100% et une **largeur** de 4

A périmètre iso fonctionnel il nous faudrait les paramètres suivants :
```
<selectiontstyle>
    <style type="point" radius="7" fillcolor="82, 98, 217" opacity="0.5" strokecolor="82, 98, 217" strokewidth="1" />
    <style type="line" color="82, 98, 217" opacity="0.5" strokecolor="82, 98, 217" strokewidth="1"
    <style type="polygon" color="82, 98, 217"opacity="0.5" strokecolor="82, 98, 217" strokewidth="1"
</selectionstyle>
<subselectiontstyle>
    <style type="point" radius="7" fillcolor="82, 98, 217" opacity="0.5" strokecolor="82, 98, 217" strokewidth="1" />
    <style type="line" color="82, 98, 217" opacity="0.5" strokecolor="82, 98, 217" strokewidth="1"
    <style type="polygon" color="82, 98, 217"opacity="0.5" strokecolor="82, 98, 217" strokewidth="1"
</subselectionstyle>
```
@Gaetanbrl , @lecault qu'en pensez-vous ?

**Comment by Gaetanbrl** [comment]
Je n'ai pas trop d'avis sur le style par défaut.
Tant qu'on retrouve le style par défaut si la config ne comprend pas les balises `<selectionstyle>` et `<subselectionstyle>`, ca me convient.

**Comment by spelhate** [comment]
> Tant qu'on retrouve le style par défaut si la config ne comprend pas les balises `<selectionstyle>` et `<subselectionstyle>`, ca me convient.

Bien entendu. Il s'agit de paramètres optionnels. La configuration par défaut s'appliquera en l'absence de ces paramètres.

**Comment by spelhate** [comment]
> Je n'ai pas trop d'avis sur le style par défaut.

Et sinon sur les possibilités de personnalisation ? Le paramétrage te semble suffisamment complet ? (fillcolor, strokecolor, strokewidth, opacity, radius) ?

**Comment by Gaetanbrl** [comment]
> Et sinon sur les possibilités de personnalisation ?

Oui c'est bien comme ca. On pourrait quasiment rajoute les lignes discontinues (lineDash) mais c'est du détail je pense ?

**Comment by spelhate** [comment]
Je teste une première implémentation à partir de ces 2 cas d'usage

Une configuration complète qui permet de tout redéfinir (couleurs, opacité...)
```
    <styles>
        <selectionstyle>
            <point radius="7" fillcolor="26, 188, 156" opacity="0.5" strokecolor="26, 188, 156" strokewidth="4" />
            <line opacity="0.5" strokecolor="26, 188, 156" strokewidth="4" />
            <polygon fillcolor="26, 188, 156" opacity="0" strokecolor="26, 188, 156" strokewidth="4" />
        </selectionstyle>
        <subselectionstyle>
            <point radius="7" fillcolor="175, 122, 197" opacity="0.5" strokecolor="175, 122, 197" strokewidth="2" />
            <line opacity="0.5" strokecolor="175, 122, 197"  strokewidth="2" />
            <polygon fillcolor="175, 122, 197" opacity="0" strokecolor="175, 122, 197" strokewidth="8" />
        </subselectionstyle>
    </styles>
```

Une configuration plus légère qui surcharge la configuration par défaut avec les seuls paramètres fournis :

 ```
 <styles>
        <selectionstyle>            
            <polygon opacity="0"  strokewidth="4" />
        </selectionstyle>
        <subselectionstyle>           
            <polygon opacity="0"  strokewidth="8" />
        </subselectionstyle>
    </styles>
```

**Comment by lecault** [comment]
Fait dans la dernière version
