### ISSUE TITLE
Template et surbrillance ne fonctionne pas sans id

### ISSUE THREAD

**Issue by Gaetanbrl** [geobretagne/mviewer#458]
**Description du bug / Describe the bug**

Lorsqu'on utilise une couche GeoJSON, le champ `id` n'est pas forcément un attribut présent dans la couche.
C'est le cas si une couche a un identifiant unique qui n'est pas un `id`. Le champ identifiant ne s'appellera donc pas `id`.

Ce cas peut se produire avec une couche de test.

Cette absence de champ "id" est bloquant dans le système de sélection avec mise en surbrillance  : 

https://github.com/geobretagne/mviewer/blob/68611d50b809e00b1e74aebe60d6cf706608ea03/js/info.js#L407

Le carrousel génère alors une erreur et toutes les features retournées par le GetFeatureInfo se charge dans le même panel.

```
Uncaught TypeError: Cannot read property 'id' of undefined
    at info.js:407
    at Array.filter (<anonymous>)
```

**Reproduire le bug / To Reproduce**

Etapes à suivre pour reproduire votre problème du type : 

1. Créer un geojson sans champ nommé `id`
2. Ajouter ou template simple
3. cliquer sur pousieurs entités sur la carte (ou sur la frontière commune entre deux entités)
4. Constater que l'on a deux entité dans le template
5. Cliquer sur une des flèche droite / gauche
6. Constater une erreur dans la console

**Comportement attendu / Exptected behavior**

Le carousel devrait changer d'entité et ne pas insérer toutes les entités dans le même volet.

**Screenshots**

Si possible, une capture d'écran pour nous aider à voir le problème décrit.

![image](https://user-images.githubusercontent.com/16317988/108727384-d05f9a00-7528-11eb-9872-fdee0d4e2acf.png)

**Environnement / Desktop**

Merci de remplir ces informations si connues :
 - Navigateur : chrome - last
 - Version 3.4

**Comment by Gaetanbrl** [comment]
Je clos.... c'est la syntaxe rendue obligatoire que j'avais complètement oublié

`<li id="{{feature_ol_uid}}" class="item">`

**Comment by Gaetanbrl** [comment]
Je clos.... c'est la syntaxe rendue obligatoire que j'avais complètement oublié

`<li id="{{feature_ol_uid}}" class="item">`

**Comment by Gaetanbrl** [comment]
@spelhate je me demande par contre comment ca va se passer pour ceux qui passent sur la version avec la surbrillance. Ils vont sans doute devoir modifier les Template déjà crées sinon ca ne fonctionnera pas.

**Comment by spelhate** [comment]
Lié à #411
Et oui il faut reprendre les templates.

**Comment by Gaetanbrl** [comment]
En effet, je l'avais oublié cette issue. On se sera tous fait avoir 🙈

**Comment by spelhate** [comment]
Commande qui peut être utile pour mettre à jour d'anciens templates

`sed -i 's/<li class="item">/<li class="item" id="{{feature_ol_uid}}">/' *.mst`
