### ISSUE TITLE
Ordre d'apparition des résultats dans le formulaire de consultation quand le clic remonte plusieurs résultats sur des couches différentes

### ISSUE THREAD

**Issue by frgis** [geobretagne/mviewer#459]
Bonjour,

je paramètre actuellement une carte mviewer avec consultation de deux couches.

Quand je clique sur la carte et que le clic traverse un objet pour chaque couche j'ai le formulaire qui propose les résultats comme ci-dessous 

Comment faire pour que les déchetteries soient systématiquement proposées avant la couche secteur de collecte (en priorite) ? Je ne trouve pas d'information sur ce point dans la doc 

![consult_mv](https://user-images.githubusercontent.com/56657014/108824637-3f3d0180-75c2-11eb-9f53-b417b3b71205.PNG)

Cordialement.

**Comment by Gaetanbrl** [comment]
Bonjour @frgis, 

Je pense qu'effectivement, ce cas n'est pas paramétrable et les couches ne s'affiche pas dans un ordre spécifique.

Lorsque vous cliquez sur la carte, le mviewer réalise un appel (requête) vers un serveur cartographique qui est nommé GetFeature ou GetFeatureInfo (voir spec. OGC WFS / WMS).

Ensuite, le serveur retourne les couche dans un ordre non prévisible avec des délais de retour qui peuvent être variable (on parle d'asynchronisme).

L'affichage dans un ordre précis nécessite de récupérer de façon organisée les réponses du serveur (1 clic = 1 requête x nombre couche interrogeable sur la carte = 1 réponse x nombre couche à interroger). 

Il faudrait alors attendre d'avoir le résultat de toutes les couches pour ensuite construire le volet d'information.

Je ne crois pas (à vérifier tout de même) que c'est réalisable avec le système de promise (c.f doc JavaScript ) mais c'est une mécanique qui doit pouvoir être implémentée (une évolution à développer donc).

**Comment by frgis** [comment]
Bonjour,

merci pour le retour. Ca m'a l'air difficile à mettre en place vu comment ça fonctionne actuellement.

Pour mon cas on a fait autrement, ce n'est pas exceptionnel mais ça passe.

Je crois que l'on arrive aux limites du logiciel, on commence à vouloir des choses spécifiques car nous essayons de l'utiliser pour des cartes dynamiques qui certes vise une utilisation simple avec très peu de couche mais l'objectif est de limiter les intéractions avec l'utilisateur pour que la carte soit accessible au plus grand nombre (que le max de personnes comprennent comment ça fonctionne) et apporte l'information en un minimum de manipulation (en moins de 30 secondes ).

Faire ce type de paramétrage demande de l'ultra spécifique à chaque carte, donc on essaie avec cet outil, qui est très bien au passage de faire ça, mais je sens qu'on atteint ses limites.
Voire que l'outil n'est pas fait pour ça -> notre public ce n'est pas des géomaticiens ou des agents techniques sur ce type de rendu.

Merci pour votre réponse, vous souhaitez que je clos la question ?

**Comment by Gaetanbrl** [comment]
Bonjour @frgis ,

L'objectif du mviewer est de proposer une configuration accessible pour que des administrateurs qui ne sont pas des experts technicien puisse composer des cartes sur un sujet donné. Le mviewer contient alors les principaux besoins en visualisation cartographique et data viz.

On constate cependant que les créateurs de carte / commanditaire prennent bien possession de l'outil et souhaitent faire ensuite du mviewer un outil de plus en plus complexe qui tend vers un outil de manipulation de données (e.g filtre avancés, représentation avec interfaces complexe, statistiques, etc...). 
Ce qui n'est pas le rôle du mviewer dans sa forme actuelle.

L'ajout de fonctionnalités reste toutefois possible via une extension ou un custom control. Je vous invite à lire la documentation à ce propos si vous êtes intéressé.

**Comment by spelhate** [comment]
> Il faudrait alors attendre d'avoir le résultat de toutes les couches pour ensuite construire le volet d'information.

C'est déjà le cas. Mais actuellement les résultats sont affichés en fonction de l'ordre de réponse des couches et pas de l'organisation dans le panneau des thématiques.
C'est ici que ça se passe : https://github.com/geobretagne/mviewer/blob/master/js/info.js#L254
@Gaetanbrl a proposé une PR #407 qui permet d'organiser l'ordre des couches sur la carte et dans le panneau des thématiques en ajoutant un attribut à chaque layer : **index**.
Il suffirait juste de réorganiser les fiches d'information en utilisant ce paramètre.

**Comment by Gaetanbrl** [comment]
> C'est déjà le cas. Mais actuellement les résultats sont affichés en fonction de l'ordre de réponse

C'est ce que je voulais expliquer @spelhate. Le GFI permet de récupérer tous les résultats mais seule l'attente d'un retour de toutes les réponse (ex: promiseAll)  permettrait ensuite de traiter les réponses pour les afficher dans un ordre spécifique (ex: par zindex de la layer).

> Il suffirait juste de réorganiser les fiches d'information en utilisant ce paramètre.

Il y a un TODO qui va bien dans ce sens en tout cas 

https://github.com/geobretagne/mviewer/blob/68611d50b809e00b1e74aebe60d6cf706608ea03/js/info.js#L367

**Comment by Gaetanbrl** [comment]
>  Le GFI permet de récupérer tous les résultats mais seule l'attente d'un retour de toutes les réponse (ex: promiseAll)

Vu avec @spelhate, l'effet promiseAll est déjà en place.

Il faut alors ajouter l'affichage des tabs selon l'index de la couche (zindex). 

Je prend le ticket pour regarder ca.

**Comment by frgis** [comment]
Bonjour,

d'accord. Pas d'urgence on a mis en prod même avec ce petit problème. Néanmoins ce sera intéressant de le paramétrer lorsque ce sera géré.

Merci beaucoup

**Comment by Gaetanbrl** [comment]
Pour mémo - équivalent promiseAll :

> https://github.com/geobretagne/mviewer/blob/master/js/info.js#L466

**Comment by Gaetanbrl** [comment]
@frgis nous venons de faire une modification pour afficher les templates dans l'ordre de visibilité des données sur la carte.

**Comment by frgis** [comment]
Bonjour,

ok, c'est noté c'est une bonne évolution.
Vous pensez sortir une version vers quelle période de l'année actuelle ?

**Comment by spelhate** [comment]
C'est prévu pour la fin du mois de mars.

**Comment by frgis** [comment]
Ok, merci.

**Comment by frgis** [comment]
pour info, là ou je vais le mettre en place c'est à cet endroit: https://www.agglopole.fr/preserverrecycler/trier-ses-dechets/connaitre-les-jours-horaires-de-collecte/

pour exemple :-)

**Comment by spelhate** [comment]
Merci pour le partage !

**Comment by Gaetanbrl** [comment]
Je crois que c'est traité. Je ferme.
