### ISSUE TITLE
Partage de Carte : non prise en compte de la légende // Sharing map : no legend in screen

### ISSUE THREAD

**Issue by lecault** [geobretagne/mviewer#46]
Lorsque je veux partager une carte en ayant sélectionné un certain nombre de couches, le permalien n'affiche pas la légende.

Un exemple ici : http://kartenn.region-bretagne.fr/kartoviz/?x=-326080&y=6100898&z=9&l=Arr%25C3%25AAts%2520ferroviaires%2520r%25C3%25A9gionaux%252CLyc%25C3%25A9es%252CR%25C3%25A9serves%2520naturelles%2520r%25C3%25A9gionales%252CCommune%252CIntercommunalit%25C3%25A9&lb=positron#

**Comment by Gaetanbrl** [comment]
Le lien est-il mort ? L'exemple ne charge pas et j'ai une erreur dans le fichier mviewer.js

Uncaught TypeError: Cannot read property 'src' of undefined

[Sur cette ligne.](https://github.com/geobretagne/mviewer/blob/master/lib/mviewer.js#L2012)

**Comment by spelhate** [comment]
Corrigé. je ferme
