### ISSUE TITLE
Ordre des templates selon les couches

### ISSUE THREAD

**Issue by Gaetanbrl** [geobretagne/mviewer#481]
**Description du bug / Describe the bug**

Effet de bord suite #459.

Issue remontée par @lecault .

Le titre du template ne correspond pas à l'affichage de la couche en consultation **lors d'un second clic au même endroit**.

**Reproduire le bug**

Etapes à suivre pour reproduire votre problème du type : 

1. Aller sur la page https://kartenn.region-bretagne.fr/mviewer/?config=apps/region/bretagne_bzh/culture.xml
2. Cliqué sur plusieurs points de couches différentes
3. Voir que le template s'ouvre
4. Voir que l'affichage est cohérent (le titre correspond à la couche affichée en haut / en 1er)
5. Cliquer à nouveau au même endroit
6. Voir que le titre n'est pas le nom de la couche affichée en haut

**Comportement attendu / Exptected behavior**

Le titre devrait toujours être le même que la couche / entité affichée dans le template.

**Complément graphique**

![issue_474](https://user-images.githubusercontent.com/16317988/113833198-a802c680-9789-11eb-891d-2ff04d7fd8f4.gif)

**Environnement / Desktop**

Merci de remplir ces informations si connues :
 - Version mviewer 3.5

**Comment by Gaetanbrl** [comment]
Actuellement, le titre affiché est celui de la première couche dans la vue.
L'ordonnancement des onglets (template de couche) selon l'affichage sur la carte ne traite que les onglets dans le panel mais pas le titre.

**Comment by Gaetanbrl** [comment]
Un second correctif est à apporter.

L'identifiant de la couche de la vue est utilisé pour construire le bouton (selecteur de couche) dans le template.
Le selecteur (`<a href...>`) numéro 1 (correspondant à la couche identifiant 1 est ensuite ciblé pour récupéré le titre.

Cet identifiant étant déjà configuré dans les couches de la vue avant de parcourir les couches, il se fit à l'ordre originel et non l'ordre rétabli selon l'affichage.

![image](https://user-images.githubusercontent.com/16317988/113838515-1f872480-978f-11eb-857a-05c398e5a8a7.png)



Donc ici, 

`$("[href='#slide-"+panel+"-1']")`

Va cibler l'`id de la couche de valeur 1 `(dans la capture, c'est la seconde couche). Ce qui ne rend plus cohérent l'affichage.

**Comment by Gaetanbrl** [comment]
@lecault peux-tu tester la branche develop (avec le correctif sur ton exemple) et fermer l'issue si OK ?

Merci.

**Comment by lecault** [comment]
Je regarde cet aprem. Merci de ta réactivité.

**Comment by lecault** [comment]
Un grand merci Gaëtan c'est validé.
