### ISSUE TITLE
Partage de carte et showintoc

### ISSUE THREAD

**Issue by lecault** [geobretagne/mviewer#483]
**Description du bug / Describe the bug**

On a dans notre projet une couche avec l'option showintoc = 'false' (voir #456) pour qu'elle n'apparaisse pas dans la légende.
On veut partager une carte dans un des trois mode disponibles (normal, simplifié, ultra-simplifié), ça ne fonctionne pas.

**Reproduire le bug / To Reproduce**

1. Partir de cette conf : https://kartenn.region-bretagne.fr/mviewer/?config=apps/region/bretagne_bzh/culture.xml
2. Cliqué sur Partager la carte et choisir un des mode
3. La carte ne s'affiche pas

**Screenshots**

Si possible, une capture d'écran pour nous aider à voir le problème décrit.
![image](https://user-images.githubusercontent.com/5269430/113862637-f5426080-97a8-11eb-8add-cd40d82dd80d.png)

**Infos supplémentaires**

Il ne doit pas aimer d'avoir des couches présentes dans l'URL et non visible dans la légende.

**Environnement / Desktop**

mviewer version 3.5

**Comment by spelhate** [comment]
C'est le bon diagnostic @lecault.
