### ISSUE TITLE
Addon isochrone : changer le picto fontawsome

### ISSUE THREAD

**Issue by vfabry** [geobretagne/mviewer#489]
Bonjour,
Et merci pour le plugin isochrone, qui est vraiment très bien !
On voudrait changer l'apparence du bouton fas fa-route qui s'affiche dans la barre à droite, mais je ne trouve pas à quel endroit on peut faire cç.
Vincent

**Comment by Gaetanbrl** [comment]
Le bouton fas fa-route est ici : 

https://github.com/geobretagne/mviewer/blob/ee820c89b97c4321b432cc560c60ec8e1c87bb15/demo/addons/isochroneAddon/isochroneAddon.js#L231

**Comment by vfabry** [comment]
merci !
