### ISSUE TITLE
Elasticsearch filter query Error

### ISSUE THREAD

**Issue by Gaetanbrl** [geobretagne/mviewer#49]
Hi,
I need to connect mviewer to Elasticsearch 5.6.x.
In debug mode i read the JS flow and discovered that queryFilter is deprecate in mviewer.js file.

Here is my query : 
![image](https://user-images.githubusercontent.com/16317988/32377516-358dc16a-c0a8-11e7-8bc9-6e0a04d2ae00.png)

Here is the wrong message : 
> type:"parsing_exception, reason: "no [query] registered for [filtered]"

[Here](https://www.elastic.co/guide/en/elasticsearch/reference/5.5/query-dsl-filtered-query.html) is the documentation for Elastic > 5.x.

**Comment by spelhate** [comment]
Hi Gaetan,

you are right. This filter is available for 1.4 Elasticsearch version an it should be upgraded.

**Comment by Gaetanbrl** [comment]
I try to upgrade this part. I hope to realise this upgrade soon but i'm not familiar with elasticsearch ^^.

**Comment by Gaetanbrl** [comment]
I don't know if this his a new bug in consequence of my modification but i hame some difficulty to get and read elastic (ajax) response. Maybe because of Cross-Origin Request.

With brower debug, javascript analyse POST response as fail...

![image](https://user-images.githubusercontent.com/16317988/32386102-7515b2bc-c0c0-11e7-870c-1321b8e0616e.png)

 but network tool display response as a success (200 OK). 
![image](https://user-images.githubusercontent.com/16317988/32386303-01ad63d2-c0c1-11e7-8f35-1773ebfe835c.png)

**Comment by spelhate** [comment]
If your ELS instance is not on the same host than mviewer, you have to use an ajax proxy or set CORS on the ELS server.

**Comment by spelhate** [comment]
Tested with a fresh 5.6.3 els instance:

Query to  find all features from layers **lycee** & **transport_regional_arret** with the search string "**zol**" and with a geographic filter (envelope)

`{
  "query": {
       "bool": {
            "must": [
              { 
                "match":{
                  "_all": {
                    "query": "zol",
                    "fuzziness": "AUTO"
                  }
               }
              },
              {
              "bool": {
                    "should": [
                       {"type" : {
                        "value" : "lycee"
                        }
                       },
                       {"type" : {
                        "value" : "transport_regional_arret"
                        }
                       }
                    ]
                }
              }
              ] ,
            "filter":{
                     "geo_shape":{
                        "geometry":{
                           "shape":{
                              "type":"envelope",
                              "coordinates":[
                                 [
                                    -1.8786164930650402,
                                    48.20378452182604
                                 ],
                                 [
                                    -1.43916336806504,
                                    47.9988118707563
                                 ]
                              ]
                           }
                        }
                     }                     
                  }
       }
  }  
}`

**Comment by Gaetanbrl** [comment]
yes, my error come from CORS. Thank you for evolution.

**Comment by spelhate** [comment]
@Gaetanbrl can you test new version  ? For me it's ok with els version 1.4 and els version 5.6.3.
See  edc8271

**Comment by Gaetanbrl** [comment]
yes i do, but i only resolved my CORS problem yesterday night. Today i could try filter and post my result :)

**Comment by Gaetanbrl** [comment]
Are you agree with this filter syntax ? i don't know why "should" have 2 array... : 

                "bool ": {
                    "should ": [
                        [{
                            "type ": {
                                "value ": "l49: vue_opportunite "
                            }
                        }]
                    ]
                }

**Comment by Gaetanbrl** [comment]
I have modify JS code to auto detect elasticsearch version by ajax GET request.
I could create PR later.

**Comment by spelhate** [comment]
i agree with you. Only One array is necessary in the "should" section. Il will correct it.
In my case, I generate from postgres database, one type per layer in only one index. I use logstash as well.

**Comment by Gaetanbrl** [comment]
Okay i need to do the same model ;) thanks ! 
i will try and write my result soon.

**Comment by Gaetanbrl** [comment]
I adapt my ES database and now, ajax request is OK filter return all lines without real filter... don't understand.

**Comment by Gaetanbrl** [comment]
- input value : "opp_4-" 
 - value in ES : "OPP_4-" 

I did not think it was case sensitive... my fault ^^

**Comment by Gaetanbrl** [comment]
It's OK for me ! I'd change some JS to be more clear and less specific. I hope to propose PR tomorrow to share (or not) : 
- forEach instead of for loop
- comments

Do you already work in EPSG:4326 ? I'd find some EPSG:4326 instead of personal variable (hardcode - sometimes we  work in 2154).

**Comment by Gaetanbrl** [comment]
More informations in doc : 
http://mviewerdoc.readthedocs.io/fr/latest/doc_dev/config_els.html 

And this [commit](https://github.com/geobretagne/mviewer/commit/edc8271b3bed9c974bdb04189dea22f2b3297a91)
