### ISSUE TITLE
Configuration EPSG

### ISSUE THREAD

**Issue by Gaetanbrl** [geobretagne/mviewer#50]
Le code EPSG des données Elasticsearch (outil de recherche d'entité) est saisi en dur à certains endroits.

- Je me demandais s'il ne serait pas intéressant de créer une variable "globale" du code à renseigner dans la balise Elasticsearch du type <Elasticsearch epsg="2154"> permettant de renseigner la projection de départ ? (déjà fait chez moi)

**Comment by spelhate** [comment]
Pour info ElasticSearch ne gère pas les projections et supporte seulement EPSG:4326. Si je comprend, tu as dans ton index ELS des types avec des coordonnées geo qui ne sont pas en WGS84 ? As tu testé un filtre géographique avec ces données ?

**Comment by Gaetanbrl** [comment]
En effet, j'ai stocké dans ELS des données en 2154. Je voudrais éviter une transformation systématique, mais autrement je peux utiliser une vue pour la reprojection en 4326. Je n'ai pas testé de filtre géographique. Mais est-ce obligatoire de laisser ELS gérer la partie spatiale et forcer le 4326 ?

Tel que je comprend le fonctionnement, ELS stock les données à indexer et n'a pas pour rôle de gérer la partie spatiale, là je me trompe sûrement...
Pour moi c'est le rôle de postgis, donc préparer mes données en amont ou encore les travailler avec OpenLayers côté front (reprojection). 
Je pensais à un fonctionnement plus souple en laissant le choix de la projection des données.

**Comment by spelhate** [comment]
J'utilise beaucoup la partie spatiale ELS. De cette façon ont peut appliquer un filtre géo aux requetes.
Exemple : quels sont les Manoirs du 17e dans l'emprise courante de la carte ?
Si tu n'es pas intéressé par la gestion spatiale ELS, tu peux dans ton config xml désactiver la dimension spatiale des filtre en mettant le paramètre <searchparameters bbox="false"/>

**Comment by Gaetanbrl** [comment]
Oui je l'ai désactivée, mais j'ai des utilités en vue. 
Donc si je comprend bien, l'écriture en dur du code EPSG est spécifique à l'utilisation de la partie spatiale ELS  et dans le cas contraire où la partie spatiale n'est pas utilisée, le code EPSG en dur est moins pertinent ?

**Comment by spelhate** [comment]
ELS +Base adresse nationale + OpenLS geoportail. Tous ces services répondent en WGS84. Ce qui est très bien.

**Comment by Gaetanbrl** [comment]
Je comprend, je clos le sujet.
