### ISSUE TITLE
Partage d'expérience addon filter

### ISSUE THREAD

**Issue by lecault** [geobretagne/mviewer#507]
**Description  / Describe**

Je souhaite partager mon utilisation de l'addon filter à la communauté. Cela n'a pas marché aussi facilement, nous avons du apporter des modifications dans le code avec Hannah pour faire fonctionner ce plugin.

1. Copie du dossier demo/addons/filter dans le répertoire de l'application
2. Paramétrage du config.json + ajout de l'extension dans le XML de l'application
3. 2 modifications nécessaires dans le fichier filter.js
    L39 : chemin d'accès à l'identifiant de la couche incorrect
    var layerParams = mviewer.customComponents.filter.config.options.mviewer.filter.layers;
   L77 : ajout d'une ligne pour affichage par défaut (nous n'avons pas vu où faire autrement)
   $("#advancedFilter").css('display','block');

Du coup je m'interroge si ces modifications sont dues à une mauvaise utilisation de notre part ou s'il y a un bug avec des modifs à prévoir ?

Loïc

**Comment by Gaetanbrl** [comment]
> Du coup je m'interroge si ces modifications sont dues à une mauvaise utilisation de notre part ou s'il y a un bug avec des modifs à prévoir ?

Sauf corrections non reportées dans le dépôt Mviewer, nous n'avons pas eu ces problèmes.

> L77 : ajout d'une ligne pour affichage par défaut 

Quel été le soucis d'affichage par défaut ? La position initiale ? il ne s'affichait pas ?

> L39 : chemin d'accès à l'identifiant de la couche incorrect

Etrange c'est l'élément de base sinon le plugin ne fonctionne pas.


Je vais tester.

**Comment by lecault** [comment]
Par défaut, il n'affiche pas le filtre sur la carte.

Sinon oui je veux bien que tu testes. Je vais retester dans la semaine.

**Comment by lecault** [comment]
Gaétan, je viens de retester et je confirme le soucis pour la L39. Si je ne change pas, le plugin ne s'affiche pas.

Concernant la L77 c'est que par défaut il ne s'affichait pas. On avait  ajouté ce bout de code pour que ce soit le cas. Mais dans la version de demo il n'y a pas ce soucis.

**Comment by Gaetanbrl** [comment]
OK merci @lecault je vais regarder.

**Comment by lecault** [comment]
Aaaaaaah !

Bien voilà j'apprend un truc la notion d'id pour ne pas dupliquer les confs :).

Merci Gaëtan pour l'explication. En effet, je trouvais bizarre de dupliquer les addons.

**Comment by Gaetanbrl** [comment]
> Bien voilà j'apprend un truc la notion d'id pour ne pas dupliquer les confs :).

C'est une astuce qu'on utilise et qui marche pas mal en effet :)
