### ISSUE TITLE
attributeoperator : add options for % position

### ISSUE THREAD

**Issue by moccand** [geobretagne/mviewer#508]
Define 3 options for the like statement in order to specify wildcard % position : 

%value%
value%
%value

**Comment by Gaetanbrl** [comment]
Hi @moccand ,

I'm not really sur to understand you request. 

To write a correct answer (e.g code, enhancement...), could you be more specific about this use case and what is the like statement (config.json file, layer param ) ? 

Thanks.

**Comment by moccand** [comment]
attributeoperator offers two options : 
- =
- like
for the like option the wildcard % is hardcoded but on both side of the values set in attributevalues.

using : 

```
attributeoperator = "like"
attributevalues="Commune,EPCI,Pays"
```

makes query with %Commune% or %EPCI% or %Pays%

this enhencement woud make possible to set precisely the wildcard position : %Commune or Commune% or the default %Commune%

this could be made by adding options to attributeoperator : 
- "like_endsby" for adding the wildcart at the begining to get all items ending by the selected attributevalues
- "like_startsby" to add the wildcard at the end to get all items starting by the selected attributevalues
-  "like" for the actual behaviour

**Comment by Gaetanbrl** [comment]
Indeed, we have plan to change the default query.
We plan to insert a new param to specify this 3 options.

@spelhate

**Comment by spelhate** [comment]
Hi,

Coming soon, an evolution with a new layer parameter **wildcardpattern** with this allowed values

- %value% (default)
- %value
- value%
