### ISSUE TITLE
Titre - prendre en compte les balises HTML

### ISSUE THREAD

**Issue by Gaetanbrl** [geobretagne/mviewer#512]
# Description

Dans un fichier de config XML, on peut modifier le titre via la propriété `title`.
Le titre par défaut "mviewer" est alors remplacé par la valeur de cette propriété `title`.

Lorsqu'on souhaite custom un peu le titre (avec une balise ou bien un lien ou bien un truc plus jacky) on est bloqué car c'est du texte qui est rajouté dans ce lien : 

https://github.com/geobretagne/mviewer/blob/e8eb0a58fc8e6eef8bfac13932f6231a084deed5/js/configuration.js#L231-L235

Je propose d'utiliser un `.append` et non un `.text` afin de pouvoir rajouter du HTML dans la balise de titre `.mv-title` si c'est possible.

# Exemple

1. Titre avec HTML
 
`title="&lt;span style='color:red'&gt;Foobarbla&lt;/span&gt;" `

![image](https://user-images.githubusercontent.com/16317988/131342337-98469759-24d2-4675-843f-77b3b9772c56.png)

2. Titre sans HTML

`title="foobar"`

![image](https://user-images.githubusercontent.com/16317988/131342573-3d52657a-90ae-4a0c-bb72-4b8498528e36.png)

**Comment by Gaetanbrl** [comment]
Par contre ca demande réflexion pour le loader qui prend actuellement le texte du title de la même façon.
Si on utilise un `.append()` et non un` .text()` on aurait donc la même présentation : 

![image](https://user-images.githubusercontent.com/16317988/131343009-932e935b-9b48-464a-8710-dd5c9ba4b6e2.png)

@lecault @Agath21 @bchartier un avis ?

Cette issue répond à un besoin qui revient régulièrement : custom le titre (e.g texte sur deux lignes avec deux couleurs différentes, donc deux div).

**Comment by lecault** [comment]
De notre côté, ce besoin n'est pas remonté mais il me semble pertinent de faire quelque chose, très bonne initiative.

Le principal est que le futur dev ne modifie pas les conf existantes.

Pour le loader, ça fait un peu bizarre si couleur mais ça reste marginal donc ça me convient.

**Comment by Gaetanbrl** [comment]
> Pour le loader, ça fait un peu bizarre si couleur mais ça reste marginal donc ça me convient.

Dans la PR associée, j'ai rajouté un paramètre `htmltitle ` qui est strictement utilisé par le titre dans l'application quand ce paramètre est saisi.

Donc zéro impacte sur le loader ou le comportement natif.

C.f la PR pour plus de détails ;)
