### ISSUE TITLE
Puce des couches dans le template

### ISSUE THREAD

**Issue by Gaetanbrl** [geobretagne/mviewer#515]
### Description du bug / Describe the bug

Lorsqu'on a plusieurs entités cliquées dans le template, on a un padding-bottom qui s'applique. Ce qui créé un décalage.
Le CSS est à modifier pour que ce padding-bottom ne s'applique pas sur ces puces. 

### Reproduire le bug

Etapes à suivre pour reproduire votre problème du type : 

1. Cliquer sur 2 entités
2. Cliquer sur la puce du second item dans le panel de droite
3. Voir un décalage entre les deux

### Comportement attendu

Les puces devrait être l'une en-dessous de l'autre sans décalage.

**Screenshots**

![image](https://user-images.githubusercontent.com/16317988/133575757-9ef44027-edaa-4125-82e7-b3b5687e9100.png)

**Comment by Agath21** [comment]
Pour résoudre le problème, il faut ajouter cette nouvelle propriété dans le mviewer.css : 
```
#right-panel .nav li.active {
    padding: 0;
}
```
![image](https://user-images.githubusercontent.com/22764056/133576432-affb7ec5-a086-47c5-af2a-6d3fc8fd4d41.png)

Je réaliserai la modification plus tard.
