### ISSUE TITLE
Recherche adresse via API IGN

### ISSUE THREAD

**Issue by lecault** [geobretagne/mviewer#516]
**Description du bug / Describe the bug**

Dans un mviewer, on active la recherche d'adresse via un service de l'IGN : 

    <olscompletion url="https://wxs.ign.fr/essentiels/ols/apis/completion" type="geoportail" attribution="IGN"/>

Lorsqu'on fait une recherche d'adresse dans la barre du mviewer, le résultat d'apparaît pas mais si on active la console, on voit que l'API est correctement interrogée : 

https://wxs.ign.fr/essentiels/ols/apis/completion?callback=jQuery110204630419894567388_1631867119775&text=redon&type=StreetAddress%2CPositionOfInterest&ter=5&_=1631867119776

**Reproduire le bug / To Reproduce**

Etapes à suivre pour reproduire votre problème du type : 

1. Aller sur la plage https://kartenn.region-bretagne.fr/kartoviz/?config=apps/region/tmp/site_region.xml
2. Faire une recherche 

**Screenshots**

![image](https://user-images.githubusercontent.com/5269430/133751179-1754e2e9-8f2e-4971-b9c3-d7021f740c1a.png)

**Informations complémentaires / Additional context**

Le service de localisation de l'IGN est plus complet que celui d'étalab. Nous en avons besoin pour une carto. Est-ce que dans la communauté certains utilise avec succès le service de l'IGN ?

Si non, il est probable qu'il y ai eu des modifications du côté de l'IGN et que le mviewer ne sait plus interpreter le résultat de la recherche.

Nous regardons de notre côté.

**Comment by Gaetanbrl** [comment]
> Si non, il est probable qu'il y ai eu des modifications du côté de l'IGN et que le mviewer ne sait plus interpreter le résultat de la recherche.

A voir, mais c'est possible.

**Comment by lecault** [comment]
Oui il ne semble pas récupérer le résultat mais ça : 

[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object]

**Comment by Gaetanbrl** [comment]
Je vais regarder d'ici peu @lecault

**Comment by lecault** [comment]
Ok merci c'est bien un problème d'interpretation.
Si je mets ça : document.write(res[0].fulltext);
Il affiche la valeur

**Comment by lecault** [comment]
J'ai trouvé il manque un " L263 dans search.js

**Comment by Gaetanbrl** [comment]
Merci @lecault je clos.
