### ISSUE TITLE
Information ressource VM nécessaire.

### ISSUE THREAD

**Issue by aymeri0613** [geobretagne/mviewer#521]
Bonjour à tous,

je découvre mviewer en ce moment, je me pose une question simple, que conseillez vous en terme de ressource sur une Vm pour déployer mviewer.

Sachant que nous aimerions définir une vue à l'échelle régionale. Je présume que les ressources vont dépendre des données à afficher sur mviewer ?

En vous remerciant de ces informations.

**Comment by bchartier** [comment]
Bonjour,
mviewer ne consomme quasiment rien comme ressource côté serveur : c'est du pur html/css/javascript qui s'exécute côté client (le navigateur de l'utilisateur). Il faut juste avoir un peu de place sur votre serveur pour stocker les fichiers contenu dans le projet Github.

**Comment by aymeri0613** [comment]
D'accord, j'avais l'impression que les données devaient être stockées sur le serveur d'hébergement de l'outil.

Merci de votre retour !

**Comment by Gaetanbrl** [comment]
> Il faut juste avoir un peu de place sur votre serveur pour stocker les fichiers contenu dans le projet Github.

On parle d'environ 150 Mo.

> c'est du pur html/css/javascript qui s'exécute côté client

Il vous faudra seulement une VM ou un serveur virtuel de test contenant un serveur web apache ou Nginx (idem qu'un site web classique).

> D'accord, j'avais l'impression que les données devaient être stockées sur le serveur d'hébergement de l'outil.

Non il n'y a aucun serveur, c'est un viewer 100% front, le stockage + diffusion doit être fait via un geoserver (ou MapServer) + PostGis par exemple.

**Comment by bchartier** [comment]
> > D'accord, j'avais l'impression que les données devaient être stockées sur le serveur d'hébergement de l'outil.
> 
> Non il n'y a aucun serveur, c'est un viewer 100% front, le stockage + diffusion doit être fait via un geoserver (ou MapServer) + PostGis par exemple.

Bah, on peut aussi avoir des données stockées sous forme de fichiers GeoJSON sur le serveur.

**Comment by aymeri0613** [comment]
Merci de vos retours. Effectivement, nous allons essayé la diffusion via geoserveur + postgis pour stocker les données.
