### ISSUE TITLE
Partage de carte et ordre des couches

### ISSUE THREAD

**Issue by lecault** [geobretagne/mviewer#523]
**Description du bug / Describe the bug**

Je suis sur un cas très bizarre.
Ca fonctionne dans un mviewer normal mais pas ici.

**Reproduire le bug / To Reproduce**

Etapes à suivre pour reproduire votre problème du type : 

1. Aller sur la page https://geobretagne.fr/mviewer/?config=../pub/sm-megalis/apps/fibre/suivi_adresse2.xml
2. Ajouter la couche Intercommunalité (dans limites administratives)
3. Partage de carte
4. La couche intercommunalité apparaît dessous alors qu'elle est dessus dans la légende (toplayer="true").
 
**Comportement attendu / Exptected behavior**

Avoir la couche intercommunalité dessus les autres couches.

**Screenshots**

![image](https://user-images.githubusercontent.com/5269430/136000259-a31446a2-7010-456b-baf6-2c69aab2b61e.png)

**Environnement / Desktop**

Merci de remplir ces informations si connues :
 - Navigateur / browser chrome

**Informations complémentaires / Additional context**

Si certains ont eu des cas similaires je suis preneur...

**Comment by lecault** [comment]
Tests effectués sans succès : 
- enlever l'opacité
- changer l'ordre dans l'URL

**Comment by Gaetanbrl** [comment]
Ce problème avait été remonté car l'ordre des couches dans la légende et l'ordre sur la carte peut ne devrait pas être identique et on retrouve pourtant des cas de ce type.

La PR en cours sur les index de couche permet justement de corriger ce problème car il ne paraît pas logique d'avoir une légende dans un ordre et des couches sur la carte dans un autre ordre.

Je pense que ce problème sera corrigé ou bien il faudra attendre à minima le merge de la PR pour vérifier...

**Comment by lecault** [comment]
Attendons la PR :)

**Comment by Gaetanbrl** [comment]
A tester dans la release 3.6 sinon sera traité dans 3.6.1 (next release).

**Comment by Gaetanbrl** [comment]
lié à #407

**Comment by lecault** [comment]
Cool merci c'est résolu sur mon exemple !

**Comment by Gaetanbrl** [comment]
super ! :)
