### ISSUE TITLE
Filtre et recherche d'entité

### ISSUE THREAD

**Issue by lecault** [geobretagne/mviewer#526]
**Description du bug / Describe the bug**

Lorsque dans une conf on cumule pour une couche un filtre et que la recherche est activé, la fiche d'information ne s'affiche pas.

**Reproduire le bug / To Reproduce**

Etapes à suivre pour reproduire votre problème du type : 

1. Aller sur la plage https://kartenn.region-bretagne.fr/kartoviz/?config=apps/region/bretagne_bzh/culture_dev.xml#
2. Cliqué sur Rechercher
3. Saisir village par exemple
4. Clic sur le résultat de recherche.
5. La carte zoome sur le résultat de la recherche mais la fiche ne s'affiche pas

Le problème est du au fait que la requête est mal formée. Il y a 2 CQL_FILTER : https://ows.region-bretagne.fr/geoserver/rb/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetFeatureInfo&FORMAT=image%2Fpng&TRANSPARENT=true&QUERY_LAYERS=aide_spectacle_vivant_art_plastique&LAYERS=aide_spectacle_vivant_art_plastique&STYLES=culture_spectacle_art_global&CQL_FILTER=discipline%20IN%20(%27Arts%20plastiques%20et%20visuels%27%2C%27M%C3%A9tiers%20d%27%27art%27)&INFO_FORMAT=application%2Fvnd.ogc.gml&FEATURE_COUNT=20&I=50&J=50&CRS=EPSG%3A3857&WIDTH=101&HEIGHT=101&BBOX=-175802.91437610053%2C6177557.394223371%2C-174837.89689400018%2C6178522.411705471&CQL_FILTER=search_id%3D%27sadt.2020.20001827%27

**Propositions**

Je vois 2 pistes pour résoudre ce problème mineur : 
- Avant affichage de la fiche, le système enlève les CQL_filter existant (inutiles dans ce cadre là)
- Ajout du filtre dans le CQL_filter existant via un AND

**Screenshots**

![image](https://user-images.githubusercontent.com/5269430/136961343-39cb6f1a-87e1-4908-8284-e32209bc7192.png)

**Informations complémentaires / Additional context**

Nous utilisons la recherche Elastic mais le problème sera le même sur FUSE.

**Comment by lecault** [comment]
Désolé j'étais en congés 15 jours.

J'ai encore une erreur sur cet exemple je viens de faire le git pull  : https://ows.region-bretagne.fr/geoserver/rb/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetFeatureInfo&FORMAT=image%2Fpng&TRANSPARENT=true&QUERY_LAYERS=aide_spectacle_vivant_art_plastique&LAYERS=aide_spectacle_vivant_art_plastique&STYLES=culture_spectacle_art_global&CQL_FILTER=discipline%20IN%20(%27Th%C3%A9%C3%A2tre%27%2C%27Musique%27%2C%27Pluridisciplinaire%27%2C%27Danse%27)&INFO_FORMAT=application%2Fvnd.ogc.gml&FEATURE_COUNT=20&I=50&J=50&CRS=EPSG%3A3857&WIDTH=101&HEIGHT=101&BBOX=-175802.91437610053%2C6177557.394223371%2C-174837.89689400018%2C6178522.411705471discipline%20IN%20(%27Th%C3%A9%C3%A2tre%27,%27Musique%27,%27Pluridisciplinaire%27,%27Danse%27)%20AND%20search_id%3D%27sadt.2020.20001827%27

L'appli est ici : https://kartenn.region-bretagne.fr/mviewer/?config=apps/region/bretagne_bzh/culture_pepci.xml#

J'avais commencé à y jeter un oeil juste avant de partir...

**Comment by Gaetanbrl** [comment]
ok je vais tester mais ca passera dans une autre release si on a toujours un problème

**Comment by Gaetanbrl** [comment]
vu @lecault ... la PR n'est pas complète ce n'est pas ce que je voulais push initialement.

Je m'occupe du correctif.

**Comment by Gaetanbrl** [comment]
Dans mon premier correctif je n'avais pas bien nettoyé l'URL du CQL initial.
De plus, lorsqu'on converti en string une URL lu via URLSearchParams, on obtient des caractère qui ne semblent pas reconnu.
Ca devrait être corrigé maintenant dans la brache feature-526.

@lecault est-ce que ce serait possible de refaire un test avec tes cas d'utilisation à partir de la branche feature-526 ?

**Comment by lecault** [comment]
Alors je n'ai plus l'erreur mais la fiche ne s'affiche pas.

https://ows.region-bretagne.fr/geoserver/rb/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetFeatureInfo&FORMAT=image/png&TRANSPARENT=true&QUERY_LAYERS=aide_images_industrie_creation&LAYERS=aide_images_industrie_creation&STYLES=culture_images_global&INFO_FORMAT=application/vnd.ogc.gml&FEATURE_COUNT=20&I=50&J=50&CRS=EPSG:3857&WIDTH=101&HEIGHT=101&BBOX=-435987.84513689496,6089831.02068234,-435022.82765479456,6090796.03816444&CQL_FILTER=discipline%20=%20%27Livres%20et%20lecture%27%20AND%20search_id%3D%27simag.2020.20000173%27

Mais je sais pourquoi : cela vient du LIKE. Mon XML est composé de 2 couches avec le même id avec un tri qui s'effectue sur le Like : 

            <layer id="aide_spectacle_vivant_art_plastique" name="Soutiens dédiés à l’art contemporain et aux métiers d'arts" visible="true" tiled="false" namespace="rb"
					queryable="true" infoformat="application/vnd.ogc.gml"
                    featurecount="20" searchable="true" 
					style="culture_spectacle_art_global" 
					url="https://ows.region-bretagne.fr/geoserver/rb/wms" 
					attribution="Région Bretagne" 
					filter="discipline IN ('Arts plastiques et visuels','Métiers d''art')"
					metadata-csw=""
					metadata="" >  
					<template url="https://kartenn.region-bretagne.fr/kartoviz/apps/region/bretagne_bzh/templates/soutien_culture.mst" />
            </layer>
            <layer id="aide_spectacle_vivant_art_plastique" name="Soutiens dédiés au spectacle vivant" visible="true" tiled="false" namespace="rb"
					queryable="true" infoformat="application/vnd.ogc.gml"
                    featurecount="20" searchable="true"
					style="culture_spectacle_art_global" 
					url="https://ows.region-bretagne.fr/geoserver/rb/wms" 
					attribution="Région Bretagne" 
					filter="discipline IN ('Théâtre','Musique','Pluridisciplinaire','Danse')"
					metadata-csw=""
					metadata="" >  
					<template url="https://kartenn.region-bretagne.fr/kartoviz/apps/region/bretagne_bzh/templates/soutien_culture.mst" />
            </layer>

Sinon sur d'autres exemples ça fonctionne : 

https://ows.region-bretagne.fr/geoserver/rb/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetFeatureInfo&FORMAT=image%2Fpng&TRANSPARENT=true&QUERY_LAYERS=aide_spectacle_vivant_art_plastique&LAYERS=aide_spectacle_vivant_art_plastique&STYLES=culture_spectacle_art_global&CQL_FILTER=discipline%20IN%20(%27Th%C3%A9%C3%A2tre%27%2C%27Musique%27%2C%27Pluridisciplinaire%27%2C%27Danse%27)&INFO_FORMAT=application%2Fvnd.ogc.gml&FEATURE_COUNT=20&I=50&J=50&CRS=EPSG%3A3857&WIDTH=101&HEIGHT=101&BBOX=-309974.17001604935%2C6143209.291109309%2C-290018.37475669413%2C6163165.086368663

Donc tu peux répercuter la correction. Pour résoudre mon soucis, il faudra que je créé une couche GeoServer par filtre et une entrée dans ELS.

**Comment by Gaetanbrl** [comment]
@lecault la PR a été réalisée dans Develop. 

Si c'est ton XML qui provoque l'erreur :

* C'est un problème de configuration et non du code ==> Issue a fermer ?
* C'est toujours un soucis du code et de gestion de ce type d'erreur ==> Investigation à poursuivre

**Comment by lecault** [comment]
Pour moi c'est une config très particulière qui ne nécessite pas un débugage. En procédant autrement, je contourne le problème.

Je ferme l'issue.
