### ISSUE TITLE
Changement de style et permalien

### ISSUE THREAD

**Issue by lecault** [geobretagne/mviewer#528]
**Description du bug / Describe the bug**

J'ai une couche de type point (pas reproduit sur d'autre type pour le moment) je veux choisir un style différent du style par défaut puis faire un permalien. Le style qui apparaît n'est pas le bon.

**Reproduire le bug / To Reproduce**

Etapes à suivre pour reproduire votre problème du type : 

1. Aller sur la plage https://kartenn.region-bretagne.fr/vn/#
2. Modifier l'analyse de la couche écluse par trafic
3. Création d'un permalien https://kartenn.region-bretagne.fr/vn/?x=-260497&y=6108847&z=8&l=voie_navigable*voie_navigable_proprietaire%2Cecluse_trafic*ecluse_trafic_millesime&lb=plan2&config=apps/default.xml&mode=u
4. Le style qui apparaît est le style par défaut de la couche (propriétaire) et non le trafic

**Contre exemple **

Sur la couche patrimoine arboré : https://kartenn.region-bretagne.fr/vn/?x=-185427&y=6153138&z=16.117875416548692&l=arbre_individuel_vn*arbre_simple&lb=plan2&config=apps/default.xml&mode=d

Je fais la même chose mais je n'ai pas le soucis : https://kartenn.region-bretagne.fr/vn/?x=-185427&y=6153138&z=16&l=arbre_individuel_vn*arbre_individuel_essence&lb=plan2&config=apps/default.xml&mode=u

**Screenshots**

![image](https://user-images.githubusercontent.com/5269430/137870436-dbc8618a-6939-40ab-affa-f66f8c5841e4.png)
**Environnement / Desktop**

Merci de remplir ces informations si connues :
 - Navigateur / browser chrome
 - Version 3.5.3

**Informations complémentaires / Additional context**

C'est un bug relevé il y a déjà un moment. 

mviewer appelle le mauvais style : 
https://ows.region-bretagne.fr/geoserver/rb/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=ecluse_trafic&STYLES=ecluse_proprietaire&CRS=EPSG%3A3857&WIDTH=2868&HEIGHT=890&BBOX=-1167957.588487542%2C5915003.179304773%2C585813.588487542%2C6459234.820695227 
au lieu de 
https://ows.region-bretagne.fr/geoserver/rb/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=ecluse_trafic&STYLES=ecluse_trafic_millesime&CRS=EPSG%3A3857&WIDTH=2868&HEIGHT=890&BBOX=-1167957.588487542%2C5915003.179304773%2C585813.588487542%2C6459234.820695227

Je ne sais pas si ce bug parle à quelqu'un. J'ai essayé de trouver des points communs entre les échecs par trouvé.

Merci d'avance,

**Comment by Gaetanbrl** [comment]
Il semble que si la couche est en dehors d'un `<groupe>`, ca fonctionne.

**Comment by Gaetanbrl** [comment]
Pour les deux couches cités dans l'issue, elles ne sont pas comparables et apporte un autre bug cité précédemment.

> La légende n'est cependant pas la bonne.

La couche `arbre_individuelle` à une limite d'échelle, la couche écluse n'en a pas.

Dans Mviewer, le fait d'avoir un paramètre `layer.scale` force la mise à jour de la légende lors de l'ajout de la couche (ou sa mise à jour depuis les paramètres du permalien). 

https://github.com/geobretagne/mviewer/blob/d862151406effda754999aed570d71fdcf923889/js/mviewer.js#L2678-L2682

Ce qui n'est pas le cas si on a pas de limite d'échelle (c'est ce qui se passe pour les écluses).

Je pense que la légende devrait toujours être recalculée à l'ajout d'une couche pour éviter ce type de cas.

**Comment by Gaetanbrl** [comment]
@lecault, la layer se charge avec les paramètres natifs et ensuite, les paramètres depuis l'URL du permalien sont pris en compte.

Sur ton exemple, un zoom + permet d'afficher le bon style. Il faudrait donc forcer ce refresh pour regénérer les tuiles.

**Comment by Gaetanbrl** [comment]
@lecault tu peux tester le correctif dans la branche developpe.

**Comment by lecault** [comment]
Cool ça fonctionne merci @Gaetanbrl

**Comment by syji35** [comment]
Bonjour.
Je me permets de rebondir sur le fix.
J'ai une application en mviewer 3.6.1 et j'ai une régression suite à ce fix sur la V3.7.
Le problème vient de cette [ligne](https://github.com/geobretagne/mviewer/blame/b908158312c1d80221e404acf75e83f7a2c7aec3/js/mviewer.js#L2746)

Lorsqu'on a une application avec des customlayers qui charge les données en " tâche de fond" (sans être forcément activé par l'utilisateur), le fait de lancer le "refresh" supprime toutes les Features de la couche layer. Du coup, on ne voit plus les features sur la carte.

Serait-il possible de ne pas lancer le refresh sur des "customlayers" ? 

Merci

**Comment by Gaetanbrl** [comment]
> Lorsqu'on a une application avec des customlayers qui charge les données en " tâche de fond" (sans être forcément activé par l'utilisateur),

Ce n'est pas un comportement que nous avons dans mviewer, donc le coeur mviewer ne doit pas gérer ces cas spécifique.
Vous pouvez le gérer via le custom layer ou une extension pour surcharger le code mviewer.

> le fait de lancer le "refresh" supprime toutes les Features de la couche layer.

Le refresh va bien forcer le re calcul si c'est prévu par la couche OL, mais je ne vois pas le problème exactement sauf si le calcule est fait une seule fois et jamais stocké pour être réutilisé au refresh (event). Auquel cas on est plus sur un problème d'architecture du code que de problème de refresh mviewer.

Vous avez un exemple à partager ?

**Comment by syji35** [comment]
> 
> Vous avez un exemple à partager ?

Je n'ai pas d'exemple déployé pour le moment. 

> Ce n'est pas un comportement que nous avons dans mviewer, donc le coeur mviewer ne doit pas gérer ces cas spécifiques. Vous pouvez le gérer via le custom layer ou une extension pour surcharger le code mviewer.
> 
Mais c'est un comportement qu'on peut avoir avec du customlayer et une extension :) Ce que je fais actuellement sur mon application.

Pour faire simple, pour des problématiques de performances je trouve ca dommage de refaire les mêmes calculs.
Je peux en effet stocker les données et les ré-appliquer à l'event refresh, mais cela peut entrainer une surcharge de mémoire niveau navigateur.
Avec potentiellement beaucoup de données à afficher, je cherche à optimiser au mieux mon application.


Je trouve aussi dommage que les données des layers soient supprimées par mviewer. Les couches ne sont-elles pas responsables de leurs propre données ?

N'est pas possible de lancer le "refresh" uniquement si il ne s'agit pas d'un "customlayers" ?

**Comment by Gaetanbrl** [comment]
On rentre dans un débat qui sort du cadre de cette issue. Une autre issue est à ouvrir si besoin.

> N'est pas possible de lancer le "refresh" uniquement si il ne s'agit pas d'un "customlayers" ?

Que faire pour les customlayers qui veulent profiter du refresh en dehors de votre cas d'usage ?

> je trouve ca dommage de refaire les mêmes calculs.

Le calcul ou pas est à gérer au refresh. C'est OL qui gère que faire des données sur la couche en rappelant la source (au custom layer de gérer la source donc).

> Les couches ne sont-elles pas responsables de leurs propre données ?

Si et pour moi ce n'est pas à Mviewer de gérer les cas spécifiques qui peuvent être nombreux.

Les custom layers peuvent surcharger OL donc je ne vois pas de problème. La couche étant reponsable de ses données, pour un custom layer c'est à la couche de gérer les cas particulier de la librairie JS OpenLayers.

Pour clore le sujet ici (à réouvrir dans une autre issue si besoin de débattre ou autre) Je ferai alors une surcharge de la méthode refresh() de la couche: 

https://github.com/openlayers/openlayers/issues/7044

On utilise ce type de surcharge quand on est dans du spécifique qui sort de l'usage classique et quand le comportement OL ne convient pas (comme ici).
