### ISSUE TITLE
Bouton géolocalisation inopérant (v3.5.2) avec une carte Mviewer insérée dans un iframe sous Google Chrome

### ISSUE THREAD

**Issue by frgis** [geobretagne/mviewer#529]
Bonjour,

nous avons publié depuis plus d'un an une carte sur le site internet : https://www.agglopole.fr/preserverrecycler/agir-pour-la-nature/gardiole-geolocalisation-des-battues/

Comme vous l'observez cette carte est appelée en iframe.

Depuis quelques mois le bouton de géoocalisation ne fonctionne plus ni sous ordinateur ni sous mobile lorsqu'on utilise Google Chrome.
Ce qui est d'autant plus étonnant c'est que si j'appelle la carte mviewer en direct ça fonctionne sous Google Chrome.
Encore plus curieux, si cette page je l'ouvre (avec iframe) dans Mozilla Firefox ça fonctionne.
Sous Edge ça ne fonctionne pas.

Est-ce que vous avez déjà rencontré ce problème, je n'arrive pas à comprendre ce qui ne fonctionne pas ?

Merci pour votre aide
![geoloc](https://user-images.githubusercontent.com/56657014/139055808-bcbf24a7-c1b9-4a8e-bd2e-f99c14781aab.PNG)

**Comment by frgis** [comment]
Bonjour,

je ne clos pas pour le moment cette anomalie qui vient probablement pas de mviewer, on est entrain d'explorer des pistes, je viendrai écrire la solution quand je l'aurai.

**Comment by frgis** [comment]
on pense à un problème associé aux Feature-policy

**Comment by frgis** [comment]
Bonjour,

c'est bon pour le problème.

J'apporte la solution : il faut ajouter dans le virtualhost d'apache la feature policy de type:

Header set Feature-Policy "geolocation 'self' https://monsiteaautoriser.fr"

après reload de la conf c'est ok.
Merci pour le temps passé à diagnostiquer le problème !

**Comment by Gaetanbrl** [comment]
Merci pour ce retour, je rajoute la doc pour les plus curieux :

https://developer.mozilla.org/fr/docs/Web/HTTP/Headers/Feature-Policy
