### ISSUE TITLE
présentation des plusieurs graphiques chartjs dans plusieurs couches intérogées (Mviewer 3.11)

### ISSUE THREAD

**Issue by jerbou** [geobretagne/mviewer#530]
**Description du bug / Describe the bug**
Sur mviewer 3.11, la représentation des graphiques chartJS est "bloquée si plusieurs couches visibles sont intérogées.

**Reproduire le bug / To Reproduce**
https://cartes.ternum-bfc.fr/?config=apps/gip-territoires-numeriques-bfc/paysage-administratif.xml#

Etapes à suivre pour reproduire votre problème du type : 
1. Aller sur la plage et constaté les retours des attributs, 
2. cliquer sur une commune, 
3. cliquer sur les mini-icones sur le volet droit pour changer l'attribut
4. constater les retours du panneau des attributs (pour chaque couches 

**Comportement attendu / Exptected behavior**
On s'attend à voir que chaque appel de couches, une présentation de graphiques pour les couches périmrêtes...

**Screenshots**

Si possible, une capture d'écran pour nous aider à voir le problème décrit.

**Environnement / Desktop**
Mviewer 3.11 / plateforme idéobfc

Merci de remplir ces informations si connues :
 - OS: [e.g. iOS] Windows
 - Navigateur / browser [e.g. chrome, safari] : firefox 93.0 (64 bits

**Informations complémentaires / Additional context**
Je prévoie de reproduire sur la version 3.4.1 et sur une dernière version 3.6 (environnement local).

Préciser par exemple si le problème a été vu suite à l'installation d'une nouvelle version ou suite à des modifications que vous auriez faites dans votre Mviewer.
Pas d'erreur retournées dans le console du navigateur. (log de chartjs)

**Comment by Gaetanbrl** [comment]
@jerbou vous avez-vous un retour sur cette issue ?

**Comment by jerbou** [comment]
@Gaetanbrl non, je relance et on essaye d'améliorer la déclaration dans les MST.

merci,
jerome

**Comment by jerbou** [comment]
ok, retour utilisateur favorable qui a débugué en autnomie (déclaration de l'unicité des appel chartjs dans ses templates MST)
