### ISSUE TITLE
Affichage d'un baselayer de type tuilage vectoriel

### ISSUE THREAD

**Issue by frgis** [geobretagne/mviewer#537]
Bonjour,

l'IGN propose depuis cette année des flux en tuilage vectoriel.

En outre, l'IGN a aussi annoncé la fin de la diffusion du service Cartes IGN et propose de le remplacer par Plan IGN.
Plan IGN n'est accessible qu'en flux tuilé en couleur et le tuilage vectoriel à l'atout de personnaliser comme on veut l'affichage quand celui-ci n'est pas adapté au contexte de la publication.

Ainsi, serait-il prévu prochainement que Mviewer gère l'affichage de ce type ressource ?

Cordialement.

**Comment by Gaetanbrl** [comment]
Bonjour,

Ce sujet est potentiellement à avancer.

Une démo existe déjà pour afficher des tuiles vectorielles avec Mviewer : 
https://kartenn.region-bretagne.fr/kartoviz/?config=demo/tile/tiles.xml

Les ressources pour cette carte sont dans le répertoire `demo/tiles` : 
https://github.com/geobretagne/mviewer/tree/master/demo/tile

Si vous intégrez le flux IGN, nous sommes preneur de toute démo / retour d'expérience / contribution.

**Comment by lecault** [comment]
Le service Cartes IGN existe toujours. Il faut pour l'utiliser renouveler sa clé : https://geoservices.ign.fr/services-web-issus-des-scans-ign

Toutefois oui sujet intéressant. Dans la démo, celui du géograndest ne semble plus fonctionner.

**Comment by frgis** [comment]
Bonjour,

ça marche @Gaetanbrl je vais me pencher là-dessus dans le courant du mois. J'ai pas fais attention, j'aurais du regarder mais étant donné que c'est assez neuf ces notions de tuiles vectorielles (en tout cas pour moi) je croyais qu'il n'y avait rien dans Mviewer pour ça.

@lecault je confirme que le service Cartes IGN sera arrêté le 31 décembre, l'IGN a publié un mot là-dessus et j'ai vérifié en leur écrivant, ils recommandent à la place Plan IGN et quand j'ai demandé s'il existe en noir et blanc ils m'ont expliqué qu'en WMTS ce n'est pas le cas mais que je peux l'afficher de cette manière en tuile vectorielle, d'où ma demande ici.

On l'utilise pour l'autre problème en cours que j'ai actuellement et il me faut trouver une solution pour garder quelque chose d'adapter en terme de plan avant fin d'année.

Bonne journée

**Comment by frgis** [comment]
Bonsoir,

j'aurais besoin d'une aide. Je suis entrain de tester le flux vecteur tuilé de l'IGN et je bloque à un endroit.

Pour afficher le flux je me suis basé sur cette discussion https://www.developpez.net/forums/d2108514/applications/sig-systeme-d-information-geographique/ign-api-geoportail/openlayers-plan-ign-vecteur-tuile/

J'ai mis en place un customlayer dont le code est celui-là
const layer = new ol.layer.VectorTile({
        mapboxStyleUrl: "https://wxs.ign.fr/static/vectorTiles/styles/PLAN.IGN/essentiels/standard.json",
        mapboxStyleSource: "plan_ign",
        // gris.json
        // sans_toponymes.json
        // transparent.json
        // accentue.json
        // attenue.json
        // bdtopo.json
        // epure.json
    source: new ol.source.VectorTile({
      format: new ol.format.MVT(),
      url: "https://wxs.ign.fr/essentiels/geoportail/tms/1.0.0/PLAN.IGN/{z}/{x}/{y}.pbf"
    }),
	declutter: true,
    attributions: '<a href="https://geoservices.ign.fr/documentation/geoservices/vecteur-tuile.html">&copy; IGN</a>',
});


new CustomLayer("maptiler", layer);


Après avoir tout réglé dans la conf (ne vous fiez pas au terme maptler, c'est une récup de l'exemple de la démo, c'est bien le flux de l'IGN que je voudrais afficher :-) ) j'obtiens les dalles qui s'affichent mais le style n'est pas chargé
![Capture](https://user-images.githubusercontent.com/56657014/143485382-b1312ff0-d1b0-41bb-86ac-cb6eafe325c9.PNG)
 
J'ai compris qu'il y a un souci avec la version d'openlayers qui n'intègre pas mapbox, mais sur ce site https://github.com/openlayers/ol-mapbox-style j'ai téléchargé la release de mapbox et j'ai essayé de l'importer dans index.html mais ça donne rien alors que apparemment ça fonctionne avec Opelayers 6.1 minimum. Ca devrait donc pouvoir fonctionner.

A mon avis j'ai un problème avec l'installation de cette librairie. Pouvez-vous m'apporter une aide pour savoir comment je peux déployer cette librairie afin de pouvoir appliquer le style ?

Bonne soirée

Info : je suis sur la dernière version de mviewer

**Comment by Gaetanbrl** [comment]
Comment avez-vous importé la librairie `ol-mapbox-style` dans Mviewer ?

**Comment by frgis** [comment]
Bonjour,

merci pour votre retour.
Donc je suis allé sur le site https://github.com/openlayers/ol-mapbox-style 
j'ai téléchargé la release au format zip 
![image](https://user-images.githubusercontent.com/56657014/143567574-50f69706-5584-4767-91fb-6940be8a8700.png)

J'ai dézippé et copié tout le dossier dans /apps/tile
![image](https://user-images.githubusercontent.com/56657014/143568152-13337bbd-36ac-45e1-95f1-2e890f061e31.png)
 (oui je sais c'est le bazarre dans mon dossier, car j'ai fais plein de tests en essayant en complément la librairie du démonstrateur en plus et même celui qui est dans demo/tile toujours sans succès  :-))

Pour finir j'ai ajouté dans index.htm en fin de fichier dans l'encart sur les balises script 
![image](https://user-images.githubusercontent.com/56657014/143567937-1b6a2181-0ea5-4895-9097-6061a28f82ea.png)


Je pense que c'est faux ou il manque quelque chose mais je ne sais pas vraiment quoi.

Si vous avez une piste ça m'aiderais car je vois pas bien quoi et ou quelque chose manque.

Merci.

**Comment by Gaetanbrl** [comment]
Je vous propose de regarder l'exemple existant dans le répertoire demo/tile et d'importer cette librairie via une extension de la même façon.

https://github.com/geobretagne/mviewer/blob/56d01528fbd4d283511240ce105d6846506a9902/demo/tile/tiles.xml#L17

Le fichier est directement récupéré en ligne via le fournisseur `unpkg` et importé dans Mviewer sans avoir de créer de répertoire spécifique d'extension.

Sinon, le fichier est placé ici si indispo via unpkg: 

https://github.com/geobretagne/mviewer/blob/master/demo/tile/olms.js

**Comment by frgis** [comment]
ok je vais essayer, merci

**Comment by frgis** [comment]
malheureusement ça a rien changé.

J'ai ajouté l'extension dans la config xml
![image](https://user-images.githubusercontent.com/56657014/143585019-fb230a2e-03a8-4d89-adc0-c1edb944b88e.png)

C'est bien chargé : 
![image](https://user-images.githubusercontent.com/56657014/143585113-1aa2b048-0caa-4118-ae11-500fe752609d.png)

Mais il ne se passe rien. Je pense que les paramètres Mapbox ne sont pas pris en compte ou erronés (mais je sais pas trop comment tester pour m'assurer que le complément mapbox style est bien ajouté dans mviewer et est chargé ou non. Je ne vois pas d'erreur dans la console c'est tout ce que je peux savoir)
![image](https://user-images.githubusercontent.com/56657014/143585208-e6d47121-a2d4-48da-8b36-9669f8412357.png)

Le fichier de style je ne le vois pas passer (json) dans la console ... pour moi le problème il se situe quelque part par là

**Comment by Gaetanbrl** [comment]
Je vous conseil dans un premier temps d'utiliser un style simple comme dans les exemples. Si ca fonctionne, tentez alors d'utiliser un fichier de style JSON.

**Comment by Gaetanbrl** [comment]
Peut-être ?

`
olms.apply(mviewer.getMap(), './JsonStylesExemple.json');
`

**Comment by frgis** [comment]
Re,

ça progresse, le style s'affiche avec ceci :

var vlayer = new ol.layer.VectorTile({
  title: "Plan IGN vecteur",
  renderMode: 'hybrid',
  source: new ol.source.VectorTile({
    tilePixelRatio: 1,
    tileGrid: ol.tilegrid.createXYZ({ maxZoom: 19 }),
    format: new ol.format.MVT(),
    projection: new ol.proj.Projection({code:"EPSG:3857"}),
    url : "https://wxs.ign.fr/essentiels/geoportail/tms/1.0.0/PLAN.IGN/{z}/{x}/{y}.pbf",
    attributions: '<a href="https://geoservices.ign.fr/documentation/services/api-et-services-ogc/vecteur-tuile-tmswmts">&copy; IGN-Géoportail</a>',
  }),
  declutter: true
});

new CustomLayer("ign", vlayer);
olms.apply(mviewer.getMap(), 'https://wxs.ign.fr/static/vectorTiles/styles/PLAN.IGN/essentiels/standard.json');

Il y a un souci sur une couche qui a un affichage curieux (très gênant), ça donne l'impression que le symbole ne peut pas être dessiné et du coup que ça affiche un autre style par défaut, On va essayer de regarder ça mais on progresse !

Merci:-)

**Comment by Gaetanbrl** [comment]
Super !

SI jamais la couche n'est pas prête au moment ou le style essai de s'appliquer, il est possible que le style par défaut soit pris. C'est une hypothèse à vérifier car on a déjà eu ce type de soucis.

Dans ce cas, vous devez attendre que la couche soit prête pour appliquer le style : 

```
new CustomLayer("ign", vlayer);
vlayer .getSource().once('change', function(e) {
    // attendre que la couche soit prête
    if (vlayer .getSource().getState() == 'ready') {
        // la couche est prête, on applique le style
        olms.apply(mviewer.getMap(), 'https://wxs.ign.fr/static/vectorTiles/styles/PLAN.IGN/essentiels/standard.json');
    }
});
```

Ce code avec un event fonctionne pour un WFS standard. A tester /  adapter avec un flux vector tile.

**Comment by Gaetanbrl** [comment]
Pour partager et mettre en forme le code dans Github, il faut surligner les lignes de code du commentaire et cliquer sur ce bouton @frgis : 

![image](https://user-images.githubusercontent.com/16317988/144008565-fe33b69c-b4f8-4eed-883a-d29f088b9058.png)

Ce sera plus simple à lire :)

**Comment by frgis** [comment]
Bonjour,

j'essaie à nouveau d'aller afficher les tuiles vecteur de l'IGN.

Pour récapituler voilà où j'en suis, le code suivant permet d'afficher le flux tuilé vectoriel avec le style (autrement dit fichiers pbf et fichier style json):

`var vlayer = new ol.layer.VectorTile({
  title: "Plan IGN vecteur",
  renderMode: 'vector',
  visible: true,
  source: new ol.source.VectorTile({
    tilePixelRatio: 1,
    tileGrid: ol.tilegrid.createXYZ({ maxZoom: 19 }),
    format: new ol.format.MVT(),
    projection: new ol.proj.Projection({code:"EPSG:3857"}),
    url : "https://wxs.ign.fr/essentiels/geoportail/tms/1.0.0/PLAN.IGN/{z}/{x}/{y}.pbf",
    attributions: '<a href="https://geoservices.ign.fr/documentation/services/api-et-services-ogc/vecteur-tuile-tmswmts">&copy; IGN-Géoportail</a>',
  }),
  declutter: false
});
	
new CustomLayer("mapbox", vlayer);
olms.apply(mviewer.getMap(), 'https://wxs.ign.fr/static/vectorTiles/styles/PLAN.IGN/essentiels/epure.json');`

![carte_mviewer1](https://user-images.githubusercontent.com/56657014/179525091-ecf73456-67c5-4ddd-a20c-1eccdc123b23.PNG)


Le souci c'est que lorsque je demande l'application du style à la carte (dernière ligne mviewer.getMap()...) seul le flux est sur la carte, il n'est pas possible de le désactiver (en décochant il reste) et le plus important toutes les autres couches ne sont plus affichées sur la carte alors qu'il y a bien des appels à ces couches dans la console réseau.
Je pense qu'il écrase la carte pour laisser uniquement dessus le flux tuilé vectoriel.

J'ai essayé de modifier cette ligne (la dernière) pour appliquer à la couche plus qu'à la carte : olms.apply(mviewer.getLayer(),'https://wxs.ign.fr/static/vectorTiles/styles/PLAN.IGN/essentiels/epure.json');  ou olms.apply(mviewer.getLayer("iddemonlayer").layer,'https://wxs.ign.fr/static/vectorTiles/styles/PLAN.IGN/essentiels/epure.json');
mais ça ne fonctionne pas j'ai une erreur dans la console à chaque fois.

Auriez-vous une piste ?
C'est dommage de s'arrêter là ...

Bonne après-midi, cordialement

**Comment by frgis** [comment]
Bonjour,

nous ne pourrons pas accorder encore de temps pour travailler là-dessus.
D'autant plus que l'on est loin de ce que l'on voudrait mettre en oeuvre.

Ainsi, dites-moi s'il vous parait pertinent de donner la possibilité dans le logiciel mviewer de paramétrer un baselayer (paramétrable dans le xml configurable) de type "VectorTileIGN" qui permettrait d'appeler un flux vectoriel et un fichier de style dans mviewer ?

Si c'est pertinent, c'est-à-dire que cela a un intérêt que ce soit ajouté dans le code source de mviewer et du coup maintenu dans les versions suivantes, est-ce que vous savez quelles sociétés ont pu travailler sur le développement de mviewer (il me semble avoir lu des noms de société sur le site) et notamment sur ce type de dev (3 sociétés différentes si possible) ?
Je serai éventuellement curieux de me renseigner afin de savoir ce que cela peut coûter.

Merci et bon week-end.

**Comment by spelhate** [comment]
> Bonjour,
> 
> nous ne pourrons pas accorder encore de temps pour travailler là-dessus. D'autant plus que l'on est loin de ce que l'on voudrait mettre en oeuvre.
> 
> Ainsi, dites-moi s'il vous parait pertinent de donner la possibilité dans le logiciel mviewer de paramétrer un baselayer (paramétrable dans le xml configurable) de type "VectorTileIGN" qui permettrait d'appeler un flux vectoriel et un fichier de style dans mviewer ?
> 
> Si c'est pertinent, c'est-à-dire que cela a un intérêt que ce soit ajouté dans le code source de mviewer et du coup maintenu dans les versions suivantes, est-ce que vous savez quelles sociétés ont pu travailler sur le développement de mviewer (il me semble avoir lu des noms de société sur le site) et notamment sur ce type de dev (3 sociétés différentes si possible) ? Je serai éventuellement curieux de me renseigner afin de savoir ce que cela peut coûter.
> 
> Merci et bon week-end.

Bonjour, oui je pense qu'il y a un intérêt à augmenter les capacités de mviewer en ajoutant un nouveau type de couche vectorTile avec la possibiliter de personnaliser l'affichage de cette couche.
Pourquoi vectorTileIGN par rapport à vectorTile ?

Pour les sociétés qui développent sur mviewer, certaines sont référencées ici : https://mviewer.netlify.app/fr/, sinon libre à elles de se manifester sur ce fil.

**Comment by frgis** [comment]
Bonjour,

j'ai écris vectorTileIGN parce que je ne sais pas si il y a une méthode spécifique ou si c'est standardisé l'appel aux ressources IGN tuilés vectorielles. En tout cas, ce qui nous intéresse aujourd'hui c'est bien les ressources IGN (et pas d'autres à ce jour c'est pour cela que j'ai indiqué vectorTileIGN au cas où mais je suppose qu'ils suivent un standard).

Mais après l'appeler vectorTile me dérange pas 

D'accord, je vais aller sur le site et je vais déjà essayer de prendre contact avec une ou plusieurs d'entre elles selon ce qui est proposé.

Bon appétit

**Comment by dds2010** [comment]
Bonjour,

J'ai testé la solution suivante chez moi et cela fonctionne:
```
var vlayer = new ol.layer.VectorTile({
    title: "Plan IGN vecteur",
    renderMode: 'vector',
    visible: true,
    source: new ol.source.VectorTile({
      tilePixelRatio: 1,
      tileGrid: ol.tilegrid.createXYZ({ maxZoom: 19 }),
      format: new ol.format.MVT(),
      projection: new ol.proj.Projection({code:"EPSG:3857"}),
      url : "https://wxs.ign.fr/essentiels/geoportail/tms/1.0.0/PLAN.IGN/{z}/{x}/{y}.pbf",
      attributions: '<a href="https://geoservices.ign.fr/documentation/services/api-et-services-ogc/vecteur-tuile-tmswmts">&copy; IGN-Géoportail</a>',
    }),
    declutter: false
  });

  fetch('https://wxs.ign.fr/static/vectorTiles/styles/PLAN.IGN/essentiels/epure.json').then(function(response) {
    response.json().then(function(glStyle) {
      olms.stylefunction(vlayer, glStyle, 'planIGN');
    });
  });
```

Il vaut mieux utiliser la fonction olms.stylefunction je pense plutôt que apply.

Cordialement

**Comment by spelhate** [comment]
Bonjour.
Avez-vous pu avancer de votre côté ?

________________________________
De : frgis ***@***.***>
Envoyé : lundi 18 juillet 2022 15:54
À : geobretagne/mviewer ***@***.***>
Cc : Subscribed ***@***.***>
Objet : Re: [geobretagne/mviewer] Affichage d'un baselayer de type tuilage vectoriel (Issue #537)


var vlayer = new ol.layer.VectorTile({

  title: "Plan IGN vecteur",

  renderMode: 'vector',

  visible: true,

  source: new ol.source.VectorTile({

    tilePixelRatio: 1,

    tileGrid: ol.tilegrid.createXYZ({ maxZoom: 19 }),

    format: new ol.format.MVT(),

    projection: new ol.proj.Projection({code:"EPSG:3857"}),

    url : "https://wxs.ign.fr/essentiels/geoportail/tms/1.0.0/PLAN.IGN/{z}/{x}/{y}.pbf",

    attributions: '<a href="https://geoservices.ign.fr/documentation/services/api-et-services-ogc/vecteur-tuile-tmswmts">&copy; IGN-Géoportail</a>',

  }),

  declutter: false

});



new CustomLayer("mapbox", vlayer);

olms.apply(mviewer.getMap(), 'https://wxs.ign.fr/static/vectorTiles/styles/PLAN.IGN/essentiels/epure.json');



c'est le même code que dans le dernier message mais j'essaie la fonction que vous m'avez indiqué précédemment ... :-)

**Comment by Gaetanbrl** [comment]
@spelhate pop https://github.com/geobretagne/mviewer/issues/675

**Comment by Gaetanbrl** [comment]
Redondante / à supprimer en faveur de #675 @frgis ?

**Comment by frgis** [comment]
Je clos ce ticket étant donné qu'il est en doublon avec l'issue #675
