### ISSUE TITLE
Feuille de route

### ISSUE THREAD

**Issue by Gaetanbrl** [geobretagne/mviewer#538]
**Description**

Le lien du README oriente vers une feuille de route qui n'est pas à jour.
https://github.com/geobretagne/mviewer/wiki/Feuille-de-route

Ne serait-ce pas à mieux d'avoir un lien vers la page "Road Map" ?
Sinon il faudrait mettre à jour la feuille de route régulièrement / à chaque PSC ?

**Comment by lecault** [comment]
Je dirai un peu des 2.
Un lien vers la roadmap oui mais il me semble intéréssant de saisir quelque part un mini CR du PSC à destination de la communauté.

**Comment by Gaetanbrl** [comment]
Pour le moment (vu en PSC) > Changer le lien vers le projet (kanban)

**Comment by lecault** [comment]
Lien modifié branch develop
