### ISSUE TITLE
Erreur build de la documentation

### ISSUE THREAD

**Issue by spelhate** [geobretagne/mviewer#539]
Le build de la documentation retourne une erreur lors de la compilation sur la plateforme readthedocs.org.
Il en résulte que la doc consultable correspond à la version 3.5.1

Probablement un lien avec https://github.com/sphinx-doc/sphinx/issues/9777

**Comment by spelhate** [comment]
Bug fixé en ajoutant un fichier requirements.txt précisant la version docutils utilisée car la dernière version 0.18 n'est pas supportée avec la version utilisée de sphinx.

**Comment by Gaetanbrl** [comment]
La doc ne semble pas bien s'afficher en latest / 3.5.x : 

https://mviewerdoc.readthedocs.io/

**Comment by spelhate** [comment]
Actuellement : 
latest = branche develop
stable = master

![image](https://user-images.githubusercontent.com/1793792/143039827-c848ad0f-140f-403b-8d99-eded0654dc2e.png)

**Comment by Gaetanbrl** [comment]
Ca refonctionne (je sais pas si une action a été faite - merci sinon) :)
