### ISSUE TITLE
Mviewer version 3.1.1-interaction couches exclusives et coches top layer ne fonctionnent pas correctement

### ISSUE THREAD

**Issue by jerbou** [geobretagne/mviewer#541]
**Description du bug / Describe the bug**

Une description courte du problème
L'affichage entre des couches exclusives (les raster mesales) et un couche top layer (limite périmètre) masque cette derniere.
Ce qui n'est pas souhaité.

**Reproduire le bug / To Reproduce**

Etapes à suivre pour reproduire votre problème du type : 

1. Aller sur la plage https://cartes.ternum-bfc.fr/?config=apps/syndicat-mixte-du-bassin-du-serein/carte_alea_erosion_sol.xml#
2. Cliquer sur une des couches (mesales été 2019)
3. La couche s'affiche, en cliquant sur d'autres couches de la thématique mesales, elles sont "exclusives" et donc l'affichage d'une autre chasse l'autre.

**Comportement attendu / Exptected behavior**
Le comportement attendu est de permettre de choisir les couches mesales (exclusives), tout en laissant la couche limite Syndicat du bassin de Serein (limite noire) en "affichage top".
Le partenaire souhaite pouvoir chanrger les couches mesales, tout en ayant constamement la couche perimetre visible "au dessus".

**Screenshots**

**Environnement / Desktop**

Merci de remplir ces informations si connues :
 - OS: [e.g. iOS] Windows
 - Navigateur / browser [e.g. chrome, safari] : firefox et chrome
 - Version [e.g. 22] : 94.0.2 (64 bits et chrome Version 96.0.4664.45

**Informations complémentaires / Additional context**

D'avance Merci !

Jérôme Boutet
IdéO BFC

**Comment by Gaetanbrl** [comment]
Bonjour,

Quelle est votre version Mviewer utilisée ?

**Comment by Gaetanbrl** [comment]
Vous semblez avoir une  v3.1.1 (ouvrir la console) pour avoir l'info.

A tester en v3.5 (avec le paramètre index).

**Comment by jerbou** [comment]
ok, merci. 

Nous prévoyons de monter d'abord en 3.4, je regarde pour reproduire dans cette version, et commenterai ici, si il y a un meilleur comportement.

**Comment by Gaetanbrl** [comment]
Seule la v3.5 contient l'indexation "forcée".
Vous pouvez tester en local si vous en avez la possibilité avec cette version 3.5 pour le test.

**Comment by jerbou** [comment]
Je confirme que la version 3.4.1 de Mviewer  corrige "presque" le comportement.

Quand il y a qu'une seul layer en toplayer et visible par défaut, la comportement attendu est là.
Des qu'il y a d'autres couches visibles par défaut, la "priorité" d'affichage n'est plus respectée, par rapport à ce qui est attendu.

https://preprod-cartes.ternum-bfc.fr/?config=apps/ademe/preprod_carte_alea_erosion_sol_V2.xml# (n'est pas disponible

Je regardera la semaine pro' en environnement local sur la Mviewer version 3.6-snapshot

**Comment by Agath21** [comment]
Bonjour @Jerbou 

Pour ma part, je viens de tester une application mviewer avec la version 3.6 et l'association des deux fonctionnalités `exclusive` et `toplayer` fonctionne. La couche `toplayer` reste affichée au premier plan malgré l'affichage successif de différentes couches exclusives. 

Je reproduis toutefois votre bug dans les versions précédentes et dans la version 3.6-snapshot.  Pour corriger le problème, il est donc nécessaire d'évoluer vers la **version 3.6**

**Comment by jerbou** [comment]
Merci @Agath21, pour le moment, nous ne pouvons pas évoluer sur la version 3.6, mais j'ai trouvé un contourement...
mettre uniquemenet visible (affichage par défaut) la couche toplayer et les couches exclusives... 
D'autres couches mises en visable false que l'utilisateur pourra afficher à sa guise.
Le comportement est dans cette "configuration" ok.

Merci pour vos conseils.

Est-ce que l'on clos ou pas ?

**Comment by Gaetanbrl** [comment]
Je clos l'issue puisque nos tests ont permis de valider que ce comportement est corrigé dans les versions >= 3.6.
A ré ouvrir si reproduction en version >= 3.6
