### ISSUE TITLE
Tooltip supprimer persistant sur couches par défaut

### ISSUE THREAD

**Issue by lecault** [geobretagne/mviewer#542]
**Description du bug / Describe the bug**

Lorsqu'on ouvre une application en mode normal. on clique sur la croix pour supprimer une couche, la tooltip supprimer reste affiché à l'écran;

Par contre, je n'ai pas ce comportement sur une couche que l'on ajoute ou après un clic sur une poubelle.

**Reproduire le bug / To Reproduce**

Etapes à suivre pour reproduire votre problème du type : 

1. Aller sur la page https://kartenn.region-bretagne.fr/vn/#
2. Cliquer sur la croix de la couche écluse ou voie navigable
3. La tooltip supprimer reste affichée

**Comportement attendu / Exptected behavior**

La tooltip supprimer ne doit plus être affichée après le clic sur croix.

**Screenshots**

![image](https://user-images.githubusercontent.com/5269430/143477515-6776ccdf-8fb3-4627-9b72-2a6e31898ddb.png)
**Environnement / Desktop**

 - Tout navigateur
 -  Version 3.6

Merci

**Comment by Gaetanbrl** [comment]
### Cause

Lié à https://github.com/geobretagne/mviewer/pull/505 qui rajoute des tooltip sur des éléments qui n'en avait pas (comme ce bouton de suppression je pense).

### Hyptohèse : 

La tooltip reste dans le DOM ( donc visible) tant que la souris n'a pas quitté l'élément HTML lié (le bouton croix ici). Donc si on supprime une couche, la cible la tooltip n'existe plus et la souris ne peut plus déclencher l'événement "en dehors du bouton" pour faire disparaître la croix.

**Comment by Gaetanbrl** [comment]
Corrigé sur Develop.

**Comment by lecault** [comment]
Merci je viens de vérifier ça fonctionne
