### ISSUE TITLE
transparence et basemaps WMTS

### ISSUE THREAD

**Issue by lionelbargeot** [geobretagne/mviewer#547]
**Description du bug / Describe the bug**

Le paramètre opacity des basemaps génère une erreur

**Reproduire le bug / To Reproduce**

Déclarer la couche suivante

```
<baselayer
        type="WMTS"
        id="ign_orthophoto"
        label="Photos aériennes IGN"
        title="Photos aériennes IGN"
        thumbgallery="apps/common/img/basemap/ign_orthophoto.png"
	url="https://wxs.ign.fr/choisirgeoportail/geoportail/wmts?"
	layers="ORTHOIMAGERY.ORTHOPHOTOS"
	fromcapacity="false"
	format="image/jpeg"
	attribution="Données cartographiques :©IGN"
	style="normal"
	matrixset="PM"
        visible="false"
        opacity="0.75"
        />
```

**Comportement attendu / Exptected behavior**

on attend la couche en transparence, mais l'appli ne se lance pas

**logs firefox**

`Uncaught AssertionError: Assertion failed. See https://openlayers.org/en/v6.3.1/doc/errors/#64 for details.
`
**Environnement / Desktop**

Merci de remplir ces informations si connues :

 - OS: Linux Mint
 - Navigateur / browser Forefox 
 - Version 84.0.1

**Informations complémentaires / Additional context**

Le problème est résolu en modifiant la ligne  1144 du fichier mviewer.js :

`setBaseOpacity(l,Number(baselayer.opacity));`

**Comment by Gaetanbrl** [comment]
Merci pour la déclaration du bug @lionelbargeot

**Comment by lecault** [comment]
Je réouvre cette issue.
Je viens de tester l'opacité sur une baselayer : https://kartenn.region-bretagne.fr/mviewer/?config=demo/v3.7.xml
Le problème est du fait de l'opacité, on voit la grille (le fond par défaut s'il y a rien) apparaître.

**Comment by Gaetanbrl** [comment]
> Le problème est du fait de l'opacité, on voit la grille (le fond par défaut s'il y a rien) apparaître.

Ca vient de la grille toujours visible et qui ne devrait pas ou de l'opacité qui déconne ? @lecault

**Comment by Gaetanbrl** [comment]
@spelhate tu sais comment est créé cette grille ?

**Comment by lecault** [comment]
Non c'est la grille. En fait elle est derrière le fond. Donc, quand on met de l'opacité, elle apparaît.

**Comment by Gaetanbrl** [comment]
Si c'est du comportement openLayers ce n'est pas un bug mviewer non ?

**Comment by lecault** [comment]
https://kartenn.region-bretagne.fr/mviewer/img/grid.png

**Comment by Gaetanbrl** [comment]
Cette grid elle est utilisée pour quoi ? par qui ?
Je ne pense pas avoir de cas d'usage dans nos utilisateurs.

**Comment by Gaetanbrl** [comment]
Je pense que c'est hors sujet avec cette issue, c'est plutôt un comportement normal natif à Mviewer et non un bug. Une issue doit être ouverte pour discuter de ce qu'on fait avec la grid, notamment avec ce cas d'usage. Si on doit apporter des modifications, alors c'est une évolution du comportement standard de la grid. 

Je serai pour fermer cette issue donc et passer la suite dans la prochaine release.

**Comment by spelhate** [comment]
> 



> @spelhate tu sais comment est créé cette grille ?



> @spelhate tu sais comment est créé cette grille ?

Oui via une propriété CSS et une basemap  (fake)

**Comment by lecault** [comment]
Je ferme cette issue et j'en ouvre une autre.
