### ISSUE TITLE
Liste de souhaits / Road map : fusion

### ISSUE THREAD

**Issue by lecault** [geobretagne/mviewer#551]
**Description  / Describe**

Lors du dernier PSC on a évoqué la refonte de la partie roadmap et liste de souhaits :
liste de souhaits : https://github.com/geobretagne/mviewer/projects/7
Road map : https://github.com/geobretagne/mviewer/projects/6

Je propose de les fusionner et de prioriser les issues.
Des catégories du genre : 
ISSUES | NEXT RELEASE 3.7 | NEXT MAJOR RELEASE 4.0 | SECONDARY | OUTSTANDING

ISSUES : liste de toutes les issues.
NEXT RELEASE : issue à traiter lors de la prochaine release.
NEXT MAJOR RELEASE : issue indispensable à long terme pour le projet mviewer. Exemple : #6
SECONDARY : non prioritaire, répond à un besoin très spécifique. Non prise en charge par PSC. Exemple #506 
OUTSTANDING : en suspens. Pas indispensable mais intéressant, nécessitant des financements. Exemple : #425 

La partie abandonnée n'a pas d'intérêt pour moi. Dans ce cas, l'issue est simplement fermée.

Qu'en pensez vous ?

**Comment by lecault** [comment]
Discussion faite au sein du PSC, nouvelle road map (évolutions possibles) https://github.com/geobretagne/mviewer/projects/8

**Comment by Gaetanbrl** [comment]
Merci @lecault c'est plus clair sous cette forme ;) !

**Comment by Gaetanbrl** [comment]
@lecault comment devons-nous déplacer les issues qui sont close ? Elles sont à enlever du projet ?

**Comment by lecault** [comment]
Pour moi oui.
