### ISSUE TITLE
Rendre modifiable le titre "Analyses" si plusieurs styles

### ISSUE THREAD

**Issue by lecault** [geobretagne/mviewer#552]
**Description / Describe**

Vu en PSC.
Si une donnée a plusieurs styles associés, il est intéréssant d'avoir la possibilité de modifier le titre "Analyses"

**Exemple / Example **

Dans ce cas précis : 
https://kartenn.region-bretagne.fr/territoires/?x=-220750&y=6144926&z=8&l=rp_struct_pop_geomdbl1*rphab_tx0014%40commune*level%20%3D%20%27Commune%27&lb=positron&config=apps/default.xml&mode=d#

![image](https://user-images.githubusercontent.com/5269430/147939132-d5246b39-b242-4a67-b651-3c7240e02060.png)

On pourrait remplacer Analyses par Catégorie d'âge

**Evolution possible**

Un paramètre styletitle ajoutable au niveau de la layer.
styletitle = "Catégories d'âge"

**Comment by Gaetanbrl** [comment]
@lecault évolution disponible dans la branche feature-552 pour test.

Merci :)

**Comment by lecault** [comment]
Test ok.

Merci Gaëtan !
