### ISSUE TITLE
Accès à une couche WMS protégée depuis un autre serveur

### ISSUE THREAD

**Issue by vfabry** [geobretagne/mviewer#565]
Bonjour,
Je publie une couche avec le geoserver de Géo2France, et cette couche n'est accessible qu'à certains utilisateurs (j'utilise geofence pour faire ça). La couche en question : 
* **layer** : ref_cites
* **URL** : https://www.geo2france.fr/geoserver/ddtm62/ows

Quand je cherche à accéder à cette couche depuis un mviewer installé sur un autre serveur (avec le paramètre secure="layer" ), quand je saisi mes identifiants la couche ne s'affiche pas.
Le mviewer en question : https://sig.hautsdefrance.fr/ext/mv_test/?config=apps/test_JD.xml# 

Je vois bien qu'il y a un problème de CORS entre sig.hautsdefrance.fr et www.geo2france.fr , aussi j'ai rajouté le paramètre useproxy="true" mais sans succès.

**Comment by spelhate** [comment]
Bonjour Vincent,
Je pense qu'il y a plusieurs soucis sur ta couche.

-  Le geoserveur ddtm62 indique que la couche ref_cites n'existe pas.
- La couche doit en principe s'**afficher** sur la carte. Les restrictions CORS bloqueront l'affichage de la légende et l'interrogation
- C'est une bonne idée d'utiliser `useproxy="true"`, à la condition d'avoir défini un proxy dans la configuration (https://mviewerdoc.readthedocs.io/fr/latest/doc_tech/config_proxy.html?highlight=proxy#configurer-le-proxy). A ta décharge, cet aspect de mviewer n'est pas très documenté. Je dois bientôt m'y coller.

**Comment by vfabry** [comment]
Merci Sébastien.
