### ISSUE TITLE
Désactivation de la navigation et du zoom (et icones associés)

### ISSUE THREAD

**Issue by eprouteau** [geobretagne/mviewer#566]
Bonjour tout le monde,

Suite à une demande, j'aurais aimé savoir si certains d'entre vous avait déjà désactivé la navigation carto sur le mviewer ainsi que la zoom via la molette et en enlevant le icones associés à la navigation.

j'ai vu que openlayers le permettait. Du coup pensez vous que via un composant on puisse bloqué la navigation ?

Bonne journée,

Emeric,

**Comment by Gaetanbrl** [comment]
Tu devrais pouvoir le faire avec du CSS via un thème personnalisé ou via une extension.

**Comment by Gaetanbrl** [comment]
je détail @eprouteau  : 

> Tu devrais pouvoir le faire avec du CSS via un thème personnalisé

Tu peux copier par exemple `css/themes/asphalt.css` dans `/app/themes/monCustom.css` et ajouter dans `monCustom.css` une section CUSTOM de ce type : 

```
/*******************************
------------- CUSTOM -----------
********************************/
#zoomtoolbar {
  /*masque la toolbar en entier*/
  display: none;
}

```

Ensuite tu appels ton CSS copier dans le config.xml (<application>) : `style="app/themes/monCustom.css"`

* **Inconvénient :** 
Si le thème initial change, tu devras reporter tes modifications à la main dans le thème mis à jour (ca arrive très rarement).

* **Avantage :** 
C'est rapide et simple, mais ca vise toute la toolbar.

> ou via une extension
Soit via du code JS ou via l'import d'un CSS mais c'est peut-être plus simple de reprendre un thème.

* **Inconvénient :** 
C'est plus complexe.

* **Avantage :** 
Tu ne t'occupes pas des évolutions du thème et si tu sais faire une petite extension c'est pas complexe à réaliser.


# La meilleure solution

Faire une  évolution pour avoir dans `<application>` la possibilité de mettre `zoom=false` et conserver le bouton pour revenir à l'étendue de départ.

**Comment by Gaetanbrl** [comment]
> Serait-ce possible via composant

Que souhaites tu faire avec ce composant et ces interactions ? Comment tu souhaites les appliquer sur la carte openlayers ?

Si tu veux modifier la map directement à partir du module il faudra que tu sois certain que la map est déjà chargée avant le chargement de ton extension. Sinon tu devra utiliser un `event listener` pour déclencher tes modification sur la map quand la mapr est bien chargée (statut `ready`).

Tu peux regarder la section de la doc OpenLayers pour voir les méthodes d'ajout / suppression d'interactions ou de contrôles  : 

https://openlayers.org/en/latest/apidoc/module-ol_Map-Map.html#addInteraction
https://openlayers.org/en/latest/apidoc/module-ol_Map-Map.html#removeInteraction

https://openlayers.org/en/latest/apidoc/module-ol_Map-Map.html#addControl
https://openlayers.org/en/latest/apidoc/module-ol_Map-Map.html#removeControl

**Comment by Gaetanbrl** [comment]
@eprouteau as-tu trouvé une solution alors ?

**Comment by eprouteau** [comment]
Je vais dans un premier temps limiter l'extent le maxzoom et désactiver les menus en css. Je me posais d'ailleurs la question de savoir si on pouvait définir un minzoom ?

Par manque de compétence en JS je vais attendre avant de désactiver les interactions mais je penses peut-être le faire à terme.

**Comment by Gaetanbrl** [comment]
La PR est en tout cas réalisée sur la branche develop, la prochaine release contiendra donc cette évolution.

**Comment by eprouteau** [comment]
@Gaetanbrl trop top :)

**Comment by Gaetanbrl** [comment]
Oui @lecault 
@eprouteau la fonctionnalité sera dispo sur master après la prochaine release.
Il faudra donc mettre à jour ton Mviewer pour l'avoir.
