### ISSUE TITLE
Barre de recherche adresse, utilisation de l'API IGN filtré ou de l'API BAN

### ISSUE THREAD

**Issue by jerbou** [geobretagne/mviewer#572]
**Description  / Describe**
Bonjour,

Nous utilisions une instance de l'API OpenLS de l'IGN, l'url était de type :
https://wxs.ign.fr/CLEF/ols/apis/completion?terr=21;25;39;58;70;71;89;90
Elle permettait de filtrer les résultats de l'autocomplétion sur nos 8 départements de BFC.
Mviewer reprenait bien les réponses...
J'ai l'impression que la "nouvelle clé" renvoie des résultats différents https://wxs.ign.fr/essentiels/geoportail/ols?

1/ Est-ce que c'est moi qui ne comprends pas comment utiliser la clé IGN nouvelle formule

Je n'ai jamais pu reproduire ce comportement de filtrage avec l'API BAN ;
La documentation https://adresse.data.gouv.fr/api-doc/adresse
propose des paramètre de priorité en lat, long mais je ne vois pas comment rajouter les paramètre &lat & long sans invalider le xml

2/ Avez vous un RETEX sur du filtrage par API BAN qui marche bien avec Mviewer, Mviewer Studio ?

D'avance Merci,

Jérôme Boutet

**Comment by Gaetanbrl** [comment]
> Avez vous un RETEX sur du filtrage par API BAN qui marche bien avec Mviewer, Mviewer Studio ?

Je ne suis pas certain de comprendre, c'est l'ajout des paramètres lat et long que tu souhaites réaliser ?

> 'ai l'impression que la "nouvelle clé" renvoie des résultats différents

@bchartier @lecault vous avez des clés IGN pour tester ?

**Comment by Gaetanbrl** [comment]
si c'est le service wxs.ign.fr/essentiels que tu souhaites utiliser il faut en effet le rajouter comme service de recherche Mviewer.
Actuellement c'est la api-adresse.data.gouv.fr qui est utilisé, avec un format de réponse et de paramètres d'envoi différents.

**Comment by Gaetanbrl** [comment]
C'est ici qu'il faut rajouter le code pour cette API

https://github.com/geobretagne/mviewer/blob/d862151406effda754999aed570d71fdcf923889/js/search.js#L271-L272

**Comment by jerbou** [comment]
Merci pour la réponse rapidissime.

Je croyais que l'on pouvait ajouter l'url comme une url de confiig basé sur le service Géoportail.

![2022-02-21_16h11_48](https://user-images.githubusercontent.com/7600693/154982130-434cdb28-8d11-40b2-a942-42203f9688d7.png)

@Gaetanbrl tu précises donc des ajouts à faire (ajout de service), autant je peux demander au prestataire de faire les modifications pour avoir un custom... autant "quelle avenir" a la config ou API geoportail dans le Mviewer (si il y a eu des changements) ? (pensez aux "utilisateurs simples")
Devrait on implémenter cette nouvelle API par défaut ?

En attendant sur le 2eme, filtage via api-adresse.data.gouv.fr si vous avez des pistes, je suis preneur :)

Merci en tout cas

**Comment by lecault** [comment]
Par sur de tout comprendre mais je mets notre RETEX.

Cette appli utilise la recherche d'adresse de l'IGN : https://www.bretagne.bzh/actions/grands-projets/fibre-pour-tous/deploiement/

Et voici le bout de code XML : 
<olscompletion url="https://wxs.ign.fr/essentiels/ols/apis/completion" type="geoportail" attribution="IGN"/>

**Comment by smevel** [comment]
cf. https://github.com/geobretagne/mviewer/issues/516

**Comment by Gaetanbrl** [comment]
Donc si je comprend bien, mviewer a déjà tout ce qu'il faut pour le service /completion.
Je vais tester.

**Question @lecault @smevel @spelhate :**

Je vois qu'il y a le service Look4 qui permet des recherches avec d'autres paramètres (e.g fuzzy) et le service géocodage (la BAN  étant aussi un service de recherche pour géocodage). 

On a un intérêt à vérifier la compatibilité avec mviewer et les intégrer si besoin ?

**Comment by jerbou** [comment]
Merci @lecault 

je ne vois pas le code XML, mais je comprends que vous utilisez déja https://wxs.ign.fr/essentiels/ols/apis/completion notamment dans https://kartenn.region-bretagne.fr/kartoviz/apps/region/tmp/site_region.xml
(en  Mviewer version 3.6.1) 
Cela fonctionne bien.

https://geobretagne.fr/mviewer/?x=668275&y=5976314&z=15&l=zdep_fin_travaux*&lb=positron&config=/pub/sm-megalis/apps/fibre/fibre_bzh.xml&mode=d

Je ne sais pas si cela peut aider mais le problème vient peut être de notre version Mviewer version 3.4.1 , qui reproduit l'issue 516 https://github.com/geobretagne/mviewer/issues/516

**Comment by Gaetanbrl** [comment]
> Je ne sais pas si cela peut aider mais le problème vient peut être de notre version Mviewer version 3.4.1

Le correctif est en effet dispo en v >= 3.6. Donc j'imagine qu'un changement de version est à envisager...

La modif a été faite ici :

https://github.com/geobretagne/mviewer/pull/517/files

**Comment by jerbou** [comment]
ok, merci. le correctif s'applique à l'API BAN si je comprends bien.
On va planifier une montée de version dans les prochains mois.

**Comment by lecault** [comment]
Le correctif s'applique à l'API IGN

**Comment by lecault** [comment]
@Gaetanbrl pour look4 intéressant à tester (notamment pour la recherche de parcelles).

**Comment by jerbou** [comment]
ok, merci à vous deux.
On planifie la montée de version.

Pour look4 @lecault je pourrais prendre un peu de temps pour tester sur notre préprod (sur du Mviewer 3.6).

On peut donc clore l'issue ?

**Comment by jerbou** [comment]
ok, oui on peut clore.
effet de bord sur Mviewer 3.4, on fait la MAJ en 3.6 pour retrouver la fonctionnalité.

Merci,
