### ISSUE TITLE
Fonctionnalité Hide / Display layer avec condition

### ISSUE THREAD

**Issue by tbrunelle9** [geobretagne/mviewer#580]
**Description détaillée / Detailed description**

Nous souhaitons paramétrer l'application afin que lorsque nous visualisons une couche layer, l'autre ne s'affiche pas. Et vice-versa. J'ai regardé dans les issues déjà présents et je ne crois pas que cela ait déjà fait l'objet d'un post. 

Mon cas d'usage :  quand j'affiche le découpage administratif des communes, je voudrai que les EPCI ne soient plus visible et inversement. L'idée serait peut être d'intégrer une condition entre des layers d'un même thème ? cela passerait par un customcontrol ?

Si vous avez des idées / suggestions, je suis preneur. Merci d'avance

**Comment by Gaetanbrl** [comment]
Il existe un paramètre exclusive qui permet :

`<Boolean> stipulant si la couche est exclusive. Si la valeur est « true », l’affichage de cette couche masquera automatiquement toutes les autres couches ayant ce paramètre activé.`

Visible dans la doc :
https://mviewerdoc.readthedocs.io/fr/latest/doc_tech/config_layers.html#parametres-pour-gerer-l-affichage-de-la-couche

Donc si vous mettez `exclusive=true` sur les EPCI `ET` aussi sur le découpage communal, vous devriez avoir un comportement qui fait que si les EPCI sont visibles, alors le découpage communal devient masqué et inversement.

**Comment by tbrunelle9** [comment]
Super merci pour la réactivité et la réponse, c'est exactement ce qu'il me manquait. 

Je n'avais pas connaissance de ce paramètre, j'ai dû passer à côté durant mes recherches. Je trouvais d'ailleurs assez étonnant que cela n'existait pas déjà.
