### ISSUE TITLE
Plugin filtre KO

### ISSUE THREAD

**Issue by Gaetanbrl** [geobretagne/mviewer#581]
## Description

La démo du plugin filter n'affiche plus le plugin : 
```
filter.js:38 Uncaught ReferenceError: _visibleLayers is not defined
    at filter.js:38:43
```

## Reproduire

1. Ouvrir la démo https://kartenn.region-bretagne.fr/kartoviz/?config=demo/filter/filter.xml#
2. Ouvrir la console et voir l'erreur

## Solution

Ajouter `_visibleLayers` comme `_visibleFeatures`

https://github.com/geobretagne/mviewer/blob/d862151406effda754999aed570d71fdcf923889/demo/addons/filter/js/filter.js#L18-L20

avec ...

`var _visibleLayers= new Map();`

**Comment by lecault** [comment]
Oui c'est corrigé. Voici une URL qui pointe sur develop : https://kartenn.region-bretagne.fr/mviewer/?config=demo/filter/filter.xml#.

Une petite release à pousser ?

**Comment by Gaetanbrl** [comment]
> Une petite release à pousser ?

Ca pourrait être pas mal ca fait un moment en effet.
