### ISSUE TITLE
Basemap transparence et grid

### ISSUE THREAD

**Issue by lecault** [geobretagne/mviewer#583]
**Description du bug / Describe the bug**

Lorsqu'on met un paramètre de transparence sur une basemap, on voit apparaître une grille.

**Reproduire le bug / To Reproduce**

Etapes à suivre pour reproduire votre problème du type : 

1. Aller sur la page https://kartenn.region-bretagne.fr/mviewer/?config=demo/v3.7.xml
2. Une grille apparaît avec le fond de carte transparent
 
**Comportement attendu / Exptected behavior**

Ne pas voir de grille

**Screenshots**

![image](https://user-images.githubusercontent.com/5269430/156764088-599fccc7-fc25-414d-b396-7e4a532d4599.png)

**Discussion entamée**

@spelhate Oui via une propriété CSS et une basemap (fake)

**Comment by lecault** [comment]
Du coup j'ai enlevé 
     background: url(../img/grid.png) repeat scroll center top #fff; 
dans le #map dans le mviewer.css

Voir le résultat même URL : https://kartenn.region-bretagne.fr/mviewer/?config=demo/v3.7.xml

Est-ce que ça peut avoir des effets de bords ?

**Comment by Gaetanbrl** [comment]
PR merge => Je clos
