### ISSUE TITLE
paramètres inputlabel querymaponclick  non fonctionnels

### ISSUE THREAD

**Issue by smevel** [geobretagne/mviewer#586]
**Description du bug / Describe the bug**
Plusieurs paramètres ne sont plus fonctionnels depuis la dernière release pour tous les modes (défaut, simplifié et ultrasimplifié).
- "inputlabel" pour le personnaliser le texte de la barre de recherche . Pour rappel l'issue à l'origine de la création du paramètre "inputlabel" : https://github.com/geobretagne/mviewer/issues/159
- querymaponclick : ouverture de la fenêtre après recherche. Pour rappel l'issue à l'origine de la création du paramètre : https://github.com/geobretagne/mviewer/pull/170

**Reproduire le bug / To Reproduce**

Etapes à suivre pour reproduire votre problème du type : 

1. Aller sur la page https://geobretagne.fr/mviewer/?x=-343315&y=6141400&z=8&l=zdep_fin_travaux*&lb=positron&config=/pub/sm-megalis/apps/fibre/fibre_bzh.xml#
2. La texte de la barre de recherche (inputlabel="Saisir votre adresse" dans le fichier config) n'apparaît pas
3. Saisir une adresse
4. Voir que rien ne se passe (ou l'erreur si identifiable)

**Comportement attendu / Exptected behavior**

- Ouverture de la pop-up automatiquement après la recherche d'adresse
- Texte de la barre de recherche modifié

**Environnement / Desktop**

Merci de remplir ces informations si connues :
 - OS: Windows 10
 - Navigateur / browser : Chrome 89, Firefox 98

**Informations complémentaires / Additional context**

problème apparu suite à l'installation de la nouvelle version 3.7

**Comment by lecault** [comment]
Problème du à une mauvaise saisie dans le XML, le searchparameters est en double : 

<searchparameters bbox="false" localities="true" features="false" static="false" querymaponclick="true" closeafterclick="true" inputlabel="Saisir votre adresse" />
<searchparameters bbox="false" localities="true" features="false" static="false"/>

Je clos
