### ISSUE TITLE
Extension - script JS

### ISSUE THREAD

**Issue by Gaetanbrl** [geobretagne/mviewer#592]
**Description du bug / Describe the bug**

@spelhate j'ai l'impression que le Mviewer ne charge pas le fichier d'une lib si ce n'est pas un type component.

Ici on va appeler le plugin si c'est du JS : 

https://github.com/geobretagne/mviewer/blob/b908158312c1d80221e404acf75e83f7a2c7aec3/js/configuration.js#L106

Mais j'ai l'impression qu'on en fait rien ?  Car ensuite quand la requête est terminé on envoi un trigger qui n'a rien à voir avec les extensions JS.

https://github.com/geobretagne/mviewer/blob/b908158312c1d80221e404acf75e83f7a2c7aec3/js/configuration.js#L124

**Comment by Gaetanbrl** [comment]
Fix réalisé dans la branche `jquery_less`.

**Comment by spelhate** [comment]
> @spelhate j'ai l'impression que le Mviewer ne charge pas le fichier d'une lib si ce n'est pas un type component.

Il y a deux types d'extensions supportés (javascript pour charger une lib externe par exemple et component)
@Gaetanbrl , ça ne fonctionne pas quand tu précises `type="javascript"` ?

**Comment by Gaetanbrl** [comment]
> ça ne fonctionne pas quand tu précises type="javascript" 

Non, et je ne vois pas comment le code actuel le permet ? Ou alors j'ai loupé un truc

**Comment by spelhate** [comment]
Je viens de tester cette conf en 3.7
```
<extensions>
    <extension type="javascript" src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.7.1/chart.min.js"/>
 </extensions>
```

Et dans la console en tapant `Chart.version` , je constate que la lib est bien chargée :
![image](https://user-images.githubusercontent.com/1793792/163972355-408488e5-51ea-460a-9391-8868315bcc4b.png)

**Comment by Gaetanbrl** [comment]
Ok j'avais pas mis le `type="javascript"`. Ca fonctionne bien du coup.

Par contre c'est dommage de ne pas avoir d'event pour le JS (ce que j'ai rajouté dans le code de la branche` jquery less`).

**Comment by Gaetanbrl** [comment]
Je clos, l'issue n'est pas.
