### ISSUE TITLE
Bug - Tooltip au mauvais endroit avec map de taille différente

### ISSUE THREAD

**Issue by Gaetanbrl** [geobretagne/mviewer#594]
### Description

J'ai une extension qui prend 50% de la taille de la fenêtre avec une carte de 50% (via le CSS).
Lorsque j'ajoute une tooltip, cette dernière ne s'affiche pas au bon endroit.

Il semblerait que ce soit ce CSS qui fixe la position avec pixels qui ne sont pas bons : 

https://github.com/geobretagne/mviewer/blob/b908158312c1d80221e404acf75e83f7a2c7aec3/js/info.js#L634-L637

J'ai donc essayé avec une overlay pour remplacer la tooltip par défaut afin d'utiliser les coordonnées et l'overlay s'affiche correctement à partir des coordonnées.

Pour le test, j'ai converti les coordonnées en pixel et là, les coordonnées pourtant corrects redonnent des pixels au mauvais emplacement comme si c'était les pixels de la position par défaut avec une carte de 100% : 

```
    let pixTest = mviewer.getMap().getPixelFromCoordinate(evt.coordinate);
    _featureTooltip.css({
        left: pixTest[0] + 'px',
        top: pixTest[1] + 'px'
    });
```

Voici le résultat la différence (en noir la mauvaise position) : 

![image](https://user-images.githubusercontent.com/16317988/164230435-5e2a6eda-87a5-40c6-885a-1eabdd4047e3.png)

@spelhate pourquoi on n'utilise pas l'overlay par défaut d'openlayers ?

**Comment by Gaetanbrl** [comment]
Il semble y avoir quelque chose qui modifie les coordonnée après le rendu de la tooltip : 

![image](https://user-images.githubusercontent.com/16317988/164233251-0f198699-3039-4391-b762-2611bdf1da2b.png)

**Comment by Gaetanbrl** [comment]
Je pense que j'ai reproduis le soucis #390.

Si on utilise un overlay on ne prendra plus du CSS pour localiser une tooltip mais les vraies coordonnées de la carte / de la feature.

Pour décaler la popup on pourra utiliser la prop offset de l'overlay : 
https://openlayers.org/en/latest/apidoc/module-ol_Overlay-Overlay.html

**Comment by spelhate** [comment]
> @spelhate pourquoi on n'utilise pas l'overlay par défaut d'openlayers ?

Je n'ai pas de réponse. Peut-être que ça n'existait pas avec ol3. Ok pour utiliser l'overlay d'Openlayers.

**Comment by Gaetanbrl** [comment]
> Peut-être que ça n'existait pas avec ol3. Ok pour utiliser l'overlay d'Openlayers.

Oui c'est probable, je me demandais surtout si la raison n'était pas dû à une utilisation polyvalente pour une autre fonctionnalité et que l'utilisation d'un overlay ajoute une régression.

> Ok pour utiliser l'overlay d'Openlayers.

Top ! :)
