### ISSUE TITLE
/!\ - UPDATE branche develop

### ISSUE THREAD

**Issue by Gaetanbrl** [geobretagne/mviewer#597]
La branche `develop` n'a pas été mise à jour suite aux dernières release.

On a donc un écart de commits entre les branches `master` et `develop` car les commits de merge ne sont pas dans la branche develop.

Ce problème peut engendrer des conflits lors du merge `master <-- develop` et donc des complications pour celui qui fait le merge.

**Les prochaines release devront donc obligatoirement afficher après le merge une branche develop et master identique.**

**Comment by lecault** [comment]
Cela vient d'où ? 
C'est pas mes modifs de docs sur develop ?

**Comment by spelhate** [comment]
Par exemple : ce commit directement fait sur master https://github.com/geobretagne/mviewer/commit/c5cc2e8fa48def0a9234fe299d24b89e4248daa4

**Comment by spelhate** [comment]
La règle 0 commit sur master. On ne fait que des merges depuis develop. Par contre je ne sais pas comment récupérer le truc.
@Gaetanbrl l'expert, tu as une idée ?

**Comment by Gaetanbrl** [comment]
> La règle 0 commit sur master.

La règle d'or en effet.

Sinon pour moi c'est dû au commit de merge. Quand on merge de develop à master, on a un commit spécifique qui est ajouté dans master. Sauf que ce commit n'existe pas dans la branche originale develop, mais que dans la branche cible du merge.

On a plusieurs solutions : 

1. A la main, faire un rebasage de develop pour récupérer tous les commit de master vers develop et ainsi ne pas écraser les nouveaux commit qui sont dans develop mais pas encore dans master (vu que la release est pas encore faite)
2. On fait la prochaine release , on supprime develop et on recréé une develop à partir de master (delete + copy from master)

Je vais tester la première solution `1` prochainement, plus propre à mon sens pour garder un espace local propre sur les PC de chacun lors du `pull` de develop.

Sinon on passera sur la seconde méthode mais il faudra bien veiller à mettre à jour vos branche develop locale, quitte à les supprimer (`git branch -d develop`) puis à faire un `fetch --force`  derrière pou récupérer la nouvelle branche develop (un truc du genre je sais plus précisément).

**Vu dernièrement sur un autre projet :** 

Si jamais on a un conflit lors de la prochaine release car on a une branche master qui diverge de develop, GitHub proposera des commandes à passer pour réaliser le rebase + merge afin d'avoir une branche develop propre et à jour avec master avant de faire le merge de la release de develop vers master. En gros on met develop à jour et ensuite on fait le merge avec une résolution de conflit à la mano. Ca peut avoir des risques car on peut mal gérer le conflit mais ca se fait bien.

**Comment by lecault** [comment]
> La règle 0 commit sur master
Oui je suis dac avec cet règle d'or

Pour l'exemple oui ça doit être un oubli sur develop que j'ai du faire directement sur master.

Tu as moyen de voir tous les commits posant soucis ?

**Comment by Gaetanbrl** [comment]
> Tu as moyen de voir tous les commits posant soucis ?

Faut chercher dans l'arbre des commits ou faire un diff sur le code (pas simple avec les modif dans develop)

**Comment by lecault** [comment]
Dans cet optique j'ai fait ça https://github.com/geobretagne/mviewer/commit/de8643db4d9539212eb9ce1b453a702103522c6c pour corriger ça https://github.com/geobretagne/mviewer/commit/d862151406effda754999aed570d71fdcf923889. 

En gros un commit pour que master et develop ai le même contenu.

Est-ce le bon mode opératoire ?

**Comment by Gaetanbrl** [comment]
> En gros un commit pour que master et develop ai le même contenu

Pas sur de comprendre ce que tu cherches à faire avec ces commits.

**Comment by lecault** [comment]
En fait j'ai fait la modif qui a été fait sur master sur develop dans un nouveau commit.
Mais j'ai l'impression que github n'aime pas cela.

**Comment by spelhate** [comment]
> Je vais tester la première solution `1` prochainement, plus propre à mon sens pour garder un espace local propre sur les PC de chacun lors du `pull` de develop.

Merci @Gaetanbrl
Si on peut aider d'une manière ou une autre.

**Comment by spelhate** [comment]
> Je vais tester la première solution `1` prochainement, plus propre à mon sens pour garder un espace local propre sur les PC de chacun lors du `pull` de develop.

Merci @Gaetanbrl
Si on peut aider d'une manière ou une autre.
