### ISSUE TITLE
Appel d'un JSON externe dans un template mustache et rendu des informations

### ISSUE THREAD

**Issue by eprouteau** [geobretagne/mviewer#600]
Bonjour,

Sur un projet perso afin d'alléger le geojson du customlayer une grande partie des attributs sont dans un fichier json propre à chaque entité.

Je souhaite pouvoir appeler ce json et afficher les informations via le template mustache de la layer (faisable en le traitant en pure js directement dans le template). 

Ma question porte sur le fait de bénéficier de la syntaxe mustache pour afficher les informations de mon json dans le template mustache suite à l'appel du json dans le template.

Est ce possible ? ou auriez vous d'autres pistes ?

J'espère que ma question est claire :)

Bonne journée,

**Comment by Gaetanbrl** [comment]
Est-ce que cette doc répond à ton besoin ?

https://mviewerdoc.readthedocs.io/fr/latest/doc_dev/customlayer_template.html?highlight=handle

Il s'agit d'utiliser un handler dans le custom layer pour appeler ton json et passer les données au mustache comme tu en as besoin.

**Comment by eprouteau** [comment]
C'est exactement ce comportement effectivement (plus je mets le nez dans le mviewer et plus j'adore :) et merci pour la qualité des docs )

Du coup j'ai regardé rapidement pour essayé de comprendre car je pars de loin niveau compréhension et dev js :). 

Dans un premier temps j'essaye de reproduire un comportement classique de fiche d'information sans l'appel à mes json mais avec le handle d'actif (car lorsqu'il est déclaré ça prend le dessus sur le comportement classique). 

j'ai déjà fait un petit bout de code mais j'ai une erreur dans la console sur le getView (par contre la fiche fonctionne).

J'ai mis le customlayer en PJ (je dois remettre en place mon git)

URL de l'appli : https://emeric-prouteau.alwaysdata.net/mviewer37/?config=apps/rando_dordogne/rando_dordogne.xml#
[boucle.zip](https://github.com/geobretagne/mviewer/files/8630576/boucle.zip)

**Comment by eprouteau** [comment]
C'est exactement ce comportement effectivement (plus je mets le nez dans le mviewer et plus j'adore :) et merci pour la qualité des docs )

Du coup j'ai regardé rapidement pour essayé de comprendre car je pars de loin niveau compréhension et dev js :) je me base sur la couche els.js

Dans un premier temps j'essaye de reproduire un comportement classique de fiche d'information sans l'appel à mes json mais avec le handle d'actif (car lorsqu'il est déclaré ça prend le dessus sur le comportement classique).

Prochaine étape faire l'appel à un json simple ;)

**Comment by eprouteau** [comment]
Avec l'exemple cluster.js, j'ai l'erreur suivante dans la console : 
![image](https://user-images.githubusercontent.com/1401902/167013489-3da928af-cb68-4f55-9115-cc0d4efe1c40.png)
 Je n'arrive pas à trouver d'où ca vient.

**Comment by Gaetanbrl** [comment]
@eprouteau je regarde de plus près en début de semaine prochaine ;)

**Comment by eprouteau** [comment]
Merci beaucoup d'avance. j'ai mis mon apps sur git pour plus de facilité

https://github.com/eprouteau/apps.git

**Comment by eprouteau** [comment]
J'ai fait ca et j'arrive à récupérer les éléments dans le template mustache

```
const layer =  new ol.layer.Vector({
    source: new ol.source.Vector({
        url: "apps/rando_dordogne/data/boucle.geojson",
        format: new ol.format.GeoJSON()
    }),
    style: new ol.style.Style({
        stroke: new ol.style.Stroke({ color: 'rgba(252, 205, 29,1.0)', width: 2 })
    })
});

const handle = function(features, views) {
    var renderHTML = function (elements) {
        features.forEach(feature => {
            feature.setProperties({
                "territoires":[
                   {
                      "type":"TERRITOIRE",
                      "id":5582341,
                      "nom":{
                         "libelleFr":"Charente-Maritime"
                      },
                      "identifier":"SITRA2_GEO_5582341",
                      "state":"PUBLISHED"
                   },
                   {
                      "type":"TERRITOIRE",
                      "id":5625635,
                      "nom":{
                         "libelleFr":"Pays Marennes-Oléron"
                      },
                      "identifier":"SITRA2_GEO_5625635",
                      "state":"PUBLISHED"
                   }
                ]
             })
            //console.log("feature",feature.getProperties())

        });

        var l = mviewer.getLayer("boucle");
        var html;
        if (l.template) {
            html = info.templateHTMLContent(elements, l);
        } else {
            html = info.formatHTMLContent(elements, l);
        }
        var view = views["right-panel"];
        view.layers.push({
            "id": view.layers.length + 1,
            "firstlayer": true,
            "manyfeatures": (elements.length > 1),
            "nbfeatures": elements.length,
            "name": l.name,
            "layerid": "boucle",
            "theme_icon": l.icon,
            "html": html
        });
    };
    renderHTML(features);
};

new CustomLayer('boucle', layer,null,handle);
```

**Comment by Gaetanbrl** [comment]
@eprouteau du coup tu as résolu ton soucis ?

**Comment by eprouteau** [comment]
@Gaetanbrl 
```
const handle = function(features, views) {
    var renderHTML = function (elements) {
        features.forEach(feature => {
            console.log("Ascent",feature.get('id_itineraire'));
            $.ajax({
                url: "apps/rando_dordogne/data/test_json.json",
                async: false,
                dataType: 'json',
                success: function(data) {
                    feature.setProperties(data)
                }
            });
            console.log("feature",feature.getProperties())
            var source = mviewer.getLayer("patrimoineculturel").layer.getSource();
            console.log("Dir",mviewer.getLayer("patrimoineculturel").layer.getSource())
        });

        var l = mviewer.getLayer("boucle");
        var html;
        if (l.template) {
            html = info.templateHTMLContent(elements, l);
        } else {
            html = info.formatHTMLContent(elements, l);
        }
        // force l'affichage selon le mode mobile ou desktop
        if (configuration.getConfiguration().mobile) {
            panel = "modal-panel";
        } else {
            panel = "right-panel"
        }
        var view = views[panel];
        view.layers.push({
            "id": view.layers.length + 1,
            "firstlayer": true,
            "manyfeatures": (elements.length > 1),
            "nbfeatures": elements.length,
            "name": l.name,
            "layerid": "boucle",
            "theme_icon": l.icon,
            "html": html
        });
    };
    renderHTML(features);
};
```

j'ai fais ca et cela semble fonctionner. Parfois au clic j'ai un retour de deux fois la même entité mais si je vide la cache du navigateur ca ne m'en renvoi bien qu'un.
