### ISSUE TITLE
Extensions et chargement de la carte

### ISSUE THREAD

**Issue by Gaetanbrl** [geobretagne/mviewer#603]
# Description

Lorsqu'on utilise des extensions, on peut avoir besoin de manipuler ou accéder à la carte via `mviewer.getMap()`.
Mais les extensions sont souvent prêtes avant la carte et `mviewer.getMap()` renvoi une erreur (e.g lorsqu'on ajoute un event au click via une extension) .

# Solution

> Testé et approuvée

Je propose de rajouter un event : 

```
        const mapReadyEvent = new CustomEvent('map-ready', {
            detail: {
              map: _map
            }
        });
        document.dispatchEvent(mapReadyEvent);
```

**Comment by lecault** [comment]
Merci Gaëtan. 
Ce soucis peut t'il expliquer le fait que des extensions ne soit pas disponibles au démarrage de l'application quelques fois ?

**Comment by Gaetanbrl** [comment]
> Ce soucis peut t'il expliquer le fait que des extensions ne soit pas disponibles au démarrage de l'application quelques fois ?

Ca dépend comment sont faites les extensions mais les raisons principales sont de ce type.

**Comment by lecault** [comment]
Bon j'ai toujours un soucis non bloquant. L'extension layerfilter ne s'affiche pas toujours.
Cela ne remet pas en cause cette PR
