### ISSUE TITLE
Associer un template mustache à un custom layer

### ISSUE THREAD

**Issue by vfabry** [geobretagne/mviewer#606]
Bonjour,

Est-ce qu'on peut associer un template mustache à un custom layer, par exemple à celui décrit ici :
https://mviewerdoc.readthedocs.io/fr/latest/doc_dev/customlayer.html#customlayer 
(arcgis rest feature) ?

Vincent

**Comment by lecault** [comment]
Bonjour Vincent, 

A partir d'un custom layer oui (exemple source WFS).
Pour l'exemple KML je pense aussi mais pas testé.

**Comment by vfabry** [comment]
Effectivement, ça fonctionne très bien. Merci Loïc !
