### ISSUE TITLE
Utilisation du paramètre titlehtml dans le fichier de config

### ISSUE THREAD

**Issue by eprouteau** [geobretagne/mviewer#607]
Bonjour tout le monde,

Je voulais savoir comment utiliser le paramètre titlehtml dans le fichier de config. En le déclarant avec comme valeur : Titre<br>Sous-titre, l'appli ne se charge pas.

Bonne journée,

**Comment by Gaetanbrl** [comment]
Je crois qu'il y a un soucis dans la doc (vu par @Agath21 )

> dans la doc c'est marqué titlehtml 
> alors que c'est htmltitle le paramètre

Il me semble qu'elle a fait la modif dans la doc (branche develop), elle est donc à rebuilder si besoin.

**Comment by Gaetanbrl** [comment]
aussi @eprouteau il faut utiliser la même syntaxe que pour la source d'un layer.
C'est à dire &lt; et non < et idem pour les autres caractères spéciaux.

En gros, c'est la colonne "Entity" des caractères ici listés : 

https://www.htmlhelp.com/reference/html40/entities/special.html

**Comment by lecault** [comment]
Pour voir un exemple : 
https://kartenn.region-bretagne.fr/kartoviz/?config=demo/v3.6.xml
https://kartenn.region-bretagne.fr/kartoviz/demo/v3.6.xml
