### ISSUE TITLE
Migration 3.2 --> 3.7

### ISSUE THREAD

**Issue by stephyritz** [geobretagne/mviewer#608]
Salut,

Nous utilisons actuellement un mviewer en version 3.2. Il y a eu plusieurs projets réalisés avec peu de complexité. Nous souhaitons savoir si un changement de version pourrait impacter nos différentes cartes existantes ? Existe-t-il des points d'attentions spécifiques à vérifier avant de monter en version ?

Voici par exemple, quelques projets concernés : 
https://sdi.georhena.eu/mviewer/?config=Carte_bonnes_pratiques.xml
https://sdi.georhena.eu/mviewer/?config=Tous_ins_Museum.xml
https://sdi.georhena.eu/mviewer/?config=vinbiodiv_FR.xml

Bonne journée !

**Comment by lecault** [comment]
Salut,

A la région je n'ai pas souvenir de difficulté du à une migration. Au vu de tes cartes je pense pas qu'il n'y ai de soucis.
Si nous remarquions des bug, un ticket était fait et la correction rapidement réalisée.

La bonne pratique est de déployer une autre instance mviewer et de tester tes cartes dessus.
Exemple : https://sdi.georhena.eu/mviewer-test/?config=Carte_bonnes_pratiques.xml

Loïc,

**Comment by stephyritz** [comment]
Super, merci pour ta réponse Loïc ! Nous allons faire comme ça alors!
