### ISSUE TITLE
Custom component indicateur

### ISSUE THREAD

**Issue by vfabry** [geobretagne/mviewer#611]
**Description / Describe**

J'aimerai avoir dans la carte un panneau qui affiche un indicateur, basé sur des objets visibles dans la carte.

**Description détaillée / Detailed description**

Si j'ai une couche de zones d'activités avec un champ _surface_disponible_, je voudrai un indicateur qui affiche le nombre total de zones visibles dans la carte, ou la somme des surfaces disponibles dans chaque zone.

**Informations complémentaires / Additional context**

Le fichier de config du custom component devra permettre de définir :

- la couche sur laquelle l'indicateur va s'afficher
- le champ de la couche concerné
- le type d'opération (count, sum, moyenne...)

L'indicateur devra se mettre à jour en fonction : 

- du déplacement dans la carte
- du zoom dans la carte
- d'un éventuel filtrage via le custom component filter

On a chargé @dds2010 de réaliser ce développement pour le compte de Géo2France. 

Vincent

**Comment by Gaetanbrl** [comment]
Merci pour le partage d'info !

> un panneau qui affiche un indicateur

Quel type de panneau vous voyez ? Un qui se déplace comme le filtre, un static, dans le panel d'info... ?

**Comment by vfabry** [comment]
Un qui se déplace, comme celui sur le filtre effectivement. Comme ça si on se déplace dans la carte, on peut bouger le panneau et voir ce qu'il y a en dessous.

**Comment by smevel** [comment]
Le comportement attendu s'apparente à la fonction Dashboard de Mapstore :
https://mapstore.geosolutionsgroup.com/mapstore/#/viewer/openlayers/8613

**Comment by Gaetanbrl** [comment]
On peut limite pousser le truc pour avoir plusieurs indicateurs sur l'écran avec une config de ce type : 

```
chart: [
  {
    type: 'line',
    layer: 'idLayerX',
    operator: 'SUM'
    ...ce que vous voulez pour custom le chart
  }
]
```

**Comment by dds2010** [comment]
Corrige moi Vincent mais il me semble qu'il ne s'agit pas ici d'intégrer un graphique type 'dataviz'. 
L'objectif était plus d'afficher un panneau avec une valeur calculée (comme sur certains des widget mapstore effectivement )

Ceci dit ça pourra être une bonne base pour intégrer ce type de graphiques par la suite et on peut effectivement prévoir un champ "type" dans la configuration mais qui se limiterait ici à 'text'. Qu'en pensez vous ?

**Comment by vfabry** [comment]
Effectivement, dans le cadre de notre commande, on se limite au calcul d'un indicateur, pas de graphique pour le moment.

**Comment by spelhate** [comment]
Mon conseil reste valable même avec une dataviz de type texte 😉 
> ```javascript
>mviewer.getMap().on('moveend', _refreshDataviz);

**Comment by dds2010** [comment]
> Mon conseil reste valable même avec une dataviz de type texte 😉
> 
> > ```js
> > mviewer.getMap().on('moveend', _refreshDataviz);
> > ```
Oui tout à fait, j'ai noté ;-) 
Merci

**Comment by dds2010** [comment]
J'ai commencé à créer un nouvel addon **stats** qui se configure la manière suivante ( en prenant modèle sur l'addon filter ):
```
{
  "js": ["js/stats.js", "js/jquery.easyDrag.min.js"],
  "css": "css/stats.css",
  "html": "stats.html?v=2",
  "target": "page-content-wrapper",
  "options": {
    "mviewer":{
      "stats":{
        "tooltipPosition": "bottom-left",
        "title": "Statistiques sur le JDD Structures",
        "open": true,
        "style": {
          "border": "1px #2e5367 solid",
          "background": "#2e5367",
          "text": "white",
          "colorButton": "#2e5367"
        },
        "stats": [
          {
            "type": "stat",
            "layerId": "structures",
            "field": "",
            "template":"<span class='structcss'>Structures :<br> {x} Objets</span>",
            "operator": "COUNT"
          },
          {
            "type": "stat",
            "layerId": "structures",
            "field": "cp",
            "template":"Moyenne : {x} ",
            "operator": "MEAN"
          },
          {
            "type": "stat",
            "layerId": "structures",
            "field": "cp",
            "template":"MIN : {x} ",
            "operator": "MIN"
          },
          {
            "type": "stat",
            "layerId": "structures",
            "field": "cp",
            "template":"MAX : {x} ",
            "operator": "MAX"
          }
        ]
      }
    }
  }
}

```
ce qui donnerait ceci (le test est pas super adapté, je fais des moyenne/min/max sur le code postal mais bon...)
<img width="1899" alt="image" src="https://user-images.githubusercontent.com/438284/173581929-e2f28414-083f-4c26-b448-9b6f5a641301.png">

L'idée c'est de pouvoir définir un template pour chaque stat qui puisse être potentiellement du html simple et on peut aussi customiser le fichier css (on pourra éventuellement faire des animations css )
