### ISSUE TITLE
[Dataviz] Template : Chart avec des données externes (vue PG/ Geoserver)

### ISSUE THREAD

**Issue by ThomaSigma** [geobretagne/mviewer#619]
Bonjour à tous, 

Je vais essayer d’être le plus clair possible. 

Je souhaite faire une dataviz en pie chart de données issues d’une vue dynamique. 

1.	**Ma vue** : Sur PostGIS, j’associe **l’aire** de chaque **essence forestière dominante** par **commune**. Le résultat est dispo sur geoserver, et disponible en WFS, ou autre format (JSON également). 
2.	Sur mviewer, ma couche commune est un custom layer, sur laquelle je souhaite afficher un template avec un chiffre clés et un pie chart. Je veux que le pie chart résume les essences forestières de la commune sélectionnée. Cependant : sur le template mst, je ne comprends pas comment appeler ma vue. Je comprends qu’il est possible d’interroger les données attributaires la couche concernée. 
Mon problème est donc double : 
-	Comment appeler une source de données externe (j’avais pensé à JQuery)
-	Comment filtrer ma vue pour n’avoir que les données de la commune sélectionnée

Peut être lié à l'issue #116 

Merci d'avance pour votre temps...

**Comment by eprouteau** [comment]
Salut, 

Je pense que j'étais dans le même cas que toi. Je suis passé par la solution https://mviewerdoc.readthedocs.io/fr/latest/doc_dev/customlayer_template.html?highlight=handle que cite @Gaetanbrl. 

Ensuite pour de la simplicité et parce ce que je n'ai pas encore d'api, je prépare un json par entité en amont avec FME que je stocke sur mon serveur et que j'appel avec jquery. tu peux récupérer le code sur mon appli https://organic-perigord.fr/mviewer37/?config=apps/rando_dordogne/rando_dordogne.xml# (il faut que je la mette sur github :) )

**Comment by spelhate** [comment]
Ça mériterait une ressource dédiée dans la page des démo : "Données externes dans un template"

**Comment by ThomaSigma** [comment]
Merci @Gaetanbrl  et @eprouteau pour votre aide ! 
Finalement, je suis passé par la méthode JQuery, dans mon mst. Cela fonctionne à merveille. Merci beaucoup. 
La partie esthétique est inspirée des exemples démo.
