### ISSUE TITLE
Remplacer le fichier de configuration XML par un fichier JSON

### ISSUE THREAD

**Issue by bchartier** [geobretagne/mviewer#62]
Je propose d'utiliser un fichier JSON à la place du fichier XML.
Avantage :
- ne plus avoir besoin du parser "maison" de fichier XML
- intégrer une configuration directement avec un élément <script> dans le page HTML

Pour conserver la compatibilité avec les fichiers XML existants, il serait possible d'intégrer le parser XML dans un fichier javascript que l'on pourrait intégrer toujours avec un élément <script>.

**Comment by spelhate** [comment]
Très bonne idée.

**Comment by spelhate** [comment]
Comment fait-on pour intégrer un fichier json via un élément <script> ?
J'ai testé sous chrome ceci : 
`<script id="__config" type="application/json" src="config.json"></script>`
Mais j'obtiens le message suivant : 

> Fetching scripts with an invalid type/language attributes is deprecated and will be removed in M56, around January 2017. See https://www.chromestatus.com/features/5760718284521472 for more details.

Une idée ?

**Comment by bchartier** [comment]
Je n'ai pas réussi à reproduire cette erreur.

Ceci dit, j'ai l'impression que l'on a que 2 solutions :
- utiliser un élément `<script type="text/javascript"...>` qui renverrait vers une source contenant du code javascript valide. Par exemple : `config = {...};`
- utiliser un élément du type `<script id="__config" type="application/json" src="config.json">` mais dont le contenu doit être ensuite chargé à l'aide d'une fonction javascript j'ai l'impression.

**Comment by spelhate** [comment]
La première solution me convient. On part la dessus ?

**Comment by bchartier** [comment]
Oui, on peut partir sur ça.

**Comment by Gaetanbrl** [comment]
prévoyez-vous 2 versions pour ce fichier de config ? une version native et une version "adaptée" à l'image du fichier de config mapfishapp qui permet de prendre en compte les paramètres modifiés et insérés sans écraser les config native.

**Comment by spelhate** [comment]
Si je comprends bien ta question, il y aura une seule version du fichier de config. Pour info une application appelle un seul fichier de conf. Par défautl, il s'agit de config.xml. Il est toutefois possible (c'est le mécanisme que nous utilisons à la région) de mobiliser un autre fichier de conf en précisant le paramètre `config=` dans l'url ex: http://kartenn.region-bretagne.fr/kartoviz/?config=demo/geobretagne.xml

**Comment by Gaetanbrl** [comment]
Très bien, je n'avais pas pensé à cette méthode d'appel de conf.

**Comment by bchartier** [comment]
@spelhate : si je comprends bien ce que tu as écrit là :
https://github.com/geobretagne/mviewer/issues/83#issuecomment-419829156
Tu as implémenté la lecture des fichiers de config au format JSON mais le fichier index.html de mviewer n'est pas encore capable de lire un fichier JSON (il convertit d'abord le fichier XML en JSON). C'est bien ça ?

**Comment by spelhate** [comment]
Oui c'est ça. Je JSON de la conf est une conversion à l'arrache du xml en utilisant le plugin jquery xml2json.

Le problème c'est que le json généré de cette façon n'est pas optimisé. On obtient par exemple ce type de structure , dérivée du xml

`{ themes: {theme: [ { id: theme1}, {id: theme2}]}`

au lieu d'avoir plus naturellement

`{ themes: [ { id: theme1}, {id: theme2}]}`

**Comment by bchartier** [comment]
On ferme ce ticket ?

**Comment by spelhate** [comment]
Je n'envisage pas de travaillerà court termes  sur cette évolution. Je propose donc de fermer.

**Comment by bchartier** [comment]
Ok.
