### ISSUE TITLE
Extension layerfilter pas toujours chargée

### ISSUE THREAD

**Issue by lecault** [geobretagne/mviewer#623]
**Description du bug / Describe the bug**

Au démarrage d'une application avec l'extension layerfilter, celle-ci n'est pas toujours chargée

**Reproduire le bug / To Reproduce**

Etapes à suivre pour reproduire votre problème du type : 

1. Aller sur la page https://kartenn.region-bretagne.fr/patrimoine/#
2. L'extension layerfilter n'apparaît pas toujours.
3. Il peut être nécessaire de réessayer.

**Comportement attendu / Exptected behavior**

Affichage systématique de l'extension.
Lien vers le XML : https://kartenn.region-bretagne.fr/mviewer/apps/region/patrimoine/patrimoine.xml

**Screenshots**

Voici l'erreur retournée dans la console :

![image](https://user-images.githubusercontent.com/5269430/175531450-46f5f7ef-0bd4-4f38-b6c4-c6a5687d92db.png)
**Environnement / Desktop**

Merci de remplir ces informations si connues :
 - Version 3.7 / 3.8

**Informations complémentaires / Additional context**

Problème remarqué il y a longtemps.
Merci !

**Comment by Gaetanbrl** [comment]
Je pense que c'est lié à ce type d'issue : 

https://github.com/geobretagne/mviewer/issues/603

C'est un problème avec les extensions qui attendre un élément du coeur mviewer qui n'est pas encore chargé (e.g `[race condition](https://dev.to/jmhungdev/is-there-race-condition-in-javascript-yes-and-no-4m4p)`)

**Comment by Gaetanbrl** [comment]
Aussi lié à https://github.com/geobretagne/mviewer/issues/281

**Comment by Gaetanbrl** [comment]
@lecault typiquement si tu cliques dans la console sur le numéro de ligne à droite de l'erreur, tu verras que ca doit pointer vers ce code : 

```
          _input = document.getElementById("layerfilter-field");
          _input.addEventListener('keyup', _layerfilter);
```

Il essaie d'appliquer un événement sur un élément HTML qui n'existe pas encore car mviewer n'a pas encore terminé de chargé la TOC j'imagine.

**Comment by lecault** [comment]
Oui on le voit au démarrage que l'extension apparaît après le reste dès fois.

**Comment by Gaetanbrl** [comment]
Faudrait revoir le fonctionnement pour cet addon.

1. Ajouter l'event keyup dans le html directement

Remplacer ca : 
https://github.com/geobretagne/mviewer/blob/b908158312c1d80221e404acf75e83f7a2c7aec3/demo/addons/layerfilter/layerfilter.html#L2


... par ca : 

`  <input id="layerfilter-field" type="text" class="form-control" placeholder="Filtrer les couches"  onkeyup="layerfilter?.filter()" i18n="custom.layerfilter.placeholder">`

le point d'interrogation `layerfilter?.filter()` indique que si filter n'existe pas ca retourne `null`.

2. On rajoute les bretelles (au cas où) : 


Dans le init, remplacer : 


return {
    init: function () {
        _input = document.getElementById("layerfilter-field");
        _input.addEventListener('keyup', _layerfilter);
        _clearbutton = document.getElementById("layerfilter-clear");
        _clearbutton.addEventListener('click', _clearfilter);
    }
};
          
          
Par ... 

```
    init: function () {
        if(!document.getElementById("layerfilter-field")) return;
        _input = document.getElementById("layerfilter-field");
        _input.addEventListener('keyup', _layerfilter);
        _clearbutton = document.getElementById("layerfilter-clear");
        _clearbutton.addEventListener('click', _clearfilter);
    }
```

3. Ajouter une méthode `filter `pour avoir `layerfilter.filter` : 

Dans le return, rajouter une propriété `filter` : 

```
  return {
      filter: _layerfilter
      init: ....
  }
```

**Comment by Gaetanbrl** [comment]
si tu veux tester avec ces modif @lecault

**Comment by Gaetanbrl** [comment]
@lecault tu peux tester la branche issue-623, j'ai fais les modifs dites au-dessus directement via github sans tester encore

**Comment by lecault** [comment]
Alors je n'ai plus d'erreur en console mais pas d'extension non plus :(

**Comment by lecault** [comment]
Ah si pareil. Tu peux voir ici https://kartenn.region-bretagne.fr/mviewer/?config=apps/region/patrimoine/patrimoine.xml

**Comment by Gaetanbrl** [comment]
C'est plus la même erreur je crois : 

> TypeError: Cannot read properties of null (reading 'hasChildNodes')

**Comment by Gaetanbrl** [comment]
Bon faut regarder plus en détail :/

**Comment by lecault** [comment]
Merci pour l'essai

**Comment by Gaetanbrl** [comment]
@lecault issue toujours d'actualité dans la develop actuelle ?

**Comment by lecault** [comment]
ça fonctionne, merci. Je clos.
