### ISSUE TITLE
Custom lyaer GeoTiff COG

### ISSUE THREAD

**Issue by vfabry** [geobretagne/mviewer#628]
Bonjour,

Je cherche à faire un custom layer qui charge un geotiff (au format cog), en me basant sur : https://openlayers.org/en/latest/examples/cog.html 
Je l'ai déclaré comme ça : 
```
const layer = new ol.layer.TileLayer({
    sources: new ol.source.GeoTIFF({
		url: "https://www.geo2france.fr/public/cog_debug/2021_R32_Ortho_0m20_RVB_COG.tif",
    })  
});
new CustomLayer('cog_public', layer);
```
Quand je l'ouvre dans un mviewer j'obtiens l'erreur : 

> error custom Layer : TypeError: ol.source.GeoTIFF is not a constructor

Vous voyez d'où peut venir le problème ?

Vincent

**Comment by spelhate** [comment]
Salut Vincent. Ca vient peut être de la version d'OpenLayers qui n'est pas adaptée ? tu utilises quelle version de mviewer ?

**Comment by vfabry** [comment]
Mviewer version 3.7

**Comment by vfabry** [comment]
OK, merci d'avoir regardé Sébastien !
