### ISSUE TITLE
(Enhancement) Mouse-position

### ISSUE THREAD

**Issue by Gaetanbrl** [geobretagne/mviewer#63]
Suite à des demandes sur l'affichage de la position de la souris, j'ai intégré ce [control ](https://openlayers.org/en/latest/apidoc/ol.control.MousePosition.html) openlayers dans un mviewer.
L'affichage du control dépend du paramètre booléen "mouseposition" dans le config.xml : 
`<application mouseposition="true"/> `

Cette contribution est-elle pertinente pour vous ? Si tel est le cas, où / comment souhaiteriez-vous voir les coordonnées du pointeur ? 
Je les affiche actuellement de manière simple à gauche du sélecteur de fond  : 

![image](https://user-images.githubusercontent.com/16317988/34408857-82246c4c-ebc6-11e7-815a-da9d279b490c.png)

Les données sont dans l'ordre x, y. La chaîne de caractères "x , y" s'affiche si la souris sort du viewport (map) :

![image](https://user-images.githubusercontent.com/16317988/34411156-39b2d372-ebd5-11e7-93f6-a005fa17f31c.png)

**Comment by bchartier** [comment]
J'aime bien cette contribution.

J'ai fait 2 commentaires dans le pull request (désolé, j'ai vu le pull request avant l'issue) :
- Pourquoi utiliser espg:3857? Les coordonnées dans cette projection ne semblent pas très utiles pour un utilisateur normal (selon moi). Si espg:3857 est requis pour vos cas d'utilisation je suggèrerais de rendre la projection paramétrable dans le config.xml et du'tiliser epsg:4326 par défaut.
- Pourquoi ce contrôle est-il actif par défaut ? Je préfèrerais qu'il ne le soit pas pour ne pas changer l'apparence des application mviewer développées jusqu'ici..

Concernant l'apparence et la position, je n'ai pas trop d'avis sur la question. Ceci dit, si l'on souhaite mettre les coordonnées à côté du contrôle de sélection de fond de carte il faudra s'assurer que cela passe bien avec les 2 types de sélecteur de fond de carte.

Pour l'exemple donné dans la copie d'écran on a une précision qui est énorme. Avoir 4 décimales après la virgule systématiquement pour des coordonnées exprimées en mètres c'est trop. Pour des coordonnées en degrés à l'inverse ce ne sera pas suffisant mais dans ce cas il faudra peut-être envisager d'utiliser la même syntaxe que pour l'affichage des coordonnées du clic sur la carte (cf. https://github.com/geobretagne/mviewer/blob/master/lib/mviewer.js#L601-L602).

Remarque en passant : comme on commence à avoir pas mal de contrôles activables sur la carte je pense qu'il faut qu'on arrive à rendre la mise en page de la carte paramétrable : permettre de repositionner et modifier l'apparence des contrôles sans forcément complexifier le config.xml (je travaille sur un prototype qui utilise Mustache pour charger en dynamique le contenu index.html).

**Comment by Gaetanbrl** [comment]
Merci pour ce retour. 

> Il faudra s'assurer que cela passe bien avec les 2 types de sélecteur de fond de carte.

Le style a été repris sur la forme de l'échelle pour éviter les soucis de visualisation avec les fonds de plan, à moins que ce type de style posé déjà des soucis de lecture. Aussi, il y avait bien un soucis avec le mode "gallery". Des modifications ont déjà été faites dans la PR sur cette problématique. 
![image](https://user-images.githubusercontent.com/16317988/34490976-f4dd441a-efe1-11e7-97d2-b200d6ae26a0.png)


> Avoir 4 décimales après la virgule systématiquement pour des coordonnées exprimées en mètres c'est trop.

Je partage l'idée. On peut en effet reprendre [ce code](https://github.com/geobretagne/mviewer/blob/master/lib/mviewer.js#L601-L602). Je fais une modification.

> je pense qu'il faut qu'on arrive à rendre la mise en page de la carte paramétrable

Ce serai super ! Mais il serait sûrement préférable d'ajouter ces modifications aux travaux en cours pour 
ne pas faire de doublons.

**Comment by spelhate** [comment]
Bonne idée que cette évolution.
A la lecture du code : https://github.com/geobretagne/mviewer/pull/64/files#diff-eea46eaeb0ce940d07a529b1c332ffbcR2632, il semble que ce nouveau contrôle n'est pas actif par défaut, ce qui me va très bien. Sinon je partage l'idée de @bchartier concernant le paramétrage de la projection utilisée pour ce contrôle. Ca pourrait donner ceci : 
`mouseposition="true" mousepositionsrs="4326"`

Sinon, j'ai commenté ta pull request concernant un bug lié à la projection.
https://github.com/geobretagne/mviewer/pull/64/commits/9fee1dca481973047b177da96414d875328d60c9#diff-eea46eaeb0ce940d07a529b1c332ffbcR2675
 En effet la projection de l'application est définie dans un config.xml dans la section mapoptions. Dans le code on peut ensuite récupérer cette valeur en utilisant cette expression : ` _projection.getCode()`.

La  projection peut être 3857, mais aussi 2154 ou autre chose. Dans le deuxième dernier cas, le controle-mouse position transforme des coordonnées 2154 en 4326 en utilisant une transformation 3857 --> 4326 et donne donc de mauvaises coordonnées.

**Comment by Gaetanbrl** [comment]
Super ! merci pour cette modification. 

> mousepositionsrs="4326"

N'est-ce pas une complexification que de mettre autant de paramètre SRS que de control ?
