### ISSUE TITLE
Gestion de l'identifiant si plusieurs extensions

### ISSUE THREAD

**Issue by vfabry** [geobretagne/mviewer#630]
**Description  / Describe**

Je ne sais pas comment paramétrer ma carte si je veux mettre plusieurs extensions. Imaginons que j'ai une première extension "stats" dans ma carte. Dans le xml de ma carte j'aurais :
`id="stats"`
...
`<extensions>`
		`<extension type="component" id="stats" path="apps/"/>`
`</extensions>`

Comment je fais pour ajouter l'extension filter, par exemple ?

Vincent

**Comment by bchartier** [comment]
Je ne suis pas le plus affuté sur ce genre de question, mais je dirais :

```
<extensions>
    <extension type="component" id="stats" path="apps/"/>
    <extension type="component" id="filter" path="apps/"/>
</extensions>
```

**Comment by vfabry** [comment]
Ce que je ne comprends pas bien, alors, c'est à quoi fait référence le id déclaré dans la partie <application> du xml, et où est-ce qu'on le retrouve dans la config des extensions/component.

**Comment by lecault** [comment]
Salut,

L'id est lié à l'application.


id="monappli"
...
<extensions>
<extension type="component" id="stats" path="apps/"/>
</extensions>

**Comment by lecault** [comment]
Je viens de me rendre compte que cette histoire d'id n'est pas explicité dans la doc je me note ça.

**Comment by vfabry** [comment]
Il m'a fallu un peu de temps (on va mettre ça sur le compte de la canicule) mais je crois que j'ai compris :
* une même appli mviewer peut avoir plusieurs extensions (gérées par l'id des extensions)
* une même extension peut servir à plusieurs applications, dans le même fichier config.json (gérées par l'id de l'application)
