### ISSUE TITLE
Nouveau template 'allintabs'

### ISSUE THREAD

**Issue by cbriand** [geobretagne/mviewer#633]
**Description / Describe**

Nouveau template pour les panels de fiches détaillées qui rend toutes les features sélectionnées indépendantes.
Au lieu d'un affichage couche par couche et d'un compteur de features sur chaque couche, le template présente un accès direct à toutes les features sélectionnées. L'astuce consiste à faire croire au MViewer qu'il y a autant de couches avec une unique feature.

_Template default_ :
![image](https://user-images.githubusercontent.com/38095778/182627561-47c791e4-49d4-4a59-9eeb-8d473715affa.png)

_Template allInTabs_ :
![image](https://user-images.githubusercontent.com/38095778/182627790-284f09a7-0bed-4cd5-a609-50c82f4c1f24.png)

**Description détaillée / Detailed description**
2 fichiers sont impactés : 
- template.js
- info.js :
    - Fonctions _queryMap et callback : répartition des features dans des couches "fictives" et gestion des html_result
    - Ajustement de la fonction orderViewsLayersByMap

**Informations complémentaires / Additional context**

Ce template est utilisé pour les cartes produites à Rennes Métropole

**Comment by spelhate** [comment]
Merci pour l'info @cbriand. Les fichiers modifiés sont visibles quelque part ?

**Comment by Gaetanbrl** [comment]
vu avec @cbriand , la PR va arriver prochainement avec le code source.

**Comment by Gaetanbrl** [comment]
@cbriand Comment ca se comporte avec d'autres couches cliquées qui n'ont pas ce template ?

**Comment by cbriand** [comment]
@Gaetanbrl Le template est défini au niveau de l'application et non au niveau de la couche. On ne peut pas avoir deux templates différents pour un même panneau.

**Comment by Gaetanbrl** [comment]
> Le template est défini au niveau de l'application et non au niveau de la couche. On ne peut pas avoir deux templates différents pour un même panneau.

Je ne comprend pas.

Lorsqu'on utilise la balise `<template>` + le paramètre `infopanel ` d'une couche on défini bien un template spécifique par couche ?

https://github.com/geobretagne/mviewer/blob/master/demo/v3.5.xml#L61

**Comment by cbriand** [comment]
OK, je pense comprendre la confusion : il existe plusieurs niveaux de template d'un panneau d'info : applicatif et couche. Le template "allintabs" concerne le rendu global du panneau d'information. Il est précisé dans les paramètre d'application templaterightinfopanel ou templatebottominfopanel et se glisse parmi les autres choix (default|brut|accordion).
Au niveau du rendu de la couche, on dispose des deux paramètres suivants : 
- infopanel : indique quel panneau d'information est activé pour la couche
- template : précise le rendu personnalisé de la fiche d'info (fichier mst)

Le template "allintabs" concerne le rendu du panneau et non pas le rendu personnalisé de la couche. Il est basé sur le template d'application "default" et son rendu par onglet. Il n'a aucune conséquence sur le rendu personnalisé de la couche, puisqu'il ne fait que répartir les features sur des couches "fictives" qui respectent le paramétrage d'origine.

**Comment by Gaetanbrl** [comment]
> concerne le rendu du panneau et non pas le rendu personnalisé de la couche

Je comprend mieux.

**Comment by spelhate** [comment]
> 

C'est juste

**Comment by spelhate** [comment]
> @Gaetanbrl Le template est défini au niveau de l'application et non au niveau de la couche. On ne peut pas avoir deux templates différents pour un même panneau.

Cest juste

**Comment by spelhate** [comment]
> OK, je pense comprendre la confusion : il existe plusieurs niveaux de template d'un panneau d'info : applicatif et couche. Le template "allintabs" concerne le rendu global du panneau d'information. Il est précisé dans les paramètre d'application templaterightinfopanel ou templatebottominfopanel et se glisse parmi les autres choix (default|brut|accordion). Au niveau du rendu de la couche, on dispose des deux paramètres suivants :
> 
>     * infopanel : indique quel panneau d'information est activé pour la couche
> 
>     * template : précise le rendu personnalisé de la fiche d'info (fichier mst)
> 
> 
> Le template "allintabs" concerne le rendu du panneau et non pas le rendu personnalisé de la couche. Il est basé sur le template d'application "default" et son rendu par onglet. Il n'a aucune conséquence sur le rendu personnalisé de la couche, puisqu'il ne fait que répartir les features sur des couches "fictives" qui respectent le paramétrage d'origine.

Pour compléter, il existe deux templates applicatifs de panneaux d'infos (brut et accordion) : 
https://github.com/geobretagne/mviewer/blob/8d6403de469bb2e4902bf7be7a76d5a4cb1f9657/js/templates.js#L241
https://github.com/geobretagne/mviewer/blob/8d6403de469bb2e4902bf7be7a76d5a4cb1f9657/js/templates.js#L261
