### ISSUE TITLE
Exposer les features interrogées

### ISSUE THREAD

**Issue by cbriand** [geobretagne/mviewer#635]
**Description / Describe**

Fonction de info.js qui retourne les "queriedFeatures".
Cette fonction peut être utile pour le développement de certaines extensions.

**Description détaillée / Detailed description**

Méthode publique qui retourne la variable _queriedFeatures du fichier info.js

**Informations complémentaires / Additional context**

**Comment by Gaetanbrl** [comment]
@cbriand est-ce que tu as un cas d'utilisation (étape par étape pour comprendre le besoin) ? Ou une démo ?

**Comment by cbriand** [comment]
Oui, je vais compléter la tache la semaine prochaine.

**Comment by cbriand** [comment]
Nous avons développé une petite extension qui affiche dans une pop-up le nombre de features cliquées et consultables quelle que soit la couche d'origine.
![image](https://user-images.githubusercontent.com/38095778/183374772-206e6f4f-dae3-45d1-81da-67783aaee8ca.png)
La fonction d'exposition des features interrogées permet ici de connaitre le nombre de résultats sans avoir à les rechercher couche par couche.

**Comment by spelhate** [comment]
Ca fonctionnerait aussi pour les données de type WMS ?

**Comment by cbriand** [comment]
> Ca fonctionnerait aussi pour les données de type WMS ?

Oui. L'exemple ci-dessus interroge un flux WMS et fonctionne aussi avec des customlayers
