### ISSUE TITLE
Evénement infopanel-ready

### ISSUE THREAD

**Issue by cbriand** [geobretagne/mviewer#637]
**Description / Describe**

Déclenchement d'un événement lorsque le panneau d'info est renseigné.
Utile pour le développement d'extensions qui traitent le panneau d'info.

**Description détaillée / Detailed description**

CustomEvent 'infopanel-ready' déclenché lorsque le DOM du panneau d'info est construit et renseigné

**Informations complémentaires / Additional context**

**Comment by Gaetanbrl** [comment]
En effet, pas mal d'event sont à rajouter dans mviewer, dont celui-ci...

Comment se comporte cet événement si on a un template complexe qui utilise des requête Ajax (asynchrone) ?

**Comment by cbriand** [comment]
@Gaetanbrl A tester. Je ne dispose pas de ce genre de template.

**Comment by spelhate** [comment]
Bonjour @cbriand 
Si je comprends bien, l'intérêt ici est de pouvoir modifier le contenu (surcharge ?) du panneau d'info depuis une extension ?

**Comment by cbriand** [comment]
Ex

> Bonjour @cbriand Si je comprends bien, l'intérêt ici est de pouvoir modifier le contenu (surcharge ?) du panneau d'info depuis une extension ?

C'est exactement le besoin que nous avons eu

**Comment by lecault** [comment]
@cbriand as tu un exemple ? J'ai du mal à voir comme cela.

**Comment by lecault** [comment]
Ah dac je vois, c'est un prérequis pour l'extension.
