### ISSUE TITLE
Couche non visible dans la toc mais interrogeable

### ISSUE THREAD

**Issue by cbriand** [geobretagne/mviewer#641]
**Description / Describe**

Une couche non visible dans la toc (propriété showintoc=false) ne doit pas être empêchée d'être interrogée. C'est la propriété "queryable" seule qui doit gérer l'interrogation ou non d'une couche.

**Description détaillée / Detailed description**

fichier info.js, fonction init : retirer la contrainte showintoc pour ajouter une couche dans la liste des couches interrogeables

**Informations complémentaires / Additional context**

**Comment by Gaetanbrl** [comment]
Cette condition permet d'éviter qu'un utilisateur retrouve toujours un résultat pour une couche qu'il ne voit pas (perturbant) alors que pour toutes les autres couche, il peut les décocher pour ne plus les interroger.

Mais je comprend le besoin qui est aussi logique. A voir si cette condition ne couvrait pas un bug...

**Comment by lecault** [comment]
Vous avez un besoin spécial ? Peut être utile si couche se suffisant à elle même sans légende...

Je ne vois pas trop l'utilité mais je comprends le principe.

**Comment by cbriand** [comment]
Un exemple : notre carte qui présente le Plan Local d'Urbanisme intercommunal (PLUi) présente différentes couches composantes du PLUi, mais permet aussi d'interroger une couche invisible "parcelles cadastrales" qu'il n'est pas utile d'afficher dans la toc mais interrogeable pour obtenir des infos règlementaire du PLUi "à la parcelle" : https://mviewer.sig.rennesmetropole.fr/plui

De plus, à mon sens, il est plus propre que chaque propriété de couche joue un seul rôle : showintoc pour la visibilité de la couche dans la toc et queryable pour l'interrogation de la couche.
