### ISSUE TITLE
Tri panneau info dans l'ordre de la toc ou de la map

### ISSUE THREAD

**Issue by cbriand** [geobretagne/mviewer#644]
**Description / Describe**

Disposer d'une propriété d'application (sortlayersinfopanel) qui permet de trier les onglets du panneau d'information dans l'ordre des couches de la toc ou dans l'ordre de la légende (=ordre de la map, par défaut).
L'organisation par ordre de la toc permet d'avoir un affichage des couches dans le panneau d'informationdans un ordre constant qui n'est dépendant des activations/désactivations de couches qui impactent l'ordre des couches sur la map.

**Description détaillée / Detailed description**

Nouveau paramètre sortlayersinfopanel peut indiquer un affichage des couches dans l'ordre de la toc. Par défaut, l'ordre de la légende (=ordre de la map) est utilisé.

Le fichier info.js est impacté.

**Comment by Gaetanbrl** [comment]
Je ne comprend pas très bien car normalement l'ordre d'affichage de la TOC c'est l'ordre d'affichage sur la carte et la légende depuis v3.6.

**Comment by Gaetanbrl** [comment]
> normalement l'ordre d'affichage de la TOC c'est l'ordre d'affichage sur la carte et la légende

Erratum, la TOC est dans l'ordre de la config (par défaut) alors que la légende et la carte sont syncro.

**Comment by cbriand** [comment]
> 

Oui, c'est ça. L'ordre de la légende et de la carte peut varier avec les activations/désactivations de couches et les glissement de couches dans la légende.

**Comment by Gaetanbrl** [comment]
J'ai passé du temps sur la PR de gestion des index des couches mais je m'en souvenais déjà plus ^^

**Comment by lecault** [comment]
démo ?
