### ISSUE TITLE
Mauvaise gestion du popover en configuration mobile

### ISSUE THREAD

**Issue by cbriand** [geobretagne/mviewer#646]
**Description du bug / Describe the bug**

En configuration mobile, lorsque le tooltip est activé, une erreur se lève lors de la consultation d'une fiche d'info d'une feature.
<pre>
Uncaught TypeError: _featureTooltip.getElement(...).popover is not a function
</pre>

**Reproduire le bug / To Reproduce**

Etapes à suivre pour reproduire votre problème du type : 

1. Produire une application qui charge un customlayer sur lequel le tooltip est activé
2. Se rendre sur la carte en configuration mobile (< url >&mode=u)
3. Afficher la fenêtre d'outils de développement (F12)
4. Afficher un tooltip
5. Cliquer pour afficher la fiche d'info
6. L'erreur s'affiche dans la console de la fenêtre d'outils de développement

**Comportement attendu / Exptected behavior**

Pas d'erreur sur la commande de disparition du tooltip

**Environnement / Desktop**

Merci de remplir ces informations si connues :
 - Navigateur / browser [e.g. chrome, safari] : chrome, firefox

**Informations complémentaires / Additional context**

L'élément sur lequel la fonction popover (bootstrap) est appliquée doit être identifié en jQuery pourque la fonction puisse s'exécuter

**Comment by lecault** [comment]
Je reproduis sur la 3.8 mais pas sur la 3.7.
Lié à #595
