### ISSUE TITLE
toplayer error

### ISSUE THREAD

**Issue by lionelbargeot** [geobretagne/mviewer#648]
**Description du bug / Describe the bug**

depuis que nous sommes passé en 3.8, l'option toplayer=true déclenche une erreur au chargement de l'application

**Reproduire le bug / To Reproduce**

Etapes à suivre pour reproduire votre problème du type : 

toplayer="true"

**Erreur js**

Uncaught TypeError: mviewer.getLayer(...) is undefined

**Environnement / Desktop**

Merci de remplir ces informations si connues :
 - OS: [linux]
 - Navigateur / browser [firefox]
 - Version [ 103.0.2 (64 bits)]

**Comment by Gaetanbrl** [comment]
est-ce que vous avez un lien vers une démo qui manifeste ce bug ?

**Comment by lionelbargeot** [comment]
Bonjour, 
https://demos.agaricids.com/mviewer/sharemed_mio_38/?config=apps/github_toplayer.xml#

**Comment by spelhate** [comment]
Bonjour,
Sur votre instance l'aplication suivante fonctionne avec une couche disposant du paramètre `toplayer="true"`
https://demos.agaricids.com/mviewer/sharemed_mio_38/apps/default.xml

J'ai plutôt l'impression qu'il s'agit dans votre casd'un problème de custom control.

**Comment by lionelbargeot** [comment]
en fait si je mets le toplayer à false, ca fonctionne : https://demos.agaricids.com/mviewer/sharemed_mio_38/?config=apps/github_toplayeroff.xml#
Il faudrait qu'on gère le paramètre dans nos custum control ?

**Comment by lionelbargeot** [comment]
on dirait qu'on a résolu notre problème. Si l'option toplayer est à true, alors il plante sur la ligne du mviewer.js : 
`                var layer = mviewer.getLayer(id).layer;`
On avait ":" dans le nom du layer (les workspaces de geoserver ....) qui fait planter le chargement de la couche. on l'a enlevé et ca charge correctement. Ce n'est donc pas un problème de toplayer, mais un problème de lecture de nom de couche.
