### ISSUE TITLE
Conserver la fonction de recherche sur les petits écrans

### ISSUE THREAD

**Issue by bchartier** [geobretagne/mviewer#65]
Aujourd'hui, le contrôle de recherche disparaît dès que la largeur de l'écran est inférieure à 768px. 
C'est directement lié aux propriétés aux caractéristiques des navbars et des formulaires de Bootstrap j'ai l'impression. Or cette fonction de recherche serait bien utile pour certaines applications sur des terminaux mobiles de petite taille.

**Comment by Gaetanbrl** [comment]
> C'est directement lié aux propriétés aux caractéristiques des navbars et des formulaires de Bootstrap

En effet, le style bootstrap prévoit une largeur minimum de 768px pour ce composant. Cela suppose, je pense, d'ajouter une règle CSS dans le fichier mviewer.css.

**Comment by SylvainMassol** [comment]
J'ai travaillé sur ce point la dans ma dernière PR, avec ajout d'une icône recherche pour plier/déplier la barre de recherche sur une ligne en dessous.
![search_resp](https://user-images.githubusercontent.com/19145908/36262177-f7c6c8f2-1266-11e8-8392-ebd130fb5213.png)

**Comment by bchartier** [comment]
Oui, j'ai vu passé la description du pull request.
Il faudrait que je teste cela.
ça a l'air intéressant.
Merci pour cette proposition.

**Comment by bchartier** [comment]
Evolution du mode responsive en place depuis plusieurs mois.
Je ferme.
