### ISSUE TITLE
URL Decode / encode attribution

### ISSUE THREAD

**Issue by lecault** [geobretagne/mviewer#655]
**Description  / Describe**

Bonjour à tous,

Je cherche à mettre dans les attributions un lien via un bouton pour télécharger la donnée depuis GeoServer. Voici un exemple d'url : https://ows.region-bretagne.fr/geoserver/interne/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=aide_pass_creation_epci&outputFormat=excel&propertyName=code_siren,nom,nb,nb_femme,nb_1er_cycle,nb_cap_bep,nb_bac,nb_bac_2,nb_bac_4,nb_bac_5,nb_moins_30_ans,nb_30_50_ans,nb_plus_50_ans,nb_nc,millesime

Le problème est qu'il faille encoder les urls pour les mettre dans les attributions et que j'ai des caractères comme & qui posent problème. Avez-vous une idée ? Merci d'avance,

`attribution="&lt;a href=&quot;https://kartenn.region-bretagne.fr/kartoviz/apps/region/economie/cartes/pass_creation.jpeg&quot; target=&quot;_blank&quot;&gt;&lt;button class=&quot;rb-but-link&quot; &gt;Télécharger carte&lt;/button&gt;&lt;/a&gt;&lt;a href=&quot;https%3A%2F%2Fows.region-bretagne.fr%2Fgeoserver%2Finterne%2Fows%3Fservice%3DWFS%26version%3D1.0.0%26request%3DGetFeature%26typeName%3Dinterne%253Aaide_pass_creation_epci%26outputFormat%3Dexcel%26propertyName%3Dcode_siren%2Cnom%2Cnb%2Cnb_femme%2Cnb_1er_cycle%2Cnb_cap_bep%2Cnb_bac%2Cnb_bac_2%2Cnb_bac_4%2Cnb_bac_5%2Cnb_moins_30_ans%2Cnb_30_50_ans%2Cnb_plus_50_ans%2Cnb_nc%2Cmillesime&quot; target=&quot;_blank&quot;&gt;&lt;button class=&quot;rb-but-link&quot; &gt;Accès aux données&lt;/button&gt;&lt;/a&gt;&lt;/br&gt;&lt;/br&gt;Le &lt;b&gt;PASS Création&lt;/b&gt; propose un accompagnement personnalisé avec des conseils stratégiques, financiers et juridiques tout au long du projet de création ou de reprise, jusqu’au développement de l’activité.&lt;/br&gt;&lt;/br&gt;&lt;a href=&quot;https://www.bretagne.bzh/aides/fiches/pass-creation/&quot; target=&quot;_blank&quot;&gt;&lt;button class=&quot;rb-but-link&quot; &gt;Plus d'informations&lt;/button&gt;&lt;/a&gt;"`

**Comment by lecault** [comment]
Précision.

Si je mets une URL non encodée, l'XML n'est pas valide :

> &quot;https://ows.region-bretagne.fr/geoserver/interne/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=aide_pass_creation_epci&outputFormat=excel&propertyName=code_siren,nom,nb,nb_femme,nb_1er_cycle,nb_cap_bep,nb_bac,nb_bac_2,nb_bac_4,nb_bac_5,nb_moins_30_ans,nb_30_50_ans,nb_plus_50_ans,nb_nc,millesime&quot;


Et si j'encode, le navigateur ne sait pas lire l'URL : 

> Et si j'encode, idem &quot;https://ows.region-bretagne.fr/geoserver/interne/ows%3Fservice=WFS%26version=1.0.0%26request=GetFeature%26typeName=aide_pass_creation_epci%26outputFormat=excel%26propertyName=code_siren,nom,nb,nb_femme,nb_1er_cycle,nb_cap_bep,nb_bac,nb_bac_2,nb_bac_4,nb_bac_5,nb_moins_30_ans,nb_30_50_ans,nb_plus_50_ans,nb_nc,millesime&quot;

**Comment by spelhate** [comment]
Dans les URL, ce qui pose souvent problème, c'est le &. Il faut donc l'encoder en le remplaçant par sa valeur "[entité html](https://developer.mozilla.org/fr/docs/Glossary/Entity)" c'est à dire `&amp;`
