### ISSUE TITLE
Loader en cas de navigateur incompatible

### ISSUE THREAD

**Issue by cbriand** [geobretagne/mviewer#656]
**Description / Describe**

Présenter un message d'explication au démarrage en cas de navigateur incompatible avec le MViewer

**Description détaillée / Detailed description**

ajout d'un loader d'erreur activé si les objets minimum du mViewer ne peuvent pas se construire (fichier index.html)

**Comment by lecault** [comment]
Tu as testé sur quels navigateurs ?

**Comment by cbriand** [comment]
> Tu as testé sur quels navigateurs ?

Principalement internet explorer qui est toujours utilisé par certains, mais qui ne permet pas de faire tourner mviewer

**Comment by Gaetanbrl** [comment]
merci pour cette issue @cbriand je la clos.
