### ISSUE TITLE
Comportement au clique sur le logo

### ISSUE THREAD

**Issue by mrouan** [geobretagne/mviewer#661]
**Description / Describe**

Quand on clique sur le logo d'un mviewer, un nouvel onglet s'ouvre et charge la page d'accueil.
Un comportement plus habituel serait de recharger la page d'accueil dans le même onglet.

**Comment by spelhate** [comment]
Bonjour,
Je suis d'accord avec votre remarque.

**Comment by Gaetanbrl** [comment]
Je me l'assigne pour la faire un peu plus tard. Si toutefois quelqu'un souhaite s'y pencher, il ne faut pas hésiter 👍

**Comment by lecault** [comment]
C'est juste un target="_blank" à enlever je pense

**Comment by Gaetanbrl** [comment]
y a un truc comme ca oui j'ai pas encore regardé, je pense ca prend 2 min à changer

**Comment by lecault** [comment]
je regarde

**Comment by Gaetanbrl** [comment]
testé => Faut dégager le target ici : 

https://github.com/geobretagne/mviewer/blob/master/index.html#L91

**Comment by Gaetanbrl** [comment]
Je vais faire la PR @lecault
