### ISSUE TITLE
Affichage résumé métadonnée incorrect [Régression]

### ISSUE THREAD

**Issue by lecault** [geobretagne/mviewer#663]
**Description du bug / Describe the bug**

Sur la version 3.8, le résumé de la métadonnée ne s'affiche pas correctement.
Sur la version 3.7, je n'ai pas ce soucis.

**Reproduire le bug / To Reproduce**

Etapes à suivre pour reproduire votre problème du type : 

1. Aller sur la page https://kartenn.region-bretagne.fr/territoires/#
2. Déplier la couche Intercommunalité
3. Clic sur le i

**Screenshots**

![image](https://user-images.githubusercontent.com/5269430/191460346-5018157b-3519-41c3-9439-ba86b79d241e.png)

**Comportement attendu**

![image](https://user-images.githubusercontent.com/5269430/191461690-6b578fd7-a8b9-430c-ad2f-3fcd7949de94.png)

**Environnement / Desktop**

Merci de remplir ces informations si connues :
 - Version 3.8

**Informations complémentaires / Additional context**

Problème lié à une évolution vers 3.8.

**Comment by Agath21** [comment]
Effectivement, j'ai également remarqué ce problème. Pour ma part, je l'ai géré dans le CSS de mon thème avec la propriété suivante :  

```
.popover-content p {
	width: 250px;
}
```

Mais il faudrait corriger ce problème pour les thèmes mviewer par défault avec une méthode plus propre.

**Comment by Gaetanbrl** [comment]
Lié à cette PR : 

https://github.com/geobretagne/mviewer/pull/595#issuecomment-1105128682

**Comment by lecault** [comment]
Du coup il faut faire les modifs dans les CSS par défaut ?

**Comment by Gaetanbrl** [comment]
@Agath21 cette règle c'est du CSS commun à tous les thèmes ou bien c'est une règle par thème ?

**Comment by Agath21** [comment]
@Gaetanbrl  Oui je pense qu'il faut régler le pb directement dans le fichier `mviewer.css` . Après je ne sais pas expliquer cette régression ...
