### ISSUE TITLE
Multilingue - Traduction éléments hors interface

### ISSUE THREAD

**Issue by stephyritz** [geobretagne/mviewer#667]
Salut,

Je suis en train de tester la mise en place d'un mviewer multilingue sans dupliquer les fichiers xml. Grâce à la documentation, j'ai bien compris comment cela fonctionnait pour la traduction des différents boutons de l'interface. 

Cependant, je n'ai pas compris comment faire en ce qui concerne la traduction des couches ou des thématiques, de la légende ou des tooltips. Est-ce que quelqu'un sait comment faire et pourrait m'aider?

**Comment by Gaetanbrl** [comment]
Pouvez-vous détailler ce que vous entendez par "traduction des couches ou des thématiques, de la légende ou des tooltips" svp ?

**Comment by stephyritz** [comment]
Oui bien sûr! Sur le prtsc joint :

- En rouge --> "couches et thématiques"
- En bleu --> "légende"
- En violet --> "tooltips"

![exemple_mviewer](https://user-images.githubusercontent.com/34446202/191544256-cacf9be2-0307-46fc-b323-9377ab15e810.png)

**Comment by spelhate** [comment]
> Salut,
> 
> Je suis en train de tester la mise en place d'un mviewer multilingue sans dupliquer les fichiers xml. Grâce à la documentation, j'ai bien compris comment cela fonctionnait pour la traduction des différents boutons de l'interface.
> 
> Cependant, je n'ai pas compris comment faire en ce qui concerne la traduction des couches ou des thématiques, de la légende ou des tooltips. Est-ce que quelqu'un sait comment faire et pourrait m'aider?

Bonjour, la traduction ne concerne que l'application mviewer (menus, messages...) et pas le contenu (thématiques, données...)

**Comment by Gaetanbrl** [comment]
A savoir que si vous souhaitez traduire un élément qui n'est pas de l'interface prévue par le coeur mviewer (template avec JavaScript, custom control...) , vous pouvez toujours traduire vos textes via : 

- la fonction publique `mviewer.tr`

**Ex:**
`mviewer.tr('tbar.right.logout')`

**Doc :** 
https://mviewerdoc.readthedocs.io/fr/stable/doc_dev/public_fonctions.html?highlight=tr#tr

- la librairie [i18njs ](https://github.com/fnando/i18n-js)disponible dans mviewer en l'appelant via la fonction `i18njs` mais avec votre propre code JavaScript pour utiliser la librairie.

**Comment by stephyritz** [comment]
D'accord. Merci beaucoup pour les informations. Je pensais que je pouvais simplement, sur base des ID des thèmes et couches, pouvoir renseigner une valeur différente dans le xml pour les balises 'name','legendurl' ou encore le "template en .mst". Du coup, je cherchais à voir quelle "clé/valeur" je pouvais utiliser sur le même modèle que dans le fichier mviewer.i18n.json.

Je n'ai pas assez de compétences en js pour aller plus loin pour l'instant mais je garde l'idée à l'esprit. La traduction des couches, thèmes, légende et tooltip pourrait être quelque chose d'intérêt commun pour les utilisateurs. Si j'avance sur le sujet, je le partagerai ici. En attendant, je vais donc continuer à dupliquer mes configurations xml pour les cartes interactives en multilingue.

Merci encore pour vos réponses!
