### ISSUE TITLE
Rappel de bonnes pratiques pour la contribution au projet ?

### ISSUE THREAD

**Issue by jerbou** [geobretagne/mviewer#669]
**Description  / Describe**
Bonjour @Gaetanbrl 
Serait-il possible de disposer d'un page qui rappel les bonnes pratiques pour indiquer la manière de contribuer au projet Mviewer.
Nous (en tant qu'acheteur publique) pourrions y faire référence pour nos différents prestataires afin de faciliter les développements et leur reversements.

D'avance Merci,

Jérôme

**Comment by Gaetanbrl** [comment]
Peux-tu me détailler ce qui manque dans ces pages ? Normalement les bonnes pratiques y sont indiquées.

https://mviewerdoc.readthedocs.io/fr/stable/doc_contrib/contrib.html

https://mviewerdoc.readthedocs.io/fr/stable/doc_contrib/doc.html

**Comment by jerbou** [comment]
ok , merci !
