### ISSUE TITLE
Measure area

### ISSUE THREAD

**Issue by Gaetanbrl** [geobretagne/mviewer#67]
![image](https://user-images.githubusercontent.com/16317988/34492043-33bc4e2a-efe6-11e7-93c7-07c11cfb7e13.png)

If user need to create a point under label, he can't click. 
Solution : set new anchor for label ant not in polygon center (centroid).

**Comment by bchartier** [comment]
Why not. Where should we create it then?

**Comment by bchartier** [comment]
@Gaetanbrl: I think I did not understand your suggestion. Was it: use the same strategy as for line measurement?

**Comment by Gaetanbrl** [comment]
I need to test line measurement.
In the picture, we have a point under the label (the third point to close triangle). 
How can we move it without modify others points ? We can't, because of label on the third point.

If this popup info is a simple overlay, it's maybe possible to affect a specific offest / anchor to display info in other place. Or maybe directly in the polygon.

**Comment by bchartier** [comment]
> I need to test line measurement.

Yes, have a look . I think it can solve your trouble.

> In the picture, we have a point under the label (the third point to close triangle).
> How can we move it without modify others points ? We can't, because of label on the third point.

I have understood which trouble we need ti solve.
My question was about the solution you suggested.

> If this popup info is a simple overlay, it's maybe possible to affect a specific offest / anchor to display info in other place. Or maybe directly in the polygon.

By applying on arbitrary and constant offset you would not solve this trouble in all possible cases. There steel would be cases where the label would mask a possible new anchor location.

**Comment by Gaetanbrl** [comment]
> Yes, have a look . I think it can solve your trouble.
Indeed, solve the trouble.

**Comment by bchartier** [comment]
Nice, we will solve this using the area mesasurement label placement strategy.

**Comment by bchartier** [comment]
Intégré à la branche develop.
Je ferme ce ticket.
