### ISSUE TITLE
Ajouter une couche tuiles vectorielles TMS/WMTS

### ISSUE THREAD

**Issue by frgis** [geobretagne/mviewer#675]
**Description / Describe**

Avoir la possibilité d'ajouter en tant que "baselayer" ou "layer" d'une carte Mviewer une ressource de type tuiles vectorielles - TMS/WMTS de l'IGN (voir le lien pour les explications https://geoservices.ign.fr/documentation/services/api-et-services-ogc/tuiles-vectorielles-tmswmts)

**Description détaillée / Detailed description**

L'utilisateur pourra configurer le ou les ressources qu'il souhaite depuis le fichier (xml) de configuration de carte :

- Ajouter un type nouveau "tilevector" ou terme équivalent disponible en "baselayer" comme en "layer",
- configuration d'une "url" pour aller récupérer les tuiles,
- configuration d'un "styleurl" pour aller récupérer un fichier de style personnalisé (json),
- Afin de gérer des ressources compléentaires (il me semble maptiler entre autres) il sera possible d'appeler directement le fichier de style qui incorpore l'url vers les données, ainsi l'"url" pourra être vide de manière optionnelle,
- La légende ne sera pas dynamique (pour éviter des complexités et surcoûts inutiles), il faudra ajouter une image fixe à partir du paramètre legendurl,
- si possible gérer l'affichage du "baselayer" et "layer" dans l'outil d'export image (selon le coût de la prestation).

**Informations complémentaires / Additional context**

Nous sommes entrain de contacter quelques sociétés en capacité de réaliser ce développement afin d'obtenir un chiffrage. Notre objectif étant que la prestation soit déversée dans les sources Mviewer afin que cette amélioration puisse profiter à la communauté utilisatrice du logiciel et être maintenue.
L'équipe qui gère le logiciel Mviewer peut-elle nous valider la possibilité de déverser ce futur développement dans le code source du logiciel afin qu'il profite à la communauté et soit maintenu ? SI besoin préciser les éléments posant problème dans les spécifications proposées et préconisations à appliquer au moment du développement pour qu'il puisse rapidement être déversé dans le code du logiciel à la fin de la prestation ?

Dans l'attente de vos retours.

**Comment by Gaetanbrl** [comment]
C'est un bon plus qu'on peut difficilement refuser comme contrib je pense.

Par contre, l'IGN conseille le format TMS. Je me demande donc l'utilité d'utiliser le WMTS, surtout que le TMS est bien plus simple à intégrer ? Quels usages pour le WMTS ?

![image](https://user-images.githubusercontent.com/16317988/194009015-c4dbfbfb-5e81-47fb-a6c9-d22634945a0b.png)


@spelhate @bchartier @lecault @dds2010 un avis  sur le format TMS / WMTS ?

**Comment by lecault** [comment]
Naturellement je suivrai le conseil de l'IGN. Surtout si ne doit plus être maintenu, ça sera le WMTS.
Question, quelqu'un connait t'il la raison de la préférence pour TMS plutôt que WMTS ?

**Comment by dds2010** [comment]
J'ai plutôt tendance à utiliser le WMTS mais sans vraiment pouvoir le justifier. ça me parait plus récent comme norme

**Comment by Gaetanbrl** [comment]
> quelqu'un connait t'il la raison de la préférence pour TMS plutôt que WMTS ?

Les deux sont très proches et c'est avant tout une question de standards. D'un côté TMS est une [spécification OSGeo](https://wiki.osgeo.org/wiki/Tile_Map_Service_Specification), alors que WMTS inspiré de TMS est [officiellement OGC](https://www.ogc.org/standards/wmts) (pas TMS).

_Tiré des spécifications WMTS :_ 
```
WMTS is inspired by the OSGeo Tile Map Service Specification (available at
http://wiki.osgeo.org/index.php/Tile_Map_Service_Specification). The team that worked
on this standard also considered similar initiatives, such as Google maps and NASA
OnEarth. This OGC standard includes both resource (RESTful approach) and procedure
oriented architectural styles (KVP and SOAP encoding) in an effort to harmonize this
interface standard with the OSGeo specification.
```

**Comment by frgis** [comment]
Peut-être autre chose à évaluer pour le choix si pas possible de gérer les deux et qu'il faut faire un choix : est-ce que les autres services qui proposent du tuilage vectoriel travaillent généralement en TMS ou bien WMTS (maptiler par exemple) ?

Est-ce que vous voulez que je pose la question à l'IGN de savoir si dans l'avenir ils vont plutôt maintenir le TMS ou le WMTS ?

Cela peut peut-être aider à faire un choix ou au moins orienter ce choix.

**Comment by Gaetanbrl** [comment]
> Est-ce que vous voulez que je pose la question à l'IGN ?

Ce serait en effet intéressant d'avoir leur argumentaire sur le choix de conseillé le TMS au WMTS.

Il faudrait avoir les specs GeoServer et MapServer également en face pour savoir quel format serait intéressant pour conserver ce côté interop. Je vais voir ce que je trouve.

**Comment by Gaetanbrl** [comment]
Les TMS et WMTS sont dispos avec les deux serveurs carto, donc pas d'orientation spécifique à choisir selon ces deux solutions : 

https://mapserver.org/mapcache/services.html
https://docs.geoserver.org/maintain/en/user/geowebcache/webadmin/defaults.html

**Comment by frgis** [comment]
Bonjour,

j'ai envoyé à l'IGN ceci il y a quelques minutes :

"Bonjour,

nous utilisons pour la production de cartes sur le Web le produit Mviewer qui est basé sur Openlayers entre-autres (https://github.com/geobretagne/mviewer).

Nous souhaitons faire réaliser prochainement un développement par une Société dans ce produit pour qu'il puisse prendre en charge l'utilisation des flux de tuiles vectorielles IGN.

Sur votre page (https://geoservices.ign.fr/documentation/services/api-et-services-ogc/tuiles-vectorielles-tmswmts), vous conseillez l'utilisation du protocole TMS plus que WMTS, pouvez-vous nous nous dire pourquoi ?
Il me semble en effet que le protocole WMTS est plus récent et qu'il est peut-être plus judicieux de prendre en charge celui-ci pour l'avenir, ou bien je me trompe ?

L'idée étant que vous nous confirmiez sur quel protocole on doit partir pour faire réaliser le développement (voir le ticket github https://github.com/geobretagne/mviewer/issues/675 pour suivre la discussion en cours sur ce sujet).
Eventuellement, si vous avez la possibilité de répondre sur le ticket, c'est encore mieux !

Merci pour vos retours."

J'attends leur retour.

**Comment by Gaetanbrl** [comment]
Super, merci pour le partage :)

**Comment by frgis** [comment]
Bonjour,

l'IGN m'a fait un retour dans lequel ils recommandent plutôt le protocole TMS et d'utiliser la librairie ol-mapbox-style, voir le contenu ci-dessous :
"Bonjour,

Nous vous encourageons à accéder aux tuiles vectorielles en  le protocole TMS.
Bien que ce protocole ne soit pas un standard officiel comme le WMTS de l'OGC, il est plus largement répandu et adapté aux usages web.
De plus ce protocole à l'avantage de formater les URLs de façon bien plus lisible.

Pour une utilisation avec openlayers il est recommandé d'utiliser l'extension
https://github.com/openlayers/ol-mapbox-style afin d'appliquer les styles que nous proposons ou que vous allez créer.

Cordialement,"

Bonne journée.

**Comment by frgis** [comment]
J'ai eu la réponse, le TMS est bien compatible avec le géotuileur donc pas de souci avec le TMS.

**Comment by Gaetanbrl** [comment]
merci pour ces retour @frgis

**Comment by Gaetanbrl** [comment]
@frgis Après tests et début d'intégration : 

- une couche TMS s'intègre avec ol 6.x

- il faut passer sur ol 7.x pour utiliser un JSON contenant style spécifique du flux (voir exemple dans commentaire précédent)
https://wxs.ign.fr/static/vectorTiles/styles/PLAN.IGN/essentiels/standard.json

- nativement, on peut utiliser un style ol (v6.x ou v7.x)  directement sur la couche VectorTile mais c'est laborieux car les styles TMS sont complexes
