### ISSUE TITLE
Démo Click sur un cluster ne fonctionne plus

### ISSUE THREAD

**Issue by Gaetanbrl** [geobretagne/mviewer#676]
**Version :** v3.8.1-snapshot
**Branche :** develop

# Description

Lorsqu'on click sur un cluster, le template ne s'affiche pas.

... analyse à suivre pour la source / éléments de résolution

**Comment by lecault** [comment]
Semble résolu suite au débugage de la semaine dernière.
Exemple : https://kartenn.region-bretagne.fr/kartoviz-dev/?config=demo/cluster.xml

**Comment by Gaetanbrl** [comment]
Testé je clos.
