### ISSUE TITLE
Astuce - Créer une démo mviewer live à partager avec peer-coding

### ISSUE THREAD

**Issue by Gaetanbrl** [geobretagne/mviewer#677]
:rotating_light: **Fini les problèmes d'installation et compagnie sur un pc Windows pour simplement tester le super mviewer qu'un collègue veut me montrer !! :boom:**

## Description

On a souvent besoin de partager une démo, un bug, tester en live ou même montrer du code en direct sur mviewer.

Alors on est peut-être en retard, mais on a récemment découvert que le site [codesandbox ](https://codesandbox.io/) pouvait nous le permettre avec la possibilité de créer et partager une carte totalement hébergée sur ce site en quelques clics (et un compte GitHub...quand même :sunglasses:).

> Comment Faire :open_mouth: ? 

On vous partage la procédure juste en-dessous :wink: :ok_hand: .

## Procédure

1. Se connecter à [codesandbox ](https://codesandbox.io/) via votre compte Github

2. Créer un nouveau projet à partir du dépôt Git Mviewer

![image](https://user-images.githubusercontent.com/16317988/194016608-2ad6415a-a9c9-40dd-ba3b-95a8db03a519.png)

4. Attendre que le projet soit importé

5. Ajouter un nouveau fichier `package.json` en créant un fichier à gauche dans l'arbre des fichiers à gauche directement

6. Y intégrer ce contenu (à adapter si besoin)

```
{
  "name": "mviewer",
  "version": "3.8.1-snapshot",
  "description": "Mviewer live demo",
  "main": "index.html",
  "scripts": {
    "start": "serve",
    "build": "echo This is a mviewer live demo with Codesandbox, there is no bundler or bundling involved!"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/geobretagne/mviewer.git"
  },
  "keywords": [
    "mviewer",
    "master",
    "codesandbox",
    "preview",
    "demo"
  ],
  "author": "PSC Mviewer",
  "license": "GNU General Public License v3.0",
  "bugs": {
    "url": "https://github.com/geobretagne/mviewer/issues"
  },
  "homepage": ".",
  "devDependencies": {
    "serve": "^11.2.0"
  }
}
```

7. Changer de branche si besoin via l'interface en haut

![image](https://user-images.githubusercontent.com/16317988/194012787-5f6bd527-7742-42fc-a17e-a37e4fc48534.png)

8. Faire un restart du projet

![image](https://user-images.githubusercontent.com/16317988/194013171-fcfad9c2-6f73-4b82-84b8-010d9dccbb25.png)

9. Voir la démo à droite (vous pouvez cliquer sur la double fenêtre à droite de l'URL pour avoir l'aperçu synchro avec votre code dans une plus grande fenêtre)

![image](https://user-images.githubusercontent.com/16317988/194013431-188d44d1-bd42-4923-b8df-306cbebdf43d.png)

10. Partagez

![image](https://user-images.githubusercontent.com/16317988/194016812-fe2ff691-6141-4b9f-ac5b-b7a4b8c7e312.png)

**Comment by spelhate** [comment]
Merci beaucoup @Gaetanbrl 
Est ce qu'il y aurait un intérêt à créer de façon persistante le fichier créé package.json dans mviewer ?

**Comment by Gaetanbrl** [comment]
> Est ce qu'il y aurait un intérêt à créer de façon persistante le fichier créé package.json dans mviewer ?

Je pense que si cet usage est "à la marge" non, mais si on peut facilement le réutiliser via un environnement local (node / npm), alors ca peut être intéressant.

**Comment by Gaetanbrl** [comment]
Je vais regarder 5 min à partir d'un clone si le "serve" est rapide à utiliser.
Car dans le package.json, il n'y a qu'une commande et 1 dépendance :

```
  "scripts": {
    "start": "serve",
    "build": "echo This is a mviewer live demo with Codesandbox, there is no bundler or bundling involved!"
  },
  "devDependencies": {
    "serve": "^11.2.0"
  }
```
