### ISSUE TITLE
Gestion des URLs par environnement dev/recette/prod

### ISSUE THREAD

**Issue by Gaetanbrl** [geobretagne/mviewer#679]
# Description

Lorsqu'on réalise des cartes dans certains environnements, nous devons respecter le processus local / tests / mise en prod :

1. Développement de la carte en local ==> `localhost:xxxx/mviewer`
2. Passage sur un environnement de test type recette / pré-pod ==> `https://recette.foo/mviewer`
3. Déploiement final vers l'environnement de production ===> `https://foo/mviewer`

Pour chacun de ces environnement, l'URL change. On doit donc modifier pour chaque environnement les chemin et URLs des couches  dans les XML, customlayers, extensions, customcontrol, etc...

C'est souvent principalement le domaine qui change.
La modification est manuelle et il y a souvent des erreurs. C'est aussi clairement fastidieux pour une carte contenant beaucoup de layers, customs, etc...

# Question

Quel système peux permettre de définir à un seul endroit le domaine ? Je pense à un fichier de config, des variables d'environnements, autres... il y a pas mal de solutions.

Si vous avez une solution à partager ou des idées, n'hésitez-pas.

**Comment by Gaetanbrl** [comment]
Voici une proposition qui fait suite à un échange technique.

## Fonctionnement général

Un fichier type .env sera placé à la racine du répertoire /apps.

Ce fichier comprendra une variable du type : 

`{"fqdn": "https://ma.recette.fr"}`

Dans le XML, URLs pourront être saisies avec la variable présente dans le fichier .env.

`<layer  url="{{fqdn}}/geoserver/rb/wms" />`


Lors de l'appel du XML au chargement de la carte, le code remplacera l'expression `{{fqdn}}` par `https://ma.recette.fr` pour obtenir un XML avec les URLs correctes. On aura alors pour notre `<layer>` dans le XML final : 

`<layer  url="https://ma.recette.fr/geoserver/rb/wms" />`

## Fonctionnement des variables globales et par application

* Un fichier .env pourra être ajouté avec le nom de la carte pour que ce fichier soit pris en compte :
maCarte.xml + maCarte.env

* Si aucun fichier .env n'a le nom de la carte, on récupèrera les variables du fichier `/apps/.env`

* Si aucun fichier .env n'existe, alors le système actuel et classique fonctionnera afin de lire simplement le XML sans chercher à remplacer des URLs.

## Que fera le JS ?

Pour accéder aux variables d'environnement, on devra lire la propriété `mviewer.env` créée et alimentée par le code JS lors de l'initialisation (via une méthode dans le fichier `mviewer.js`) :

`console.log(mviewer.env) ==> { fqdn: "https://ma.recette.fr/geoserver/rb/wms" }`

En reprenant notre fichier plus haut, lors de la lecture de la variable d'environnement `fqdn `, on aura alors ajouter une propriété dans la variable globale `mviewer.env` afin d'obtenir :

`mviewer.env.fqdn`

_Exemple :_ 

`console.log(mviewer.env.fqdn) ==> "https://ma.recette.fr/geoserver/rb/wms" `

## Custom layer et Custom control

Les variables d'environnements étant accessibles via mviewer.env.fqdn, on pourra les utiliser dans les fichiers JS mviewer custom control et custom layer.

Il faudra toutefois veiller à ce que ces variables soient rendues disponibles **AVANT** le chargement des customs layer et custom control.


**Qu'en pensez-vous ?**

**Comment by pierrejego** [comment]
Personne pas d'avis ?
Comment vous faites chez vous actuellement ? vous travaillez directement en production ou vous passez un script suite aux changement de plateforme ?
