### ISSUE TITLE
template et customlayer ne fonctionne plus

### ISSUE THREAD

**Issue by Gaetanbrl** [geobretagne/mviewer#684]
Version: 3.8.1-snapshot
Branche: develop

**Bloquant pour la prochaine release !**

## Description

Le clic sur une feature du mviewer ?config=demo/dataviz.xml ne fonctionne plus malgré l'affichage de la surbrillance.

Pour reproduire il faut avoir un customLayer + un template (voir l'exemple [dataviz.xml](https://kartenn.region-bretagne.fr/kartoviz/?config=demo/dataviz.xml) en 3.8.1-snapshot).

**C'est cependant fonctionnel sur une version antérieure.**

Je suspecte une régression suite aux dernière PR (@cbriand ?).

Je n'ai pas plus d'infos pour le moment.

**Comment by lecault** [comment]
J'ai cette erreur sur cette PR : https://github.com/geobretagne/mviewer/pull/634

**Comment by cbriand** [comment]
Je reproduis l'erreur. J'investigue.
