### ISSUE TITLE
Icon thématique dans fiche d'information [3.9]

### ISSUE THREAD

**Issue by lecault** [geobretagne/mviewer#688]
**Description du bug / Describe the bug**

Dans la 3.9 en cours de test, l'icon de la thématique n'apparaît plus :

![image](https://user-images.githubusercontent.com/5269430/200321780-2c8b2e57-94e1-4bdc-b6a0-f4b0b485ef27.png)

**Reproduire le bug / To Reproduce**

Etapes à suivre pour reproduire votre problème du type : 

1. Aller sur la page https://kartenn.region-bretagne.fr/kartoviz-dev/?config=apps/region/ame/ame.xml
2. Cliquer sur une entité

**Comportement attendu / Exptected behavior**

![image](https://user-images.githubusercontent.com/5269430/200321900-cdf212a4-2ddd-4563-80f9-a917124312a8.png)

**Environnement / Desktop**

Merci de remplir ces informations si connues :
 - Version 3.9 (dev)

**Comment by Gaetanbrl** [comment]
vu avec @lecault 

Ligne à remettre => N'aurait pas du être supprimée :

https://github.com/geobretagne/mviewer/pull/640/files#diff-10d6e62c846b22d2126cac364b63c3f2b96b1725136f66c386f12fa518e99869L515
