### ISSUE TITLE
Fuse et recherche sur linéaire / polygone

### ISSUE THREAD

**Issue by lecault** [geobretagne/mviewer#69]
Dans l'exemple ci-dessous : https://geobretagne.fr/mviewer/?config=apps/41e4fb5fd302be2bd33916c7cfb4e652.xml#

On veut tester l'interrogation FUSE sur une géométrie de type ligne. Par exemple taper "Servel" : il ne zoome pas sur l'entité mais sur le monde il est perdu.

=> Le mviewer zoome sur la géométrie du linéaire et non l'emprise ce qui fait qu'OL n'arrive pas à comprendre cf ci-dessous : 

onclick="mviewer.zoomToLocation(-3.493861817976021,48.74558310537614,-3.493801929214453,48.74560682954797,-3.4935217682241615,48.74570305745294,-3.4933016297963024,48.74578160724175,-3.4930294278707845,48.74581292135147,-3.4925754432157827,48.74580961345259,-3.4922279229987505,48.745823640915546,-3.491806708074563,48.74585431632667,-3.4914574063394417,48.74587560401858,-3.4910875024599486,48.745905203608515,-3.4907702374329603,48.74592291038965,-3.490523558770292,48.74594204942119,-3.490269914385888,48.745949041210054,-3.4899611348868933,48.74594836446914,-3.4892939783142536,48.7458978434685,-3.489091158921148,48.745878716765674,-3.488936055597443,48.745851555159334,-3.488852379608891,48.745789965095526,-3.4886696429920674,48.74571599402236,-3.488521950065508,48.74566256029499,-3.5121035446331756,48.748452125294335,-3.5119317440890856,48.7484547811643,-3.51175421833883,48.748458900415415,-3.5114567474801013,48.748462123637836,-3.511152167012633,48.748467982632235,-3.5109022615315153,48.748472570928186,-3.510678251278559,48.748483767778396,-3.510442244689886,48.74849115867028,-3.5102625988961678,48.74849987134209,-3.5101444533032113,48.74850245513045,-3.509891915688652,48.74850763627961,-3.509720816534513,48.748503781755176,-3.5095423127979273,48.74849496896945,-3.5094190890490733,48.74847903271473,-3.5093257726721996,48.74845873630133,-3.5091984763857447,48.74840833077778,-3.50903111480253,48.748338453778445,-3.508934613268699,48.7482932639756,-3.508725010292005,48.74820806629492,-3.508561579772112,48.74814244572491,-3.5083739444038256,48.74806754649424,-3.5082273608761785,48.74802247247692,-3.5080816979869693,48.74798988243984,-3.5079585509009497,48.74796923956785,-3.507844532655754,48.74796174069053,-3.5076399296250322,48.7479552808897,-3.5074972918092264,48.74795162152853,-3.5072820515814267,48.747941391176994,-3.5070806856622125,48.747928481461116,-3.5068203949114642,48.747920658818515,-3.5066290551222297,48.74790673971228,-3.5064622086315045,48.747899061006905,-3.5063192298862433,48.747892733081244,-3.5061865411315125,48.747876875328075,-3.5060821310072297,48.74785451082593,-3.5059752394265793,48.74782333101669,-3.5058729528241708,48.747783163348686,-3.5057896916082223,48.74774618453958,-3.5056993574401316,48.74770154268944,-3.505617430769103,48.7476591167063,-3.505525793390354,48.747598990016684,-3.5054246076914097,48.747533017601285,-3.505328166003066,48.74747237602671,-3.505240501363792,48.74741683972397,-3.5051803795984773,48.747380804784655,-3.5050365323240733,48.747290915791325,-3.5049409342813203,48.7472315698588,-3.504830215882093,48.747159862354664,-3.5046734748137416,48.747064426305144,-3.504589456698276,48.74701092414341,-3.5043833841249166,48.746881759118054,-3.504248108086303,48.746797993521966,-3.504099823927485,48.74670779204183,-3.5038445932380635,48.74655417747195,-3.50366377951163,48.74644251418516,-3.503384872548088,48.74626783770245,-3.5031707346023735,48.746128488950916,-3.5029926125179136,48.74601667426424,-3.5026942538566765,48.74581689354062,-3.5023761492008463,48.74561620151667,-3.5020562675728173,48.74542277129257,-3.5017361610960536,48.745227562082505,-3.5015396602446165,48.74510960975462,-3.501337328565909,48.7449884014969,-3.501115002947389,48.74483786702854,-3.500988068360527,48.74474512560667,-3.5009119909185555,48.7446795371132,-3.5007921762342273,48.744589531419194,-3.5006638417523663,48.744496420253654,-3.500263015451889,48.744517033497516,-3.499942657178027,48.744552846762446,-3.4995970407190646,48.744624095840265,-3.4992304065171687,48.74472158951306,-3.4989164071431254,48.74480718671069,-3.4985264441353054,48.74489165530224,-3.4981819219612955,48.744950303244394,-3.4978611422821033,48.74500404201092,-3.4974294654727327,48.745069347860436,-3.4969906117684904,48.745131471398196,-3.4967589721299452,48.74516231936005,-3.496464548830388,48.74516802129554,-3.496191825249907,48.745152811734584,-3.495849842420127,48.74512535288844,-3.495611163200952,48.74510107732149,-3.4953718390582313,48.7450929543773,-3.4951283088603344,48.745115509210194,-3.4949067774065425,48.745161905983736,-3.4945641367854563,48.745277742934775,-3.4943263519271386,48.74538772362209,-3.4940545215577976,48.74550676794101,-3.493861817976021,48.74558310537614,15,'Servel - Trébeurden - Lann ar Waremm n°2 vélo (non balisé)');"

**Comment by Gaetanbrl** [comment]
Je suis depuis très récemment sur la résolution de ce bug. 
La [fonction](https://github.com/geobretagne/mviewer/blob/master/lib/mviewer.js#L1402) qui permet de trouver la localisation de l'objet à afficher fonctionne très bien avec des points car les coordonnées contienne un X et un Y et non pas un ensemble de point X et Y (polygon, lignes...).

**Comment by Gaetanbrl** [comment]
j'ai apporté un correctif que je vous proposerai, il me reste la question du niveau de zoom à régler. Le niveau étant par défaut à 15, ce n'est pas adapté pour tous les objets.

**Comment by bchartier** [comment]
Pour la question du zoom, je pense qu'il faut utiliser autant que possible la même stratégie que celle mise en œuvre dans la fonction zoomToFeature :
https://github.com/geobretagne/mviewer/blob/master/lib/mviewer.js#L3257
Cette fonction utilise la méthode fit de ol.view.

Après on peut également se poser la question : est-ce qu'une valeur paramétrable de zoom max  pourrait être utile pour éviter de zoomer trop fortement sur de petit objets.

**Comment by Gaetanbrl** [comment]
C'est exactement la fonction que j'étais sur le point d'intégrer pour faire un zoom sur l'emprise d'un objet. Il est possible de controler le niveau de zoom après avoir fait le fit, afin de le re-modifier au zoom max. Enfin, si cette option n'est pas dispo nativement avec le fit bien sur.

**Comment by spelhate** [comment]
La limite actuelle de la fonction zoomToLocation est de ne pouvoir zoomer que sur un point (2 coordonnées). L'intérêt de cette fonction est de pouvoir être appelée depuis le DOM HTML très facilement e, fournaissant deux paramètres. exemple `onclick="mviewer.zoomToLocation(-3.270139132465777,47.803223956364036,15);" `
Ce méchanisme est plus difficile à mettre en oeuvre pour des entités géographiques complexes.
Une première solution consisterait à tester le type de géométrie de l'entité. Si la géométrie est différente du point, il faudrait passer par une fonction intermédiaire retournant un centroide.
La solution que vous proposez est intéressante mais nécessite à mon sens un plus gros investissement.

**Comment by Gaetanbrl** [comment]
En effet @spelhate , c'est bien fonctionnel dans un premier temps, mais des utilisateurs m'ont remontés que le niveau de zoom par défaut ne leur convient pas. J'ai du ajouter dans mon code une fonction pour faire un zoom sur l'emprise d'une géométrie quelconque, ce qui permet de s'affranchir de la question niveau de zoom.

**Comment by spelhate** [comment]
Que se passe t'il si la géométrie est un point ?

**Comment by spelhate** [comment]
Sinon une autre approche comme évoqué avec @Gaetanbrl : https://github.com/spelhate/mviewer/commit/71e2fbe25197ce2255da5e1bc946f4c5497dcee8 ?
C'est choix...

**Comment by bchartier** [comment]
Sur le principe ça a l'air bien.

Deux remarques :
- si je comprends bien, ol.view.fit n'est pas utilisé pour avoir une fonction générique _getLonLatZfromGeometry au prix d'une complexité un peu plus forte. C'est ça ?

- le fait que _getLonLatZfromGeometry retourne une chaîne de caractères plutôt qu'une structure de données me gène : ça rend la fonction utilisable que pour construire une chaîne de caractères alors que cela pourrait servir ailleurs pour d'autres manipulations avec OpenLayers.

**Comment by spelhate** [comment]
On peut faire en sorte que getLonLatZfromGeometry retourne un objet de ce type
```
{
    lon:value,
    lat: value,
    z: value
}
```
et on aurait alors quelque chose de plus générique.
Sinon on peut également s'appuyer sur ol.view.fit comme proposé par @Gaetanbrl en précisant une valeur de maxZoom (nécessaire pour les géométries de type point).

**Comment by Gaetanbrl** [comment]
Sur un point cela agi de la même façon avec le code que j'ai testé : 

![image](https://user-images.githubusercontent.com/16317988/36261378-69783678-1264-11e8-8572-07faf7dab093.png)

**Comment by bchartier** [comment]
@spelhate : ta modification de getLonLatZfromGeometry me va bien.
L'usage de fit offre moins de possibilités.

**Comment by Gaetanbrl** [comment]
Si je comprend bien @spelhate getLonLatZfromGeometry permet de récupérer un niveau le zoom optimale et le centre d'une géométrie donnée et selon un niveau de zoom max ?
C'est pas mal, ca permet de ne pas refaire d'autres méthodes en plus du zoomToLocation.

**Comment by spelhate** [comment]
Oui c'est ça.

**Comment by spelhate** [comment]
PR #77
