### ISSUE TITLE
Astuce - Utiliser Github Codespaces avec Mviewer

### ISSUE THREAD

**Issue by Gaetanbrl** [geobretagne/mviewer#690]
### Description 
📣📣📣
`Vous avez une compte GitHub` et vous souhaitez tester le super projet Mviewer dont vous avez entendu parlé récemment sans faire plus d'effort 😎 ? 

Un billet précédent présentait [Codesandbox avec Mviewer](https://github.com/geobretagne/mviewer/issues/677). 
Voyez ici comment utiliser la fonctionnalité `[GitHub Codespaces](https://github.com/features/codespaces)`.

En bref, Codespace permet de développer / exécuter une application en direct (live) dans GitHub directement sans installer quelque chose sur votre ordinateur ou sur un serveur. Pratique non ?! 👏

Un peu de doc avant de commencer 😉👌 : 

https://docs.github.com/en/codespaces

### C'est parti ! 🔥🔥🔥

**1.** Se connecter à GitHub

**2.** [Faites un fork](https://mviewerdoc.readthedocs.io/fr/latest/doc_tech/config_practices.html#fork) du projet Mviewer

**3.** Sur https://github.com/MON_ORGA/mviewer ou votre Fork (remplacez MON_ORGA par votre url GitHub personnelle ou d'organisation)

**4.** Cliquer sur `<> Code` 

![image](https://user-images.githubusercontent.com/16317988/201603685-4c8b5d71-4ec6-46cf-b876-7c28233e19f3.png)

**5.** Cliquer sur `+` à droite de la ligne

![image](https://user-images.githubusercontent.com/16317988/201603762-d84bdaad-1f12-43fa-b5c9-9367bbfb2edd.png)

**7.** Une nouvelle page s'ouvre avec l'environnement `VSCode`. Grâce à la présence des fichiers `package.json` et `package-lock.json`, GitHub à pu charger un environnement et détecter que certains paquets Node sont à installer au chargement de la page.

**8.** Attendre que le répertoire `nodes_module` apparaisse dans l'arborescence des fichiers (il contiendra toutes les dépendances installées)

**9.** Cliquez sur Terminal dans le volet du bas

**10.** Ecrire `npm start` pour exécuter le serveur de test / développement

![image](https://user-images.githubusercontent.com/16317988/201604704-8fa91667-4436-47ab-a5ce-19b82689bb35.png)

**11.** Un nouvel onglet s'ouvre avec mviewer. Vous pouvez ouvrir n'importe quelle application du répertoire demo (ou d'un autre répertoire) en ajoutant à la fin de l'URL de l'onglet les paramètres habituels. 

Pour la démo `demo/vector.xml` on obtiendra  donc : 

`?config=demo/vector.xml`

**12.** Vous pouvez aussi aller à l'URL `/demo` directement pour voir le catalogue et tester les démos

💥🌟 **Vous pouvez maintenant tester les démo, développer sur vos branches au sein de votre fork sans bouger de la page GitHub !** 💪🔥

===========
Souvenez-vous 😮☝️ ! Vous devez avoir pris connaissance de ces règles si ce sont vos premiers pas dans le code Mviewer :

📓📓📓

- [x] https://mviewerdoc.readthedocs.io/fr/latest/doc_dev/dev_intro.html
- [x] https://mviewerdoc.readthedocs.io/fr/latest/doc_contrib/contrib.html

**Comment by lecault** [comment]
Ah oui c'est super, plus besoin de developper en local

**Comment by spelhate** [comment]
Top. Merci pour l'astuce @Gaetanbrl .
Je recommande également d'utiliser la page  /demo/ pour accéder ensuite directement à toutes les démos.
