### ISSUE TITLE
Documentation - Utilisation des flux tuilés vectoriels

### ISSUE THREAD

**Issue by frgis** [geobretagne/mviewer#694]
**Description **

Actuellement, le développement d'une nouvelle fonctionnalité est en cours pour gérer depuis le fichier de configuration l'affichage d'un baselayer ou d'un layer de type flux tuilé vectoriel (#675 ). ll est nécessaire de documenter le fonctionnement.

**Solution **

Compléter la documentation.

**Comment by Gaetanbrl** [comment]
@frgis je clos cette issue étant donné que la doc a été réalisée dans la PR TMS.
