### ISSUE TITLE
Créer des éléments HTML en javascript

### ISSUE THREAD

**Issue by Gaetanbrl** [geobretagne/mviewer#70]
A plusieurs endroits du code certain éléments HTML sont crées par des chaîne de caractères.
Que pensez-vous de créer ces éléments en javascript ?

On pourrai remplacer la création des listes de cete façon : 

```str += '<li class="fuse list-group-item" data-icon="false" title="' + result_label + '">' +
'<a href="#" onclick="mviewer.zoomToFeatureExtent('
+ geom+ '\');">'
+ result_label + '</a></li>';```

/* -------- Deviendra  ---------- */

```// create list element by JS                    
var listItem = document.createElement("li");
listItem.setAttribute("class","fuse list-group-item");
listItem.title = result_label;
listItem.dataset.icon = "false";
                    
// create hyperlink element by JS
var hyperlink = document.createElement("a");
hyperlink.appendChild(document.createTextNode(result_label));                           
hyperlink.onclick = function(){
      return mviewer.zoomToFeatureExtent(geom);
};
listItem.appendChild(hyperlink);

**Comment by spelhate** [comment]
Si je résume, pour un résultat identique, il faudra écrire 3 fois plus de code ? ;-)
L'un des intérêts lié à l'utilisation du framework jQuery n'est il pas d'abbréger le code.

>  Write less, do more.

**Comment by bchartier** [comment]
Cela pourrait avoir un intérêt si l'on voulait ajouter des choses optionnelles ou rendre la chose moins dépendante d'un version particulière d'HTML. Mais comme @spelhate le dit, la plus-value n'est pas évidente.
@Gaetanbrl : quels avantages aurions-nous à utiliser les fonctions de JQuery ?

**Comment by Gaetanbrl** [comment]
Ce sont des fonctions javascript pures  W3C pour la manipulation du DOM. Ma proposition ne concerne aucune dépendance externe comme JQuery mais plus une manière rependue d'écrire avec javascript. 
@spelhate je suis plutôt de ton avis, elle alourdi de quelques lignes le code mais je pensais gagner en maintenance...

**Comment by bchartier** [comment]
> De plus, j'ai l'impression que l'event onclick écrit de cette façon ne permet pas de passer un objet en paramètre (ex: une géométrie)

Je pense qu'on peut faire exactement les mêmes actions en manipulant le DOM avec des fonctions élémentaires ou en insérant brutalement un élément à partir d'une chaîne de caractères. Dans les deux cas le DOM est mis à jour (avec les fonctions natives de javascript ou avec des fonctions de JQuery).

**Comment by Gaetanbrl** [comment]
Dans des tests pour l'issue #69 l'objet était pris comme "[objet objet]" ne place de [xmin, ymin,xmax,ymax].  Pour contourner cela, j'ai du passer paramètre directement le paramètre en  string 
"["+"xmin , ymin,xmax,ymax" +"]"

C'est du détail mais si ça peut laisser une trace de ce que j'ai eu comme obstacle peut être que cela resservira à quelqu'un.

Je ferme l'issue merci à tous pour vos réponse !
