### ISSUE TITLE
Mention mauvaise version console

### ISSUE THREAD

**Issue by lecault** [geobretagne/mviewer#713]
**Constat**

Depuis la version 3.9, on a la mention 3.8.1 qui apparait dans la console :

![image](https://user-images.githubusercontent.com/5269430/208122489-2e89d77b-07d9-4853-99fc-71f9d1fda3a2.png)

En regardant dans le code, on trouve cette mention dans : 

apps/.env

{
"version": "3.8.1-snapshot"
 }

mviewer/package.json

  "name": "mviewer",
  "version": "3.8.1-snapshot",
  "description": "Mviewer",

**Question**

Pour les montées de version, on modifie en plus la version à ces 2 endroits ? 
Ou on dépersonnalise ces valeurs (je pense au .env).

Merci

**Comment by Gaetanbrl** [comment]
Cette log ne devrait plus  ou pas s'afficher, et la version dans le fichier `apps/.env` est un exemple par défaut.

**Comment by Gaetanbrl** [comment]
Log supprimée. Cette valeur ne s'affichera plus dans la console.

**Comment by Gaetanbrl** [comment]
Je clos.
