### ISSUE TITLE
Beautify javascript

### ISSUE THREAD

**Issue by spelhate** [geobretagne/mviewer#73]
Je propose d'utiliser http://jsbeautifier.org/ pour nettroyer tout le javascript de mviewer.
L'objectif est d'homogénéiser l'indentation et de supprimer les espaces ou tabulations superflues. Qu'en pensez vous ?

**Comment by bchartier** [comment]
http://jsbeautifier.org/ semble paramétrable (indentation et bien d'autres choses).
Il faudrait qu'on soit d'accord sur ces paramètres.

**Comment by spelhate** [comment]
Ok. je me lance.
indentation avec 4 espaces.

**Comment by Gaetanbrl** [comment]
Certaines conventions sont expliquées [ici](https://www.w3schools.com/js/js_conventions.asp).

Indentation avec 4 espaces c'est pas mal.

**Comment by bchartier** [comment]
Perso, je préfère 2 plutôt que 4 mais je me plierai à votre préférence.
Les conventions de W3Schools m'ont l'air pas mal et assez classiques.

**Comment by Gaetanbrl** [comment]
Assez d'accord, cela permet de rester un peu "standard" ou classique.
Je me demande si jsbeautifier ne reprend pas ces normes déjà car on retrouve 4 espaces d'indentation en paramètres par défaut.

**Comment by spelhate** [comment]
Je vous propose
indentation 4 espaces (pas de tabulation),
espaces autour des opérateurs et après une virgule,
pas d'espace en fin de ligne,
130 caractères max pour une ligne

**Comment by bchartier** [comment]
ok

**Comment by SylvainMassol** [comment]
ok pour moi aussi.
