### ISSUE TITLE
Uniformisé le style des boutons de la bar d'outils

### ISSUE THREAD

**Issue by Gaetanbrl** [geobretagne/mviewer#75]
Lorsque l'on utilise l'outil de mesure, on remarque un décalage sur le bouton de mesure linéaire quelque soit sont état (actif ou non).
![image](https://user-images.githubusercontent.com/16317988/36299937-7a260ae0-12ff-11e8-9b9d-3b300ec9973e.png)

![image](https://user-images.githubusercontent.com/16317988/36299953-87068104-12ff-11e8-98d3-8ae34e0fdf7f.png)

Il y a en effet un effet de bordure différent : [code](https://github.com/geobretagne/mviewer/blob/master/css/mviewer.css#L1552).

**Comment by Gaetanbrl** [comment]
J'ai aussi un cas d'utilisation lié à ces règles de style. J'ai rajouté une "toolbox" sur le principe de l'outil de mesure.  
Pour ne pas rajouter de lignes supplémentaires dans le css, j'ai centralisé le style de ces boutons en une seule règle à rajouter dans le fichier html pour les boutons type outil : [code](https://github.com/METIS-GEO/mviewer/blob/issue74/css/mviewer.css#L1533-L1536).

**Comment by spelhate** [comment]
Bien vu @Gaetanbrl. Je n'arrive pas à accéder à ton lien : erreur 404.

**Comment by Gaetanbrl** [comment]
J'avais un conflit avec le config.xml pour la PR. J'ai refais la branche et fais la PR avec les bonnes différences.  Tu peux y vois les modifications maintenant et j'actualise le lien.
