### ISSUE TITLE
WFS Fuse et WMS en double

### ISSUE THREAD

**Issue by Gaetanbrl** [geobretagne/mviewer#78]
Quand on ajoute un flux WMS et qu'on souhaite aussi appeler ce flux pour une utilisation avec Fuse, la couche est chargée deux fois dans le panneau latéral : 1 fois en WMS (normal) et 1 foix en WFS alors que l'affichage du WFS n'est pas souhaitable car l'information est dans le WMS. 
![image](https://user-images.githubusercontent.com/16317988/36390182-6923f20c-15a2-11e8-9dbc-9479e239963f.png)

**Comment by Gaetanbrl** [comment]
Je pensais à plusieurs options : 
 - utiliser un paramètre dans le fichier de config pour laisser tout de même la possibilité d'utiliser ce wfs comme réalisé dans l'exemple kartenn. 
- Après avoir importé toutes les couches du fichier de config, vérifier qu'une couche n'est pas affichée à la fois en WMS et en WFS. Mais le risque est de casser la possibilité d'affiché deux style différents via un WMS et un WFS de manière volontaire.

Je n'ai pas creuser plus les autres possibilités...

**Comment by Gaetanbrl** [comment]
Suite à quelques tests j'ai appliqué une solution assez simple et j'aimerai votre avis : @spelhate @bchartier .
Pour[ le code](https://github.com/METIS-GEO/mviewer/blob/issue78/lib/mviewer.js#L1870-L1880).

Dans le config.xml, un paramètre booléen "manage" permet de gérer la visibilité (insertion ou non) d'une couche dans le volet latéral de gestion des couches **geojson**. 
Côté lib, on control que le type de couche soit en geojson et le paramètre **manage = "false"**. 

Cela ne s'applique pour les **geojson**. J'ai limité cette modification à mon cas d'utilisation, mais le type peut être étendu.

**Comment by Gaetanbrl** [comment]
le code vient d'être modifié pour assurer le Control de ce paramètre également dans les groupes de couche.

Pour voir la modification : Code.

**Comment by Gaetanbrl** [comment]
> je me pose la question de pourquoi utiliser WMS dans ce cas de figure ?

Le WMS reprend le SLD depuis le geoserver. Le WFS oblige une reproduction du SLD via le fichier featurestyle.js. Dans mon cas, les styles sont trop complexes pour les passer facilement et sans perte de temps en javascript. A moins de réaliser le style WFS selon le SLD de son homologue WMS.

> le fait de donner le choix de mettre une couche ou non dans le panneau latéral est sans doute intéressant. Est-ce que cela veut dire que la couche n'est pas visible ? Si oui, pourquoi ?

C'est un point d'échange que je souhaite aborder. La couche est toujours visible avec le style openLayers par défaut (sauf opacité à 0), ce qui n'est pas propre car on a toujours la couche dans la légende. Il faudrait également ne pas charger cette couche dans la légende et imposer un style null. D'autres utilisations peuvent être envisagées comme mettre en surbrillance des éléments du WFS à titre d'exemple. 
Fuse oblige t il l'import de couche dans la map @bchartier ?

> Il est sans doute devenu opportun de nous faire une réunion en audio conférence

En effet, ce peut être envisagé.

**Comment by spelhate** [comment]
Pour info, je prépare une pull request pour nettoyer le code en lien avec #73 et les règles discutées.
Ok pour échanger en visio ou téléphone. J'ai des disponibilités la semaine prochaine.

**Comment by bchartier** [comment]
>> je me pose la question de pourquoi utiliser WMS dans ce cas de figure ?

> Le WMS reprend le SLD depuis le geoserver. Le WFS oblige une reproduction du SLD via le fichier featurestyle.js. Dans mon cas, les styles sont trop complexes pour les passer facilement et sans perte de temps en javascript. A moins de réaliser le style WFS selon l'appel du SLD de son homologue WMS.

Oui, je comprends bien ce que vous cherchez à faire. Mais WMS est vraiment un truc basique qui est juste fait pour afficher une image. Du coup on a souvent tendance à mettre du WMS avec du WFS ou autre chose encore. C'est bien compliqué quand on n'a pas beaucoup d'objets et une représentation graphique simple à mettre en place (ce qui n'est pas forcément votre cas si je comprends bien).

> Fuse oblige t il l'import de couche dans la map @bchartier ?

Bah, je trouve que vous posez la question à l'envers. Fuse est l'un des moteurs d'indexation que l'on peut activer pour certaines couches. "searchengine" est un attribut des couches. S'il est utilisé il est forcément associé à une couche. Aujourd'hui, me semble-t-il, la recherche avec Fuse ou avec Elasticsearch d'objets d'une couche n'est active que lorsque la couche est visible dans la carte.

>> Il est sans doute devenu opportun de nous faire une réunion en audio conférence

> En effet, c'est une bonne idée !

Ce n'est pas la mienne.

>> Il faut absolument que les sources soient comparables

> J'utilise jsbeautifier... je dois utiliser quelle règle de style ?

Quand @spelhate aura appliqué les règles qu'il a proposées dans #73, vous pourrez utiliser utiliser l'outil que vous voulez tant qu'il est possible de le configurer avec ces règles.
Avant cela il vaut mieux ne pas utiliser d'outils type jsbeautifier si vous voulez soumettre modifications du code (à mon humble avis).

**Comment by SylvainMassol** [comment]
J'ai été confronté au même problème pour la recherche d'objet, en l’occurrence la recherche de parcelle cadastrale.

- La solution Elasticsearch présente deux inconvénients pour moi : l'ajout d'un outil supplémentaire dans notre infra (accessoirement outil que je ne maitrise pas), et la duplication ( et synchronisation) des objets de recherche dans cette base d'indexation.

- La solution Fuse est plus souple, mais à mon avis peu adapté au gros volume d'objet comme le cadastre. En effet charger toutes les parcelles d'une agglomération en vecteur coté client va vite faire exploser le navigateur (peut être que les tuiles vectorielles pourraient contourner le probléme).

- J'ai donc créé ma propre "API" de localisation depuis Postgis à partir de cet [article ](http://rachbelaid.com/postgres-full-text-search-is-good-enough/) en php . J'ai modifié le code Mviewer en conséquence, mais je n'ai pas proposé d'amélioration car la méthode est très spécifique et très dépendante de l'infrastructure serveur. je peux néanmoins partager si ça intéresse certain.

> attention à ne pas trop coller de rustines sur un code. J'ai l'impression que nous avons une tendance à enrichir mviewer au fur et à mesure sans vision globale. Est-ce qu'il ne vaudrait pas mieux prendre le temps de réfléchir à refondre certains points du code ? Il est sans doute devenu opportun de nous faire une réunion en audio conférence pour discuter des faiblesses, évolutions et de l'architecture de l'outil pour essayer de mettre en place une vision commune et à plus long terme.

Je n'ai pas l'habitude de travailler en groupe sur des projets mais je partage ce point de vue. Je serais heureux de pouvoir échanger avec vous, si je suis dispo.

**Comment by bchartier** [comment]
> J'ai été confronté au même problème pour la recherche d'objet, en l’occurrence la recherche de parcelle cadastrale.
> 
> La solution Elasticsearch présente deux inconvénients pour moi : l'ajout d'un outil supplémentaire dans notre infra (accessoirement outil que je ne maitrise pas), et la duplication ( et synchronisation) des objets de recherche dans cette base d'indexation.
> 
> La solution Fuse est plus souple, mais à mon avis peu adapté au gros volume d'objet comme le cadastre. En effet charger toutes les parcelles d'une agglomération en vecteur coté client va vite faire exploser le navigateur (peut être que les tuiles vectorielles pourraient contourner le probléme).
> 
> J'ai donc créé ma propre "API" de localisation depuis Postgis à partir de cet article en php . J'ai modifié le code Mviewer en conséquence, mais je n'ai pas proposé d'amélioration car la méthode est très spécifique et très dépendante de l'infrastructure serveur. je peux néanmoins partager si ça intéresse certain.

Oui, Fuse n'est du tout adapté à l'indexation de gros volume de données.

D'accord aussi avec le fait que la recherche d'une parcelle du cadastre n'est pas l'objet d'un index tel que celui proposé par Elasticsearch ni celui proposé par Fuse. C'est plutôt comparable aux services de géocodage de la BAN ou de l'IGN. Il est donc logique de passer par une API.

Par contre, je ne suis pas d'accord avec le fait de dire que c'est trop spécifique. Oui, ce que vous avez fait avec PostGIS est spécifique à votre architecture. Néanmoins c'est un besoin courant pour beaucoup d'utilisateurs de mviewer (en général des administrations publiques). Il existe des services web pour ce type de recherche. Exemple : https://geoservices.ign.fr/documentation/geoservices/geocodage.html#recherche-par-parcelles-cadastrales
Ils ne sont peut-être pas idéaux pour diverses raisons. Il serait bon de réfléchir à l'intégration de ce genre de fonction dans mviewer (dans un autre ticket que celui-ci).

**Comment by SylvainMassol** [comment]
Je suis d'accord la localisation cadastrale est un besoin courant pour beaucoup d'utilisateur. 
Je ne connaissais pas le service de géocodage cadastral de l'IGN, et en effet il pourrait être intéressant de l’intégrer dans mviewer.
Il a quand même l'inconvénient de nécessiter une recherche peu pratique pour l'utilisateur lambda (ex : 940670000D0041), et comme pour l'API BAN du gouvernement l'impossibilité de limiter la recherche à une étendue ou unité administrative.
Je peux aussi avoir besoin de rechercher d'autres objets, qui ne sont disponibles que dans ma base de donnée (équipements communaux, lignes et arrêts de bus...) sans les envoyer en masse sous forme de vecteur coté client.

### Proposition : 
Peut être vaudrait-il ajouter un autre searchengine générique (en + de fuse, et elasticsearch) avec le même principe. 
Par exemple **_searche_service_custom_** avec une variable **_url_searche_service_custom_** (adresse du service de recherche). La fonction enverrait génériquement en POST AJAX: 
- Nom de la couche
- Texte recherché
- XMin, YMin, XMax, YMax (Si restriction à l'emprise).

Et attendrait en retour : 
- Une proposition sous forme de texte
- Une valeur X Y de localisation.
- _Accessoirement un niveau de zoom_

Je pourrais fournir un exemple avec PostGIS, et chacun pourrait l'adapter à son architecture.

**Ce n'est qu'une proposition, je ne suis pas convaincu qu'elle respecte la philosophie mviewer (client simple).**

**Comment by Gaetanbrl** [comment]
Je trouve cette proposition très pertinente dans le sens où elle évite un autre service ELS qui ne sera utilisé que pour la recherche, sauf besoin annexe et évite aussi le chargement en masse des objets avec Fuse.  Par contre cela nécessite plus de compétence avec postgreSQL etc...

**Comment by spelhate** [comment]
Je trouve la proposition de @SylvainMassol intéressante ainsi que celle de @bchartier sur l'utilisation d'API existantes (IGN...)  Il faut qu'on en discute ensemble.
Je vous adresse un framadate par mel pour convenir d'un créneau d'audio/visio conférence avec notamment un point sur les mécanismes de recherche mobilisables et à développer.
L'idée est construire  ensemble une roadmap

Sinon je viens de merger la PR #79 en lien avec #73. Ca devrait faciliter les contributions.

**Comment by bchartier** [comment]
Oui, bonne idée de définir une feuille de route ensemble.
Par contre, la discussion s'écarte de la question initiale du ticket.
Du coup, j'ai créé un ticket spécifique pour cette nouvelle discussion : #80

**Comment by bchartier** [comment]
Finalement, on en est où du sujet initié par @Gaetanbrl ?

**Comment by bchartier** [comment]
@Gaetanbrl : je ferme ce ticket ?

**Comment by Gaetanbrl** [comment]
je pense....

**Comment by bchartier** [comment]
Ok, je ferme car la discussion sur l'évolution des fonctions de recherche a été déplacée là : #80.
