### ISSUE TITLE
Recherche d'une donnée

### ISSUE THREAD

**Issue by lecault** [geobretagne/mviewer#8]
Grâce à Elastic Search, avoir la possibilité de saisir dans la  barre en haut à droite le contenu d'une donnée (exemple nom d'un lycée, identifiant d'une écluse...).

On ajoute dans la donnée un champ nommé search_id qui sera unique pour toutes les entités du SIG région.

Un paramètre permet d'activer ou non cette recherche ainsi que la recherche d'adresse.

**Comment by spelhate** [comment]
Done
