### ISSUE TITLE
Couches de données exclusives

### ISSUE THREAD

**Issue by spelhate** [geobretagne/mviewer#84]
Dans certains cas d'usage, il est opportun d'empêcher l'affichage simultané de certaines couches identifiées. Exemple avec une application disposant d'une couche des contours administratifs et de 3 couches (a, b et c).
On souhaite mixer l'affichage de la couche contours administratifs avec une seule des 3 couches (a ,b ou c).
Une solution consiste en la création d'un nouveau paramètre de couche : `exclusive`. Si ce paramètre à la valeur true, l'affichage de la couche exclusive entrainera automatiquement le masquage de toute autre couche ayant également le paramètre `exclusive`.

**Comment by bchartier** [comment]
On pourrait voir ce type de besoins de 2 manières différentes :
- soit faire en sorte que d'empêcher certaines couches de s'afficher en même temps. Le paramètre `exclusive` que tu proposes pourrait faire l'affaire.
- soit faire en sorte que certaines couches ne s'affichent que lorsque d'autres couches s'affichent. Par exemple, n'afficher une sur-couche des toponymes que lorsque le fond de carte est une ortho. Cela pourrait passer par une notion de groupe de couches qui contiendrait l'ortho et la surcouche des toponymes dont on ne pourrait pas rendre l'une des 2 visibles sans rendre l'autre visible. Cela correspondrait à une approche `inclusive` plutôt que `exclusive`.

Juste une réflexion en passant...
