### ISSUE TITLE
UI : Themes / groupes

### ISSUE THREAD

**Issue by KentinUltram** [geobretagne/mviewer#85]
Lorsque l'on clique sur un groupe contenant des layers pour le fermer, il se ferme ne laissant affiché que le  thème, au lieu de seulement remonter jusqu'à la liste des groupes. Est-ce voulu ?
Est-ce qu'il possible de garder affiché la liste des groupes dans le menu et de ne passer en "hidden " que la liste des layers ?
De même avec les thèmes, un seul peut s'afficher à la fois.

**Comment by spelhate** [comment]
> Lorsque l'on clique sur un groupe contenant des layers pour le fermer, il se ferme ne laissant affiché que le thème, au lieu de seulement remonter jusqu'à la liste des groupes. Est-ce voulu ?

Il ne s'agit pas d'un comportement voulu. Toute contribution pour corriger celà est bienvenue.

> De  même avec les thèmes, un seul peut s'afficher à la fois.

Ici c'est voulu ;-)

**Comment by KentinUltram** [comment]
J'essaie de trifouiller le code et ai fait quelques tests mais rien de concluant pour l'instant, surtout parce que j'ai un peu de mal avec le html généré via le js, lui dire de passer en "hidden" une liste avec l'id hardcoded ne passe pas pour le moment.

**Comment by spelhate** [comment]
Je vais regarder de mon côté.

**Comment by spelhate** [comment]
Le comportement du panneau thématique est géré  dans ce  [fichier](https://github.com/geobretagne/mviewer/blob/master/lib/simple-slidebar/slidebar_menu.js)
Je viens de corriger le bug ici  f2ef5a1

**Comment by KentinUltram** [comment]
Parfait je vais propager dans mon viewer ! Je ne tapais au bon endroit, j'avais tenté dans le jqm-templates.js
