### ISSUE TITLE
Image or svg icon for theme element

### ISSUE THREAD

**Issue by ebocher** [geobretagne/mviewer#89]
Currently the theme element uses an icon  tag related to a font.
Is there a way to set an image or a svg icon ?

**Comment by spelhate** [comment]
Actually There is no way to set an image/icon to the theme element except using font Awesome tag

**Comment by ebocher** [comment]
Thanks for the answer
Any support planed in the future for this issue ?

**Comment by spelhate** [comment]
No support planed for this issue but PR's are welcome ! :D

**Comment by domlysz** [comment]
Seems this issue is now fixed on master, as the doc says it's possible to use a css class.

**Comment by spelhate** [comment]
Solved with 8f707689f235963f35b455e4a2c1db1bff6b9e35
You can create custom icon with svg or image by creating custom css class:

```
.mycustomicon::before {
    content: '';
    display: inline-block;
    height: 1em;
    width: 1em;
    background: url(../img/logo/worldwide.svg) no-repeat scroll;
    background-size: 16px 16px;
    margin-top: 9px;
}
```

and then call it setting icon parameter as `icon=".mycustomicon"`

**Comment by ebocher** [comment]
@spelhate  thanks a lot.
Sorry but we are too busy to contribute. By the way, thanks for our great job.

**Comment by ebocher** [comment]
@gpetit
