### ISSUE TITLE
wms geoservice ign en layer

### ISSUE THREAD

**Issue by fxduponcheel** [geobretagne/mviewer#91]
Bonjour

J'arrive à utiliser les wms des geoservices ign en baselayer
Par contre je n'y arrive pas en essayant de les faire fonctionner en layer

exemple avec le parcellaire : 

le base layer ci dessous fonctionne :
<baselayer 
type="WMS" 
id="cadastre" 
label="Cadastre IGN" 
title="GéoCouesnon" 
thumbgallery="img/basemap/cadastre.png" 
url="http://wxs.ign.fr/""clef""/geoportail/r/wms?" 
layers="CADASTRALPARCELS.PARCELS" 
format="image/jpeg" 
visible="false" 
fromcapacity="false"
/>

Par contre en layer, cela ne fonctionne pas : 
<layer 
id="CADASTRALPARCELS.PARCELS"
name="Cadastre (BD Parcellaire IGN)"
url="http://wxs.ign.fr/""clef""/geoportail/r/wms?" 
/>

Des idées ?

Merci pour laide

**Comment by fxduponcheel** [comment]
pourquoi as tu le suffixe gpp3- dans ton url ign ? La mienne commence directement par wxs.ign ....
Merci pour ton aide Stéphane

**Comment by fxduponcheel** [comment]
Pour info, ça fonctionne avec du wms vecteur. incompressible !!

**Comment by spelhate** [comment]
Je viens de retirer le préfixe gpp3- dans la démo et ça fonctionne aussi.
Sinon ta requête (badRequest) retourne ce message :  Key does not exist or has expired.
Il faut remplacer dans l'URL ""cle"" par ta clé.

**Comment by fxduponcheel** [comment]
oui je sais c'est moi qui ai remplacé ma clef par ""clef"" sur le forum ... et je me suis rendu compte que ça servait à rien :)

j'ai essayé avec une autre donnée: 
ça ça marche en baselayer :
<baselayer  type="WMS" id="rpg2016" label="RPG 2016" title="GéoPortail" maxscale="2000" thumbgallery="https://www.geoportail.gouv.fr/depot/layers/LANDUSE.AGRICULTURE2016/vignettes/LANDUSE.AGRICULTURE2016-quickViewSMLL.jpg"
    url="http://wxs.ign.fr/2xryea16937feh8tjfhqnsj0/geoportail/r/wms?" layers="LANDUSE.AGRICULTURE2016" format="image/jpeg" visible="false" fromcapacity="false"
    attribution="&lt;a href='http://www.geoportail.fr/' target='_blank'>&lt;img src='http://api.ign.fr/geoportail/api/js/latest/theme/geoportal/img/logo_gp.gif'>&lt;/a>" style="normal" matrixset="PM" maxzoom="22"/>

et ça marche pas en layer :
<layer 
id="LANDUSE.AGRICULTURE2016"
name="Cultures 2016"
type="wms"
opacity="0,5"
url="http://wxs.ign.fr/2xryea16937feh8tjfhqnsj0/geoportail/r/wms?"
legendurl="https://www.geoportail.gouv.fr/depot/layers/LANDUSE.AGRICULTURE2014/legendes/LANDUSE.AGRICULTURE2014-legend.png"
attribution="">
</layer> 

ça commence à me courir :)

**Comment by fxduponcheel** [comment]
<layer 
		id="LANDUSE.AGRICULTURE2016"
            name="Cultures 2016"
            type="wms"
			opacity="0,5"
            url="http://wxs.ign.fr/2xryea16937feh8tjfhqnsj0/geoportail/r/wms?"
            legendurl="https://www.geoportail.gouv.fr/depot/layers/LANDUSE.AGRICULTURE2014/legendes/LANDUSE.AGRICULTURE2014-legend.png"
			
			attribution="">
        </layer>

**Comment by fxduponcheel** [comment]
bizarre mes copier coller n'ont pas fonctionné ..

**Comment by fxduponcheel** [comment]
<baselayer  type="WMS" id="rpg2016" label="RPG 2016" title="GéoPortail" maxscale="2000" thumbgallery="https://www.geoportail.gouv.fr/depot/layers/LANDUSE.AGRICULTURE2016/vignettes/LANDUSE.AGRICULTURE2016-quickViewSMLL.jpg"
    url="http://wxs.ign.fr/2xryea16937feh8tjfhqnsj0/geoportail/r/wms?" layers="LANDUSE.AGRICULTURE2016" format="image/jpeg" visible="false" fromcapacity="false"
    attribution="&lt;a href='http://www.geoportail.fr/' target='_blank'>&lt;img src='http://api.ign.fr/geoportail/api/js/latest/theme/geoportal/img/logo_gp.gif'>&lt;/a>" style="normal" matrixset="PM" maxzoom="22"/>

**Comment by fxduponcheel** [comment]
baselayer  type="WMS" id="rpg2016" label="RPG 2016" title="GéoPortail" maxscale="2000" thumbgallery="https://www.geoportail.gouv.fr/depot/layers/LANDUSE.AGRICULTURE2016/vignettes/LANDUSE.AGRICULTURE2016-quickViewSMLL.jpg"
    url="http://wxs.ign.fr/2xryea16937feh8tjfhqnsj0/geoportail/r/wms?" layers="LANDUSE.AGRICULTURE2016" format="image/jpeg" visible="false" fromcapacity="false"
    attribution="&lt;a href='http://www.geoportail.fr/' target='_blank'>&lt;img src='http://api.ign.fr/geoportail/api/js/latest/theme/geoportal/img/logo_gp.gif'>&lt;/a>" style="normal" matrixset="PM" maxzoom="22"/

**Comment by spelhate** [comment]
Tu as une démo en ligne ?
Et pour le parcellaire cadastral c'est bon chez toi (ton 1er exemple), car cela fonctionne dans la démo que je propose.
Sinon d'une manière générale, les messages d'erreurs retournés par les requêtes adressées aux géoservices de l'IGN comportent des indications utiles. Dans ton cas quels sont les messages d'erreur ?

**Comment by spelhate** [comment]
J'ai trouvé pourquoi ça ne marche pas chez toi. Enfin plutôt pourquoi ça ne s'affiche pas.
Tu as mis une opacité à 0 sur cette couche (opacity="0") et donc la couche est invisible.
Dans ta config, il faut mettre opacity=0.5 à la place de 0,5 (pas de virgule)
Je viens de vérifier ici : http://geocouesnon.sage-couesnon.fr/geocouesnon/

**Comment by fxduponcheel** [comment]
j'ai remplacé par un point. ça ne fonctionne tjs pas

**Comment by fxduponcheel** [comment]
message d'erreur :

<ExceptionReport>
<Exception exceptionCode="MissingRights">
Wrong referer or wrong IP Adress or wrong User-Agent
</Exception>
</ExceptionReport>

**Comment by fxduponcheel** [comment]
Mais pq ça fonctionne en baselayer ??? T'as un contact à l'IGN que je pourrais joindre ?

**Comment by fxduponcheel** [comment]
Sinon j'ai ça comme erreur :

ServiceException code="InvalidParameterValue" 
  La valeur du parametre WIDTH est superieure a la valeur maximum autorisee par le service.

**Comment by fxduponcheel** [comment]
j'ai rajouté tiled="true" et ça fonctionne
Merci Sebastien !

**Comment by spelhate** [comment]
Ok. je ferme.

**Comment by MarieJag** [comment]
Bonjour,

J'ai un problème similaire avec les couches IGN.
Je travaille sur un mviewer "Données satelitaires" et je voudrais ajouter les données spatial IGN (SPOT et Pleiades).
Sur le mviewer, lorsque je coche la couche "SPOT" à afficher, rien ne s'affiche.
J'ai le même problème avec la couche d'occupation du sol Theia.

Voici ma config pour la couche SPOT (où je remplace xxxxxxxxxxxxxxxxxxxxxxxx dans l'url du flux par ma clé IGN)

		
  	<theme name="Images IGN - tests" collapsed="false" id="images IGN"
    icon="caret-right">
			 
    <group name="Images SPOT" id="SPOT">
		<layer id="ORTHOIMAGERY.ORTHO-SAT.SPOT.2017"
            name="SPOT 2017"
            visible="false" 
            tiled="true"
            queryable="true"
			legendurl=""
            infoformat="text/html"
            url="http://wxs.ign.fr/xxxxxxxxxxxxxxxxxxxxxxxx/geoportail/r/wms?"
            attribution="Source du flux : IGN"
            metadata="md"
            metadata-csw="md" >
    </group>
      </layer>
		</theme>

Et voici le lien vers le mviewer
https://geobretagne.fr/pub/dreal_b/mviewer/?config=../apps/teledetection/config.xml#

Peut-être avez-vous des idées ?

Merci,

Marie

**Comment by fxduponcheel** [comment]
Bonjour

 

J’ai fait l’essai pour la couche ORTHOIMAGERY.ORTHO-SAT.SPOT.2017 avec le mviewer Geocouesnon, ça fonctionne.

 

<layer 

id="ORTHOIMAGERY.ORTHO-SAT.SPOT.2017"

            name="spot2017"

            tiled="true"           

            url="http://wxs.ign.fr/xxxxxxxxxxxxx/geoportail/r/wms?"

            legendurl=" " 

attribution="Géoportail">

        </layer>

 

 

 

Cordialement,

 

François-Xavier Duponcheel

Chargé de mission Environnement-SIG

Syndicat Mixte du SAGE Couesnon

02 99 99 22 51

www.sage-couesnon.fr

 

De : MarieJag [mailto:notifications@github.com] 
Envoyé : mercredi 24 avril 2019 17:49
À : geobretagne/mviewer
Cc : fxduponcheel; Author
Objet : Re: [geobretagne/mviewer] wms geoservice ign en layer (#91)

 

Bonjour,

J'ai un problème similaire avec les couches IGN.
Je travaille sur un mviewer "Données satelitaires" et je voudrais ajouter les données spatial IGN (SPOT et Pleiades).
Sur le mviewer, lorsque je coche la couche "SPOT" à afficher, rien ne s'affiche.
J'ai le même problème avec la couche d'occupation du sol Theia.

Voici ma config pour la couche SPOT (où je remplace xxxxxxxxxxxxxxxxxxxxxxxx dans l'url du flux par ma clé IGN)

      
 
<theme name="Images IGN - tests" collapsed="false" id="images IGN"
 
icon="caret-right">
 
              
 
<group name="Images SPOT" id="SPOT">
 
        <layer id="ORTHOIMAGERY.ORTHO-SAT.SPOT.2017"
 
        name="SPOT 2017"
 
        visible="false" 
 
        tiled="true"
 
        queryable="true"
 
               legendurl=""
 
        infoformat="text/html"
 
        url="http://wxs.ign.fr/xxxxxxxxxxxxxxxxxxxxxxxx/geoportail/r/wms?"
 
        attribution="Source du flux : IGN"
 
        metadata="md"
 
        metadata-csw="md" >
 
</group>
 
  </layer>
 
        </theme>
 

Et voici le lien vers le mviewer
https://geobretagne.fr/pub/dreal_b/mviewer/?config=../apps/teledetection/config.xml# <https://geobretagne.fr/pub/dreal_b/mviewer/?config=../apps/teledetection/config.xml> 

Peut-être avez-vous des idées ?

Merci,

Marie

**Comment by MarieJag** [comment]
Bonjour François Xavier, 

Merci pour cette réponse. 
Bizarre, toujours rien sur mon mviewer, même quand je copie-colle des config d'autres mviewer sur lesquels l'affichage des flux IGN fonctionne. 
En revanche le lien de l'IGN fonctionne bien bien sur mapfishapp. 
Je constate que j'ai ce problème avec les couches http:// (j'ai le même problème avec la couche OSO Theia et la couche du CBNB) 
J'ai essayé en remplaçant http:// par https:// mais toujours rien. 
Cela peut-il venir de la config de mon mviewer ( [ https://geobretagne.fr/pub/dreal_b/mviewer/?config=../apps/teledetection/config.xml# | https://geobretagne.fr/pub/dreal_b/mviewer/?config=../apps/teledetection/config.xml# ] ) qui ne gèrerai pas l'affichage des http:// ? 



De: "fxduponcheel" <notifications@github.com> 
À: "geobretagne/mviewer" <mviewer@noreply.github.com> 
Cc: "Marie JAGAILLE" <marie.jagaille@imt-atlantique.fr>, "Manual" <manual@noreply.github.com> 
Envoyé: Jeudi 25 Avril 2019 09:39:45 
Objet: Re: [geobretagne/mviewer] wms geoservice ign en layer (#91) 

Bonjour 



J’ai fait l’essai pour la couche ORTHOIMAGERY.ORTHO-SAT.SPOT.2017 avec le mviewer Geocouesnon, ça fonctionne. 



<layer 

id="ORTHOIMAGERY.ORTHO-SAT.SPOT.2017" 

name="spot2017" 

tiled="true" 

url="http://wxs.ign.fr/xxxxxxxxxxxxx/geoportail/r/wms?" 

legendurl=" " 

attribution="Géoportail"> 

</layer> 







Cordialement, 



François-Xavier Duponcheel 

Chargé de mission Environnement-SIG 

Syndicat Mixte du SAGE Couesnon 

02 99 99 22 51 

www.sage-couesnon.fr 



De : MarieJag [mailto:notifications@github.com] 
Envoyé : mercredi 24 avril 2019 17:49 
À : geobretagne/mviewer 
Cc : fxduponcheel; Author 
Objet : Re: [geobretagne/mviewer] wms geoservice ign en layer (#91) 



Bonjour, 

J'ai un problème similaire avec les couches IGN. 
Je travaille sur un mviewer "Données satelitaires" et je voudrais ajouter les données spatial IGN (SPOT et Pleiades). 
Sur le mviewer, lorsque je coche la couche "SPOT" à afficher, rien ne s'affiche. 
J'ai le même problème avec la couche d'occupation du sol Theia. 

Voici ma config pour la couche SPOT (où je remplace xxxxxxxxxxxxxxxxxxxxxxxx dans l'url du flux par ma clé IGN) 

 

<theme name="Images IGN - tests" collapsed="false" id="images IGN" 

icon="caret-right"> 

 

<group name="Images SPOT" id="SPOT"> 

<layer id="ORTHOIMAGERY.ORTHO-SAT.SPOT.2017" 

name="SPOT 2017" 

visible="false" 

tiled="true" 

queryable="true" 

legendurl="" 

infoformat="text/html" 

url="http://wxs.ign.fr/xxxxxxxxxxxxxxxxxxxxxxxx/geoportail/r/wms?" 

attribution="Source du flux : IGN" 

metadata="md" 

metadata-csw="md" > 

</group> 

</layer> 

</theme> 


Et voici le lien vers le mviewer 
https://geobretagne.fr/pub/dreal_b/mviewer/?config=../apps/teledetection/config.xml# <https://geobretagne.fr/pub/dreal_b/mviewer/?config=../apps/teledetection/config.xml> 

Peut-être avez-vous des idées ? 

Merci, 

Marie

**Comment by smevel** [comment]
Marie,
Nous avons modifié la clé IGN et ajouté les données Pléïades. Nous allons gérons les redirections pour avoir des adresses IGN avec la clé IGN comme pour le WMTS.
Je reviens vers toi.
Stéphane

> Bonjour François Xavier, Merci pour cette réponse. Bizarre, toujours rien sur mon mviewer, même quand je copie-colle des config d'autres mviewer sur lesquels l'affichage des flux IGN fonctionne. En revanche le lien de l'IGN fonctionne bien bien sur mapfishapp. Je constate que j'ai ce problème avec les couches http:// (j'ai le même problème avec la couche OSO Theia et la couche du CBNB) J'ai essayé en remplaçant http:// par https:// mais toujours rien. Cela peut-il venir de la config de mon mviewer ( [ https://geobretagne.fr/pub/dreal_b/mviewer/?config=../apps/teledetection/config.xml# | https://geobretagne.fr/pub/dreal_b/mviewer/?config=../apps/teledetection/config.xml# ] ) qui ne gèrerai pas l'affichage des http:// ?

**Comment by fxduponcheel** [comment]
Bonjour Marie. Je ne vais pas pouvoir t’aider, ça dépasse malheureusement mes compétences…

 

Cordialement,

 

François-Xavier Duponcheel

Chargé de mission Environnement-SIG

Syndicat Mixte du SAGE Couesnon

02 99 99 22 51

www.sage-couesnon.fr

 

De : MarieJag [mailto:notifications@github.com] 
Envoyé : jeudi 25 avril 2019 10:37
À : geobretagne/mviewer
Cc : fxduponcheel; Author
Objet : Re: [geobretagne/mviewer] wms geoservice ign en layer (#91)

 

Bonjour François Xavier, 

Merci pour cette réponse. 
Bizarre, toujours rien sur mon mviewer, même quand je copie-colle des config d'autres mviewer sur lesquels l'affichage des flux IGN fonctionne. 
En revanche le lien de l'IGN fonctionne bien bien sur mapfishapp. 
Je constate que j'ai ce problème avec les couches http:// (j'ai le même problème avec la couche OSO Theia et la couche du CBNB) 
J'ai essayé en remplaçant http:// par https:// mais toujours rien. 
Cela peut-il venir de la config de mon mviewer ( [ https://geobretagne.fr/pub/dreal_b/mviewer/?config=../apps/teledetection/config.xml# | https://geobretagne.fr/pub/dreal_b/mviewer/?config=../apps/teledetection/config.xml# ] ) qui ne gèrerai pas l'affichage des http:// ? 



De: "fxduponcheel" <notifications@github.com> 
À: "geobretagne/mviewer" <mviewer@noreply.github.com> 
Cc: "Marie JAGAILLE" <marie.jagaille@imt-atlantique.fr>, "Manual" <manual@noreply.github.com> 
Envoyé: Jeudi 25 Avril 2019 09:39:45 
Objet: Re: [geobretagne/mviewer] wms geoservice ign en layer (#91) 

Bonjour 



J’ai fait l’essai pour la couche ORTHOIMAGERY.ORTHO-SAT.SPOT.2017 avec le mviewer Geocouesnon, ça fonctionne. 



<layer 

id="ORTHOIMAGERY.ORTHO-SAT.SPOT.2017" 

name="spot2017" 

tiled="true" 

url="http://wxs.ign.fr/xxxxxxxxxxxxx/geoportail/r/wms?" 

legendurl=" " 

attribution="Géoportail"> 

</layer> 







Cordialement, 



François-Xavier Duponcheel 

Chargé de mission Environnement-SIG 

Syndicat Mixte du SAGE Couesnon 

02 99 99 22 51 

www.sage-couesnon.fr 



De : MarieJag [mailto:notifications@github.com] 
Envoyé : mercredi 24 avril 2019 17:49 
À : geobretagne/mviewer 
Cc : fxduponcheel; Author 
Objet : Re: [geobretagne/mviewer] wms geoservice ign en layer (#91) 



Bonjour, 

J'ai un problème similaire avec les couches IGN. 
Je travaille sur un mviewer "Données satelitaires" et je voudrais ajouter les données spatial IGN (SPOT et Pleiades). 
Sur le mviewer, lorsque je coche la couche "SPOT" à afficher, rien ne s'affiche. 
J'ai le même problème avec la couche d'occupation du sol Theia. 

Voici ma config pour la couche SPOT (où je remplace xxxxxxxxxxxxxxxxxxxxxxxx dans l'url du flux par ma clé IGN) 

 

<theme name="Images IGN - tests" collapsed="false" id="images IGN" 

icon="caret-right"> 

 

<group name="Images SPOT" id="SPOT"> 

<layer id="ORTHOIMAGERY.ORTHO-SAT.SPOT.2017" 

name="SPOT 2017" 

visible="false" 

tiled="true" 

queryable="true" 

legendurl="" 

infoformat="text/html" 

url="http://wxs.ign.fr/xxxxxxxxxxxxxxxxxxxxxxxx/geoportail/r/wms?" 

attribution="Source du flux : IGN" 

metadata="md" 

metadata-csw="md" > 

</group> 

</layer> 

</theme> 


Et voici le lien vers le mviewer 
https://geobretagne.fr/pub/dreal_b/mviewer/?config=../apps/teledetection/config.xml# <https://geobretagne.fr/pub/dreal_b/mviewer/?config=../apps/teledetection/config.xml> 

Peut-être avez-vous des idées ? 

Merci, 

Marie

**Comment by MarieJag** [comment]
Merci Stéphane et François-Xavier pour vos réponses,
A suivre donc pour les flux IGN.
Si jamais cela peut-être utile à d'autres, pour les autres couches que je mentionnais OSO (Theia) et végétation (CBNB) qui ne s’affichaient pas dans le mviewer, il fallait enlever dans la config 
exportpng="true"
(voir sujet https://github.com/geobretagne/mviewer/issues/37)
Bonne journée,
Marie
