### ISSUE TITLE
Forcer l'utilisation d'une version de WMS

### ISSUE THREAD

**Issue by bchartier** [geobretagne/mviewer#92]
Lors d'un test avec un service WMS de GeoIDE nous avons détecté une anomalie dans l'utilisation de WMS 1.3.0 (côté serveur WMS de GeoIDE et non côté mviewer) qui pourrait être contournée si nous pouvions forcer l'utilisation de WMS 1.1.1 dans la configuration de la couche en question.

Je vous propose qu'on puisse ajouter un paramètre optionnel owsversion au niveau des éléments baselayer et layer. Ce paramètre prendrait une valeur du type  "1.1.1", "1.3.0". Il ne s'appliquerait que lorsque le type de la couche serait WMS ou WMTS.

Une alternative pourrait être de supporter des types enrichis (ce qui éviterait d'avoir à gérer de nouvelles paramètres dans le fichier de config : "wms:1.1.1" par exemple.

Qu'en pensez-vous ?

**Comment by spelhate** [comment]
:+1:  pour le paramètre optionnel owsversion

**Comment by bchartier** [comment]
Faut-il considérer que l'objet de ce ticket pourrait être traité par #94, qu'il vaut mieux traiter ce dernier et abandonner #92 ?
