### ISSUE TITLE
Forcer l'emploi de certains paramètres dans les requêtes GetMap

### ISSUE THREAD

**Issue by bchartier** [geobretagne/mviewer#94]
Au cours d'un test d'utilisation d'un service WMS publié via Mapproxy, un problème singulier est apparu : l'incapacité d'utiliser le format JPEG quand la requête GetMap contient le paramètre TILED. Il s'agit sans doute d'un souci au niveau de la configuration du Mapproxy en question. Il se trouve que pas mal d'implémentations de WMS (que ce soit au niveau de clients ou de serveurs) utilisent des paramètres non prévus par le standard pour des besoins spécifiques. Je me suis donc demandé si cela peut être pertinent de forcer les requêtes GetMap de certaines couches à utiliser ou ne pas utiliser certains paramètres (pour éviter de profiter de certains effets de bord ou pour profiter de capacités spécifiques).

Après je ne sais pas si ce serait facile à mettre en place ou si cela serait d'une grande utilité. Des avis ?

**Comment by spelhate** [comment]
Tu as un exemple de Mapproxy qui sert du WMS ?

**Comment by bchartier** [comment]
https://osm.geopicardie.fr/mapproxy/demo/

**Comment by spelhate** [comment]
Je résume ce que j'ai compris

Tu souhaites désactiver l'emploi de certains paramètres lors des appels getMap effectués par des couches de type baselayer (couche de fond) ou éventuellement rajouter ou écraser des paramètres prédéfinis.
Exemple pour un getMap (WMS) effectué par une couche de type baselayer les paramètres suivants sont automatiquement appliqués : 

- SERVICE=WMS
- VERSION=1.1.1
- TILED=TRUE

Les paramètres configurables sont actuellement

- LAYERS
- FORMAT

On pourrait effectivement créer un nouveau paramètre "owsoptions" avec tous les paramètres propres au service concerné. exemple `owsoptions=VERSION:1.3.0,TILED:FALSE,EXCEPTIONS:application/vnd.ogc.se_inimage`

Dans ce cas précis, les paramètres VERSION et TILED seraient écrasés et un nouveau pramètre EXCEPTIONS serait créé.

**Comment by bchartier** [comment]
Oui, tu résumes bien ce que je j'avais en tête.

Pour illustrer une requête qui fonctionne avec mon Mapproxy :
https://osm.geopicardie.fr/mapproxy/service?LAYERS=faded&TRANSPARENT=true&VERSION=1.1.1&FORMAT=image%2Fjpeg&SERVICE=WMS&REQUEST=GetMap&STYLES=&EXCEPTIONS=application%2Fvnd.ogc.se_xml&SLD_VERSION=1.0.0&SRS=EPSG%3A3857&BBOX=-499356.28544407,6059677.1205228,-418027.28734865,6141006.1186182&WIDTH=532&HEIGHT=532

Une requête qui ne fonctionne pas avec mon Mapproxy (présence du paramètre TILED=true ajouté par mviewer) :
https://osm.geopicardie.fr/mapproxy/service?LAYERS=faded&TRANSPARENT=true&VERSION=1.1.1&FORMAT=image%2Fjpeg&SERVICE=WMS&REQUEST=GetMap&STYLES=&EXCEPTIONS=application%2Fvnd.ogc.se_xml&SLD_VERSION=1.0.0&SRS=EPSG%3A3857&BBOX=-499356.28544407,6059677.1205228,-418027.28734865,6141006.1186182&WIDTH=532&HEIGHT=532&TILED=true

**Comment by spelhate** [comment]
Et pour être complet j'ajoute une requête qui fonctionne avec mviewer si le format utilisé est png 
https://osm.geopicardie.fr/mapproxy/service?SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=false&LAYERS=grey&TILED=true&WIDTH=256&HEIGHT=256&SRS=EPSG%3A3857&STYLES=&BBOX=-173664.9282639213%2C6129638.172244854%2C-171218.94335879566%2C6132084.15714998
;-)

**Comment by bchartier** [comment]
Oui, merci.
J'ai oublié de préciser que le souci ne semble se présenter qu'avec JPEG.

**Comment by bchartier** [comment]
Ma compréhension du problème que je rencontrais :
* Insérer le paramètre TILED=true dans les requêtes WMS indique aux serveurs qu'il s'agit d'une requête WMS-C.
* MapProxy vérifie que l'emprise des requêtes WMS-C est cohérente avec la grille paramétrée dans MapProxy.
* Dans mon cas particulier la carte est en EPSG:2154. Une grille pour EPSG:2154 est présente sur le serveur MapProxy en question mais mviewer ne la connaît pas.
=> MapProxy rejète les requêtes.

J'ai essayé de modifier le code de mviewer pour configurer associer TileGrid équivalent sans succès.
J'ai donc proposé d'intégrer un paramètre tiled pour les baselayers dans le pullrequest.

**Comment by spelhate** [comment]
Ok. Merci @bchartier . Je laisse le ticket ouvert car d'autres cas d'utilisation nécessitent l'emploi de paramètres supplémentaires dans les requêtes de type GetMap.

**Comment by bchartier** [comment]
Oui. Je suis tout à fait d'accord.

**Comment by bchartier** [comment]
La pull request a été fusionnée dans la branche develop. Je ferme le ticket.
