### ISSUE TITLE
Mise à jour de la documentation

### ISSUE THREAD

**Issue by spelhate** [geobretagne/mviewer#95]
Mette à jour la doc readthedocs du projet https://github.com/geobretagne/mviewer.doc

- Supprimer les redondances avec README.md
- Documenter les dernières évolutions

**Comment by bchartier** [comment]
Toujours d'actualité ?

**Comment by spelhate** [comment]
Oui. Des choses ont été entamées sur l'aspect contributions. Mais il reste à documenter les dernières évolutions.

**Comment by spelhate** [comment]
Je ferme pour la release 3.2
