### ISSUE TITLE
Isochrone et attribut

### ISSUE THREAD

**Issue by Dortmunder** [geobretagne/mviewer#97]
Quand on ajoute la fonction Isochrone dans un mviewer (via l'API de l'IGN), l'accès aux attributs des couches ne fonctionne plus. Exemple : 
https://www.geopicardie.fr/mviewer/?config=transport_hdf.xml
Si j'enlève le thème avec l'isochrone du fichier de config, j'ai à nouveau accès aux attributs des couches.
Est-ce qu'il y a un moyen de contourner le problème ?

Vincent Fabry
administrateur GéoPicardie

**Comment by Dortmunder** [comment]
En fait il faut que la couche Isochrone ne soit pas affichée pour que l'affichage des attributs fonctionne.

**Comment by bchartier** [comment]
Est-ce qu'on un moyen d'améliorer cela ?

**Comment by spelhate** [comment]
A l'affichage de la couche isochrones, l'interrogation des autres couches est désactivé.
Il faudrait remplacer ce comportement par une désactivation de l'interrogation au moment où on trace le point, point de départ du calcul.

**Comment by bchartier** [comment]
C'est un comportement qui a été codé pour le calcul des isochrones ou c'est un mécanisme plus général. [Je pense que c'est spécifique aux isochrones mais je préfère être sûr]

**Comment by spelhate** [comment]
Il s'agit d'un comportement codé pour le calcul des isochrones. Je corrige.

**Comment by Dortmunder** [comment]
Merci Sébastien !
(et bonne année !)

Vincent
Administrateur GéoPicardie





[cid:image001.png@01D4A66E.38DE8EB0]

Vincent FABRY
Direction de la prospective et des stratégies régionales
Administrateur des systèmes d'information


Tél. +33374271583 - Standard. +33374270000
Vincent.FABRY@hautsdefrance.fr<mailto:Vincent.FABRY@hautsdefrance.fr>




151 Avenue du président Hoover
59555 LILLE CEDEX

15 Mail Albert 1er
80000 AMIENS CEDEX



[cid:image002.jpg@01D4A66E.38DE8EB0]<https://lsi.cr-picardie.fr/r/53/0d11fd13-15a1-47d0-9c31-a18fb23d72df/undefined>

[cid:image003.jpg@01D4A66E.38DE8EB0]<https://lsi.cr-picardie.fr/r/54/a82fff69-8f35-4edd-8349-c74fda9e0c9f/undefined>

[cid:image004.png@01D4A66E.38DE8EB0]<https://lsi.cr-picardie.fr/r/92/1ac9fbaf-62d2-4547-b890-b05aaec3e45e/undefined>

[cid:image005.jpg@01D4A66E.38DE8EB0]<https://lsi.cr-picardie.fr/r/55/392159e1-0284-4bbd-bad7-affa8f79ace1/undefined>

[cid:image006.jpg@01D4A66E.38DE8EB0]<https://lsi.cr-picardie.fr/r/56/bd3906a6-977f-44c4-8963-6fc9bb440089/undefined>


[cid:image007.jpg@01D4A66E.38DE8EB0]

Pensez environnement : n'imprimez ce message que si nécessaire.




[cid:image008.jpg@01D4A66E.38DE8EB0]<https://lsi.cr-picardie.fr/r/103/acd035c4-d91f-42d3-9331-59d1243b2781/undefined>




De : spelhate [mailto:notifications@github.com]
Envoyé : jeudi 3 janvier 2019 13:46
À : geobretagne/mviewer <mviewer@noreply.github.com>
Cc : FABRY Vincent <Vincent.FABRY@hautsdefrance.fr>; State change <state_change@noreply.github.com>
Objet : Re: [geobretagne/mviewer] Isochrone et attribut (#97)


Il s'agit d'un comportement codé pour le calcul des isochrones. Je corrige.
