### ISSUE TITLE
Paramètre "theme" transmis par l'URL

### ISSUE THREAD

**Issue by Dortmunder** [geobretagne/mviewer#98]
J'essaie d'instancier un mviewer avec un theme comme paramètre dans l'URL, mais ça m'affiche le theme par défaut 

https://www.geopicardie.fr/mviewer/?theme=green

le fichier green.css est bien présent dans css/theme

Vincent Fabry
GéoPicardie

**Comment by spelhate** [comment]
Ok. Correction planifiée.

**Comment by Dortmunder** [comment]
Merci !
Question subsidiaire : est-ce qu'on pourra instancier avec deux paramètres ? Par exemple un thème et un contexte ?

**Comment by spelhate** [comment]
Oui
